# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Aqueduct::Api::V1::DescribeConfigResponse`.
# Please instead update this file by running `bin/tapioca dsl Aqueduct::Api::V1::DescribeConfigResponse`.


class Aqueduct::Api::V1::DescribeConfigResponse < Google::Protobuf::AbstractMessage
  sig do
    params(
      clusters: T.nilable(T.any(Google::Protobuf::RepeatedField[Aqueduct::Api::V1::DescribeConfigResponse::ClusterConfigInfo], T::Array[Aqueduct::Api::V1::DescribeConfigResponse::ClusterConfigInfo]))
    ).void
  end
  def initialize(clusters: T.unsafe(nil)); end

  sig { void }
  def clear_clusters; end

  sig { returns(Google::Protobuf::RepeatedField[Aqueduct::Api::V1::DescribeConfigResponse::ClusterConfigInfo]) }
  def clusters; end

  sig do
    params(
      value: Google::Protobuf::RepeatedField[Aqueduct::Api::V1::DescribeConfigResponse::ClusterConfigInfo]
    ).void
  end
  def clusters=(value); end
end
