# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Github::DependencyGraphPlatform::Graphql::V1::GetDependenciesForManifestRequest`.
# Please instead update this file by running `bin/tapioca dsl Github::DependencyGraphPlatform::Graphql::V1::GetDependenciesForManifestRequest`.


class Github::DependencyGraphPlatform::Graphql::V1::GetDependenciesForManifestRequest < Google::Protobuf::AbstractMessage
  sig { params(manifest_id: T.nilable(Integer), repository_id: T.nilable(Integer)).void }
  def initialize(manifest_id: nil, repository_id: nil); end

  sig { void }
  def clear_manifest_id; end

  sig { void }
  def clear_repository_id; end

  sig { returns(Integer) }
  def manifest_id; end

  sig { params(value: Integer).void }
  def manifest_id=(value); end

  sig { returns(Integer) }
  def repository_id; end

  sig { params(value: Integer).void }
  def repository_id=(value); end
end
