# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Licensing::BundledLicenseAssignmentsAgreementUnlinkingJob`.
# Please instead update this file by running `bin/tapioca dsl Licensing::BundledLicenseAssignmentsAgreementUnlinkingJob`.


class Licensing::BundledLicenseAssignmentsAgreementUnlinkingJob
  class << self
    sig do
      params(
        agreement_id: ::String,
        revoke_blas: T.nilable(T::Boolean),
        block: T.nilable(T.proc.params(job: Licensing::BundledLicenseAssignmentsAgreementUnlinkingJob).void)
      ).returns(T.any(Licensing::BundledLicenseAssignmentsAgreementUnlinkingJob, FalseClass))
    end
    def perform_later(agreement_id, revoke_blas: T.unsafe(nil), &block); end

    sig { params(agreement_id: ::String, revoke_blas: T.nilable(T::Boolean)).void }
    def perform_now(agreement_id, revoke_blas: T.unsafe(nil)); end
  end
end
