# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/github/copilot/v2/copilot_clickwrap_saved_event.proto

require 'google/protobuf'

require 'hydro/schemas/github/v1/entities/request_context_pb'
require 'hydro/schemas/github/v1/entities/business_pb'
require 'hydro/schemas/github/v1/entities/user_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.github.copilot.v2.CopilotClickwrapSavedEvent" do
    optional :request_context, :message, 1, "hydro.schemas.github.v1.entities.RequestContext"
    optional :business, :message, 2, "hydro.schemas.github.v1.entities.Business"
    optional :actor, :message, 3, "hydro.schemas.github.v1.entities.User"
  end
end

module Hydro
  module Schemas
    module Github
      module Copilot
        module V2
          CopilotClickwrapSavedEvent = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.copilot.v2.CopilotClickwrapSavedEvent").msgclass
        end
      end
    end
  end
end
