# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/github/copilot/v2/copilot_for_business_trial_changed.proto

require 'google/protobuf'

require 'hydro/schemas/github/v1/entities/business_pb'
require 'hydro/schemas/github/v1/entities/organization_pb'
require 'hydro/schemas/github/v1/entities/user_pb'
require 'hydro/schemas/github/copilot/v2/entities/copilot_plan_pb'
require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.github.copilot.v2.CopilotForBusinessTrialChanged" do
    optional :staff_actor, :message, 1, "hydro.schemas.github.v1.entities.User"
    optional :organization, :message, 2, "hydro.schemas.github.v1.entities.Organization"
    optional :business, :message, 3, "hydro.schemas.github.v1.entities.Business"
    optional :previous_trial_ends_at, :message, 4, "google.protobuf.Timestamp"
    optional :updated_trial_ends_at, :message, 5, "google.protobuf.Timestamp"
    optional :reason, :string, 6
    optional :old_copilot_plan, :enum, 7, "hydro.schemas.github.copilot.v2.entities.CopilotPlan"
    optional :new_copilot_plan, :enum, 8, "hydro.schemas.github.copilot.v2.entities.CopilotPlan"
  end
end

module Hydro
  module Schemas
    module Github
      module Copilot
        module V2
          CopilotForBusinessTrialChanged = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.copilot.v2.CopilotForBusinessTrialChanged").msgclass
        end
      end
    end
  end
end
