#!/bin/bash
#
# This script replaces the .git subfolder with that of a shallow clone, leaving everything else the same.
#
# Usage: scalar-clone
#
# Performs a scalar clone of the repository, and deletes the original. This is much smaller than a full clone, but still operates
# largely the same way. Branches are fetched on demand, and the history is fetched from the server as needed.

set -e

scalar clone --full-clone https://github.com/github/github.git /workspaces/github-scalar
mv /workspaces/github-scalar/src /workspaces/github2
rm -rf /workspaces/github-scalar
