# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Orgs::Domain::CustomProperties`.
# Please instead update this file by running `bin/tapioca dsl Orgs::Domain::CustomProperties`.


class Orgs::Domain::CustomProperties
  include GeneratedDomainAccessorMethods

  module GeneratedDomainAccessorMethods; end
end
