# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/github/actions/v0/gate_request_created.proto

require 'google/protobuf'

require 'hydro/schemas/github/v1/entities/integration_pb'
require 'hydro/schemas/github/v2/entities/repository_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.github.actions.v0.GateRequestCreated" do
    optional :gate_request_id, :int64, 1
    optional :gate_id, :int64, 2
    optional :gate_type, :enum, 3, "hydro.schemas.github.actions.v0.GateRequestCreated.GateType"
    optional :check_suite_id, :int64, 4
    optional :check_run_id, :int64, 5
    optional :repository, :message, 6, "hydro.schemas.github.v2.entities.Repository"
    optional :integration, :message, 7, "hydro.schemas.github.v1.entities.Integration"
  end
  add_enum "hydro.schemas.github.actions.v0.GateRequestCreated.GateType" do
    value :UNKNOWN, 0
    value :TIMEOUT, 1
    value :MANUAL_APPROVAL, 2
    value :BRANCH_POLICY, 3
    value :CUSTOM, 4
  end
end

module Hydro
  module Schemas
    module Github
      module Actions
        module V0
          GateRequestCreated = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.actions.v0.GateRequestCreated").msgclass
          GateRequestCreated::GateType = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.actions.v0.GateRequestCreated.GateType").enummodule
        end
      end
    end
  end
end
