# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/github/actions/v0/invocation_unblocked.proto

require 'google/protobuf'

require 'hydro/schemas/github/v1/entities/user_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.github.actions.v0.InvocationUnblocked" do
    optional :account, :message, 1, "hydro.schemas.github.v1.entities.User"
  end
end

module Hydro
  module Schemas
    module Github
      module Actions
        module V0
          InvocationUnblocked = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.actions.v0.InvocationUnblocked").msgclass
        end
      end
    end
  end
end
