# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/github/actions/v0/resolve_action_request.proto

require 'google/protobuf'

require 'google/protobuf/wrappers_pb'
require 'hydro/schemas/github/enterprise_account/v0/entities/enterprise_installation_pb'
require 'hydro/schemas/github/v1/entities/user_pb'
require 'hydro/schemas/github/v2/entities/repository_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.github.actions.v0.ResolveActionRequest" do
    optional :resolved_repository, :message, 1, "hydro.schemas.github.v2.entities.Repository"
    optional :ref, :bytes, 2
    optional :resolved_sha, :bytes, 3
    optional :user, :message, 4, "hydro.schemas.github.v1.entities.User"
    optional :connect_request, :bool, 5
    optional :enterprise_installation, :message, 6, "hydro.schemas.github.enterprise_account.v0.entities.EnterpriseInstallation"
    optional :workflow_run_id, :message, 7, "google.protobuf.Int64Value"
    optional :job_id, :string, 8
    optional :workflow_repository_id, :message, 9, "google.protobuf.Int64Value"
    optional :action_nwo, :string, 10
    optional :package_id, :message, 11, "google.protobuf.Int64Value"
    optional :resolved_ref, :bytes, 12
  end
end

module Hydro
  module Schemas
    module Github
      module Actions
        module V0
          ResolveActionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.actions.v0.ResolveActionRequest").msgclass
        end
      end
    end
  end
end
