# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/github/actions/v0/workflow_run_execution.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.github.actions.v0.WorkflowRunExecution" do
    optional :actor_id, :int64, 1
    optional :attempt, :int64, 2
    optional :conclusion, :string, 3
    optional :check_suite_id, :int64, 4
    optional :repository_id, :int64, 5
    optional :repository_owner_id, :int64, 6
    optional :status, :string, 7
    optional :workflow_run_external_id, :string, 8
    optional :workflow_run_id, :int64, 9
    optional :workflow_run_path, :string, 10
    optional :started_at, :message, 11, "google.protobuf.Timestamp"
    optional :completed_at, :message, 12, "google.protobuf.Timestamp"
  end
end

module Hydro
  module Schemas
    module Github
      module Actions
        module V0
          WorkflowRunExecution = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.actions.v0.WorkflowRunExecution").msgclass
        end
      end
    end
  end
end
