# typed: strict
# frozen_string_literal: true

# Public: Represents a single hunk within a GitHub::Diff::Entry. Diff entries
# contain one or more hunks and this interface allows us to pass around single
# hunks istead of the entire entry. This is helpful since hunks for a single entry
# may be split over multiple summarization prompts.
#
# Examples:
#
#   diffs = pr.historical_comparison.diffs
#   # => ["#<GitHub::Diff::Entry path=\"README.md\">", "#<GitHub::Diff::Entry path=\"user.rb\">", …]
#   hunks = PullRequests::Copilot::DiffHunk.diffs_to_hunks
#   # => [
#     "#<DiffHunk entry=\"#<GitHub::Diff::Entry path=\"README.md\">\">",
#     "#<DiffHunk entry=\"#<GitHub::Diff::Entry path=\"README.md\">\">",
#     "#<DiffHunk entry=\"#<GitHub::Diff::Entry path=\"user.rb\">\">",
#     …
#   ]
#
module PullRequests
  module Copilot
    class DiffHunk
      include GitHub::Memoizer
      extend T::Sig

      HEADER_CONTEXT_REGEX = /\A@@[^@]+@@\s+(?<context>.+)\z/

      # Public: Takes an array of diff entries and returns
      # a flat array of diff hunks that make up the entries.
      #
      # diffs - An Array of GitHub::Diff::Entry instances
      #
      # Returns an Array of DiffHunk instances.
      sig { params(diffs: T::Array[GitHub::Diff::Entry]).returns(T::Array[DiffHunk]) }
      def self.diffs_to_hunks(diffs)
        GitHub.dogstats.time("copilot.prompt.diffs_to_hunks", tags: ["size:#{diffs.size}"]) do
          diffs.flat_map do |entry|
            hunks = entry.enumerator.chunk_while do |_, next_line|
              next_line.type != :hunk
            end

            hunks.map do |hunk|
              header, *lines = hunk
              self.new(header:, lines:, entry:)
            end
          end
        end
      end

      sig { returns(GitHub::Diff::Line) }
      attr_reader :header

      sig { returns(T::Array[GitHub::Diff::Line]) }
      attr_reader :lines

      sig { returns(GitHub::Diff::Entry) }
      attr_reader :entry

      delegate :left, :right, to: :first_line

      # Public: Initializes a new DiffHunk object.
      #
      # header - A GitHub::Diff::Line of type :hunk
      # lines  - An Array of GitHub::Diff:Line objects of
      #          type :context, :addition, or :deletion
      # entry  - The GitHub::Diff::Entry containing the hunk.
      sig { params(header: GitHub::Diff::Line, lines: T::Array[GitHub::Diff::Line], entry: GitHub::Diff::Entry).void }
      def initialize(header:, lines:, entry:)
        @header = header
        @lines = lines
        @entry = entry
      end

      sig { returns(GitHub::Diff::Line) }
      def first_line
        T.must(lines.first)
      end

      # Public: Attempts to pull context from the hunk header.
      #
      # Example:
      #
      #   header text: "@@ -173,7 +173,7 @@ def hello_world"
      #   context: "def hello_world"
      #
      # Returns context String if found or nil if not.
      sig { returns(T.nilable(String)) }
      memoize def header_context
        match = HEADER_CONTEXT_REGEX.match(header.text)
        match && match[:context]
      end

      sig { returns(String) }
      def file_name
        name = "`#{entry.path}`"
        name << " which was renamed from `#{entry.a_path}`" if entry.renamed?
        name
      end

      sig { returns(String) }
      def file_path
        entry.path
      end

      sig { returns(T.nilable(String)) }
      def hunk_context
        " in `#{header_context}`".html_safe if header_context # rubocop:disable Rails/OutputSafety
      end

      sig { returns(String) }
      def quote_diff
        diff = lines.map(&:text).join("\n")
        diff_block(diff)
      end

      sig { returns(String) }
      def diff_text
        modified_line_texts = lines.map do |line|
          "[#{line.left},#{line.right}]" + line.text
        end

        body_text = modified_line_texts.join("\n")

        # Diffs expect a trailing newline, otherwise the diff will include
        # a \ No newline at end of file at the end of the file.
        # Here we make sure if that line is present in the diff generated by the comparison object we remove it.
        diff = (header.text + "\n" + body_text).delete_suffix("\\ No newline at end of file")

        diff_block(diff)
      end

      sig { returns(String) }
      def diff_text_without_line_numbers
        body_text = lines.map(&:text).join("\n")

        # Diffs expect a trailing newline, otherwise the diff will include
        # a \ No newline at end of file at the end of the file.
        # Here we make sure if that line is present in the diff generated by the comparison object we remove it.
        diff = (header.text + "\n" + body_text).delete_suffix("\\ No newline at end of file")

        diff
      end

      sig { returns(T::Array[T::Hash[Symbol, String]]) }
      def entry_line_attributes
        entry.each_line.map do |line|
          {
            line_number: line_number(line).to_s,
            line_content: line.text,
            line_side: side(line)
          }
        end
      end

      private

      sig { params(diff: String).returns(String) }
      def diff_block(diff)
        fence = diff.include?("```") ? "~~~" : "```"

        <<~DIFF.html_safe # rubocop:disable Rails/OutputSafety
          #{fence}diff
          #{diff.chomp}
          #{fence}
        DIFF
      end

      sig { params(line: GitHub::Diff::Line).returns(String) }
      def side(line)
        line.deletion? ? "L" : "R"
      end

      sig { params(line: GitHub::Diff::Line).returns(Integer) }
      def line_number(line)
        return line.left if line.deletion?
        line.right
      end
    end
  end
end
