# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/github/sponsors/v0/sponsorship_preference_change.proto

require 'google/protobuf'

require 'hydro/schemas/github/v1/entities/request_context_pb'
require 'hydro/schemas/github/v1/entities/user_pb'
require 'hydro/schemas/github/sponsors/v0/entities/sponsorship_pb'
require 'hydro/schemas/github/marketplace/v0/entities/marketplace_listing_pb'
require 'hydro/schemas/github/marketplace/v0/entities/marketplace_listing_billing_plan_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.github.sponsors.v0.SponsorshipPreferenceChange" do
    optional :request_context, :message, 1, "hydro.schemas.github.v1.entities.RequestContext"
    optional :previous_sponsorship, :message, 2, "hydro.schemas.github.sponsors.v0.entities.Sponsorship"
    optional :current_sponsorship, :message, 3, "hydro.schemas.github.sponsors.v0.entities.Sponsorship"
    optional :tier, :message, 4, "hydro.schemas.github.marketplace.v0.entities.MarketplaceListingBillingPlan"
    optional :marketplace_listing, :message, 5, "hydro.schemas.github.marketplace.v0.entities.MarketplaceListing"
    optional :actor, :message, 6, "hydro.schemas.github.v1.entities.User"
  end
end

module Hydro
  module Schemas
    module Github
      module Sponsors
        module V0
          SponsorshipPreferenceChange = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.sponsors.v0.SponsorshipPreferenceChange").msgclass
        end
      end
    end
  end
end
