# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/github/sponsors/v0/sponsors_fraud_review_create.proto

require 'google/protobuf'

require 'hydro/schemas/github/sponsors/v0/entities/sponsors_fraud_review_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.github.sponsors.v0.SponsorsFraudReviewCreate" do
    optional :fraud_review, :message, 1, "hydro.schemas.github.sponsors.v0.entities.SponsorsFraudReview"
  end
end

module Hydro
  module Schemas
    module Github
      module Sponsors
        module V0
          SponsorsFraudReviewCreate = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.sponsors.v0.SponsorsFraudReviewCreate").msgclass
        end
      end
    end
  end
end
