# typed: true
# frozen_string_literal: true

class Repository
  # NOTE: Changes to this module and method should be kept in sync with Repositories::Domain#create.
  # This module is deprecated! Use the domain method instead.
  module Creatable
    class Result
      def initialize(success, allowed, repository, error_message = nil)
        @success = success
        @allowed = allowed
        @repository = repository
        @error_message = error_message
      end

      # Boolean indicating whether the repo creation succeeded.
      attr_reader :success
      alias_method :success?, :success

      # Boolean indicating whether the user is allowed to create a new repo.
      # False means disallowed. Always true when 'success' is true.
      attr_reader :allowed

      # Resulting repository record. Already persisted when 'success' is true,
      # unsaved otherwise.
      attr_reader :repository

      # Error generated by repository creation as a String
      attr_reader :error_message

      # pre-receive hook failures that block template init
      attr_accessor :template_hook_failure

      # Public: Is there a error due to not being able to set private visibility
      # This happens due to plan limits on private repositories
      #
      # Return Boolean
      def privatization_billing_error?
        repository&.errors[:visibility].present? && repository.owner&.per_seat_plan_only? && !repository.owner&.has_any_trade_restrictions?
      end
    end

    # Creates a repository for the given user or organization after checking
    # permissions. This lets the user choose to automatically initialize the
    # repo with a .gitignore file.
    #
    # This is typically called from RepositoriesController#create.
    #
    #   user               - The saved and valid User record creating the new repo. Usually
    #                        set to current_user.
    #   owner              - Login of the User or Organization that owns the new repo.
    #   repo               - Hash of the new repository attributes:
    #   name               - Repo name as a String.
    #   public             - True means public, false means private.
    #   visibility         - Used in place of 'public'. Can be public, private, internal.
    #   template           - True marks the repository as a template, false otherwise.
    #   description        - Optional description as a String.
    #   homepage           - Optional homepage URL as a String.
    #   auto_init          - Automatically initialize the repository when true.
    #   license_template   - Repo license as a String. e.g. "MIT".
    #   reflog_data        - Reflog data needed to create initial commit
    #   custom_properties  - A hash of custom properties to set for the repository
    #   gitignore_template - gitignore template as a String. e.g. "Ruby".
    #   has_wiki           - Set up wiki for repo
    #   has_downloads      - Set up downloads for repo
    #   has_issues         - Set up issues for repo
    #   team_id            - The team that's granted access to this repository.
    #                        Orgs only.
    #   allow_merge_commit - Allow the creation of merge commits - defaults to true.
    #   allow_squash_merge - Allow squash merges - defaults to true.
    #   allow_rebase_merge - Allow rebase merges - defaults to true.
    #   payment_details    - Optional Hash of any other attributes.
    #   role               - If the user should be treated as an admin (default: nil).
    #                        :admin - To treat the user as an admin.
    #                        :octoshift_migrator - To treat the user as a user whos migrating/importing.
    #
    # At least one of `allow_merge_commit`, `allow_squash_merge` and `allow_rebase_merge`
    # must be `true`, otherwise repository creation will fail.
    #
    # Returns a Repository::Creatable::Result object indicating success or failure.
    def handle_creation(user, owner, repo, reflog_data = {}, payment_details = nil, role: nil, skip_validation: false, synchronous: false, custom_properties: nil, current_integration_context: nil, source_repository: nil)
      GitHub.dogstats.distribution_time("repository.handle_creation") do
        o = RepositoryOrchestration.create_repository(
          actor: user,
          owner_login: owner,
          repo_attributes: repo,
          reflog_data: reflog_data,
          payment_details: payment_details,
          role: role,
          skip_validation: skip_validation,
          custom_properties: custom_properties,
          current_integration_context: current_integration_context,
          source_repository: source_repository
        )
        if o.errors.any?
          GitHub.dogstats.increment("repository", tags: ["action:create", "valid:false"])
          return Repository::Creatable::Result.new(false, !(o.allowed == false), o.built_repository, o.errors[:repository].first)
        end

        o.execute(synchronous: synchronous)

        if o.failed?
          # If we fail before saving the repo, then o.repository will be nil, so get content from o.built_repository
          repo = o.built_repository || o.repository
          return Repository::Creatable::Result.new(false, !(o.allowed == false), repo, o.error_message)
        elsif o.skipped?
          result = Repository::Creatable::Result.new(false, true, o.built_repository, o.error_message)
          return result
        end
        result = Repository::Creatable::Result.new(true, true, o.repository)
        result.template_hook_failure = T.must(o.repository).template_hook_failure
        return result
      end
    end
  end
end
