# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Primer::CurrentAttributes`.
# Please instead update this file by running `bin/tapioca dsl Primer::CurrentAttributes`.


class Primer::CurrentAttributes
  include GeneratedAttributeMethods

  class << self
    sig { returns(T.untyped) }
    def nonce; end

    sig { params(value: T.untyped).returns(T.untyped) }
    def nonce=(value); end
  end

  module GeneratedAttributeMethods
    sig { returns(T.untyped) }
    def nonce; end

    sig { params(value: T.untyped).returns(T.untyped) }
    def nonce=(value); end
  end
end
