# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/github/merge_queue/v1/merge_queue_entry_event.proto

require 'google/protobuf'

require 'hydro/schemas/github/merge_queue/v1/entities/merge_group_entry_pb'
require 'hydro/schemas/github/merge_queue/v1/entities/merge_queue_pb'
require 'hydro/schemas/github/merge_queue/v1/entities/merge_queue_entry_pb'
require 'hydro/schemas/github/merge_queue/v1/entities/required_status_check_pb'
require 'hydro/schemas/github/v1/entities/pull_request_pb'
require 'hydro/schemas/github/v1/entities/user_pb'
require 'hydro/schemas/github/v1/entities/protected_branch_pb'
require 'hydro/schemas/github/v1/entities/repository_pb'
require 'google/protobuf/wrappers_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.github.merge_queue.v1.MergeQueueEntryEvent" do
    optional :event, :enum, 1, "hydro.schemas.github.merge_queue.v1.MergeQueueEntryEvent.Event"
    optional :pull_request, :message, 2, "hydro.schemas.github.v1.entities.PullRequest"
    optional :repository, :message, 3, "hydro.schemas.github.v1.entities.Repository"
    optional :protected_branch, :message, 4, "hydro.schemas.github.v1.entities.ProtectedBranch"
    optional :queue, :message, 5, "hydro.schemas.github.merge_queue.v1.entities.MergeQueue"
    optional :entry, :message, 6, "hydro.schemas.github.merge_queue.v1.entities.MergeQueueEntry"
    repeated :group_entries, :message, 7, "hydro.schemas.github.merge_queue.v1.entities.MergeGroupEntry"
    optional :enqueuer, :message, 8, "hydro.schemas.github.v1.entities.User"
    optional :dequeuer, :message, 9, "hydro.schemas.github.v1.entities.User"
    repeated :required_status_checks, :message, 10, "hydro.schemas.github.merge_queue.v1.entities.RequiredStatusCheck"
    optional :removal_reason, :enum, 11, "hydro.schemas.github.merge_queue.v1.MergeQueueEntryEvent.RemovalReason"
    optional :queue_depth, :message, 12, "google.protobuf.Int32Value"
  end
  add_enum "hydro.schemas.github.merge_queue.v1.MergeQueueEntryEvent.Event" do
    value :UNKNOWN_EVENT, 0
    value :CREATE, 1
    value :UPDATE, 2
    value :DESTROY, 3
  end
  add_enum "hydro.schemas.github.merge_queue.v1.MergeQueueEntryEvent.RemovalReason" do
    value :UNKNOWN_REMOVAL_REASON, 0
    value :MERGE, 1
    value :ROLL_BACK, 2
    value :MANUAL, 3
    value :MERGE_CONFLICT, 4
    value :CI_FAILURE, 5
    value :CI_TIMEOUT, 6
    value :ALREADY_MERGED, 7
    value :QUEUE_CLEARED, 8
    value :BRANCH_PROTECTIONS, 9
    value :GIT_TREE_INVALID, 10
    value :INVALID_MERGE_COMMIT, 11
  end
end

module Hydro
  module Schemas
    module Github
      module MergeQueue
        module V1
          MergeQueueEntryEvent = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.merge_queue.v1.MergeQueueEntryEvent").msgclass
          MergeQueueEntryEvent::Event = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.merge_queue.v1.MergeQueueEntryEvent.Event").enummodule
          MergeQueueEntryEvent::RemovalReason = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.merge_queue.v1.MergeQueueEntryEvent.RemovalReason").enummodule
        end
      end
    end
  end
end
