# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/github/repositories/v1/rename_branch.proto

require 'google/protobuf'

require 'hydro/schemas/github/v1/entities/repository_pb'
require 'hydro/schemas/github/v1/entities/user_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.github.repositories.v1.RenameBranch" do
    optional :actor, :message, 1, "hydro.schemas.github.v1.entities.User"
    optional :repository_owner, :message, 2, "hydro.schemas.github.v1.entities.User"
    optional :repository, :message, 3, "hydro.schemas.github.v1.entities.Repository"
    optional :old_branch, :string, 4
    optional :new_branch, :string, 5
    optional :default_branch, :bool, 6
  end
end

module Hydro
  module Schemas
    module Github
      module Repositories
        module V1
          RenameBranch = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.repositories.v1.RenameBranch").msgclass
        end
      end
    end
  end
end
