import {ChevronDownIcon, ChevronUpIcon, StopIcon} from '@primer/octicons-react'
import {IconButton} from '@primer/react'
import {Octicon} from '@primer/react/deprecated'
import {Fragment, useMemo, useState} from 'react'
import {useRoutePayload} from '@github-ui/react-core/use-route-payload'
import type {ExemptionRequestPayload, NewExemptionRequestPayload} from '../delegated-bypass-types'

import type {RuleRun} from '@github-ui/repos-rules/types/rules-types'

import styles from './SecretScanningSecretsDetails.module.css'
import {clsx} from 'clsx'

export function SecretScanningSecretsDetails({ruleRuns}: {ruleRuns: RuleRun[]}) {
  const [showDetails, setShowDetails] = useState(false)
  const payload = useRoutePayload<ExemptionRequestPayload | NewExemptionRequestPayload>()
  let resourceId = 'Unknown'
  if ('resourceId' in payload && payload.resourceId) {
    resourceId = payload.resourceId
  } else if ('request' in payload && payload.request.resourceId) {
    resourceId = payload.request.resourceId
  }

  const {tokenType, commitMetadata} = useMemo((): {
    tokenType: string
    commitMetadata: Array<{commitHash: string; path: string; refName: string}>
  } => {
    const ruleRun = ruleRuns.at(-1)
    let reloadedTokenType = 'Unknown'
    let reloadedCommitMetadata = [{commitHash: 'Unknown', path: 'Unknown', refName: 'Unknown'}]

    if (ruleRun?.metadata && 'secrets' in ruleRun.metadata) {
      const matchingSecrets = ruleRun.metadata.secrets.filter(secret => secret.bypass_placeholder_ksuid === resourceId)
      if (matchingSecrets.length === 1 && matchingSecrets[0]) {
        reloadedTokenType = matchingSecrets[0].token_metadata.label
        reloadedCommitMetadata = matchingSecrets[0].locations.map(location => ({
          commitHash: location.commit_oid,
          path: location ? `${location.path}:${location.start_line}:${location.start_line_byte_position}` : `Unknown`,
          refName: payload.ruleSuite.refName || '',
        }))
      }
    } else if (ruleRun?.metadata) {
      // Metadata generated by the secret scanning content scan rule is in the format: {<path>: <SecretsMetadata>}.
      // We'll take the first secret from the first SecretsMetadata value.
      const metadataValues = Object.entries(ruleRun?.metadata)[0]
      if (metadataValues) {
        const [key, scanResults] = metadataValues
        if (scanResults.secrets.length > 0) {
          const secret = scanResults.secrets[0]
          const location = secret?.locations[0]
          reloadedTokenType = secret.token_metadata.label
          // The commit is still pending since it's being tried via the web UI.
          reloadedCommitMetadata = [
            {
              commitHash: 'Pending (from file editor)',
              path: `${key}${location ? `:${location?.start_line}:${location?.start_line_byte_position}` : ``}`,
              refName: payload.ruleSuite.refName || '',
            },
          ]
        }
      }
    }
    return {
      tokenType: reloadedTokenType,
      commitMetadata: reloadedCommitMetadata,
    }
  }, [ruleRuns, resourceId, payload.ruleSuite.refName])

  const ruleDisplayName = 'Secrets detected'

  return (
    <div className={styles.Box}>
      <div className={styles.Box_1}>
        <div className={styles.Box_2}>
          <Octicon icon={StopIcon} size={16} className={styles.Octicon} />
          <span className={styles.Text}>{ruleDisplayName} </span>
        </div>
        <div className={styles.Box_2}>
          <IconButton
            aria-label="View details"
            variant="invisible"
            icon={showDetails ? ChevronUpIcon : ChevronDownIcon}
            onClick={() => setShowDetails(!showDetails)}
            className={styles.IconButton}
          />
        </div>
      </div>
      {showDetails && (
        <>
          <div className={styles.Box_2}>
            <span className={styles.Text_1}>{tokenType}</span>
          </div>
          <ul className={clsx('Box', styles.Box_3)}>
            {commitMetadata.map(({commitHash, path, refName}) => {
              return (
                <Fragment key={`${commitHash}-container`}>
                  <li className="commitHash" key={commitHash}>
                    commit: {commitHash}
                  </li>
                  <li className="metadata" key={`${commitHash}:${path}`}>
                    path: {path}
                  </li>
                  <li className="metadata" key={`${commitHash}:${refName}`}>
                    branch: {refName}
                  </li>
                </Fragment>
              )
            })}
          </ul>
        </>
      )}
    </div>
  )
}
