# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Mvnd::Migrations::Api::V1::Project`.
# Please instead update this file by running `bin/tapioca dsl Mvnd::Migrations::Api::V1::Project`.


class Mvnd::Migrations::Api::V1::Project < Google::Protobuf::AbstractMessage
  sig do
    params(
      body: T.nilable(String),
      closed_at: T.nilable(Google::Protobuf::Timestamp),
      created_at: T.nilable(Google::Protobuf::Timestamp),
      creator_resource_id: T.nilable(String),
      is_public: T.nilable(T::Boolean),
      name: T.nilable(String),
      number: T.nilable(Integer),
      owner_resource_id: T.nilable(String),
      owner_type: T.nilable(T.any(Symbol, Integer)),
      resource_id: T.nilable(String),
      updated_at: T.nilable(Google::Protobuf::Timestamp)
    ).void
  end
  def initialize(body: nil, closed_at: nil, created_at: nil, creator_resource_id: nil, is_public: nil, name: nil, number: nil, owner_resource_id: nil, owner_type: nil, resource_id: nil, updated_at: nil); end

  sig { returns(String) }
  def body; end

  sig { params(value: String).void }
  def body=(value); end

  sig { void }
  def clear_body; end

  sig { void }
  def clear_closed_at; end

  sig { void }
  def clear_created_at; end

  sig { void }
  def clear_creator_resource_id; end

  sig { void }
  def clear_is_public; end

  sig { void }
  def clear_name; end

  sig { void }
  def clear_number; end

  sig { void }
  def clear_owner_resource_id; end

  sig { void }
  def clear_owner_type; end

  sig { void }
  def clear_resource_id; end

  sig { void }
  def clear_updated_at; end

  sig { returns(T.nilable(Google::Protobuf::Timestamp)) }
  def closed_at; end

  sig { params(value: T.nilable(Google::Protobuf::Timestamp)).void }
  def closed_at=(value); end

  sig { returns(T.nilable(Google::Protobuf::Timestamp)) }
  def created_at; end

  sig { params(value: T.nilable(Google::Protobuf::Timestamp)).void }
  def created_at=(value); end

  sig { returns(String) }
  def creator_resource_id; end

  sig { params(value: String).void }
  def creator_resource_id=(value); end

  sig { returns(Object) }
  def has_closed_at?; end

  sig { returns(Object) }
  def has_created_at?; end

  sig { returns(Object) }
  def has_updated_at?; end

  sig { returns(T::Boolean) }
  def is_public; end

  sig { params(value: T::Boolean).void }
  def is_public=(value); end

  sig { returns(String) }
  def name; end

  sig { params(value: String).void }
  def name=(value); end

  sig { returns(Integer) }
  def number; end

  sig { params(value: Integer).void }
  def number=(value); end

  sig { returns(String) }
  def owner_resource_id; end

  sig { params(value: String).void }
  def owner_resource_id=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def owner_type; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def owner_type=(value); end

  sig { returns(String) }
  def resource_id; end

  sig { params(value: String).void }
  def resource_id=(value); end

  sig { returns(T.nilable(Google::Protobuf::Timestamp)) }
  def updated_at; end

  sig { params(value: T.nilable(Google::Protobuf::Timestamp)).void }
  def updated_at=(value); end
end
