# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Mvnd::Migrations::Api::V1::PullRequestReview`.
# Please instead update this file by running `bin/tapioca dsl Mvnd::Migrations::Api::V1::PullRequestReview`.


class Mvnd::Migrations::Api::V1::PullRequestReview < Google::Protobuf::AbstractMessage
  sig do
    params(
      attachment_resource_ids: T.nilable(T.any(Google::Protobuf::RepeatedField[String], T::Array[String])),
      body: T.nilable(String),
      comments: T.nilable(T.any(Google::Protobuf::RepeatedField[Mvnd::Migrations::Api::V1::PullRequestReviewComment], T::Array[Mvnd::Migrations::Api::V1::PullRequestReviewComment])),
      created_at: T.nilable(Google::Protobuf::Timestamp),
      head_sha: T.nilable(String),
      resource_id: T.nilable(String),
      state: T.nilable(T.any(Symbol, Integer)),
      submitted_at: T.nilable(Google::Protobuf::Timestamp),
      threads: T.nilable(T.any(Google::Protobuf::RepeatedField[Mvnd::Migrations::Api::V1::PullRequestReviewThread], T::Array[Mvnd::Migrations::Api::V1::PullRequestReviewThread])),
      user_resource_id: T.nilable(String)
    ).void
  end
  def initialize(attachment_resource_ids: T.unsafe(nil), body: nil, comments: T.unsafe(nil), created_at: nil, head_sha: nil, resource_id: nil, state: nil, submitted_at: nil, threads: T.unsafe(nil), user_resource_id: nil); end

  sig { returns(Google::Protobuf::RepeatedField[String]) }
  def attachment_resource_ids; end

  sig { params(value: Google::Protobuf::RepeatedField[String]).void }
  def attachment_resource_ids=(value); end

  sig { returns(String) }
  def body; end

  sig { params(value: String).void }
  def body=(value); end

  sig { void }
  def clear_attachment_resource_ids; end

  sig { void }
  def clear_body; end

  sig { void }
  def clear_comments; end

  sig { void }
  def clear_created_at; end

  sig { void }
  def clear_head_sha; end

  sig { void }
  def clear_resource_id; end

  sig { void }
  def clear_state; end

  sig { void }
  def clear_submitted_at; end

  sig { void }
  def clear_threads; end

  sig { void }
  def clear_user_resource_id; end

  sig { returns(Google::Protobuf::RepeatedField[Mvnd::Migrations::Api::V1::PullRequestReviewComment]) }
  def comments; end

  sig { params(value: Google::Protobuf::RepeatedField[Mvnd::Migrations::Api::V1::PullRequestReviewComment]).void }
  def comments=(value); end

  sig { returns(T.nilable(Google::Protobuf::Timestamp)) }
  def created_at; end

  sig { params(value: T.nilable(Google::Protobuf::Timestamp)).void }
  def created_at=(value); end

  sig { returns(Object) }
  def has_created_at?; end

  sig { returns(Object) }
  def has_submitted_at?; end

  sig { returns(String) }
  def head_sha; end

  sig { params(value: String).void }
  def head_sha=(value); end

  sig { returns(String) }
  def resource_id; end

  sig { params(value: String).void }
  def resource_id=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def state; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def state=(value); end

  sig { returns(T.nilable(Google::Protobuf::Timestamp)) }
  def submitted_at; end

  sig { params(value: T.nilable(Google::Protobuf::Timestamp)).void }
  def submitted_at=(value); end

  sig { returns(Google::Protobuf::RepeatedField[Mvnd::Migrations::Api::V1::PullRequestReviewThread]) }
  def threads; end

  sig { params(value: Google::Protobuf::RepeatedField[Mvnd::Migrations::Api::V1::PullRequestReviewThread]).void }
  def threads=(value); end

  sig { returns(String) }
  def user_resource_id; end

  sig { params(value: String).void }
  def user_resource_id=(value); end
end
