# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Mvnd::Migrations::Api::V1::RefDetails`.
# Please instead update this file by running `bin/tapioca dsl Mvnd::Migrations::Api::V1::RefDetails`.


class Mvnd::Migrations::Api::V1::RefDetails < Google::Protobuf::AbstractMessage
  sig { params(commit_sha: T.nilable(String), name: T.nilable(String)).void }
  def initialize(commit_sha: nil, name: nil); end

  sig { void }
  def clear_commit_sha; end

  sig { void }
  def clear_name; end

  sig { returns(String) }
  def commit_sha; end

  sig { params(value: String).void }
  def commit_sha=(value); end

  sig { returns(String) }
  def name; end

  sig { params(value: String).void }
  def name=(value); end
end
