# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `EducationWeb::V1::EmailDomainKind`.
# Please instead update this file by running `bin/tapioca dsl EducationWeb::V1::EmailDomainKind`.


module EducationWeb::V1::EmailDomainKind
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

EducationWeb::V1::EmailDomainKind::EMAIL_DOMAIN_KIND_UNKNOWN_INVALID = 0
EducationWeb::V1::EmailDomainKind::FACULTY = 3
EducationWeb::V1::EmailDomainKind::MIXED_USE = 1
EducationWeb::V1::EmailDomainKind::STUDENT = 2
