# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GitHub::Proto::SecretScanning::Types::V1::JobGroupType`.
# Please instead update this file by running `bin/tapioca dsl GitHub::Proto::SecretScanning::Types::V1::JobGroupType`.


module GitHub::Proto::SecretScanning::Types::V1::JobGroupType
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

GitHub::Proto::SecretScanning::Types::V1::JobGroupType::JOB_GROUP_TYPE_BACKFILL = 2
GitHub::Proto::SecretScanning::Types::V1::JobGroupType::JOB_GROUP_TYPE_CONTENT_BACKFILL = 3
GitHub::Proto::SecretScanning::Types::V1::JobGroupType::JOB_GROUP_TYPE_DISCUSSION_BACKFILL = 6
GitHub::Proto::SecretScanning::Types::V1::JobGroupType::JOB_GROUP_TYPE_DRY_RUN = 1
GitHub::Proto::SecretScanning::Types::V1::JobGroupType::JOB_GROUP_TYPE_GENERIC_SECRETS_BACKFILL = 4
GitHub::Proto::SecretScanning::Types::V1::JobGroupType::JOB_GROUP_TYPE_PULL_REQUEST_BACKFILL = 5
GitHub::Proto::SecretScanning::Types::V1::JobGroupType::JOB_GROUP_TYPE_UNKNOWN = 0
GitHub::Proto::SecretScanning::Types::V1::JobGroupType::JOB_GROUP_TYPE_WIKI_BACKFILL = 7
