# typed: true
# frozen_string_literal: true

class SchemaWriter
  extend T::Helpers
  attr_accessor :dry
  attr_reader :dry_run_results, :changed

  abstract!

  # Note: Using the type syntax at the end seems to cause type errors around the code.
  # @dry_run = T.let({
  #   errors: Hash.new { |h, k| h[k] = [] }, # { rule_type => [error, ...]}
  #   changes: {
  #     added: [], # [file_path, ...]
  #     modified: [],
  #     deleted: []
  #   }
  # }, T::Hash[Symbol, T::Hash[Symbol, T::Array[String]]])

  sig { void }
  def initialize
    @dry_run_results = {
      errors: Hash.new { |h, k| h[k] = [] }, # { rule_type => [error, ...]}
      changes: {
        added: [], # [file_path, ...]
        modified: [],
        deleted: []
      }
    }
    @configurable_types = configurable_types
    @changed = false
  end

  sig { params(path: String, contents: String, dry: T::Boolean).void }
  def write(path, contents, dry: false)
    exists = false
    if File.exist?(path)
      exists = true
      existing = File.read(path)
      return if existing == contents
    end

    if dry
      change_type = exists ? :modified : :added

      # TODO Potentially: add the contents to the dry run so its viewable while debugging
      @dry_run_results[:changes][change_type] << path
    else
      File.write(path, contents)
      @changed = true
    end

    @dry_run_results if dry
  end

  # Adds spaces to your text!
  sig { params(text: String, spaces: Integer).returns(String) }
  def add_spaces(text, spaces)
    space = " " * spaces
    text.split("\n").map { |line| space + line }.join("\n")
  end

  # Returns a subset of rules
  sig { returns(T::Hash[String, RuleEngine::BaseRule]) }
  def configurable_types
    @configurable_types ||= RuleEngine::Evaluator::REGISTERED_RULES.select { |_rule_type, impl| impl.is_user_configurable? || impl.publish_api }
  end

  # Generates a customisable header for each file
  sig { params(comment: String).returns(String) }
  def generate_header(comment)
    <<~HEADER
      # typed: true
      # frozen_string_literal: true

      # DO NOT EDIT MANUALLY
      # This is an autogenerated file of #{comment.chomp}
      # Please instead update this file by running `bin/dump-rules-schema`.

    HEADER
  end
end
