# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Turboscan::Proto::GenerateSyncFixRequest`.
# Please instead update this file by running `bin/tapioca dsl Turboscan::Proto::GenerateSyncFixRequest`.


class Turboscan::Proto::GenerateSyncFixRequest < Google::Protobuf::AbstractMessage
  sig { params(sarif: T.nilable(String)).void }
  def initialize(sarif: nil); end

  sig { void }
  def clear_sarif; end

  sig { returns(String) }
  def sarif; end

  sig { params(value: String).void }
  def sarif=(value); end
end
