# typed: true
# frozen_string_literal: true

class MemexProjectColumn < ApplicationRecord::Domain::Memexes
  include GitHub::Validations
  extend GitHub::Encoding
  include GitHub::Memoizer
  include Instrumentation::Model
  include MemexProjectColumn::FieldDependency
  include MemexProjectColumn::ConversionDependency
  include ContextualActor

  class IssueTypeColumnBackfillError < StandardError
    def initialize(memex_project_column)
      @message = if memex_project_column.invalid?
        memex_project_column.errors.full_messages.join(", ")
      else
        "Could not create Type column."
      end
    end
  end

  force_utf8_encoding :name
  force_utf8_encoding :name_slug
  attr_reader :normalized_settings

  belongs_to :memex_project, inverse_of: :memex_project_columns
  belongs_to :creator, class_name: "User"
  has_many :memex_project_column_values, inverse_of: :memex_project_column
  destroy_dependents_in_background :memex_project_column_values

  ASSIGNEES_COLUMN_NAME = "Assignees"
  REVIEWERS_COLUMN_NAME = "Reviewers"
  LABELS_COLUMN_NAME = "Labels"
  LINKED_ISSUES_COLUMN_NAME = "Linked issues"
  LINKED_PULL_REQUESTS_COLUMN_NAME = "Linked pull requests"
  MILESTONE_COLUMN_NAME = "Milestone"
  REPOSITORY_COLUMN_NAME = "Repository"
  TITLE_COLUMN_NAME = "Title"
  TRACKS_COLUMN_NAME = "Tracks"
  TRACKED_BY_COLUMN_NAME = "Tracked by"
  STATUS_COLUMN_NAME = "Status"
  TYPE_COLUMN_NAME = "Type"
  PARENT_ISSUE_COLUMN_NAME = "Parent issue"
  SUB_ISSUES_PROGRESS_COLUMN_NAME = "Sub-issues progress"

  # Used for CSV serialization of MemexProjectItems and should not be used outside of this context,
  # this constant defines the default column used to serialize the URL of a MemexProjectItem (i.e. the content URL)
  # This is used for backward compatibility of CSV exports generated by the Memex client.
  # For more details on its usage, please see MemexProjectItemCsvSerializer.
  CSV_DEFAULT_COLUMN = { header: "URL", index: 1 }.freeze

  RESERVED_COLUMN_NAMES = [
    ASSIGNEES_COLUMN_NAME,
    REVIEWERS_COLUMN_NAME,
    LABELS_COLUMN_NAME,
    LINKED_ISSUES_COLUMN_NAME,
    LINKED_PULL_REQUESTS_COLUMN_NAME,
    MILESTONE_COLUMN_NAME,
    REPOSITORY_COLUMN_NAME,
    TITLE_COLUMN_NAME,
    TRACKS_COLUMN_NAME,
    TRACKED_BY_COLUMN_NAME,
    STATUS_COLUMN_NAME,
    PARENT_ISSUE_COLUMN_NAME,
    SUB_ISSUES_PROGRESS_COLUMN_NAME,
    "Repo",
    "Assignee",
    "Reviewer",
    "Label",
    "Linked Issue",
    "Linked Pull Request",
    "Linked pull request",
    "Linked pull requests",
    "Tracked By",
    "is",
    "no",
    "author",
    "created",
    "updated"
  ].freeze

  RESERVED_COLUMN_NAME_CHARACTERS = [":"]

  NEW_COLUMN_NAME = "New Column"

  NAME_BYTESIZE_LIMIT = 255

  # A generic type can customized by the user for their own use cases.
  # A generic type can be either system-defined or user-defined.
  GENERIC_TYPES = %w(
    text
    single_select
    number
    date
    iteration
  ).freeze

  # Generic column types have a value of 60 and above, while special column types have a value below 60.
  # 60 was chosen as being a halfway point of the 127 values we can store with the current int.
  enum :data_type, {
    assignees: 0,
    labels: 1,
    milestone: 2,
    repository: 3,
    title: 4,
    linked_pull_requests: 5,
    reviewers: 6,
    tracks: 7,
    tracked_by: 8,
    issue_type: 9,
    parent_issue: 10,
    sub_issues_progress: 11,
    text: 60,
    single_select: 61,
    number: 62,
    date: 63,
    iteration: 64,
  }

  ON_CREATE_INSTRUMENTATION_KEY = "field_create"

  before_validation :normalize_settings
  before_validation :generate_name_slug, if: :will_save_change_to_name?

  validates :memex_project, presence: true
  validates(:name, presence: true, bytesize: { maximum: NAME_BYTESIZE_LIMIT }, unicode: true)
  validate :name_is_not_reserved
  # The column name should be unique per project. However, if we are copying columns from an existing project,
  # then we skip checking this because it is assumed that the validation was performed when the column was created.
  # This saves N DB queries when creating N columns in the new project.
  # To skip checking name uniqueness, wrap the creation code inside a `MemexProject::Copier.with_copying` block.
  # Callers SHOULD ensure that the name is unique before calling `with_copying`.
  validates_uniqueness_of :name_slug, scope: :memex_project_id, unless: -> { MemexProject::Copier.copying? || MemexProject::Migrator.migrating? }
  validate :name_does_not_contain_reserved_characters
  validate :creator_has_verified_email, on: :create
  validates :position, presence: true, numericality: { only_integer: true, greater_than: 0 }
  # Position of a column should be unique per project. However, if we are copying columns from an existing project,
  # then we skip this check because it is assumed that the validation was performed when the column was created.
  # This saves N DB queries when creating N columns in the new project.
  # To skip checking position uniqueness, wrap the creation code inside a `MemexProject::Copier.with_copying` block.
  # Callers SHOULD ensure that the position is unique before calling `with_copying`.
  validates_uniqueness_of :position, scope: :memex_project_id, unless: -> { MemexProject::Copier.copying? || MemexProject::Migrator.migrating? }
  validates :data_type, presence: true
  validates :user_defined, inclusion: { in: [true, false] }
  validates :visible, inclusion: { in: [true, false] }
  validate :default_columns_persisted, on: :create
  # Columns can only be created if the number of columns does not exceed the max number of columns. However, if we are
  # copying columns from an existing project, then we skip this check because it is assumed that the validation was
  # performed when the column was created. This saves N DB queries when creating N columns in the new project.
  # To skip checking the column limit, wrap the creation code inside a `MemexProject::Copier.with_copying` block.
  # Callers SHOULD ensure that the column limit will not be exceeded before calling `with_copying`.
  validate :column_can_be_created, on: :create, if: :user_defined?, unless: -> { MemexProject::Copier.copying? || MemexProject::Migrator.migrating? }
  validate :name_is_not_changing, on: :update, if: :system_defined?
  validate :settings_are_valid
  validate :status_settings_not_empty, on: :update
  validate :data_type_conversion_is_allowed, on: :update, if: :data_type_changed?

  # The backfill_system_defined_type_column do not use after_commit callbacks on purpose as we want to rollback the
  # transaction if the system-defined issue type column cannot be backfilled when expected.
  after_update :backfill_system_defined_type_column, if: :user_defined_type_column_is_renamed?
  after_destroy :backfill_system_defined_type_column, if: :user_defined_type_column_is_destroyed?

  after_destroy :remove_view_visibility

  after_commit :instrument_creation_event, on: :create
  after_commit :instrument_update_event, on: :update
  after_commit :update_workflow_actions, on: :update
  after_destroy_commit :instrument_deletion
  after_commit :remove_deleted_single_select_values
  after_commit :remove_deleted_iteration_values
  after_commit :queue_reindex_project_items, on: :create, if: :queue_reindex_project_items_after_create_commit?

  # Determines which column is selected by default for new Memex projects.
  attribute :default_column, :boolean, default: false

  # Determines if we need to resync project items after a new column is created. This should be enabled sparingly
  # as it will be an expensive operation.
  attr_writer :queue_reindex_project_items_after_create_commit

  # Column visibility is no longer managed by the Column.visible attribute,
  # but is instead defined on the MemexProjectView. The visible attribute
  # should be deprecated in code, but is still used in the database, so we
  # need to provide defaults when generating a column, even though they're unused.
  # `default_column` is used to determine which column are included in the MemexProject.default_view
  SYSTEM_DEFINED_COLUMNS = [
    {
      name: TITLE_COLUMN_NAME,
      data_type: :title,
      visible: true,
      default_column: true,
    },
    {
      name: ASSIGNEES_COLUMN_NAME,
      data_type: :assignees,
      visible: true,
      default_column: true,
    },
    {
      name: STATUS_COLUMN_NAME,
      data_type: :single_select,
      visible: true,
      default_column: true,
      settings: {
        # We intentionally hard-code option IDs in this configuration to make
        # sure that the client can immediately identify a single-select option
        # after a memex has been created (without refreshing the page that was
        # initialized with the default columns of a memex).
        options: [
          {
            id: "f75ad846",
            name: "Todo",
            color: "GREEN",
            description: "This item hasn't been started"
          },
          {
            id: "47fc9ee4",
            name: "In Progress",
            color: "YELLOW",
            description: "This is actively being worked on"
          },
          {
            id: "98236657",
            name: "Done",
            color: "PURPLE",
            description: "This has been completed"
          },
        ]
      }
    },
    {
      name: LABELS_COLUMN_NAME,
      data_type: :labels,
      visible: false,
    },
    {
      name: LINKED_PULL_REQUESTS_COLUMN_NAME,
      data_type: :linked_pull_requests,
      visible: false,
    },
    {
      name: MILESTONE_COLUMN_NAME,
      data_type: :milestone,
      visible: false,
    },
    {
      name: REPOSITORY_COLUMN_NAME,
      data_type: :repository,
      visible: false,
    },
    {
      name: TYPE_COLUMN_NAME,
      data_type: :issue_type,
      visible: false,
    },
    {
      name: REVIEWERS_COLUMN_NAME,
      data_type: :reviewers,
      visible: false,
    },
    {
      name: PARENT_ISSUE_COLUMN_NAME,
      data_type: :parent_issue,
      visible: false,
    },
    {
      name: SUB_ISSUES_PROGRESS_COLUMN_NAME,
      data_type: :sub_issues_progress,
      visible: false,
    },
  ]

  # Maps a column's data type to its top-level key in a `memex_project_item`'s
  # `value` for use in sorting.
  DATA_TYPE_SORT_ACCESSORS = {
    assignees: :login,
    reviewers: :name,
    labels: :name,
    linked_pull_requests: :number,
    tracks: :progress,
    milestone: :title,
    repository: :name,
    title: :title,
    text: :raw,
    number: :value,
    date: :value,
    issue_type: :name,
  }.freeze

  scope :user_defined, -> { where(user_defined: true) }
  scope :named, ->(name) { where(name: name) }
  scope :by_position_and_creation_time, -> { order(position: :asc, created_at: :asc) }

  # Returns a read-only list of MemexProjectColumn objects representing those
  # that should be included by default in a brand new memex.
  #
  # This method does is NOT guaranteed to produce identical results with each
  # invocation. For example, the generated ID of a `single_select` column's
  # options may change.
  #
  # excluding - Array<String> for the names of columns that should be excluded
  #   from the returned set of default columns. This can be used to omit a new
  #   column as part of a progressive rollout.
  #
  # Returns Array<MemexProjectColumn>.
  sig { params(excluding: T::Array[String]).returns(T::Array[MemexProjectColumn]) }
  def self.default_columns(excluding: [])
    defaults = SYSTEM_DEFINED_COLUMNS.reject { |c| excluding.include?(c[:name]) }
    defaults.each_with_index.map do |params, index|
      record = self.new(params.merge(user_defined: false, position: index + 1))
      record.normalize_settings
      record.readonly!
      record
    end
  end

  def self.default_column(name, excluding: [])
    default_columns(excluding: excluding).find { |c| c.name == name }
  end

  def self.reserved_column_names(actor: nil, owner: nil)
    RESERVED_COLUMN_NAMES.deep_dup.tap do |reserved_columns|
      if owner&.organization? && !MemexProject::Copier.copying?
        reserved_columns << TYPE_COLUMN_NAME
      end
    end
  end

  def special_type_association
    raise NotImplementedError if generic_type?

    case data_type
    when "assignees", "labels", "milestone", "repository", "issue_type"
      data_type.to_sym
    when "linked_pull_requests"
      :close_issue_references
    when "reviewers"
      :review_requests
    when "parent_issue"
      :parent_issue_relation
    when "sub_issues_progress"
      :sub_issue_list
    else
      nil
    end
  end

  def content_sort_key
    DATA_TYPE_SORT_ACCESSORS[data_type.to_sym]
  end

  def hidden?
    !visible?
  end

  def system_defined?
    !user_defined?
  end

  memoize def special_type?
    return false unless (klass = to_field_class)

    klass.special_type_serializable?
  end

  def generic_type?
    GENERIC_TYPES.include?(data_type)
  end

  def status?
    single_select? && name == STATUS_COLUMN_NAME
  end

  # The serializable ID of this column.
  #
  # For user-defined columns, this will be the ID of the column's row in the
  # database. For system-defined columns, this will be the (reserved) name of
  # the column.
  #
  # Return Integer or String.
  def synthetic_id
    user_defined? ? id : name
  end

  def to_hash(items: [], require_prefilled_associations: true, prefilled_associations: nil, redacted_issue_ids: [])
    result = {
      dataType: data_type.camelize(:lower),
      id: synthetic_id,
      databaseId: id,
      name: name,
      nameSlug: name_slug,
      position: position,
      userDefined: user_defined,
      visible: visible,
      settings: camelized_settings,
      partialFailures: prefilled_associations&.partial_failures(synthetic_id)
    }.tap do |h|
      h[:defaultColumn] = default_column? if new_record?
    end

    column_values = items.reduce([]) do |values, item|
      val = item.column_values(
        columns: [self],
        require_prefilled_associations: require_prefilled_associations,
        prefilled_associations: prefilled_associations,
        redacted_issue_ids: redacted_issue_ids
      )[0][:value]
      values << { memexProjectItemId: item.id, value: val } if val.present?
      values
    end

    result[:memexProjectColumnValues] = column_values if column_values.present?
    result
  end

  def settings_options
    (self.settings || {}).fetch("options", []).map(&:with_indifferent_access)
  end

  sig { returns(T::Array[Settings::OptionEntry]) }
  def settings_options_objects_all
    settings_options.map do |option|
      Settings::OptionEntry.new(option.symbolize_keys)
    end
  end

  # When names is nil then this method will return all option IDs (current default implementation.)
  # When names is not nil then only options that match the names will be returned.
  def settings_option_ids(names = nil)
    return [] unless single_select?

    # Ensure we are comparing downcased names to downcased names
    # The null-coalescing operator (&.) will short-circuit and return nil if titles is nil
    names = names&.map(&:downcase)&.to_set

    settings_options
      .select { |o| names.nil? || names.include?(o["name"].downcase) }
      .map { |o| o["id"] }
  end

  def single_select_option(id)
    return nil unless single_select?
    settings_options.find { |o| o["id"] == id }
  end

  sig { params(id: T.untyped).returns(T.nilable(Settings::OptionEntry)) }
  def single_select_option_object(id)
    if (option = single_select_option(id))
      Settings::OptionEntry.new(option.symbolize_keys)
    end
  end

  def settings_options_names_html
    return @settings_options_names_html if defined?(@settings_options_names_html)
    return [] unless single_select?

    settings_options.map do |option|
      {
        "id" => option["id"],
        "name" => option["name"],
        "name_html" => settings_option_name_safe_html(option)
      }
    end
  end

  def settings_iterations
    Array.wrap((self.settings || {}).dig("configuration", "iterations"))
  end

  def settings_iterations_objects_all
    (settings_iterations + settings_completed_iterations).map do |iteration|
      Settings::Iteration.new(iteration.symbolize_keys)
    end
  end

  def settings_iteration_ids
    return [] unless iteration?
    settings_iterations.map { |i| i["id"] }
  end

  def settings_iteration(id)
    return unless iteration?
    settings_iterations.find { |i| i["id"] == id }
  end

  sig { params(id: String).returns(T.nilable(T::Hash[String, T.untyped])) }
  def settings_all_iteration(id)
    return unless iteration?
    (settings_iterations + settings_completed_iterations).find { |i| i["id"] == id }
  end

  def settings_all_iterations
    (settings_completed_iterations + settings_iterations).sort_by { |i| i["start_date"] }
  end

  # When titles is nil then this method will return all iteration IDs.
  # When titles is not nil then only iterations that match the titles will be returned.
  def settings_all_iterations_ids(titles = nil)
    # Ensure we are comparing downcased titles to downcased titles
    # The null-coalescing operator (&.) will short-circuit and return nil if titles is nil
    titles = titles&.map(&:downcase)&.to_set

    settings_all_iterations
      .select { |i| titles.nil? || titles.include?(i["title"].downcase) }
      .map { |o| o["id"] }
  end

  def settings_completed_iterations
    Array.wrap((self.settings || {}).dig("configuration", "completed_iterations"))
  end

  def settings_completed_iteration_ids
    return [] unless iteration?
    settings_completed_iterations.map { |i| i["id"] }
  end

  def normalize_settings
    @normalized_settings = begin
      Settings
        .new(data_type, settings&.with_indifferent_access)
        .allocate_iterations
    rescue Settings::InitializationError
      nil
    end

    self.settings = @normalized_settings&.serialize
  end

  def generate_name_slug
    self.name_slug = name.downcase.gsub(" ", "-") if name
  end

  # support for single_select and iteration data_types
  # see app/platform/helpers/project_v2_field.rb#L10 for more details
  def platform_type_name
    @platform_type_name ||
    case data_type
    when "single_select"
      "ProjectV2SingleSelectField"
    when "iteration"
      "ProjectV2IterationField"
    else
      "ProjectV2Field"
    end
  end

  attr_writer :platform_type_name

  def async_viewer_can_update?(viewer)
    async_memex_project.then do |memex_project|
      T.must(memex_project).async_viewer_can_update?(viewer)
    end
  end

  def async_readable_by?(viewer)
    async_memex_project.then do |memex_project|
      T.must(memex_project).async_readable_by?(viewer)
    end
  end

  def sync_iteration_column_completed_iterations
    return unless iteration?
    return if settings_iterations.empty? && settings_completed_iterations.empty?

    current_settings = settings || {}
    # this method ensures that iterations are correctly ordered, deduplicated,
    # and in the correct buckets vis-a-vis completed status
    normalize_settings
    if @normalized_settings
      normalized_settings_serialized = @normalized_settings.serialize
      log_sync do
        next :skip if normalized_settings_serialized == current_settings
        update!(settings: normalized_settings_serialized)
      end
    end
  end

  private def log_sync
    result = yield
    GitHub.dogstats.increment(
      "memex_project_column.sync_iteration_column_completed_iterations",
      tags: ["skipped:#{result == :skip}"]
    )
  end

  # Returns an Integer that will be stored in the `memex_project_column_values.json_value_id` column
  # and used to index denormalized values stored for this particular type of column.
  def json_value_id(json_value)
    # The method will need to be generalized once more than milestone columns are denormalized with
    # a value containing an ID that we want to index.
    return unless milestone?
    json_value&.with_indifferent_access&.dig(:value, :id)
  end

  # Override ApplicationRecord::Base#reset_memoized_attributes to make sure that we clear memoization variables
  # on reload.
  sig { void }
  def reset_memoized_attributes
    remove_instance_variable(:@camelized_settings) if defined?(@camelized_settings)
    remove_instance_variable(:@camelized_iteration_settings) if defined?(@camelized_iteration_settings)
    remove_instance_variable(:@camelized_progress_settings) if defined?(@camelized_progress_settings)
    remove_instance_variable(:@settings_options_names_html) if defined?(@settings_options_names_html)
    remove_instance_variable(:@normalized_settings) if defined?(@normalized_settings)
    remove_instance_variable(:@insights_entity_org) if defined?(@insights_entity_org)
    remove_instance_variable(:@to_field) if defined?(@to_field)
  end

  sig { params(identifier: T.nilable(T.any(Integer, String))).returns(T.nilable(T::Boolean)) }
  def matches_identifier?(identifier)
    return false if identifier.blank?
    id.to_s == identifier.to_s || system_defined? && name.casecmp?(identifier)
  end

  private

  # Explicitly flag that we want to reindex all project items after the column is created.
  def queue_reindex_project_items_after_create_commit?
    @queue_reindex_project_items_after_create_commit
  end

  # This should only be called sparingly as it will be an expensive operation.
  sig { returns(T.nilable(ResyncMemexProjectItemsIndexJobStatus)) }
  def queue_reindex_project_items
    memex_project&.queue_reindex_items
  end

  def settings_option_name_safe_html(settings_option)
    # html_safe is safe here because the values written here are sanitized on write
    # see XSS tests in test/models/memex_project_column/settings_test.rb
    # and in test/integration/orgs/memex_project_column_options_controller_test.rb
    settings_option["name_html"].html_safe  # rubocop:disable Rails/OutputSafety
  end

  def settings_are_valid
    if normalized_settings && !normalized_settings.valid?
      normalized_settings.errors.full_messages.each { |msg| errors.add(:settings, msg.downcase) }
    end
  end

  def status_settings_not_empty
    return unless status?
    options = normalized_settings&.options || []

    if options.empty?
      errors.add(:settings, "requires a minimum of one #{STATUS_COLUMN_NAME} value")
    end
  end

  def camelized_settings
    return @camelized_settings if defined?(@camelized_settings)

    @camelized_settings = if settings && settings["options"]
      camelized_settings = settings.deep_dup
      camelized_settings["options"].each do |o|
        o["nameHtml"] = o.delete("name_html")
        # Projects not modified since color & description were added will not have these fields yet
        o["descriptionHtml"] = o.delete("description_html") || ""
        o["description"] = o["description"] || ""
        o["color"] = o["color"] || MemexProjectColumn::Settings::OptionEntry::DEFAULT_COLOR
      end
      camelized_settings

    elsif settings && settings["configuration"]
      return @camelized_iteration_settings if defined?(@camelized_iteration_settings)
      camelized_iteration_settings = settings.deep_dup
      camelized_configuration = camelized_iteration_settings["configuration"]

      camelized_configuration["startDay"] = camelized_configuration.delete("start_day")
      camelized_configuration["completedIterations"] = camelized_configuration.delete("completed_iterations")
      camelized_configuration["iterations"] = (camelized_configuration["iterations"] || [])
        .map do |i|
          h = Settings::Iteration.new(i.with_indifferent_access).attributes
          h.deep_transform_keys { |k| k.to_s.camelize(:lower) }
        end
      camelized_configuration["completedIterations"] = (camelized_configuration["completedIterations"] || [])
        .map do |i|
          h = Settings::Iteration.new(i.with_indifferent_access).attributes
          h.deep_transform_keys { |k| k.to_s.camelize(:lower) }
        end
      @camelized_iteration_settings = camelized_iteration_settings

    elsif settings && settings["progress_configuration"]
      return @camelized_progress_settings if defined?(@camelized_progress_settings)
      @camelized_progress_settings = settings.deep_dup.deep_transform_keys { |key| key.camelize(:lower) }

    else
      settings
    end
  end

  def name_is_not_reserved
    return unless changed_attributes.keys.include?("name")
    return unless user_defined?

    reserved_columns = self.class.reserved_column_names(actor: actor, owner: memex_project&.owner)

    if reserved_columns.any? { |r| r.casecmp?(name) }
      errors.add(:name, "cannot have a reserved value")
    end
  end

  def name_does_not_contain_reserved_characters
    return unless changed_attributes.keys.include?("name")
    return unless user_defined?

    if RESERVED_COLUMN_NAME_CHARACTERS.any? { |c| name.include?(c) }
      characters = RESERVED_COLUMN_NAME_CHARACTERS.join(", ")
      errors.add(:name, "cannot contain any of the following characters: #{characters}")
    end
  end

  def creator_has_verified_email
    return unless GitHub.email_verification_enabled?

    return unless user_defined?

    return if creator&.bot?

    errors.add(:creator, "must have a verified email address") unless creator&.verified_emails?
  end

  def default_columns_persisted
    return unless user_defined?

    unless memex_project&.memex_project_columns&.any?(&:system_defined?)
      errors.add(:user_defined, "column cannot be added until default columns have been persisted")
    end
  end

  def column_can_be_created
    return unless (project = memex_project)

    if project.memex_project_columns.count >= MemexProject::COLUMN_LIMIT
      errors.add(:base, "Projects cannot have more than #{MemexProject::COLUMN_LIMIT} fields, including default and custom fields")
    end
  end

  def name_is_not_changing
    if changed_attributes.keys.include?("name")
      errors.add(:name, "cannot be changed for a system defined column")
    end
  end

  def instrument_creation_event
    # system defined columns are created by the system, so don't need to be tracked to an actor
    return unless user_defined?

    GlobalInstrumenter.instrument "memex_event", {
      actor: actor,
      memex_project: memex_project,
      memex_project_column: self,
      performed_at: Time.current,
      name: ON_CREATE_INSTRUMENTATION_KEY
    }
    instrument :create, prefix: "project_field"
  end

  def instrument_update_event
    GlobalInstrumenter.instrument "memex_project_column.update", {
      actor: actor,
      memex_project: memex_project,
      memex_project_column: self,
      performed_at: Time.current,
    }
    instrument :update, prefix: "project_field"
  end

  def instrument_deletion
    GlobalInstrumenter.instrument "memex_project_column.delete", {
      actor: actor,
      memex_project: memex_project,
      memex_project_column: self,
      performed_at: Time.current,
    }
    instrument :delete, prefix: "project_field"
  end

  def event_payload
    payload = {
      project_field: self,
      project_number: memex_project&.number,
      project: memex_project,
      public_project: memex_project&.public?,
      actor: actor,
      performed_at: Time.current,
    }.tap do |p|
      owner = memex_project&.owner

      p[owner.event_prefix] = owner if owner
    end
    payload
  end

  # Dig out previous options, if any. Represent the state of no previous
  # options with an empty array, for return type consistency.
  #
  # Returns Array
  def previous_options
    self.previous_changes.dig("settings", 0, "options") || []
  end

  # Designed to run after commit (or other event where we don't yet know what
  # kind of column we're dealing with), this checks to see if the options for
  # a single-select column changed.
  #
  # Returns Boolean
  def options_changed?
    return false unless self.single_select?
    return false unless self.previous_changes["settings"]
    return false if previous_options.empty?
    true
  end

  # Designed to run after commit, this derives the ids of any options that were
  # removed from a single-select column's settings.
  #
  # Returns Array<String>
  def diff_options_removed
    previous_option_ids = previous_options.map { |o| o["id"] }
    diff = previous_option_ids - settings_option_ids
    diff
  end

  def remove_deleted_single_select_values
    return false unless options_changed?
    removed_option_ids = diff_options_removed
    RemoveMemexProjectColumnValuesJob.perform_later(self.id, removed_option_ids)
  end

  # When an option is removed from a single-select column's settings, we may
  # need to update workflows and/or workflow actions that were configured to
  # use the option that has now been deleted.
  #
  # Returns nothing
  def update_workflow_actions
    return unless options_changed?

    removed_option_ids = diff_options_removed
    return if removed_option_ids.empty?
    DisableMemexWorkflowsWithInvalidOptionJob.perform_later(column_id: self.id, removed_option_ids: removed_option_ids)
  end

  def user_defined_type_column_is_renamed?
    user_defined? && name_previously_changed? && name_previously_was.casecmp?(MemexProjectColumn::TYPE_COLUMN_NAME)
  end

  def user_defined_type_column_is_destroyed?
    destroyed? && user_defined? && name.casecmp?(MemexProjectColumn::TYPE_COLUMN_NAME)
  end

  def backfill_system_defined_type_column
    return unless (project = memex_project)
    return unless project.org_owned?

    issue_type_column = project.backfill_issue_type_column

    if issue_type_column.persisted? && issue_type_column.previously_new_record?
      GitHub.dogstats.increment("memex_project_column.backfill_issue_type_column", tags: ["result:success"])
    elsif issue_type_column.invalid?
      GitHub.dogstats.increment("memex_project_column.backfill_issue_type_column", tags: ["result:error"])
      errors.add(:base, :issue_type_column_backfill_failed)

      # Report a custom user error to monitor errors backfilling system-defined Type column
      err = IssueTypeColumnBackfillError.new(issue_type_column)
      Failbot.report_user_error(err, memex_project_id: project.id)

      raise ActiveRecord::Rollback
    end
  end

  def remove_deleted_iteration_values
    return unless self.iteration?
    return unless self.previous_changes.dig("settings")
    # If there were no previous iterations, there's nothing to clean up
    return unless previous_iterations = self.previous_changes.dig("settings", 0, "configuration", "iterations")
    return unless previous_completed_iterations = self.previous_changes.dig("settings", 0, "configuration", "completed_iterations")

    # handle cases where any of these values are nil and ensure an array is returned
    candidate_iterations = [previous_iterations, previous_completed_iterations].compact.reduce([], :|)
    previous_iteration_ids = candidate_iterations.map { |o| o["id"] }

    RemoveMemexProjectColumnValuesJob.perform_later(self.id, (previous_iteration_ids - settings_iteration_ids - settings_completed_iteration_ids))
  end

  def remove_view_visibility
    return unless memex_project
    memex_project&.memex_project_views&.map { |view| view.remove_column!(self) }
  end
end
