# typed: true
# frozen_string_literal: true

require "prime"

module GitHub
  module SSH
    extend self

    # To help with coordinated disclosure of incidents, you can mark a blocklist file as requiring a feature flag
    # Add an entry to this map where the key is the filename of the blocklist within config/ssh_key_blocklists, and the value is a feature flag symbol
    # If that feature flag is not enabled, the block list will be ignored.
    FEATURE_FLAGS = {
      # Example:
      # "blocklist.some-security-incident": :blocklist_some_security_incident
    }

    ALL_BLOCKLISTS = Dir[Rails.root.join("config/ssh_key_blocklists/blocklist.*")].to_a.freeze

    def active_blocklists
      ALL_BLOCKLISTS.filter do |path|
        name = File.basename(path)
        flag = FEATURE_FLAGS[name.to_sym]

        # If there's no flag for this block list, enable it.
        next true if flag.nil?

        # Otherwise, enable it if the flag is active.
        GitHub.flipper[flag].enabled?(GitHub::FlipperRole.local_role)
      end
    end

    # Check if the specified key is known to have been compromised.
    #
    # key - a SSHData::PublicKey::Base instance
    #
    # Returns boolean.
    def blocklisted_key?(key)
      result = Progeny::Command.new("grep #{Shellwords.shellescape(key.fingerprint)} #{active_blocklists.join(" ")}")

      if result.status.exitstatus > 1
        Kernel.raise "error checking for compromised key"
      end

      blocked = !result.out.empty?
      if blocked
        # Count attempted uses of blocked keys, to help us decide whether to
        # remove key blocklists
        GitHub.dogstats.increment("ssh.key.blocked")
      end

      blocked
    end

    # Check for security problems with an RSA key.
    #
    # key - An OpenSSL::PKey::RSA instance.
    #
    # Returns boolean.
    def weak_rsa_key?(key)
      small_prime_factor?(key) || infineon?(key)
    end

    # First 10000 primes.
    #
    # Returns an Array of OpenSSL::BN.
    def small_primes
      @small_primes ||= T.must(Prime.first(10000)).map(&:to_bn).freeze
    end

    # Verify that this key's modulus is not trivially factorable.
    #
    # key - An OpenSSL::PKey::RSA instance.
    #
    # Returns boolean.
    def small_prime_factor?(key)
      n = key.params["n"]
      small_primes.any? { |prime| (n % prime).zero? }
    end

    # Large int workaround is documented here: https://sorbet.org/docs/error-reference#3002
    INFIEON_FINGERPRINT_ALLOWLIST = {
      3   => 6,
      5   => 30,
      7   => 126,
      11  => 1026,
      13  => 5658,
      17  => 107286,
      19  => 199410,
      23  => 8388606,
      29  => 536870910,
      31  => 2147483646,
      37  => 67109890,
      41  => 2199023255550,
      43  => 8796093022206,
      47  => 140737488355326,
      53  => 5310023542746834,
      59  => 576460752303423486,
      61  => 1455791217086302986,
      67  => "147573952589676412926".to_i,
      71  => "20052041432995567486".to_i,
      73  => "6041388139249378920330".to_i,
      79  => "207530445072488465666".to_i,
      83  => "9671406556917033397649406".to_i,
      89  => "618970019642690137449562110".to_i,
      97  => "79228162521181866724264247298".to_i,
      101 => "2535301200456458802993406410750".to_i,
      103 => "1760368345969468176824550810518".to_i,
      107 => "50079290986288516948354744811034".to_i,
      109 => "473022961816146413042658758988474".to_i,
      113 => "10384593717069655257060992658440190".to_i,
      127 => "144390480366845522447407333004847678774".to_i,
      131 => "2722258935367507707706996859454145691646".to_i,
      137 => "174224571863520493293247799005065324265470".to_i,
      139 => "696898287454081973172991196020261297061886".to_i,
      149 => "713623846352979940529142984724747568191373310".to_i,
      151 => "1800793591454480341970779146165214289059119882".to_i,
      157 => "126304807362733370595828809000324029340048915994".to_i,
      163 => "11692013098647223345629478661730264157247460343806".to_i,
      167 => "187072209578355573530071658587684226515959365500926".to_i,
    }.map { |p, f| [p.to_bn, f.to_bn] }

    # This checks for keys generated by Infineon chips that are vulnerable to
    # CVE-2017-15361.
    #
    # https://www.yubico.com/support/security-advisories/ysa-2017-01/
    #
    # key - An OpenSSL::PKey::RSA instance.
    #
    # Returns boolean.
    def infineon?(key)
      n = key.params["n"]
      INFIEON_FINGERPRINT_ALLOWLIST.none? do |prime, fingerprint|
        !fingerprint.bit_set?(n % prime)
      end
    end
  end
end
