# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/github/v1/feature_preview_open_modal_click.proto

require 'google/protobuf'

require 'hydro/schemas/github/v1/entities/request_context_pb'
require 'hydro/schemas/github/v1/entities/user_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.github.v1.FeaturePreviewOpenModalClick" do
    optional :request_context, :message, 1, "hydro.schemas.github.v1.entities.RequestContext"
    optional :user, :message, 2, "hydro.schemas.github.v1.entities.User"
    optional :link_location, :enum, 3, "hydro.schemas.github.v1.FeaturePreviewOpenModalClick.LinkLocation"
  end
  add_enum "hydro.schemas.github.v1.FeaturePreviewOpenModalClick.LinkLocation" do
    value :UNKNOWN, 0
    value :USER_DROPDOWN, 1
    value :NOTIFICATIONS, 2
  end
end

module Hydro
  module Schemas
    module Github
      module V1
        FeaturePreviewOpenModalClick = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.v1.FeaturePreviewOpenModalClick").msgclass
        FeaturePreviewOpenModalClick::LinkLocation = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.v1.FeaturePreviewOpenModalClick.LinkLocation").enummodule
      end
    end
  end
end
