# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/github/v1/gist_update.proto

require 'google/protobuf'

require 'hydro/schemas/github/v1/entities/gist_pb'
require 'hydro/schemas/github/v1/entities/gist_file_pb'
require 'hydro/schemas/github/v1/entities/specimen_data_pb'
require 'hydro/schemas/github/v1/entities/request_context_pb'
require 'hydro/schemas/github/v1/entities/spamurai_form_signals_pb'
require 'hydro/schemas/github/v1/entities/user_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.github.v1.GistUpdate" do
    optional :request_context, :message, 1, "hydro.schemas.github.v1.entities.RequestContext"
    optional :actor, :message, 2, "hydro.schemas.github.v1.entities.User"
    optional :previous_gist, :message, 3, "hydro.schemas.github.v1.entities.Gist"
    optional :current_gist, :message, 4, "hydro.schemas.github.v1.entities.Gist"
    optional :previous_head_sha, :string, 5
    optional :current_head_sha, :string, 6
    repeated :previous_files, :message, 7, "hydro.schemas.github.v1.entities.GistFile"
    repeated :current_files, :message, 8, "hydro.schemas.github.v1.entities.GistFile"
    optional :spamurai_form_signals, :message, 9, "hydro.schemas.github.v1.entities.SpamuraiFormSignals"
    repeated :specimen_files, :message, 10, "hydro.schemas.github.v1.entities.SpecimenData"
    optional :specimen_gist_description, :message, 11, "hydro.schemas.github.v1.entities.SpecimenData"
    repeated :specimen_files_path, :message, 12, "hydro.schemas.github.v1.entities.SpecimenData"
    repeated :feature_flags, :string, 13
  end
end

module Hydro
  module Schemas
    module Github
      module V1
        GistUpdate = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.v1.GistUpdate").msgclass
      end
    end
  end
end
