# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/github/v1/milestone_update.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'hydro/schemas/github/v1/entities/user_pb'
require 'hydro/schemas/github/v1/entities/milestone_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.github.v1.MilestoneUpdate" do
    optional :actor, :message, 1, "hydro.schemas.github.v1.entities.User"
    optional :milestone, :message, 2, "hydro.schemas.github.v1.entities.Milestone"
    optional :previous_title, :string, 3
    optional :previous_description, :string, 4
    optional :previous_state, :string, 5
    optional :previous_due_on, :message, 6, "google.protobuf.Timestamp"
  end
end

module Hydro
  module Schemas
    module Github
      module V1
        MilestoneUpdate = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.v1.MilestoneUpdate").msgclass
      end
    end
  end
end
