# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/github/v1/pull_request_merge_external.proto

require 'google/protobuf'

require 'hydro/schemas/github/v1/entities/user_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.github.v1.PullRequestMergeExternal" do
    optional :actor, :message, 1, "hydro.schemas.github.v1.entities.User"
    optional :client_type, :enum, 2, "hydro.schemas.github.v1.PullRequestMergeExternal.ClientType"
  end
  add_enum "hydro.schemas.github.v1.PullRequestMergeExternal.ClientType" do
    value :GIT, 0
    value :DESKTOP, 1
  end
end

module Hydro
  module Schemas
    module Github
      module V1
        PullRequestMergeExternal = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.v1.PullRequestMergeExternal").msgclass
        PullRequestMergeExternal::ClientType = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.v1.PullRequestMergeExternal.ClientType").enummodule
      end
    end
  end
end
