# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/github/v1/sso_page_view.proto

require 'google/protobuf'

require 'hydro/schemas/github/v1/entities/request_context_pb'
require 'hydro/schemas/github/v1/entities/user_pb'
require 'hydro/schemas/github/v1/entities/organization_pb'
require 'hydro/schemas/github/v1/entities/business_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.github.v1.SsoPageView" do
    optional :request_context, :message, 1, "hydro.schemas.github.v1.entities.RequestContext"
    optional :user, :message, 2, "hydro.schemas.github.v1.entities.User"
    optional :org, :message, 3, "hydro.schemas.github.v1.entities.Organization"
    optional :business, :message, 4, "hydro.schemas.github.v1.entities.Business"
  end
end

module Hydro
  module Schemas
    module Github
      module V1
        SsoPageView = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.v1.SsoPageView").msgclass
      end
    end
  end
end
