# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Hydro::Schemas::Github::Database::V0::MaxExecutionTime`.
# Please instead update this file by running `bin/tapioca dsl Hydro::Schemas::Github::Database::V0::MaxExecutionTime`.


class Hydro::Schemas::Github::Database::V0::MaxExecutionTime < Google::Protobuf::AbstractMessage
  sig do
    params(
      app: T.nilable(String),
      catalog_service: T.nilable(String),
      category: T.nilable(String),
      cluster_name: T.nilable(String),
      deployed_to: T.nilable(String),
      digest: T.nilable(String),
      fingerprint: T.nilable(String),
      job: T.nilable(String),
      job_id: T.nilable(String),
      length_trimmed: T.nilable(Integer),
      length_untrimmed: T.nilable(Integer),
      name: T.nilable(String),
      package: T.nilable(String),
      query: T.nilable(String),
      query_trimmed: T.nilable(String),
      request_id: T.nilable(String),
      route: T.nilable(String),
      schema: T.nilable(String),
      server: T.nilable(String),
      time: T.nilable(Integer),
      type: T.nilable(String),
      user: T.nilable(String)
    ).void
  end
  def initialize(app: nil, catalog_service: nil, category: nil, cluster_name: nil, deployed_to: nil, digest: nil, fingerprint: nil, job: nil, job_id: nil, length_trimmed: nil, length_untrimmed: nil, name: nil, package: nil, query: nil, query_trimmed: nil, request_id: nil, route: nil, schema: nil, server: nil, time: nil, type: nil, user: nil); end

  sig { returns(String) }
  def app; end

  sig { params(value: String).void }
  def app=(value); end

  sig { returns(String) }
  def catalog_service; end

  sig { params(value: String).void }
  def catalog_service=(value); end

  sig { returns(String) }
  def category; end

  sig { params(value: String).void }
  def category=(value); end

  sig { void }
  def clear_app; end

  sig { void }
  def clear_catalog_service; end

  sig { void }
  def clear_category; end

  sig { void }
  def clear_cluster_name; end

  sig { void }
  def clear_deployed_to; end

  sig { void }
  def clear_digest; end

  sig { void }
  def clear_fingerprint; end

  sig { void }
  def clear_job; end

  sig { void }
  def clear_job_id; end

  sig { void }
  def clear_length_trimmed; end

  sig { void }
  def clear_length_untrimmed; end

  sig { void }
  def clear_name; end

  sig { void }
  def clear_package; end

  sig { void }
  def clear_query; end

  sig { void }
  def clear_query_trimmed; end

  sig { void }
  def clear_request_id; end

  sig { void }
  def clear_route; end

  sig { void }
  def clear_schema; end

  sig { void }
  def clear_server; end

  sig { void }
  def clear_time; end

  sig { void }
  def clear_type; end

  sig { void }
  def clear_user; end

  sig { returns(String) }
  def cluster_name; end

  sig { params(value: String).void }
  def cluster_name=(value); end

  sig { returns(String) }
  def deployed_to; end

  sig { params(value: String).void }
  def deployed_to=(value); end

  sig { returns(String) }
  def digest; end

  sig { params(value: String).void }
  def digest=(value); end

  sig { returns(String) }
  def fingerprint; end

  sig { params(value: String).void }
  def fingerprint=(value); end

  sig { returns(String) }
  def job; end

  sig { params(value: String).void }
  def job=(value); end

  sig { returns(String) }
  def job_id; end

  sig { params(value: String).void }
  def job_id=(value); end

  sig { returns(Integer) }
  def length_trimmed; end

  sig { params(value: Integer).void }
  def length_trimmed=(value); end

  sig { returns(Integer) }
  def length_untrimmed; end

  sig { params(value: Integer).void }
  def length_untrimmed=(value); end

  sig { returns(String) }
  def name; end

  sig { params(value: String).void }
  def name=(value); end

  sig { returns(String) }
  def package; end

  sig { params(value: String).void }
  def package=(value); end

  sig { returns(String) }
  def query; end

  sig { params(value: String).void }
  def query=(value); end

  sig { returns(String) }
  def query_trimmed; end

  sig { params(value: String).void }
  def query_trimmed=(value); end

  sig { returns(String) }
  def request_id; end

  sig { params(value: String).void }
  def request_id=(value); end

  sig { returns(String) }
  def route; end

  sig { params(value: String).void }
  def route=(value); end

  sig { returns(String) }
  def schema; end

  sig { params(value: String).void }
  def schema=(value); end

  sig { returns(String) }
  def server; end

  sig { params(value: String).void }
  def server=(value); end

  sig { returns(Integer) }
  def time; end

  sig { params(value: Integer).void }
  def time=(value); end

  sig { returns(String) }
  def type; end

  sig { params(value: String).void }
  def type=(value); end

  sig { returns(String) }
  def user; end

  sig { params(value: String).void }
  def user=(value); end
end
