# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Mvnd::Migrations::Api::V1::Entities::InitialOrganizationSettings`.
# Please instead update this file by running `bin/tapioca dsl Mvnd::Migrations::Api::V1::Entities::InitialOrganizationSettings`.


class Mvnd::Migrations::Api::V1::Entities::InitialOrganizationSettings < Google::Protobuf::AbstractMessage
  sig do
    params(
      member_privileges: T.nilable(Mvnd::Migrations::Api::V1::Entities::MemberPrivileges),
      organization_resource_id: T.nilable(String),
      repository_default: T.nilable(Mvnd::Migrations::Api::V1::Entities::RepositoryDefault),
      resource_id: T.nilable(String),
      webhooks: T.nilable(T.any(Google::Protobuf::RepeatedField[Mvnd::Migrations::Api::V1::Entities::Webhook], T::Array[Mvnd::Migrations::Api::V1::Entities::Webhook]))
    ).void
  end
  def initialize(member_privileges: nil, organization_resource_id: nil, repository_default: nil, resource_id: nil, webhooks: T.unsafe(nil)); end

  sig { void }
  def clear_member_privileges; end

  sig { void }
  def clear_organization_resource_id; end

  sig { void }
  def clear_repository_default; end

  sig { void }
  def clear_resource_id; end

  sig { void }
  def clear_webhooks; end

  sig { returns(Object) }
  def has_member_privileges?; end

  sig { returns(Object) }
  def has_repository_default?; end

  sig { returns(T.nilable(Mvnd::Migrations::Api::V1::Entities::MemberPrivileges)) }
  def member_privileges; end

  sig { params(value: T.nilable(Mvnd::Migrations::Api::V1::Entities::MemberPrivileges)).void }
  def member_privileges=(value); end

  sig { returns(String) }
  def organization_resource_id; end

  sig { params(value: String).void }
  def organization_resource_id=(value); end

  sig { returns(T.nilable(Mvnd::Migrations::Api::V1::Entities::RepositoryDefault)) }
  def repository_default; end

  sig { params(value: T.nilable(Mvnd::Migrations::Api::V1::Entities::RepositoryDefault)).void }
  def repository_default=(value); end

  sig { returns(String) }
  def resource_id; end

  sig { params(value: String).void }
  def resource_id=(value); end

  sig { returns(Google::Protobuf::RepeatedField[Mvnd::Migrations::Api::V1::Entities::Webhook]) }
  def webhooks; end

  sig { params(value: Google::Protobuf::RepeatedField[Mvnd::Migrations::Api::V1::Entities::Webhook]).void }
  def webhooks=(value); end
end
