# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Mvnd::Migrations::Api::V1::Entities::Issue`.
# Please instead update this file by running `bin/tapioca dsl Mvnd::Migrations::Api::V1::Entities::Issue`.


class Mvnd::Migrations::Api::V1::Entities::Issue < Google::Protobuf::AbstractMessage
  sig do
    params(
      assignees_resource_ids: T.nilable(T.any(Google::Protobuf::RepeatedField[String], T::Array[String])),
      attachment_resource_ids: T.nilable(T.any(Google::Protobuf::RepeatedField[String], T::Array[String])),
      body: T.nilable(String),
      closed_at: T.nilable(Google::Protobuf::Timestamp),
      created_at: T.nilable(Google::Protobuf::Timestamp),
      labels: T.nilable(T.any(Google::Protobuf::RepeatedField[String], T::Array[String])),
      resource_id: T.nilable(String),
      title: T.nilable(String),
      updated_at: T.nilable(Google::Protobuf::Timestamp),
      user_resource_id: T.nilable(String)
    ).void
  end
  def initialize(assignees_resource_ids: T.unsafe(nil), attachment_resource_ids: T.unsafe(nil), body: nil, closed_at: nil, created_at: nil, labels: T.unsafe(nil), resource_id: nil, title: nil, updated_at: nil, user_resource_id: nil); end

  sig { returns(Google::Protobuf::RepeatedField[String]) }
  def assignees_resource_ids; end

  sig { params(value: Google::Protobuf::RepeatedField[String]).void }
  def assignees_resource_ids=(value); end

  sig { returns(Google::Protobuf::RepeatedField[String]) }
  def attachment_resource_ids; end

  sig { params(value: Google::Protobuf::RepeatedField[String]).void }
  def attachment_resource_ids=(value); end

  sig { returns(String) }
  def body; end

  sig { params(value: String).void }
  def body=(value); end

  sig { void }
  def clear_assignees_resource_ids; end

  sig { void }
  def clear_attachment_resource_ids; end

  sig { void }
  def clear_body; end

  sig { void }
  def clear_closed_at; end

  sig { void }
  def clear_created_at; end

  sig { void }
  def clear_labels; end

  sig { void }
  def clear_resource_id; end

  sig { void }
  def clear_title; end

  sig { void }
  def clear_updated_at; end

  sig { void }
  def clear_user_resource_id; end

  sig { returns(T.nilable(Google::Protobuf::Timestamp)) }
  def closed_at; end

  sig { params(value: T.nilable(Google::Protobuf::Timestamp)).void }
  def closed_at=(value); end

  sig { returns(T.nilable(Google::Protobuf::Timestamp)) }
  def created_at; end

  sig { params(value: T.nilable(Google::Protobuf::Timestamp)).void }
  def created_at=(value); end

  sig { returns(Object) }
  def has_closed_at?; end

  sig { returns(Object) }
  def has_created_at?; end

  sig { returns(Object) }
  def has_updated_at?; end

  sig { returns(Google::Protobuf::RepeatedField[String]) }
  def labels; end

  sig { params(value: Google::Protobuf::RepeatedField[String]).void }
  def labels=(value); end

  sig { returns(String) }
  def resource_id; end

  sig { params(value: String).void }
  def resource_id=(value); end

  sig { returns(String) }
  def title; end

  sig { params(value: String).void }
  def title=(value); end

  sig { returns(T.nilable(Google::Protobuf::Timestamp)) }
  def updated_at; end

  sig { params(value: T.nilable(Google::Protobuf::Timestamp)).void }
  def updated_at=(value); end

  sig { returns(String) }
  def user_resource_id; end

  sig { params(value: String).void }
  def user_resource_id=(value); end
end
