#!/bin/bash
#/ Usage: script/alive-server
#/
#/ Runs the alive service.


SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
source $SCRIPT_DIR/dx/lib/subproject-containers

SUBPROJECT_VERSION=$(subproject_version "alive")
echo "alive version $SUBPROJECT_VERSION"

# Run the service.
start_subproject --name alive --entrypoint "/go/bin/alive-local" \
  -e ALIVE_ADDR=127.0.0.1:3002 \
  -e ALIVE_FE_INTERNAL_ADDR=127.0.0.1:6060 \
  -e ALIVE_KAFKA_BROKERS=127.0.0.1:9092 \
  -e ALIVE_KAFKA_VERSION=1.1.1 \
  -e ALIVE_AUTHZD_ENDPOINT=http://127.0.0.1:8091 \
  -e ALIVE_FE_ORIGINS='github.localhost,github.localhost:*,*.ghe.localhost,*.ghe.localhost:*' \
  -e ALIVE_SECRETS=2554d23ebb5f6e12bfa0b39e64df2886 \
  -e ALIVE_ENCRYPTION_KEYS=a1epVZRjhoXUUnml9+EJLA== \
  -e ALIVE_FE_SHUTDOWN_TIME=3s \
  -e ALIVE_PRESENCE_ENABLED=true \
  -e ALIVE_REDIS=redis://127.0.0.1:6379/4 \
  -e ALIVE_RUN_MULTIPLE=true \
  -e ALIVE_ROUTER_INTERNAL_ADDR=:6062 \
  "ghcr.io/github/alive/alive-local:$SUBPROJECT_VERSION"
