#!/usr/bin/env safe-ruby
# frozen_string_literal: true

#
# Usage: ./script/background-jobs-invalid-queues <environment>
# Gets the invalid job queues for an environment.
# - Environments available: dotcom, proxima, enterprise, staff, development
#
# A queue becomes invalid within an environment either when:
# - There is no corresponding configuration for that particular environment.
# - The job queue configuration explicitly indicates that it should not be executed there.

queues_environment = ARGV.shift or abort "usage: script/background-jobs-invalid-queues <environment>"

require_relative "../config/environment"
require_relative "../lib/background_job_queues"

def get_invalid_queues_for_environment(environment)
  allowed_environments = BackgroundJobQueues.allowed_environments
  if allowed_environments.include?(environment)
    BackgroundJobQueues.invalid_queue_configurations(environment: environment.to_sym).keys
  else
    puts "Wrong environment. Try one of these: #{allowed_environments.join(",")}"
  end
end

puts get_invalid_queues_for_environment(queues_environment)
