#!/bin/bash
#/ Usage: build-cache_go
#/
#/ Build and install the version specified in config/cache_go-version.
#/ This is run automatically by script/bootstrap for all development environments.
#/
set -e
unset CDPATH

# show usage
if [ "$1" = "--help" ]; then
    grep ^#/ <"$0" |cut -c4-
    exit
fi

# change into root project dir
cd "$(dirname "$0")/.."

# revision where we should build
pinned=$(grep -v ^# config/cache_go-version)
revision="${1:-$pinned}"
short_revision="$(echo $revision | cut -c1-10)"

# cache_go repository URL to clone from. this assumes that SSH is setup properly for
# the current user.
giturl="$(./script/gh-clone-url github/cache_go)"

# build path locations
builddir="vendor/cache_go"
installdir="script/ci/bin"
logfile="log/cache_go-build.log"

# fetch the remote repository into the builddir
fetch() {
    progress=
    [ -t 1 ] && progress="--progress"
    git --git-dir="$builddir/.git" \
        fetch -u -q $progress --prune --force "$giturl" "+refs/heads/*:refs/heads/*"
}

check_cache_go() {
    if [ "$revision" = "$(cat "$installdir/cache_go-version" 2>/dev/null)" ] && [ -x "$installdir/cache_go" ]; then
        return 0
    else
        return 1
    fi
}

# bail if the already built revision is up-to-date
if check_cache_go; then
    echo "cache_go build $short_revision is up-to-date."
    exit 0
fi

# clone or fetch the git repo if needed
if [ ! -d "$builddir/.git" ]; then
    echo "Fetching $giturl for the first time. This may take a while." 2>&1
    git init -q "$builddir"
    fetch
elif [ "$pinned" != "$revision" ]; then
    echo "Fetching $giturl for update ..." 2>&1
    fetch
elif ! git --git-dir="$builddir/.git" cat-file -e "$revision" 2>/dev/null; then
    echo "Fetching $giturl for update ..." 2>&1
    fetch
fi

# resolve requested revision to commit oid.
commit=$(git --git-dir="$builddir/.git" rev-parse --verify -q "$revision" || true)
if ! git --git-dir="$builddir/.git" cat-file -e "$commit" 2>/dev/null ; then
    echo "ERROR: Revision not found: $revision" 2>&1
    exit 1
fi

# prep install dir
mkdir -p "$installdir"
prefix=$(cd "$installdir" && pwd)

# change in and build some stuff
echo "cache_go build at $(echo $commit | cut -c1-10) commencing (see $logfile) ..."
set +e
(
    set -ex
    echo "Building cache_go at $(echo $commit | cut -c1-10) ..."
    cd "$builddir"
    # [ ! -e ssh_host_key.dev ] && ssh-keygen -N "" -m PEM -t rsa -f ssh_host_key.dev
    # [ ! -e dss_host_key.dev ] && ssh-keygen -N "" -m PEM -t ssh-dss -f dss_host_key.dev
    time git --git-dir=".git" --work-tree="." reset --hard "$commit"
    time go mod vendor
    time go build -o "$prefix/cache_go" -v -ldflags "-s -w" ./cmd/cache_go/main.go
) 1> "$logfile" 2>&1
res=$?
set -e

# check for failure
if [ $res -ne 0 ]; then
    echo "!! cache_go build failed oh no. The last lines of output follow:" 2>&1
    tail -n 100 "$logfile"
    echo "** See $logfile for more ..." 2>&1
    exit $res
fi

# write the current build version file
echo "$commit" > "$installdir/cache_go-version"

# if a <branch> was given, and it resolves
cat <<-EOF > config/cache_go-version
# cache_go version built into development environments.
# See 'script/build-cache_go --help' for info on changing this file.
$commit
EOF

echo "$installdir/cache_go installed at $installdir."
true
