#!/bin/bash

set -eou pipefail

script/checkout-subproject sarif-gem

RUBY="/workspaces/github/bin/safe-ruby-quick"
BUNDLE="${RUBY} /workspaces/github/vendor/ruby/current/bin/bundle"

(cd vendor/sarif-gem \
  && ${BUNDLE} install \
  && ${BUNDLE} exec rake native gem \
  && cp "$(${RUBY} -r rubygems -e 'puts "pkg/#{Gem::Specification::load("sarif.gemspec").full_name}-#{RUBY_PLATFORM}.gem"')" /workspaces/github/vendor/cache/ \
)
