#!/bin/bash
set -e

root=$(cd $(dirname "$0")/.. && pwd)

case "$1" in
'' | install | update ) mode=command ;;
* ) mode=exec ;;
esac

$mode "$root/bin/safe-ruby-quick" "$root/vendor/ruby/current/bin/bundle" "$@"

"$root/script/bundler-rebuild-tapioca-gem-rbis"
