#!/bin/bash
set -e

root=$(cd $(dirname "$0")/.. && pwd)

if [ -z "$BOOTSTRAPPING" ] &&
   [ -z "$GITHUB_SKIP_RBI" ] &&
   [ -z "$ENTERPRISE" ] &&
   [ "$RAILS_ENV" != "production" ]
then

echo
echo "**********************************************"
echo "Attempting to automatically rebuild RBI files."
echo "Please report any issues to #sorbet in Slack."
echo "**********************************************"
echo

"$root/bin/tapioca" gem

echo
echo "**********************************************"
echo "RBI generation complete!"
echo "**********************************************"
echo

fi
