#!/bin/bash -e
#
# Remove files no longer needed after bootstrapping.
# This reduces the size of the golden image.
#
rm -rf vendor/ruby/src vendor/dogstats vendor/cache_go

echo "vendor size after cleaning: $(du -sh vendor | awk '{ print $1 }')"
