#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../config/environment"

processor = CodeQuality::PullRequestAnalysisProcessor.new
consumer = GitHub.hydro_consumer(processor.options)

GitHub.hydro_client.run(processor, consumer: consumer, shutdown_signals: [:INT, :TERM])
