#!/bin/bash

RUBY_NEXT_SHA=$(sed -n 's/^RUBY_NEXT_SHA="\([^"]*\)"/\1/p' config/ruby-version)

git fetch --no-tags https://github.com/ruby/ruby.git master >/dev/null 2>&1

COMMITS_BEHIND=""
for i in {1..10}; do
  # Calculate the number of commits from RUBY_NEXT_SHA to HEAD of master
  if COMMITS_BEHIND=$(git rev-list --count ${RUBY_NEXT_SHA}..FETCH_HEAD 2>/dev/null); then
    break
  fi
  # The commit likely belongs to a fork, so we try to loop through the parents
  # until we find a SHA that belongs to the main repository.
  PARENT_SHA=$(gh api \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    /repos/ruby/ruby/commits/$RUBY_NEXT_SHA \
    2>/dev/null | jq -r '.parents[0].sha')
  if [ -z "$PARENT_SHA" ] || [ "$PARENT_SHA" = "null" ]; then
    COMMITS_BEHIND=""
    break
  fi
  RUBY_NEXT_SHA="$PARENT_SHA"
done

if [ -z "$COMMITS_BEHIND" ]; then
  exit 1
fi

echo "$COMMITS_BEHIND"
