#!/bin/bash

RAILS_SHA=$(sed -n 's/^rails_version = "[^"]*\.\([a-f0-9]\{7,40\}\)"/\1/p' Gemfile)

git fetch --no-tags https://github.com/rails/rails.git main >/dev/null 2>&1

COMMITS_BEHIND=""
for i in {1..10}; do
  # Calculate the number of commits from RAILS_SHA to HEAD of main
  if COMMITS_BEHIND=$(git rev-list --count ${RAILS_SHA}..FETCH_HEAD 2>/dev/null); then
    break
  fi
  # The commit likely belongs to a fork, so we try to loop through the parents
  # until we find a SHA that belongs to the main repository.
  PARENT_SHA=$(gh api \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    /repos/rails/rails/commits/$RAILS_SHA \
    2>/dev/null | jq -r '.parents[0].sha')
  if [ -z "$PARENT_SHA" ] || [ "$PARENT_SHA" = "null" ]; then
    COMMITS_BEHIND=""
    break
  fi
  RAILS_SHA="$PARENT_SHA"
done

if [ -z "$COMMITS_BEHIND" ]; then
  exit 1
fi

echo "$COMMITS_BEHIND"
