#!/usr/bin/env ruby
# typed: strict
# frozen_string_literal: true

require_relative "../config/environment"

processor = CopilotPLG::SharedThreadEventProcessor.new
consumer = GitHub.with_hydro_cluster(:copilot) { GitHub.hydro_consumer(processor.options) }

SharedThreadEventProcessorError = Class.new(StandardError)

begin
  GitHub.logger.info("start", { "code.namespace" => processor.class.name })
  GitHub.hydro_client.run(processor, consumer: consumer, shutdown_signals: [:INT, :TERM])
  GitHub.logger.info("finish", { "code.namespace" => processor.class.name })
rescue => e
  GitHub.logger.error("failed to run stream processor", { "code.namespace" => processor.class.name, :exception => e })
  Failbot.report(SharedThreadEventProcessorError.new(e))
  raise
end
