#!/usr/bin/env ruby
# frozen_string_literal: true

require "optparse"

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: create-prs-by-codeowners [options]"

  opts.on("-m", "--commit-message MESSAGE", "Commit Message") do |m|
    options[:commit_message] = m
  end

  opts.on("-t", "--title TITLE", "PR Title") do |t|
    options[:title] = t
  end

  opts.on("-b", "--body-file FILE", "PR Body File") do |b|
    options[:body_file] = b
  end

  opts.on("-l", "--label LABEL", "PR Label") do |l|
    options[:label] = l
  end

  opts.on("-r", "--branch-base BASE", "Branch Base") do |r|
    options[:branch_base] = r
  end
end.parse!

begin
  require "codeowners"
rescue LoadError
  puts "Please rerun the script with safe-ruby"
  puts "bin/create-prs-by-codeowners #{ARGV.join(" ")}"
  exit
end

pwd = Dir.getwd

puts "🚀 Let's start creating pull requests by CODEOWNERS\n\n"
puts "Please note that this script only works with modified files, and not with added/removed files"

# Get all currently modified files.
modified_files = `git status --short`.lines
                  .select { |line| line.start_with?(/^\s?M\s+/) }
                  .map { |line| line.chomp.sub(/^\s?M\s+/, "") }

total_files = modified_files.length
puts "📁 Total files: #{total_files}\n\n"

# Taken from script/codeowners
# We could call out to the script, but that'd end up loading the file repeatedly.
codeowners_file = File.expand_path("../../CODEOWNERS", __FILE__)
codeowners = Codeowners::File.new(File.read(codeowners_file))

modified_files_by_team = modified_files.group_by do |file|
  codeowners.for(file).keys.first.to_s
end

total_teams = modified_files_by_team.length
puts "👩 Total teams to be notified by your changes: #{total_teams}\n\n"

# get current branch name
starting_branch = `git branch --show-current`

# Get commandline args
commit_message = options[:commit_message]
pr_title = options[:title]
pr_body_file = options[:body_file]
label_name = options[:label]
pr_body_file_path = "#{pwd}/#{pr_body_file}"
branch_base = options[:branch_base] || "batch-update-#{Time.now.to_i}"

if commit_message.nil? || commit_message.empty?
  puts "❌ The -m/--commit-message argument must be the commit message. For example: 'Change buttons to primary'."
  exit
end

if pr_title.nil? || pr_title.empty?
  puts "❌ The -t/--title argument must be a pull request title. For example: 'Update buttons across multiple features'."
  exit
end

if pr_body_file.nil? || pr_body_file.empty?
  puts "❌ The -b/--body-file must be the path to your pull request body file. This file can be placed in the root. For example: 'PR.log'. Usage of a .log extension is recommended since it gets gitignored by default."
  exit
end

puts "📝 Content we'll use to create your pull requests:"
puts "1️⃣  Commit message: #{commit_message}"
puts "2️⃣  Pull request title: #{pr_title}"
puts "3️⃣  Pull request body file path (markdown): #{pr_body_file_path}"
puts "4️⃣  Branch base: #{branch_base}"
if label_name
  puts "5️⃣  Label name: #{label_name}\n\n"
end

# stash the changes before running all the steps
# to avoid potential for errors if there are existing stashes
puts "🦺 Stashing all changes to avoid potential errors.\n\n"
`git stash`

# run all the steps to create the PRs by code owner team
modified_files_by_team.each do |team, files|
  team = team.gsub("@github/", "")
  team = "unowned" if team.empty?

  puts "🔄 Building a pull request for #{team}."
  branch_name = "#{branch_base.strip}/#{team}"

  # create PR from starting branch
  puts "ℹ️ Checking out #{starting_branch}..."
  `git checkout #{starting_branch}`

  # get changes from stash
  puts "ℹ️ Get changes from stash..."
  `git stash pop`

  # create team branch
  puts "ℹ️ Checking out #{branch_name}..."
  `git checkout -B #{branch_name}`

  puts "ℹ️ Stage everything that's owned by #{team}..."
  `git add #{files.join(" ")}`

  # commit and push changes
  puts "ℹ️ Committing..."
  `git commit --message "#{commit_message}"`
  puts "ℹ️ Pushing... (#{branch_name})"
  `SKIP_ALL_PREPUSH_CHECKS=1 git push -u origin #{branch_name}`

  # stash everything that isn't owned by the specified team
  puts "ℹ️ Stash everything else"
  `git stash`

  # create draft pr with needed info, settings and reviewers
  puts "ℹ️ Creating a PR for #{team}."
  `gh pr create -d --body-file #{pr_body_file_path} -t "[codeowner: github/#{team}] #{pr_title}" --label "#{label_name}"`
  puts "✅ Finished creating a PR for #{team}."
end

# move back to where we started
`git checkout #{starting_branch}`
