#!/usr/bin/env safe-ruby
# typed: true
# frozen_string_literal: true

puts "=> Loading the environment..."

require_relative "../config/environment"

unless Rails.env.development?
  puts "=> This script is only intended for development."
  exit 1
end

class CreatePrivateRegistrySecretsApp
  def call
    if Apps::Privileged.integration(:private_registry_secrets).present?
      puts "=> The private registry secrets GitHub app already exists."
    else
      puts "=> Creating the private registry secrets GitHub app..."
      integration = Apps::Privileged::PrivateRegistrySecrets.seed_database!
      create_dot_env_file(integration)
    end
  end

  private

  def create_dot_env_file(integration)
    File.open(dotenv_path, "w") do |file|
      file.puts "PRIVATE_REGISTRIES_APP_NEXT_GLOBAL_ID=\"#{integration.next_global_id}\""
    end
  end

  def dotenv_path
    dotenv_path = "tmp/private-registries.env.local"

    puts "Saving Private Registries envvars to `#{dotenv_path}`"
    dotenv_path
  end
end

if __FILE__ == $0
  CreatePrivateRegistrySecretsApp.new.call
  puts "=> Done!"
end
