#!/bin/bash
set -e

GREEN='\033[0;32m'
NC='\033[0m' # No Color

if [ ! -z "$COPILOT_CODE_REVIEW" ]; then
  export COPILOT_CODE_REVIEW_MODE=true
fi

./bin/toggle-feature-flag enable copilot_code_review_v1
./bin/rails runner 'Apps::Privileged::CopilotPullRequestReviewer.seed_database!'

echo -e "\n${GREEN}➡️ Copilot Pull Request Reviewer setup complete!${NC}"
