#!/bin/bash
set -e

GREEN='\033[0;32m'
NC='\033[0m' # No Color

./bin/toggle-feature-flag enable copilot_pr_reviews_v1 -F copilot_pr_reviews_repository_access -F copilot_reviews_automatic_repo_rule
./bin/rails runner 'Apps::Privileged::CopilotPullRequestReviewer.seed_database!'

echo -e "\n${GREEN}➡️ Copilot Pull Request Reviewer setup complete!${NC}"
