#!/usr/bin/env bash
# This is a wrapper script to run export_mcp_schema.rb with Rails runner

# Get the directory of the current script
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Run the Ruby script with Rails runner
"$DIR/../bin/rails" runner "$DIR/export_mcp_schema.rb"
