#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../config/environment"
processor = GitHub::StreamProcessors::FeatureManagement::FeatureFlagUpdateProcessor.new(use_memcached_host_group_id: true)
consumer = GitHub.hydro_consumer(processor.options.merge({ deliver_tombstone_messages: true }))

FeatureFlagUpdateProcessorError = Class.new(StandardError)

begin
  GitHub.logger.info("start", { "code.namespace" => processor.class.name })
  File.write("/tmp/feature_flag_update_processor.startup", "ready")
  GitHub.hydro_client.run(processor, consumer: consumer, shutdown_signals: [:INT, :TERM])
  GitHub.logger.info("finish", { "code.namespace" => processor.class.name })
rescue => e
  GitHub.logger.error("failed to run stream processor", { "code.namespace" => processor.class.name, :exception => e })
  Failbot.report(FeatureFlagUpdateProcessorError.new(e))
  raise
end
