#!/usr/bin/env bash
set -e

TEST_GOTAUTH=${TEST_GOTAUTH:-0}
TEST_REPOSD=${TEST_REPOSD:-0}

if [[ "$TEST_GOTAUTH" -eq 0 && "$TEST_REPOSD" -eq 0 ]]; then
  echo "TEST_GOTAUTH or TEST_REPOSD must be set to 1"
  exit 1
fi

GOTAUTH_TESTS=""
REPOSD_TESTS=""

if [ "$TEST_REPOSD" = "1" ]; then
  # REPOSD_TESTS=$(grep -rlE --include="*_test.rb" ":get.*/repos/.*/contents" test/)
  REPOSD_TESTS='test/integration/api/repository_contents/get_contents_test.rb -n "/Api::RepositoryContents::GetBlobContentsTest/"'

fi

if [ "$TEST_GOTAUTH" = "1" ]; then
  DEFAULT_GOTAUTH_TEST_PATTERNS=(
    test/lib/git_auth/access_characterization_test.rb
  )

  MATCHING_GOTAUTH_TESTS=$(grep -rl --include="*_test.rb" -e "GitHub::GitAuthTestCase" -e "GitAuthCertificateFixturesTest" -e ":gotauth" test/)
  GOTAUTH_TESTS="${DEFAULT_GOTAUTH_TEST_PATTERNS[*]} ${MATCHING_GOTAUTH_TESTS[*]}"
  GOTAUTH_TESTS=${GOTAUTH_TESTS//"test/lib/git_auth/access_characterization_test.rb"/}
  GOTAUTH_TESTS=${GOTAUTH_TESTS//"test/lib/git_auth/access_test.rb"/}
fi

TESTS="$REPOSD_TESTS $GOTAUTH_TESTS"
EXPANDED_TESTS=""
for pattern in $TESTS; do
  for file in $pattern; do
    EXPANDED_TESTS="$EXPANDED_TESTS $file"
  done
done
TESTS=$EXPANDED_TESTS

echo "$TESTS"
