#!/usr/bin/env bash
set -e

TEST_PULLSD=${TEST_PULLSD:-0}

PULLSD_TESTS=""

if [ "$TEST_PULLSD" = "1" ]; then
  PULLSD_TESTS=(
    test/integration/api/pulls_test.rb
  )
fi

EXPANDED_TESTS=""
for pattern in "${PULLSD_TESTS[@]}"; do
  for file in $pattern; do
    EXPANDED_TESTS="$EXPANDED_TESTS $file"
  done
done
TESTS=$EXPANDED_TESTS

echo "$TESTS"
