#!/usr/bin/env ruby
# frozen_string_literal: true

#
#/ Usage: generate-column-encryption-transition <model_name> <attribute_name>
#/
#/ This generates a column encryption transition file
#/ as well as a test file.

require "optparse"

parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{$0} model_name attribute_name"
end

parser.parse!

unless (model_name_arg = ARGV.shift)
  abort parser.help
end

unless (attribute_name_arg = ARGV.shift)
  abort parser.help
end

require_relative "../config/boot"
require "active_support/all"
require "erb"
require "fileutils"

model_name = model_name_arg.camelize
transition_model_name = model_name.tr("::", "")
model_name_underscored = model_name.tr("::", "").underscore
attribute_name = attribute_name_arg.underscore
transition_file = "lib/github/transitions/encrypt_#{model_name_underscored.underscore}.rb"
test_file = "test/lib/github/transitions/encrypt_#{model_name_underscored.underscore}_test.rb"
file_without_lib_or_extension = transition_file.gsub(/(^lib\/|\.rb$)/, "")

error_message = <<~MSG
  It appears "#{transition_file}" already exists.
  This is likely due to "#{model_name}" already having an encrypted attribute prior to the one added in this transition.
  In this case you will re-use the existing transition to encrypt the new attribute.
  Be sure to update the tests at "#{test_file}" to include tests for the new attribute as well.
  If you have any questions feel free to reach out to #prodsec-engineering
MSG

FileUtils.mkdir_p File.dirname transition_file
FileUtils.mkdir_p File.dirname test_file

def render_template(template_filename, output_filename, error_message, binding)
  if File.exist? output_filename
    abort error_message
  end

  template = File.read(template_filename)
  File.open(output_filename, "wb") do |f|
    erb = ERB.new(template, trim_mode: "-")
    erb.filename = output_filename
    f.write erb.result binding
  end
  puts output_filename
end

render_template "lib/github/transitions/templates/column_encryption_transition_template.erb", transition_file, error_message, binding
render_template "lib/github/transitions/templates/column_encryption_transition_test_template.erb", test_file, error_message, binding

# Add the feature flags to the fast feature flag linter
feature_flag_lint_file = "test/fast/linting/feature_flags_test.rb"
feature_flag_lint_file_content = File.read(feature_flag_lint_file)

feature_flag_lint_file_content.gsub!(/(ALLOWED_FEATURES\s*=\s*Set\.new\(\[\s*)(.*?)(\s*\]\))/m) do |_match|
  set_content = $2
  new_element = '"encrypt_as_plaintext_' + model_name_underscored + "_" + attribute_name + '", # used for encryption tests'
  "#{Regexp.last_match(1)}#{set_content}\n    #{new_element}#{Regexp.last_match(3)}"
end

File.open(feature_flag_lint_file, "w") { |file| file.write(feature_flag_lint_file_content) }
