#!/bin/sh

set -e

if [ -z "$1" ]; then
  echo "Usage: $0 <path prefix>"
  echo "Example:"
  echo "  $0 orca/v0"
  exit 1
fi

HYDRO_SCHEMA_PREFIX="proto/hydro/schemas/$1"

# note: the Gem version may not match the appropriate protoc version
# to apply here. Check the Hub link below for the right one:
# https://thehub.github.com/epd/engineering/products-and-services/internal/hydro/guides/adding-a-new-event/#githubgithub
PROTOC_VERSION=$(bundle exec gem list | grep google-protobuf | grep -oP '\d+\.\d+\.\d+')
echo "Using protoc version: ${PROTOC_VERSION}"

(
  cd /workspaces
  if [ ! -d "hydro-schemas" ]; then
    git clone https://github.com/github/hydro-schemas.git
  fi

  cd hydro-schemas
  git pull

  echo
  echo "Generating Ruby files from Hydro schemas matching $@..."
  find "${HYDRO_SCHEMA_PREFIX}" -name '*.proto'
  echo

  set -x
  script/generate \
    --protoc-version="${PROTOC_VERSION}" \
    --ruby-out="/workspaces/github/lib" \
    "${HYDRO_SCHEMA_PREFIX}"
)
