#!/usr/bin/env safe-ruby
# frozen_string_literal: true

#/ Usage: ghe-scim-identities-csv -d [options]
#/
#/ OPTIONS:
#/   -h, --help               Show this message.
#/   -r, --no-header          Don't use a header row.
#/   -o, --stdout             Print output to STDOUT. Optional.
#/   -f <FILE>, --file <FILE> Path to CSV File. Recommended to be /data/user/tmp. Optional.

require "optparse"

def help!
  exec "grep ^#/<'#{__FILE__}'|cut -c4-"
end

header        = true
use_stdout    = false
csv_file      = nil

begin
  OptionParser.new do |opts|
    opts.on("-r", "--no-header") { header = false }
    opts.on("-o", "--stdout")    { use_stdout = true }
    opts.on_tail("-h", "--help") { help! }
    opts.on("-fCSVFILE", "--file CSVFILE") do |f|
      help! if f.nil?
      csv_file = f
    end
    opts.parse!
  end
  rescue OptionParser::InvalidOption, OptionParser::MissingArgument => e
    STDERR.puts e.message
    help!
end

if ARGV.any?
  STDERR.puts "Unknown arguments: #{ARGV.join(", ")}\n"
  help!
end

# silence environment loading warnings
original_verbosity = $VERBOSE
$VERBOSE = nil
require File.expand_path("../../config/environment", __FILE__)
$VERBOSE = original_verbosity

if use_stdout
  output_io = STDOUT
else
  date = Time.now.strftime("%Y%m%d%H%M%S")
  file = csv_file || "/data/user/tmp/scim-identities-#{date}.csv"
  puts "Saving list of SCIM identities to '#{file}'..."
  output_io = File.open(file, "w")
end

begin
  ScimIdentitiesCSVGenerator.new(
    header: header,
    output_io: output_io).run
rescue ScimIdentitiesCSVGenerator::Error => e
  abort e.message
end

unless use_stdout
  puts "Done."
end
