#!/bin/bash
# ARG: Dockerfile,
#  The name of the Dockerfile to build. Current options are Dockerfile.golden (Stretch) and Dockerfile.golden-buster (Buster)

set -e

if [ -z "$1" ] ; then
  echo "No Dockerfile specified for golden image build. Exiting."
  exit 1
fi

# Build our base container
DOCKERFILE=${1}
BUILDER_IMAGE="github-golden-builder:latest"
BUILDER_CONTAINER="github-golden-builder-$(date +%s)"
GIT_TOKEN=$(cat ${HOME}/.git-credentials | cut -c13-52)
echo "docker build -f ${DOCKERFILE} --build-arg GIT_TOKEN=<redacted> -t ${BUILDER_IMAGE} ."
docker build -f ${DOCKERFILE} --build-arg GIT_TOKEN=$GIT_TOKEN -t "${BUILDER_IMAGE}" .

# Determine the distro and codename the image is running on
DISTRO_DATA=$(docker run --privileged --name "OS-DIAGNOSTIC-$(date +%s)" "${BUILDER_IMAGE}" cat /etc/os-release)
DISTRO=$(echo "$DISTRO_DATA" | sed -nr 's/ID=([a-zA-Z\s+])/\1/p')
DISTRO_CODENAME=$(echo "$DISTRO_DATA" | sed -nr 's/VERSION_CODENAME=([a-zA-Z\s+])/\1/p')

# Run script/bootstrap with a privileged container in an attempt to use docker in docker
docker run --privileged \
  --name "${BUILDER_CONTAINER}" \
  -e BUILD_BRANCH=$BUILD_BRANCH \
  -e DISTRO_CODENAME=$DISTRO_CODENAME \
  -e GPR_GITHUB_USERNAME \
  -e GPR_GITHUB_TOKEN \
  -e GIT_TOKEN=$GIT_TOKEN \
  "${BUILDER_IMAGE}" \
  runuser -u build -- script/golden-image-build

# Export our container as the properly named golden image
# Do some really nasty regexp and sed magic to get the tag to use for the golden image
IMAGE_TAG=$(echo "$BUILD_BRANCH" | egrep -o "^(\w+\/)?(revert-.*-)?enterprise-([0-9\.]+)-(release|backport)" | sed -e 's,-backport$,,' -e 's,-release$,,' | sed -e 's,^[A-Za-z0-9]*/,,' | sed -e 's,^revert-[0-9]*-,,')
# Set a default if we're not on an enterprise branch
if [ -z "$IMAGE_TAG" ] ; then
  # Runs that are not from master or main are considered dry runs and should not publish the image
  if [[ "$BUILD_BRANCH" == "master" ]] || [[ "$BUILD_BRANCH" == "main" ]] ; then
    IMAGE_TAG="bootstrap"
  else
    IMAGE_TAG="dry-run"
  fi
fi

IMAGE_OS_TAG="${IMAGE_TAG}-${DISTRO}-${DISTRO_CODENAME}"

octofactory_url="octofactory.service.private-us-east-1.github.net"

GOLDEN_CONTAINER_URL=${octofactory_url}/github-golden-docker/github-github
GOLDEN_CONTAINER_URL_AND_TAG=${GOLDEN_CONTAINER_URL}:$IMAGE_TAG

# Download tarballs of the subproject containers to be cached in the slim golden build
if [[ "$SKIP_CACHING_SUBPROJECT_IMAGES_IN_GOLDEN_IMAGE" == "true" ]]; then
  echo "Skipping caching subproject containers container images in the golden image"
else
  SUBPROJECT_IMAGE_DIR="vendor/subproject-images"
  mkdir -p $SUBPROJECT_IMAGE_DIR
  IMAGES=$(jq -r 'to_entries | .[] | "\(.key) \(.value)"' "script/dx/subproject-to-image-map.json")
  while read -r SUBPROJECT_VERSION_FILE IMAGE; do
    SUBPROJECT_NAME=$(echo "$SUBPROJECT_VERSION_FILE" | sed 's/^config\///; s/-version$//')
    SUBPROJECT_SHA=$(cat $SUBPROJECT_VERSION_FILE | grep -v ^#)
    echo docker pull "\"$IMAGE:$SUBPROJECT_SHA\""
    docker pull "$IMAGE:$SUBPROJECT_SHA"
    echo docker save -o "\"$SUBPROJECT_IMAGE_DIR/${SUBPROJECT_NAME}.tar\"" "\"$IMAGE:$SUBPROJECT_SHA\""
    docker save -o "$SUBPROJECT_IMAGE_DIR/${SUBPROJECT_NAME}.tar" "$IMAGE:$SUBPROJECT_SHA"
  done <<< "$IMAGES"
fi

# Create a new image from the bootstrapped container and then use it to create a slim golden.
# The "slim" golden image copies directories one-by-one from the bootstrapped vendor directory.
# (We can't use FROM to create a multi-stage Dockerfile right now because bootstrapping requires
# docker-in-docker, which only works with elevated privileges.)
CONTAINER_ID=$(docker ps -a -f"name=${BUILDER_CONTAINER}" -q)
docker commit "$CONTAINER_ID" "${BUILDER_IMAGE}"
DOCKERFILE_SLIM=$(script/generate-dockerfile-golden-slim ${BUILDER_IMAGE})
echo "Generated Dockerfile: $DOCKERFILE_SLIM"
echo "$DOCKERFILE_SLIM" | docker build --tag "${GOLDEN_CONTAINER_URL_AND_TAG}" -f- .
docker tag $GOLDEN_CONTAINER_URL_AND_TAG $GOLDEN_CONTAINER_URL:$BUILD_SHA
docker tag $GOLDEN_CONTAINER_URL_AND_TAG $GOLDEN_CONTAINER_URL:$IMAGE_OS_TAG

if [[ "$DRY_RUN" == "1" ]] || [[ "$JANKY_ENV_DRY_RUN_GOLDEN_IMAGE" == "1" ]] || [[ "$IMAGE_TAG" == "dry-run" ]] ; then
  echo "==> DRY RUN: docker push $GOLDEN_CONTAINER_URL:$IMAGE_OS_TAG"

  if [[ $DISTRO == "debian" ]] && [[ $DISTRO_CODENAME == "stretch" ]] ; then
    echo "==> DRY RUN: docker push $GOLDEN_CONTAINER_URL:$BUILD_SHA"
    echo "==> DRY RUN: docker push $GOLDEN_CONTAINER_URL_AND_TAG"
  fi
else
  echo "Executing: docker push $GOLDEN_CONTAINER_URL:$IMAGE_OS_TAG"
  docker push $GOLDEN_CONTAINER_URL:$IMAGE_OS_TAG

  # Only push the legacy tag for Debian Stretch to maintain backwards compatibility
  if [[ $DISTRO == "debian" ]] && [[ $DISTRO_CODENAME == "stretch" ]] ; then
    echo "Executing: docker push $GOLDEN_CONTAINER_URL:$BUILD_SHA"
    docker push $GOLDEN_CONTAINER_URL:$BUILD_SHA

    echo "Executing: docker push $GOLDEN_CONTAINER_URL_AND_TAG"
    docker push $GOLDEN_CONTAINER_URL_AND_TAG
  fi
fi
