#!/bin/bash
set -e

export RAILS_ENV=test
export GITHUB_CI=1

if [ "$DISTRO_CODENAME" == "stretch" ]; then
  export SKIP_NODE=true
fi

# Write git credentials to $HOME/.git-credentials which is /workspace/.git-credentials
script/ci/copy-git-credentials

# Bootstrap our base dependencies
script/bootstrap --local --deployment

# Bootstrap RUBY_NEXT dependencies
# Temporarily disable installing the datadog profiling extension by setting
# the DD_PROFILING_NO_EXTENSION environment variable
DD_PROFILING_NO_EXTENSION=true RUBY_NEXT=1 script/bootstrap --local --deployment

# Strip out everything that isn't vendor, basically
script/clean-golden-vendor
ls -1 | grep -v vendor | xargs rm -rf
