#!/bin/sh

if [ ! -d /workspaces/github/vendor/gotauth ]; then
    echo "Directory /workspaces/github/vendor/gotauth does not exist, you need to clone gotauth"
    exit 1
fi

# We should prebuild this, but for dev purposes this makes it easier.
cd /workspaces/github/vendor/gotauth || exit 1
export HEAVEN_DEPLOYED_ENV=test
export GITHUB_TELEMETRY_LOGS_LEVEL=debug
export DATABASE_CONFIG_PATH=./config/db.test.yaml
exec script/server
