#!/bin/bash
#/ Installs the 1Password CLI if it is not already installed.
#/ CLI reference: https://developer.1password.com/docs/cli/reference

GREEN='\033[0;32m'
NC='\033[0m' # No Color

(op --version &> /dev/null) || {
	echo -e "\n${GREEN}➡️ 1Password CLI not installed. Installing now...\n${NC}"

	# Download 1Password CLI
	# The latest release can be found here: https://app-updates.agilebits.com/product_history/CLI2
	url="https://cache.agilebits.com/dist/1P/op2/pkg/v2.30.0/op_linux_amd64_v2.30.0.zip"

	mkdir -p ./tmp
	wget -O ./tmp/op.zip "$url"
	unzip ./tmp/op.zip -d ./tmp
	rm ./tmp/op.zip

	# Verify the CLI installed is authentic
	# See docs for verification instructions: https://developer.1password.com/docs/cli/verify/
	gpg --keyserver hkps://keyserver.ubuntu.com --receive-keys 3FEF9748469ADBE15DA7CA80AC2D62742012EA22
	if [ $? -ne 0 ]; then
		echo "Error: Failed to retrieve GPG key. Aborting installation." >&2
		exit 1
	fi

	gpg --keyserver hkps://keyserver.ubuntu.com --verify ./tmp/op.sig ./tmp/op
	if [ $? -ne 0 ]; then
		echo "Error: GPG signature verification failed. Aborting installation." >&2
		exit 1
	fi

	# Move the CLI to the user's PATH
	sudo mv ./tmp/op /usr/local/bin/op
	sudo mv ./tmp/op.sig /usr/local/bin/op.sig

	echo -e "\n${GREEN}1Password CLI installed successfully."

	if [ -z "${ONEP_PASSWORD}" ] || [ -z "${ONEP_SECRET_KEY}" ]; then
		echo -e "Please authenticate with 1Password via:\n\neval \$(op account add --address github.1password.com --email \"${GITHUB_USER}@github.com\" --signin)"
		echo -e "Tip: Set ONEP_PASSWORD and ONEP_SECRET_KEY secrets to do this automatically next time: https://github.com/settings/codespaces"
	else
		echo -e "Encountered ONEP_PASSWORD and ONEP_SECRET_KEY variables; automatically adding account and logging in"
		eval $(printf '%s' "${ONEP_PASSWORD}" | op account add --address github.1password.com --email "${GITHUB_USER}@github.com" --secret-key "${ONEP_SECRET_KEY}" --signin)
	fi
}
