#!/bin/bash
#/ Usage: script/kafka-lite-server
#/
#/ Runs kafka-lite service.

SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
CONFIG_DIR=$(readlink -f "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/../config")

arg_topics=$(cat $CONFIG_DIR/kafka-server-seeds)

source $SCRIPT_DIR/dx/lib/subproject-containers

SUBPROJECT_VERSION=$(subproject_version "kafka-lite")
echo "kafka-lite version $SUBPROJECT_VERSION"

# Run the kafka-lite go service.
start_subproject --name kafka-lite --entrypoint "/kafka-lite" \
  "ghcr.io/github/kafka-lite/kafka-lite:$SUBPROJECT_VERSION" \
  --listen-address 0.0.0.0:9092 \
  --advertised-listener-address kafka-lite.localhost:9092 \
  --store redis \
  --log-format production \
  --max-message-age-ms 86400000 \
  $arg_topics
