#!/bin/bash

# Usage: script/kredz-server
# Start the github/kredz web server if the repository has been cloned in the Codespace, or no-op otherwise.

set -e

if test -d /workspaces/actions/actions-codespaces; then
  echo "Actions Development devcontainer detected, kredz server will be started by actions-codespaces."
  sleep infinity
elif test -f /workspaces/kredz/script/server; then
  echo "Starting kredz server..."
  cd /workspaces/kredz && script/server --fast
else
  echo "github/kredz repository has not been cloned, sleeping."
  echo "If you want to run the github/kredz server, first run 'script/setup-kredz-server',"
  echo "then 'overmind restart kredz'."
  sleep infinity
fi
