#!/bin/bash
#/ Usage: script/memory-alpha-server
#/
#/ Runs memory-alpha service.

# If we need to run the service multiple times on different ports, this name should be parameterized with the port.
NAME="memory-alpha"

SKIP_MEMORY_ALPHA="${SKIP_MEMORY_ALPHA:-false}"

if [ "$SKIP_MEMORY_ALPHA" = "true" ] || [ "$SKIP_MEMORY_ALPHA" = "1" ]; then
  echo "memory-alpha has been disabled"
  sleep infinity
elif [[ "$DX_EDGE" = true ]] && [[ "$DX_FEATURE_SUBPROJECT_CONTAINERS" = true ]]; then
  SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
  source $SCRIPT_DIR/dx/lib/subproject-containers

  pushd $SCRIPT_DIR/..
  mkdir -p ./tmp/memory-alpha/test/buckets/local-bucket

  SUBPROJECT_VERSION=$(subproject_version "memory-alpha")
  echo "memory-alpha version $SUBPROJECT_VERSION"

  # ensure we have the config files
  script/build-subproject --clone-only -v memory-alpha

  # Ensure we clean up any existing containers, and remove after shutdown.
  cleanup_docker() {
    echo "Stopping ${NAME}..."
    docker stop ${NAME} &> /dev/null || true
    docker rm ${NAME} &> /dev/null || true
    exit 0
  }

  trap cleanup_docker EXIT INT QUIT TERM HUP

  docker stop ${NAME} &> /dev/null || true
  docker rm ${NAME} &> /dev/null || true

  docker run -d --name ${NAME} --network host \
    -e STORE_CONFIG=/tmp/config/stores_codespaces.yaml \
    -v $(pwd)/vendor/memory-alpha/config/development:/tmp/config \
    -v $(pwd)/tmp/memory-alpha/test:/app/test \
    ghcr.io/github/memory-alpha/memory-alpha:${SUBPROJECT_VERSION} \
    --profilerPort 18080

  docker logs --follow ${NAME} &
  wait
else
  app_dir="$(cd "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)"
  cd $app_dir

  script/build-subproject -v memory-alpha || exit 1

  # Latest version of MA does not work with codespaces since we
  # updated to Golang 1.23. We are adding and configuring a replica of the
  # codespaces config file that will be used by the memory-alpha process.
  # Remove this once the linked issue is addressed.
  # https://github.com/github/memory-alpha/issues/1272
  cat << 'EOF' > vendor/memory-alpha/store_codespaces.yaml
---
buckets:
  # You can use the general bucket in your codespace, you only need to wire the following credentials
  # configuration in your Dotcom app, access-key:local-access-key and secret-key:local-secret-key
  # When running the server you will need to run it using MEMORY_ALPHA_URL=\"http://github.localhost:8080\" GH_CLUSTER=0 ./script/server
  # The files will be uploaded under the \`test/buckets/general\` directory, and once they codespaces is gone the files will also
  # be removed.
  - bucket: general
    backing-bucket: local-bucket
    type: local
    credentials:
      primary:
        path: test/buckets
    account-config:
      enable-proxy-get: true
  - bucket: git-lfs
    backing-bucket: git-lfs-dev
    type: azure
    region: westus2
    credentials:
      primary:
        access-key: LFS_AZURE_ACCESS_KEY
        storage-account: LFS_AZURE_STORAGE_ACCOUNT
    account-config:
      enable-proxy-get: true
      enable-verify-put-content: true
      usage-billing-product: lfs
  # Comment out the following bucket if you want to test against Azure
  - bucket: github-development-user-asset-6210df
    backing-bucket: local-bucket
    type: local
    credentials:
      primary:
        path: test/buckets
    account-config:
      enable-proxy-get: true
  # Uncomment the following bucket if you want to test against Azure
  # - bucket: github-development-user-asset-6210df
  #   backing-bucket: memory-alpha-codespaces-dev-container
  #   signed-url-expiry: 5m
  #   type: azure
  #   region: eastus
  #   credentials:
  #     primary:
  #       access-key: MEMORY_ALPHA_AZURE_ACCESS_KEY
  #       storage-account: MEMORY_ALPHA_AZURE_STORAGE_ACCOUNT
EOF
  export STORE_CONFIG=store_codespaces.yaml

  # We create a temporary directory that will be used
  # by the local storage otherwise we will get errors
  # more here https://pkg.go.dev/gocloud.dev/blob/fileblob
  MATMPDIR=$(pwd)/vendor/memory-alpha/tmp
  mkdir -p $MATMPDIR

  cd vendor/memory-alpha
  TMPDIR=$MATMPDIR exec bin/memory-alpha-server --profilerPort 18080 > /tmp/memory-alpha.log 2>&1
fi
