#!/bin/bash

# Usage: script/models-gateway-server
# Start the github/models-gateway web server if the repository has been cloned in the Codespace, or no-op otherwise.

set -e

if test -f /workspaces/models-gateway/script/server; then
  echo "Starting models-gateway server..."
  cd /workspaces/models-gateway && script/server

else
  echo "github/models-gateway repository has not been cloned, sleeping."
  echo "If you want to run the github/models-gateway server, first run 'script/setup-codespaces-models-gateway',"
  echo "then 'overmind restart models-gateway'."
  sleep infinity
fi
