#!/bin/bash

set -e

./bin/toggle-feature-flag enable migrations_vnext_api_migrations
script/multi-tenant/toggle-feature-flags enable

export ALL_USERS_ARE_EMPLOYEES=1
export MVND_HMAC_KEY="deadbeef"
export MVND_HOST="http://localhost:8083"
export NO_VOLTRON=1

# ensure multi-tenant flag is passed to script/server
if [[ ! " $@ " =~ " --multi-tenant " ]]; then
  ./script/server --multi-tenant "$@"
else
  ./script/server "$@"
fi
