#!/bin/bash
# This script should be run after npm dependencies are changed. It is responsible for ensuring
# packages are patched up if necessary.
set -e

# Hoist all packages to the top-level node_modules
npm start -w @github-ui/hoist-node-modules

# Verify package versions
npm start -w @github-ui/verify-package-versions

# Apply patches to packages
npm run apply-patches

# Copy mathjax static assets
./script/copy-mathjax-static-assets
