#!/usr/bin/env ruby
# typed: true
# frozen_string_literal: true

file_path = ARGV[0]
if file_path.nil? || file_path.empty?
  puts "Usage: #{__FILE__} <file_path> <task>"
  puts "file_path is required, task is optional."
  puts "Example: #{__FILE__} ui/packages/github-models-repo/routes/prompt/components/__tests__/Compare.test.tsx test"
  puts "Example: #{__FILE__} app/assets/modules/github/workflow-runs/workflow-run-branch-filter.ts"
  exit 1
end

task = ARGV[1]
if task.nil? || task.empty?
  puts "No task specified, defaulting to 'tsc'"
  task = "tsc"
end

PACKAGE_PREFIX = "ui/packages"
ALT_PACKAGE_PREFIX = "app/assets/modules"

def package_name_for(dir)
  if dir.include?(PACKAGE_PREFIX)
    dir.split(PACKAGE_PREFIX)[1].split("/")[1]
  elsif dir.include?(ALT_PACKAGE_PREFIX)
    "app-assets-modules"
  end
end

file_dir = File.dirname(file_path)
package_name = package_name_for(file_dir)

if package_name
  puts "Running #{task} for package #{package_name}"
  success = system("nx run @github-ui/#{package_name}:#{task}")
  exit(success ? 0 : 1)
else
  puts "Not sure how to run task #{task} for the package containing: #{file_path}"
  exit 1
end
