#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

export DESTINATION="${ASSETS_PATH:-public/assets}"
export NODE_ENV="${NODE_ENV:-${RAILS_ENV:-development}}"

echo "Compiling assets for $NODE_ENV in $DESTINATION"

precompile_assets() {
  bin/safe-ruby script/fingerprint-static-assets.rb

  # Remove the UI manifest for production builds. This will come from deploys from github-ui.
  if [[ "$NODE_ENV" == "production" ]]; then
    rm -f public/assets/ui-manifest*.json
  fi
}

precompile_assets
