#!/bin/bash

SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")

# Note: If this directory doesn't exist or is empty, run `./script/build-subproject pullsd`
PULLSD_VENDOR_PATH="${SCRIPT_DIR}/../vendor/pullsd"

if [ ! -d "$PULLSD_VENDOR_PATH" ]; then
    echo "Directory $PULLSD_VENDOR_PATH does not exist, you need to clone pullsd"
    exit 1
fi

export GITHUB_TELEMETRY_LOGS_LEVEL=debug
export DATABASE_CONFIG_PATH=${DATABASE_CONFIG_PATH:-./config/db.test.yaml}
export MONOLITH_TWIRP_HMAC="octocat"

start_pullsd() {
  cd "$PULLSD_VENDOR_PATH" || exit 1

  ./script/setup && ./script/server
}

start_pullsd
