#!/bin/bash

SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
REPOSD_VENDOR_PATH="${SCRIPT_DIR}/../vendor/reposd"

if [ ! -d $REPOSD_VENDOR_PATH ]; then
    echo "Directory $REPOSD_VENDOR_PATH does not exist, you need to clone reposd"
    exit 1
fi

# We should prebuild this, but for dev purposes this makes it easier.
cd $REPOSD_VENDOR_PATH || exit 1

export HEAVEN_DEPLOYED_ENV=test
export GITHUB_TELEMETRY_LOGS_LEVEL=debug
export DATABASE_CONFIG_PATH=${DATABASE_CONFIG_PATH:-./config/db.test.yaml}
export PORT=${PORT:-1342}
export SPOKESD_URL=${SPOKESD_URL:-http://127.0.0.1:1345}
export AUTHZD_URL=${AUTHZD_URL:-http://127.0.0.1:8081}
export AUTHND_URL=${AUTHND_URL:-http://127.0.0.1:8082}

exec script/server --reposd
