#!/bin/bash
# Usage: run-automated-transition <transition-file-name> <arguments>
USAGE="Usage: run-automated-transition <transition-file-name> <arguments>"

set -e

if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
  echo "${USAGE}" 1>&2
  exit 1
fi

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )"

if [[ $# -eq 0 ]] ; then
    # No arguments given, nothing to do. This usually happens when
    # the transition-job-template is deployed.
    exit 0
fi

filename="$1"
shift

"$ROOT_DIR"/bin/safe-ruby "lib/github/transitions/$filename" "$@"
