#!/bin/bash

GITHUB_UI_PREFIX=""
if [[ "$UI" = true || "$UI" = 1 ]]; then
  GITHUB_UI_PREFIX="--prefix ../github-ui"
else
  echo "Ignoring Alloy UI assets since UI=1 is not set"
  sleep infinity
  exit 0
fi

if [[ "$VITE" = true || "$VITE" = 1 ]]; then
  # For vite, we generate a fake manifest.alloy.json to enable SSR in Rails
  # The actual asset compilation is handled by the vite alloy sever in the alloy-server process
  npm run $GITHUB_UI_PREFIX precompile-assets-for-tests
  sleep infinity
  exit 0
fi

# Run the webpack server
npm run $GITHUB_UI_PREFIX webpack:alloy:serve --progress false
