#!/bin/bash

if [[ -n "$SKIP_UI" || -n "$UI_MANIFEST_SHA" ]]; then
  echo "Ignoring UI dev server since SKIP_UI or UI_MANIFEST_SHA is set"
  sleep infinity
  exit 0
fi

GITHUB_UI_PREFIX=""
if [[ "$UI" = true || "$UI" = 1 ]]; then
  GITHUB_UI_PREFIX="--prefix ../github-ui"
fi

# Run the webpack server
npm run $GITHUB_UI_PREFIX dev -w @github-ui/ui-manifest
