#!/bin/bash

if [[ -n "$SKIP_UI" || -n "$UI_MANIFEST_SHA" ]]; then
  echo "Ignoring CSS UI assets since SKIP_UI or UI_MANIFEST_SHA is set"
  sleep infinity
  exit 0
fi

GITHUB_UI_PREFIX=""
if [[ "$UI" = true || "$UI" = 1 ]]; then
  GITHUB_UI_PREFIX="--prefix ../github-ui"
fi

if [[ "$VITE" = true || "$VITE" = 1 ]]; then
  # Vite is run by the js-assets script, so we don't need to do anything here
  echo "Vite is run by the js-assets script, doing nothing in css-assets"
  sleep infinity
else
  # Run the webpack server
  npm run $GITHUB_UI_PREFIX webpack:css:serve --progress false
fi
