#!/bin/bash

if [[ -n "$SKIP_UI" || -n "$UI_MANIFEST_SHA" ]]; then
  echo "Ignoring JS UI assets since SKIP_UI or UI_MANIFEST_SHA is set"
  sleep infinity
  exit 0
fi

GITHUB_UI_PREFIX=""
if [[ "$UI" = true || "$UI" = 1 ]]; then
  GITHUB_UI_PREFIX="--prefix ../github-ui"
fi

if [[ "$VITE" = true || "$VITE" = 1 ]]; then
  # Run the vite server
  npm run $GITHUB_UI_PREFIX vite
else
  # Run the webpack server
  npm run $GITHUB_UI_PREFIX webpack:serve --progress false
fi
