#!/bin/bash

GITHUB_UI_PREFIX=""
if [[ "$UI" = true || "$UI" = 1 ]]; then
  GITHUB_UI_PREFIX="--prefix ../github-ui"
else
  echo "Ignoring JS UI assets since UI=1 is not set"
  sleep infinity
  exit 0
fi

if [[ "$VITE" = true || "$VITE" = 1 ]]; then
  # Run the vite server
  npm run $GITHUB_UI_PREFIX vite
else
  # Run the webpack server
  npm run $GITHUB_UI_PREFIX webpack:serve --progress false
fi
