#!/bin/bash

if [[ "$VITE" = true || "$VITE" = 1 ]]; then
  # For vite, we generate a fake manifest.alloy.json to enable SSR in Rails
  # The actual asset compilation is handled by the vite alloy sever in the alloy-server process
  npm run precompile-assets-for-tests
  sleep infinity
  exit 0
fi

# Run the webpack server
npm run webpack:alloy:watch --progress false
