#!/bin/bash

GITHUB_UI_PREFIX=""
if [[ "$UI" = true || "$UI" = 1 ]]; then
  GITHUB_UI_PREFIX="--prefix ../github-ui"
else
  echo "Ignoring UI dev server since UI=1 is not set"
  sleep infinity
  exit 0
fi

# Run the webpack server
npm run $GITHUB_UI_PREFIX dev -w @github-ui/ui-manifest
