#!/bin/bash

if [[ "$VITE" = true || "$VITE" = 1 ]]; then
  # Vite is run by the js-assets script, so we don't need to do anything here
  echo "Vite is run by the js-assets script, doing nothing in css-assets"
  sleep infinity
else
  # Run the webpack server
  npm run webpack:css:serve --progress false
fi
