#!/bin/bash
set -e

# This script sets up the github/codespaces-lsp repository for a github/github codespace.

RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
NC='\033[0m' # No Color

# Function to print help message
help() {
   echo "Sets up the github/codespaces-lsp repository for a github/github codespace."
   echo
   echo "Usage: setup-codespaces-codespaces-lsp [-b branch] [-d|h] "
   echo "Options:"
   echo "-d     Before starting, delete the existing codespaces-lsp directory in the codespace."
   echo "-w     Add the codespaces-lsp repo as a workspace in VS Code."
   echo "-h     Print this help message."
   echo "-b     The branch to clone for the codespaces-lsp repo."
   echo
}

BRANCH=main

# Get the options
while getopts ":hdwb:" opt; do
   case $opt in
      h) # display help message
         help
         exit;;
      d) # Delete the repository if it exists
         DELETE_REPO=true;;
      w) # Add the repository as a workspace in VS Code
         ADD_TO_WORKSPACE=true;;
      b) # If a branch was provided, re-set the variable
         BRANCH=$OPTARG;;
     :)
      echo "Error: Option -$OPTARG requires an argument."
      exit 1;;
     \?) # Invalid option
         echo "Error: Invalid option -$OPTARG"
         exit 1;;
   esac
done

# If the codespaces-lsp repo already exists and the delete argument hasn't been specified, echo a warning and exit.
if [[ -d "/workspaces/codespaces-lsp" && -z "$DELETE_REPO" ]]; then
  echo -e "${RED}The codespaces-lsp directory already exists in this codespace.${NC} \nYou can rerun the setup script with the -d argument to force the deletion of the existing repository."
  exit 1
fi

if [ "$DELETE_REPO" = true ]; then
  echo -e "\n${GREEN}➡️ Deleting the existing codespaces-lsp repo...\n${NC}"
  rm -rf /workspaces/codespaces-lsp
fi

# Do a shallow clone of codespaces-lsp to the same dir as the github/github repo.
# If a branch was supplied, use that branch for the clone.
echo -e "\n${GREEN}➡️ Cloning codespaces-lsp repo...\n${NC}"
git clone https://github.com/github/codespaces-lsp /workspaces/codespaces-lsp --branch $BRANCH

# Install npm dependencies
echo -e "\n${GREEN}➡️ Installing NPM dependencies...\n${NC}"
cd /workspaces/codespaces-lsp
npm install

# Build the codespaces-lsp package
echo -e "\n${GREEN}➡️ Building codespaces-lsp package...\n${NC}"
npm run compile

# Link codespaces-lsp package to the workbench package
echo -e "\n${GREEN}➡️ Linking local github/codespaces-lsp to workbench...\n${NC}"
npm link
cd /workspaces/github/ui/packages/workbench
npm link @github/codespaces-lsp

# Add the codespaces-lsp repo as a workspace in VS Code
if [ "$ADD_TO_WORKSPACE" = true ]; then
   echo -e "\n${GREEN}➡️ Adding codespaces-lsp to VS Code workspace...\n${NC}"
   code --add /workspaces/codespaces-lsp
fi

echo -e ""
echo -e "${GREEN}🎉🎉 FINISHED! The codespaces-lsp repo has been set up! 🎉🎉"
echo -e ""
