#!/usr/bin/env safe-ruby
# frozen_string_literal: true
require_relative "../config/environment"

puts "Setting up issue dependencies..."

# We depend on Issues React, so make sure it's enabled first
if GitHub.flipper[:issues_react].enabled?
  puts "Issues React is already enabled, skipping..."
else
  puts "Setting up Issues React..."
  system("script/setup-issues-react")
end

GitHub.flipper[:issue_dependencies].enable

puts "🎉 Issue dependencies is setup and ready to use!"
