#!/usr/bin/env safe-ruby
# frozen_string_literal: true

puts "=> Loading the environment..."

require_relative "#{Rails.root}/config/environment"
require_relative "#{Rails.root}/script/seeds/objects"
require_relative "#{Rails.root}/script/seeds/runner"
require_relative "#{Rails.root}/script/seeds/runners/models_byok"

unless Rails.env.development?
  raise "This is a dev-only script"
end

KREDZ_WORKSPACE = "/workspaces/kredz"

IS_PRISTINE = !!(ARGV.delete("--pristine"))

class SetupModelsByok
  def call
    puts "============================================================"
    puts "Starting Models BYOK (Bring Your Own Key) setup"
    puts "You may find running `script/setup-models` useful as well."
    puts "============================================================\n\n"

    setup_custom_app
    setup_kredz
    enable_feature_flags
    run_seeds

    puts "\n\nModels BYOK setup completed. 🎉 Go forth and build cool things!"
  end

  private

  def enable_feature_flags
    flags = [
      :github_models_byok,
    ]
    puts "Enabling feature flags"

    flags.each do |flag|
      puts "Enabling #{flag} feature..."
      GitHub.flipper[flag].enable
    end
  end

  def setup_custom_app
    puts "Setting up custom integration app..."
    run_cmd "bin/create-byok-custom-models-app"
  end

  def run_seeds
    puts "Running seeds..."
    Seeds::Runner::ModelsByok.execute({ pristine: IS_PRISTINE })
  end

  def setup_kredz
    puts "\nEnsuring kredz is up and running..."

    kredz_repo_url = run_cmd "script/gh-clone-url github/kredz"

    unless Dir.exist?(KREDZ_WORKSPACE)
      if @pristine
        kill_kredz
        puts "Removing existing #{KREDZ_WORKSPACE}..."
        run_cmd "rm -rf #{KREDZ_WORKSPACE}"
      end

      puts "Cloning #{kredz_repo_url} into #{KREDZ_WORKSPACE}..."
      run_cmd "git clone --depth 1 #{kredz_repo_url} #{KREDZ_WORKSPACE}"
    end

    Dir.chdir(KREDZ_WORKSPACE) do
      puts "Setting up kredz..."

      kill_kredz

      run_cmd "script/setup"
      # Currently chatops doesnt work for us, comment out
      run_cmd "sed -i 's/^chatops:/# &/g' Procfile"

      puts "Starting kredz..."
      run_cmd <<~SH
        script/server --fast > /tmp/kredz.log 2>&1 &
        echo $! > /tmp/kredz.pid
      SH

      puts "Kredz logs avaliable at `/tmp/kredz.log`"

      puts "Waiting for kredz to be ready..."
      # 5008 is Kredz' port as of now: https://github.com/github/kredz/blob/5888e62fd0f20d3df74565e305d8b7d09780ddb0/script/server#L10
      wait_for_cmd "curl -s -o /dev/null -w '%{http_code}' http://localhost:5008/_health", "200"
    end
  end

  def kill_kredz
    if File.exist?("/tmp/kredz.pid")
      puts "Killing existing kredz process..."
      run_cmd "kill $(cat /tmp/kredz.pid) || true"
      run_cmd "rm -f /tmp/kredz.pid"
    end
  end

  def wait_for_cmd(cmd, stdout)
    max_attempts = 10
    attempt = 0
    while attempt < max_attempts
      begin
        output = run_cmd cmd, quiet: true
        if output == stdout
          return
        end
      rescue => e
        attempt += 1
        sleep 2
      end
    end
    raise "Command never returned '#{stdout}' after #{max_attempts} attempts"
  end

  def run_cmd(cmd, quiet: false)
    stdout_str = String.new
    puts "Running cmd: #{cmd}"

    rd, wr = IO.pipe
    pid = spawn("bash", "-c", cmd, out: wr, err: wr)
    wr.close

    while (line = rd.gets)
      unless quiet
        puts "[cmd]: #{line}"
      end
      stdout_str << line
    end

    Process.wait(pid)
    status = $?.exitstatus

    unless status == 0
      unless quiet
        puts "+++++++++"
        puts cmd
        puts "+++++++++"
      end
      raise "Command failed with status #{status}"
    end

    stdout_str.strip
  end
end

SetupModelsByok.new.call
