#!/usr/bin/env safe-ruby
# frozen_string_literal: true

require_relative "#{Rails.root}/config/environment"
require_relative "#{Rails.root}/script/seeds/objects"
require_relative "#{Rails.root}/script/seeds/runner"
require_relative "#{Rails.root}/script/seeds/runners/azure_models"

unless Rails.env.development?
  raise "This is a dev-only script"
end

class SetupModels
  def call
    puts("Starting Models setup")

    enable_feature_flags
    create_models

    puts "Models setup completed."
  end

  private

  def enable_feature_flags
    flags = [
      :project_neutron_fetch_catalog_items_job,
      :project_neutron_o1_models,
    ]
    puts "Enabling feature flags"

    flags.each do |flag|
      puts "Enabling #{flag}"
      GitHub.flipper[flag].enable
    end
  end

  def create_models
    puts "Creating models"
    Seeds::Runner::AzureModels.execute({})
  end
end

SetupModels.new.call
