#!/bin/bash
set -e

# This script sets up the github/github-ui repository for a github/github codespace.

RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print help message
help() {
   echo "Sets up the github/github-ui repository for a github/github codespace."
   echo
   echo "Usage: setup-codespaces-github-ui [-b branch] [-d|h] "
   echo "Options:"
   echo "-b     Specify the github-ui branch to clone. Defaults to main if not provided."
   echo "-d     Before starting, delete the existing github-ui directory in the codespace."
   echo "-w     Warmup webpack builds."
   echo "-s     Silence some errors."
   echo "-h     Print this help message."
   echo
}

# Set the branch as main. If a branch is provided as an argument, it will be set to that when we parse the provided options.
BRANCH=main

# Get the options
while getopts ":b:hdws" opt; do
   case $opt in
      h) # display help message
         help
         exit;;
      b) # If a branch was provided, re-set the variable
         BRANCH=$OPTARG;;
      d) # Delete the repository if it exists
         DELETE_REPO=true;;
      w) # Warmup webpack builds
         WARMUP_WEBPACK=true;;
      s) # Silence some errors
         SILENT=true;;
     :)
      echo "Error: Option -$OPTARG requires an argument."
      exit 1;;
     \?) # Invalid option
         echo "Error: Invalid option -$OPTARG"
         exit 1;;
   esac
done

if [ "$DELETE_REPO" = true ]; then
  echo -e "\n${GREEN}➡️ Deleting the existing github-ui repo...\n${NC}"
  sudo rm -rf /workspaces/github-ui
fi

# If the github-ui repo already exists and the delete argument hasn't been specified, cleanly exit.
if [[ -d "/workspaces/github-ui" && -z "$DELETE_REPO" ]]; then

  if [ "$SILENT" == true ]; then
    exit 0
  else
    echo -e "${RED}The github-ui directory already exists in this codespace.${NC} \nYou can rerun the setup script with the -d argument to force the deletion of the existing repository."
    exit 1
  fi
fi

# Do a clone of github-ui to the /workspaces/github-ui dir
# If a branch was supplied, use that branch for the clone.
echo -e "\n${GREEN}➡️ Cloning github-ui repo at branch $BRANCH...\n${NC}"
git clone https://github.com/github/github-ui /workspaces/github-ui --branch $BRANCH

# Bootstrap github-ui
echo -e "\n${GREEN}➡️ Bootstrapping github-ui...\n${NC}"
( cd /workspaces/github-ui ; script/bootstrap )

if [ "$WARMUP_WEBPACK" = true ]; then
  echo -e "\n${GREEN}➡️ Warming up webpack...\n${NC}"
  ( cd /workspaces/github-ui ; script/warmup-webpack )
fi

echo -e "\n${GREEN}➡️ Setting up pre-push hooks\n${NC}"
( cd /workspaces/github-ui ; ln -fs $(pwd)/script/pre-push .git/hooks/pre-push )

# Install Playwright dependencies and browsers
echo -e "\n${GREEN}➡️ Installing Playwright dependencies and browsers...\n${NC}"
( cd /workspaces/github-ui ; yes | npx playwright install --with-deps)

echo -e ""
echo -e "${GREEN}🎉🎉 FINISHED! The github-ui repo has been set up! 🎉🎉"
echo -e "${GREEN}To start github-ui in another Codespaces along side with dotcom, run the following command:${NC}"
echo -e ""
echo -e "${ORANGE}code /workspaces/github-ui${NC}"
