#!/usr/bin/env safe-ruby
# frozen_string_literal: true

require_relative "../config/environment"

unless Rails.env.development?
  raise "This is a dev-only script"
end

puts "Setting up issue dependencies..."

puts "Setting up Issues React..."
system("script/setup-issues-react --skip-seed-data")

GitHub.flipper[:issue_dependencies].enable
GitHub.flipper[:issue_dependencies_internal_dev].enable

puts "Seeding Issue Dependencies..."

seed_options = ARGV & [
  "--verbose", "-v",
  "--small", "-s",
  "--medium", "-m",
  "--full", "-f",
]
system("bin/seed issue_dependencies #{seed_options.join(" ")}")

puts "🎉 Issue dependencies is setup and ready to use!"
