#!/usr/bin/env safe-ruby
# frozen_string_literal: true

require_relative "../script/seeds/runners/issues_react"
require_relative "../script/seeds/runners/issue_fields"
require_relative "../config/environment"

unless Rails.env.development?
  raise "This is a dev-only script"
end

# puts "Seeding issues react..."
Seeds::Runner::IssuesReact.execute({ minimal: true })

# puts "Seeding issue fields..."
Seeds::Runner::IssueFields.execute

puts "Setting up feature flags..."

github_org = Organization.find_by(login: "github")
issue_fields_repo = Repository.find_by(name: "issue-fields", organization: github_org)
monalisa = User.find_by(login: "monalisa")

FeatureFlag.vexi_management.add_feature_flag_actors(:issue_fields, [github_org, issue_fields_repo])
FeatureFlag.vexi_management.add_feature_flag_actors(:issue_fields_actor_can_see, [monalisa])

puts "Issues Fields are setup!"
