#!/usr/bin/env safe-ruby
# frozen_string_literal: true

require_relative "../script/seeds/runners/issues_react"
require_relative "../script/seeds/runners/issue_fields"
require_relative "../config/environment"

unless Rails.env.development?
  raise "This is a dev-only script"
end

puts "Setting up feature flags..."
GitHub.flipper[:issue_fields].enable

puts "Seeding issues react..."
Seeds::Runner::IssuesReact.execute({ minimal: true })

puts "Seeding issue fields..."
Seeds::Runner::IssueFields.execute

puts "Issues Fields are setup!"
