#!/bin/sh

echo "=> cloning github/starry"
mkdir -p /workspaces/starry
git clone https://github.com/github/starry /workspaces/starry

echo "
=> make build"
cd /workspaces/starry
make build

echo "
=> starry service is set up! call `STARRY_HMAC_KEY_0=abc MYSQL_DB_NAME=github_development make run` to start the service.
"
