#!/bin/bash
set -e

cleanup() {
  export GITHUB_TOKEN=$GITHUB_TOKEN_TMP
}

export GITHUB_TOKEN_TMP=$GITHUB_TOKEN
export GITHUB_TOKEN=''
trap cleanup EXIT

export PAT=ghp_MonalisaTheOctoPatMonalisaTheOctoPat
gh auth logout -h github.com || true
gh auth logout -h github.localhost -u monalisa || true
echo $PAT | gh auth login -h github.localhost --with-token

# Create setup actions
cd /workspaces/actions-org
for repo in setup-node setup-dotnet setup-ruby setup-java; do
  STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://github.localhost/actions/$repo)
  if [ $STATUS -eq 200 ]; then
    EMPTY=$(gh repo view actions/setup-node --json isEmpty --jq '.isEmpty')
    if [ "$EMPTY" = "true" ]; then
      echo "*** $repo is empty, populating ***"
      cd $repo
      git push -u http://monalisa:$PAT@github.localhost/actions/$repo.git main
      cd ..
    else
      echo "*** $repo already exists ***"
    fi
  else
    echo "*** Creating actions repo $repo ***"
    gh repo create actions/$repo --public
    cd $repo
    git push -u http://monalisa:$PAT@github.localhost/actions/$repo.git main
    cd ..
  fi
done

sudo chmod 777 /opt # This may be necessary for setup-ruby to work

# New test repo
cd /workspaces/packsmoke/packages-smoke-tests
sed -i 's/runs-on: ubuntu-latest/runs-on: self-hosted/' .github/workflows/*.yml
sed -i 's/ruby\/setup-ruby@v1/actions\/setup-ruby@v1/' .github/workflows/*-rubygems.yml

if git diff --quiet && git diff --staged --quiet; then
  echo "Changes already pushed to packages-smoke-tests..."
else
  git add config .github/*
  git commit -m "dev"
fi

# Create releases for actions
for repo in setup-node setup-dotnet setup-java; do
  if gh release view --repo github.localhost/actions/$repo v4 >/dev/null 2>&1; then
    echo "$repo@v4  exists"
  else
    gh release create --repo github.localhost/actions/$repo --title v4 --notes v4 v4
  fi
done

if gh release view --repo github.localhost/actions/setup-ruby v1 >/dev/null 2>&1; then
  echo "setup-ruby@v1 exists"
else
  gh release create --repo github.localhost/actions/setup-ruby --title v1 --notes v1 v1
fi

export org="github"

# Create ORG repos for each visibility
cd /workspaces/packsmoke/packages-smoke-tests
for visibility in public internal private; do
  if gh repo view $org/pst-$visibility >/dev/null 2>&1; then
    echo "*** $org/pst-$visibility already exists ***"
  else
    echo "*** Creating $org repo pst-$visibility ***"
    gh repo create $org/pst-$visibility --$visibility
    git push -u http://monalisa:$PAT@github.localhost/$org/pst-$visibility.git main
  fi
done

# Create publish IA repos
for nwo in actions/publish-immutable-action github/test-publish-internal-ts-action; do
  if gh repo view $nwo >/dev/null 2>&1; then
    echo "*** $nwo already exists ***"
  else
    echo "*** Creating repo $nwo ***"
    gh repo create $nwo --public
  fi
done

# Push script changes and tags to the publish IA repos
cd /workspaces/actions-org/publish-immutable-action
sed -i 's/github\.com/github.localhost/' .github/workflows/*.yml
sed -i 's/runs-on: ubuntu-latest/runs-on: self-hosted/' .github/workflows/*.yml
sed -i 's/immutable-actions/github/' .github/workflows/*.yml

if git diff --quiet && git diff --staged --quiet; then
  echo "Changes already pushed to publish-immutable-action..."
else
  git add .
  git commit -m "dev"
  git push -u http://monalisa:$PAT@github.localhost/actions/publish-immutable-action.git main
fi

cd /workspaces/packsmoke/test-publish-internal-ts-action
sed -i 's/immutable-actions\/publish-action-package/actions\/publish-immutable-action/g' .github/workflows/*.yml
# When copy-pasting `\\\\\/` into bash to create this script, it changes it to `\\\/` in the script itself.
# Then in the `sed` command the backslashes are telling it to interpret it as `\/` which is in the yaml file.
sed -i 's/immutable-actions\\\\\/publish-action-package/actions\\\\\/publish-immutable-action/g' .github/workflows/*.yml

sed -i 's/immutable-actions\/sync-releases-to-immutable-action/actions\/sync-releases-to-immutable-action/g' .github/workflows/*.yml
sed -i 's/immutable-actions\/test-publish-internal-ts-action/github\/test-publish-internal-ts-action/g' .github/workflows/*.yml
sed -i 's/runs-on: ubuntu-latest/runs-on: self-hosted/' .github/workflows/*.yml
sed -i 's/github\.com/github.localhost/' .github/workflows/*.yml

if git diff --quiet && git diff --staged --quiet; then
  echo "Changes already pushed to test-publish-internal-ts-action..."
else
  git add .
  git commit -m "dev"
  git push -u http://monalisa:$PAT@github.localhost/github/test-publish-internal-ts-action.git main
  git tag v0.0.0 # Necessary as a bootstrap so E2E test works
  git push -u http://monalisa:$PAT@github.localhost/github/test-publish-internal-ts-action.git v0.0.0
fi

export user="monalisa"

# Create USER repos for each visibility
cd /workspaces/packsmoke/packages-smoke-tests
for visibility in public private; do
  if gh repo view $user/pst-$visibility >/dev/null 2>&1; then
    echo "*** $user/pst-$visibility already exists ***"
  else
    echo "*** Creating $user repo pst-$visibility ***"
    gh repo create $user/pst-$visibility --$visibility
    git push -u http://monalisa:$PAT@github.localhost/$user/pst-$visibility.git main
  fi
done

mkdir -p /workspaces/runners
cd /workspaces/runners
curl -o actions-runner-linux-x64-2.315.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.315.0/actions-runner-linux-x64-2.315.0.tar.gz
for i in 0 1 2 3 4 5 6; do
  rm -rf r$i
  mkdir -p r$i
  tar xzf ./actions-runner-linux-x64-2.315.0.tar.gz -C r$i
done

repositories="github/pst-public \
github/pst-internal \
github/pst-private \
monalisa/pst-public \
monalisa/pst-private \
actions/publish-immutable-action \
github/test-publish-internal-ts-action"

i=0
# Avoid changing this order so the runner names match the VS Code task
for nwo in $repositories; do
  cd /workspaces/runners/r$i
  echo "*** Getting runner registration token for $nwo ***"
  token=$(curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $PAT" -H "X-GitHub-Api-Version: 2022-11-28" http://api.github.localhost/repos/$nwo/actions/runners/registration-token | jq -r '.token')
  ./config.sh remove
  # Runners must have unique names, so generate a random one since it's a pain to remove them
  runner_name=${nwo//\//-}-$(openssl rand -hex 5)

  # Retry a few times with geometric backoff because this is flaky
  attempt=0
  maxAttempts=20
  retryInterval=$((i + 4))
  while [ $attempt -lt $maxAttempts ]; do
    echo "*** Registering runner for $nwo ***"
    if ./config.sh --url http://github.localhost/$nwo --token $token --unattended --name $runner_name --labels ubuntu-latest; then
      break
    fi
    echo "Failed to configure runner $runner_name for $nwo, (attempt $((attempt)) of $((maxAttempts))) retrying..."
    attempt=$((attempt + 1))
    sleep $retryInterval
  done
  i=$((i + 1))
done
