#!/bin/bash
set -o errexit

# Sets up the github/attester repository for a github/github Codespaces.

# run checks before trying to setup
run_checks() {
  # Ensure we're in a Codespaces environment
  if [ "$CODESPACES" != "true" ]; then
    echo "This script should only be run in a GitHub Codespaces. Exiting."
    exit 1
  fi

  # Check if the directory /workspaces/attester exists
  if [ -d "/workspaces/attester" ]; then
    echo "The directory /workspaces/attester already exists. Exiting."
    exit 1
  fi
}

# setup Attester and its dependencies
setup_attester() {
  echo -e '\n==== Cloning attester into /workspaces/attester ===='
  git clone git@github.com:github/attester.git /workspaces/attester

  echo -e ""
  echo -e "🎉 FINISHED! The attester repo has been set up at /workspaces/attester! 🎉"
  echo -e "To start attester, open a new terminal window in /workspaces/attester and run 'make dev-server'"
}

run_checks
setup_attester
