#!/usr/bin/env safe-ruby
# frozen_string_literal: true

require_relative "../script/seeds/runners/issues_react"
require_relative "../config/environment"

unless Rails.env.development?
  raise "This is a dev-only script"
end

disable_ssr = ARGV.include?("--disable-ssr")

puts "Setting up feature flags..."

# Issues React
GitHub.flipper[:issues_react].enable # feature flag for issue#dashboard
GitHub.flipper[:issues_react_v2].enable # feature flag for issue#create, issue#show, issue#index
GitHub.flipper[:issues_react_logged_out].enable # feature flag for issue#create, issue#show, issue#index for logged out users
GitHub.flipper[:react_sandbox].enable
GitHub.flipper[:issues_react_global_add].enable
GitHub.flipper[:api_insights_rest].enable
GitHub.flipper[:issues_react_dashboard_saved_views].enable
GitHub.flipper[:issues_react_use_defer_directive].enable
GitHub.flipper[:sub_issues].enable
GitHub.flipper[:graphql_skip_reauthorize_scoped_items].enable
GitHub.flipper[:issues_react_validate_timeline_items].enable
GitHub.flipper[:issues_react_csr_index_actions].enable
GitHub.flipper[:issues_react_milestone_show].enable


# SSR
if disable_ssr
  GitHub.flipper[:disable_issues_react_ssr].enable
end

# Live Updates
GitHub.flipper[:pull_request_sub_triggers].enable
GitHub.flipper[:pull_request_single_subscription].enable
GitHub.flipper[:use_pull_request_subscriptions_enabled].enable

# Tasklists
GitHub.flipper[:tasklist_block].enable
GitHub.flipper[:tasklist_block_markdown_at_rest].enable

# Pull request dashboard
GitHub.flipper[:new_pulls_dashboard].enable

# Issue types
GitHub.flipper[:issue_types].enable

# Search
GitHub.flipper[:issues_advanced_search].enable

# Misc
GitHub.flipper[:api_insights_rest].enable
GitHub.flipper[:graphql_rescue_not_unique_client].enable # https://github.com/github/graphql-platform/issues/919
GitHub.flipper[:issues_react_bypass_template_selection].enable # https://github.com/github/issues/issues/9704
GitHub.flipper[:issues_react_grouped_diff_on_edit_history].enable # https://github.com/github/issues/issues/12526

puts "Creating issue dashboard feature preview..."
ff = FlipperFeature.find_by_name("issues_react")
Feature.create(public_name: "Issues React dashboard experience", slug: "issues_react", flipper_feature: ff, feedback_link: "https://github.com")
monalisa = User.find_by_login("monalisa")
monalisa.enable_feature_preview(:issues_react)

puts "Creating issues_react_v2 feature preview..."
ff = FlipperFeature.find_by_name("issues_react_v2")
Feature.create(public_name: "Issues React v2 experience", slug: "issues_react_v2", flipper_feature: ff, feedback_link: "https://github.com")
monalisa = User.find_by_login("monalisa")
monalisa.enable_feature_preview(:issues_react_v2)

# Dismisses the initial notice about the Projects feature so we don't have to guess
# if we need to dismiss it or not in the E2E tests.
monalisa.dismiss_notice("projects_beta_splash")

puts "Seeding issues react..."
Seeds::Runner::IssuesReact.execute({ minimal: true })

puts "Repairing Elastometer indexes..."
Elastomer::App.run ["repair"]

puts "Issues React is setup!"
