#!/bin/bash
set -e

# This script sets up the github/reposd repository for a github/github codespace.

RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print help message
help() {
   echo "Sets up the github/reposd repository for a github/github codespace."
   echo
   echo "Usage: setup-codespaces-reposd [-b branch] [-d|h] "
   echo "Options:"
   echo "-b     Specify the reposd branch to clone. Defaults to main if not provided."
   echo "-d     Before starting, delete the existing reposd directory in the codespace."
   echo "-h     Print this help message."
   echo
}

# Set the branch as main. If a branch is provided as an argument, it will be set to that when we parse the provided options.
BRANCH=main

# Get the options
while getopts ":b:hd" opt; do
   case $opt in
      h) # display help message
         help
         exit;;
      b) # If a branch was provided, re-set the variable
         BRANCH=$OPTARG;;
      d) # Delete the repository if it exists
         DELETE_REPO=true;;
     :)
      echo "Error: Option -$OPTARG requires an argument."
      exit 1;;
     \?) # Invalid option
         echo "Error: Invalid option -$OPTARG"
         exit 1;;
   esac
done

if [ "$DELETE_REPO" = true ]; then
  echo -e "\n${GREEN}➡️ Deleting the existing reposd repo...\n${NC}"
  rm -rf /workspaces/reposd
fi

# Change git user.email if it's a github noreply address
email_match='@users.noreply.github.com'
user_email=$(git config user.email)
if [[ $user_email =~ $email_match ]]; then
  # Get username from email address
  if [[ $user_email =~ [0-9]*\+(.*)@ ]]; then
    # Email format: <DIGITS>+username@users.noreply.github.com
    eval $(git config user.email "${BASH_REMATCH[1]}@github.com")
  else
    # Email format: username@users.noreply.github.com
    eval $(git config user.email $user_email)
  fi
fi

# Do a clone of reposd to the /workspaces/reposd dir
# If a branch was supplied, use that branch for the clone.
echo -e "\n${GREEN}➡️ Cloning reposd repo at branch $BRANCH...\n${NC}"
git clone https://${GITHUB_TOKEN}@github.com/github/reposd /workspaces/reposd --branch $BRANCH

# Build gotauth & reposd
echo -e "\n${GREEN}➡️ Building reposd...\n${NC}"
( cd /workspaces/reposd ; make reposd )

code --install-extension golang.go

echo -e ""
echo -e "${GREEN}🎉🎉 FINISHED! The reposd repo has been set up! 🎉🎉"
echo -e "${GREEN}To start reposd for github, run the following commands:${NC}"
echo -e ""
echo -e "\t${ORANGE}cd /workspaces/reposd && ./bin/reposd${NC}"
echo -e ""
echo -e "${GREEN}To start github, run the following commands:${NC}"
echo -e ""
echo -e "\t${ORANGE}cd /workspaces/github && REPOSD=1 script/server${NC}"
