#!/bin/sh
# usage: source ./script/setup-pink-panda

echo "=> cloning github/pinkpanda"
mkdir -p /workspaces/pinkpanda
git clone https://github.com/github/pinkpanda /workspaces/pinkpanda

cd /workspaces/pinkpanda
. script/bootstrap

echo "
=> make"
make

echo "
=> Pink Panda service is set up!"
