#!/bin/bash
set -e

setup_turboquality() {
  if [ -d /workspaces/turboquality ]; then
    echo -e "\n==== turboquality already exists in /workspaces/turboquality ===="
  else
    echo -e '\n==== Cloning turboquality into /workspaces/turboquality ===='
    gh repo clone github/turboquality /workspaces/turboquality
  fi

  pushd /workspaces/turboquality
  echo -e '\n==== Bootstrapping turboquality services ===='
  script/setup
  make build
  popd
}

setup_turboquality

echo -e ""
echo -e "🎉🎉 FINISHED! The turboquality repo has been set up at /workspaces/turboquality! 🎉🎉"
echo -e "To start the turboquality Twirp server, run the following command:"
echo -e "cd /workspaces/turboquality && bin/twirpserver"
echo -e "To start the turboquality PR analysis processor, run the following command once script/server is running:"
echo -e "cd /workspaces/github && bin/code-quality-pull-request-analysis-processor"
