#!/bin/bash

# Usage: script/slack-ghe-router-tunnel-server
# Start the github/slack ngrok tunnel for the GHE router if the repository has been cloned in the Codespace and
# the .env.ghe file exists, or no-op otherwise.

set -e

if test -f /workspaces/slack/bin/ngrok; then
  if [ -f /workspaces/slack/.env.ghe ]; then
    if [ -f /workspaces/slack/.env.slack ]; then
      cd /workspaces/slack && \
        bin/ngrok http localhost:4000 --config ngrok.yml --log=stdout --domain="${GITHUB_USER}-slack-ghe-router.ngrok.io"

    elif [ -f /workspaces/slack/.env.teams ]; then
      cd /workspaces/slack && \
        bin/ngrok http localhost:4000 --config ngrok.yml --log=stdout --domain="${GITHUB_USER}-teams-ghe-router.ngrok.io"

    else
      echo "Neither .env.slack nor .env.teams exists, sleeping."
      echo "If you want to run ngrok for github/slack, first run 'bin/setup-slack-repo -m',"
      echo "then 'overmind restart slack-ghe-router-tunnel'."
      sleep infinity
    fi

  else
    echo ".env.ghe does not exist, sleeping."
    echo "If you want to run ngrok for github/slack, first run 'bin/setup-slack-repo -m',"
    echo "then 'overmind restart slack-ghe-router-tunnel'."
    sleep infinity
  fi

else
  echo "/workspaces/slack/bin/ngrok does not exist, sleeping."
  echo "If you want to run ngrok for github/slack, first run 'bin/setup-slack-repo -m',"
  echo "then 'overmind restart slack-ghe-router-tunnel'."
  sleep infinity
fi
