#!/bin/bash
# Usage: script/start-primer-react-watcher
#
# Runs a watcher that automatically builds /workspace/primer/react when it changes.

# Only run if node_modules/@primer/react is a symlink, indicating dotcom has been
# configured to run from a local copy of primer/react.
if [ -L node_modules/@primer/react ]; then
  script/primerize start primer/react
else
  echo "primer/react does not appear to be linked for local development. Run bin/primerize setup primer/react to hook it up."
fi
