#!/bin/bash
#/ Usage: script/treelights-server
#/
#/ Runs treelights service.

# If we need to run the service multiple times on different ports, this name should be parameterized with the port.
NAME="treelights"

SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
source $SCRIPT_DIR/dx/lib/subproject-containers

SUBPROJECT_VERSION=$(subproject_version "treelights")
echo "treelights version $SUBPROJECT_VERSION"

# Run the service.
start_subproject --name ${NAME} \
  "ghcr.io/github/treelights/treelights-focal:$SUBPROJECT_VERSION"
