#!/bin/bash
set -eou pipefail

current_gems="$(readlink --canonicalize ./vendor/gems/current/)"
turboscan_directory=("$current_gems"/../bundler/gems/turboscan-*/)

(cd "$turboscan_directory" && go run ./cmd/turbomock)
