#!/bin/bash
#/ Usage: script/turboghas-server
#/
#/ Runs turboghas service.
set -euo pipefail

export BROKERS=127.0.0.1:9092
export MYSQL_ADDR=localhost:3306
export MYSQL_DB_NAME=github_development_turboghas

turboghas_directory="$(bin/bundle show turboghas-client)"
(cd "${turboghas_directory}/schemas" && (skeema lint github || true) && skeema push github --allow-unsafe --debug && skeema push github_test --allow-unsafe --debug)
(cd "${turboghas_directory}" && go run ./cmd/turboghas -processor)
