# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Blackbird::Query::V1::AlephRange`.
# Please instead update this file by running `bin/tapioca dsl Blackbird::Query::V1::AlephRange`.


class Blackbird::Query::V1::AlephRange < Google::Protobuf::AbstractMessage
  sig do
    params(
      end: T.nilable(Blackbird::Query::V1::AlephPosition),
      start: T.nilable(Blackbird::Query::V1::AlephPosition)
    ).void
  end
  def initialize(end: nil, start: nil); end

  sig { void }
  def clear_end; end

  sig { void }
  def clear_start; end

  sig { returns(T.nilable(Blackbird::Query::V1::AlephPosition)) }
  def end; end

  sig { params(value: T.nilable(Blackbird::Query::V1::AlephPosition)).void }
  def end=(value); end

  sig { returns(Object) }
  def has_end?; end

  sig { returns(Object) }
  def has_start?; end

  sig { returns(T.nilable(Blackbird::Query::V1::AlephPosition)) }
  def start; end

  sig { params(value: T.nilable(Blackbird::Query::V1::AlephPosition)).void }
  def start=(value); end
end
