# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Blackbird::Query::V1::TextDocumentDefinitionResponse`.
# Please instead update this file by running `bin/tapioca dsl Blackbird::Query::V1::TextDocumentDefinitionResponse`.


class Blackbird::Query::V1::TextDocumentDefinitionResponse < Google::Protobuf::AbstractMessage
  sig { params(body: T.nilable(Blackbird::Query::V1::AlephLocationResponse)).void }
  def initialize(body: nil); end

  sig { returns(T.nilable(Blackbird::Query::V1::AlephLocationResponse)) }
  def body; end

  sig { params(value: T.nilable(Blackbird::Query::V1::AlephLocationResponse)).void }
  def body=(value); end

  sig { void }
  def clear_body; end

  sig { returns(Object) }
  def has_body?; end
end
