#!/bin/bash

# The "next" version of Ruby. Usually this tracks the upcoming version,
# released in December of each year and is bumped each week, but may be the
# previous version for some time after we upgrade.
# This is tested in CI but doesn't run in production.
RUBY_NEXT_SHA="e0545a02503983e8824d0fb5972c15d51093d927"

# The current version of Ruby, which we run in production. This may include
# backports. Currently this is Ruby 3.4.4
RUBY_SHA="a38531fd3f617bf734ef7d6c595325f69985ea1d"

if [ -n "$JANKY_ENV_RUBY_SHA" ]; then
  echo -n "$JANKY_ENV_RUBY_SHA"
elif [ -n "$RUBY_NEXT" ]; then
  echo -n "$RUBY_NEXT_SHA"
else
  echo -n "$RUBY_SHA"
fi
