#!/bin/bash

# The "next" version of Ruby. Usually this tracks the upcoming version,
# released in December of each year and is bumped each week, but may be the
# previous version for some time after we upgrade.
# This is tested in CI but doesn't run in production.
RUBY_NEXT_SHA="ac24f70fb0c0cc80d30ec6e96b3369079775d0dc"

# The current version of Ruby, which we run in production. This may include
# backports. Currently this is Ruby 3.4.5
RUBY_SHA="20cda200d3ce092571d0b5d342dadca69636cb0f"

if [ -n "$JANKY_ENV_RUBY_SHA" ]; then
  echo -n "$JANKY_ENV_RUBY_SHA"
elif [ -n "$RUBY_NEXT" ]; then
  echo -n "$RUBY_NEXT_SHA"
else
  echo -n "$RUBY_SHA"
fi
