#!/bin/bash

# The "next" version of Ruby. Usually this tracks the upcoming version,
# released in December of each year and is bumped each week, but may be the
# previous version for some time after we upgrade.
# This is tested in CI but doesn't run in production.
RUBY_NEXT_SHA="97c133a8591495156f46b53c613abee8c7088a04"

# The current version of Ruby, which we run in production. This may include
# Currently this is Ruby 3.4.2
RUBY_SHA="d2930f8e7a5db8a7337fa43370940381b420cc3e"

if [ -n "$JANKY_ENV_RUBY_SHA" ]; then
  echo -n "$JANKY_ENV_RUBY_SHA"
elif [ -n "$RUBY_NEXT" ]; then
  echo -n "$RUBY_NEXT_SHA"
else
  echo -n "$RUBY_SHA"
fi
