# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/github/platform_health/v1/user_generated_content.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'hydro/schemas/github/v1/entities/repository_pb'
require 'hydro/schemas/github/v1/entities/request_context_pb'
require 'hydro/schemas/github/v1/entities/spamurai_form_signals_pb'
require 'hydro/schemas/github/v1/entities/specimen_data_pb'
require 'hydro/schemas/github/v1/entities/user_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.github.platform_health.v1.UserGeneratedContent" do
    optional :request_context, :message, 1, "hydro.schemas.github.v1.entities.RequestContext"
    optional :spamurai_form_signals, :message, 2, "hydro.schemas.github.v1.entities.SpamuraiFormSignals"
    optional :action_type, :enum, 3, "hydro.schemas.github.platform_health.v1.UserGeneratedContent.ActionType"
    optional :content_type, :enum, 4, "hydro.schemas.github.platform_health.v1.UserGeneratedContent.ContentType"
    optional :actor, :message, 5, "hydro.schemas.github.v1.entities.User"
    optional :original_type_url, :string, 6
    optional :content_database_id, :int64, 7
    optional :content_global_relay_id, :string, 8
    optional :content_created_at, :message, 9, "google.protobuf.Timestamp"
    optional :content_updated_at, :message, 10, "google.protobuf.Timestamp"
    optional :title, :message, 11, "hydro.schemas.github.v1.entities.SpecimenData"
    optional :content, :message, 12, "hydro.schemas.github.v1.entities.SpecimenData"
    optional :parent_content_author, :message, 13, "hydro.schemas.github.v1.entities.User"
    optional :parent_content_database_id, :int64, 14
    optional :parent_content_global_relay_id, :string, 15
    optional :parent_content_created_at, :message, 16, "google.protobuf.Timestamp"
    optional :parent_content_updated_at, :message, 17, "google.protobuf.Timestamp"
    optional :owner, :message, 18, "hydro.schemas.github.v1.entities.User"
    optional :repository, :message, 19, "hydro.schemas.github.v1.entities.Repository"
    optional :content_visibility, :enum, 20, "hydro.schemas.github.platform_health.v1.UserGeneratedContent.ContentVisibility"
  end
  add_enum "hydro.schemas.github.platform_health.v1.UserGeneratedContent.ActionType" do
    value :ACTION_TYPE_UNKNOWN, 0
    value :CREATE, 1
    value :UPDATE, 2
  end
  add_enum "hydro.schemas.github.platform_health.v1.UserGeneratedContent.ContentType" do
    value :CONTENT_TYPE_UNKNOWN, 0
    value :COMMIT_COMMENT, 1
    value :DISCUSSION, 2
    value :DISCUSSION_COMMENT, 3
    value :FEED_POST, 18
    value :FEED_POST_COMMENT, 19
    value :GIST, 4
    value :GIST_COMMENT, 5
    value :GIST_FILE, 12
    value :ISSUE, 6
    value :ISSUE_COMMENT, 7
    value :MEMEX_PROJECT, 15
    value :MEMEX_PROJECT_COLUMN_VALUE, 16
    value :MEMEX_PROJECT_ITEM, 17
    value :PROJECT, 8
    value :PROJECT_CARD, 9
    value :PULL_REQUEST, 10
    value :PULL_REQUEST_REVIEW_COMMENT, 11
    value :REPOSITORY_DESCRIPTION, 13
    value :PROFILE_BIO, 14
    value :PRONOUN, 21
    value :PULL_REQUEST_REVIEW, 20
  end
  add_enum "hydro.schemas.github.platform_health.v1.UserGeneratedContent.ContentVisibility" do
    value :VISIBILITY_UNKNOWN, 0
    value :PUBLIC, 1
    value :PRIVATE, 2
    value :INTERNAL, 3
    value :SECRET, 4
  end
end

module Hydro
  module Schemas
    module Github
      module PlatformHealth
        module V1
          UserGeneratedContent = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.platform_health.v1.UserGeneratedContent").msgclass
          UserGeneratedContent::ActionType = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.platform_health.v1.UserGeneratedContent.ActionType").enummodule
          UserGeneratedContent::ContentType = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.platform_health.v1.UserGeneratedContent.ContentType").enummodule
          UserGeneratedContent::ContentVisibility = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.platform_health.v1.UserGeneratedContent.ContentVisibility").enummodule
        end
      end
    end
  end
end
