# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Hydro::Schemas::Github::Billing::V0::ZuoraWebhook`.
# Please instead update this file by running `bin/tapioca dsl Hydro::Schemas::Github::Billing::V0::ZuoraWebhook`.


class Hydro::Schemas::Github::Billing::V0::ZuoraWebhook < Google::Protobuf::AbstractMessage
  sig { params(webhook_id: T.nilable(Integer)).void }
  def initialize(webhook_id: nil); end

  sig { void }
  def clear_webhook_id; end

  sig { returns(Integer) }
  def webhook_id; end

  sig { params(value: Integer).void }
  def webhook_id=(value); end
end
