import {referenceID} from '@github-ui/copilot-chat/utils/copilot-chat-helpers'
import {
  type FileReference,
  type IssueReference,
  NullMessageId,
  type ThreadScopedFileReference,
} from '@github-ui/copilot-chat/utils/copilot-chat-types'

export type PreviewableContentTypes = 'file' | 'issue' | 'new-issue' | 'image' | 'file-reference'

export type PreviewableContentIdentifier = `${PreviewableContentTypes}:${string}`

export type VersionedPreviewableContentIdentifier = `${PreviewableContentIdentifier}#${string}`

export type FileIdentifier = `file:${string}#${number}.${number}` | `file:${string}#${number}`

export interface PreviewableContentBase {
  messageId: string
  name: string
  id: PreviewableContentIdentifier
  type: PreviewableContentTypes
}

export interface VersionedPreviewableContent extends PreviewableContentBase {
  id: VersionedPreviewableContentIdentifier
  timestamp: Date
}

export interface File extends VersionedPreviewableContent {
  id: FileIdentifier
  language: string
  value: string
  type: 'file'
  name: string
  isStreaming: boolean
  /** true if the user has edited this File */
  isUserEdited: boolean
  /** if this file is from a reference (i.e. not generated by Copilot) this will be set */
  reference?: FileReference | ThreadScopedFileReference
}

export interface Issue extends PreviewableContentBase {
  number: number
  owner: string
  repo: string
  type: 'issue'
  id: `issue:${string}`
}

export interface NewIssue extends PreviewableContentBase {
  owner: string
  repo: string
  type: 'new-issue'
  id: `issue:${string}`
  body?: string
}

export interface Image extends PreviewableContentBase {
  altText: string
  type: 'image'
  url: string
  id: `image:${string}`
}

export type PreviewableContent = File | Issue | Image | NewIssue

/**
 * A map of unversioned identifiers to a list of versioned identifiers.
 */
export type VersionedItemsMap = ReadonlyMap<PreviewableContentIdentifier, PreviewableContentIdentifier[]>

/**
 * A map of identifiers to the content they identify.
 */
export type ItemsMap = ReadonlyMap<PreviewableContentIdentifier, PreviewableContent>

export function stripVersionFromId(id: PreviewableContentIdentifier): PreviewableContentIdentifier {
  return id.split('#')[0] as PreviewableContentIdentifier
}

export function getRevisionNumber(id: PreviewableContentIdentifier, versionedItems: VersionedItemsMap): number | null {
  const baseId = stripVersionFromId(id)
  const versions = versionedItems.get(baseId) ?? []
  const versionIndex = versions.indexOf(id)
  return versions.length > 1 && versionIndex !== -1 ? versionIndex + 1 : null
}

export function makeReferenceFromFile(item: File): ThreadScopedFileReference {
  return {
    type: 'thread-scoped-file',
    name: item.name,
    language: item.language,
    text: item.value,
  }
}

export function makeItemFromThreadScopedFileReference(
  ref: ThreadScopedFileReference,
  messageId: string,
  messageIndex: number,
  timestamp: string,
): File {
  return {
    type: 'file',
    id: `file:${ref.name}#${messageIndex}`, // TODO: this should be messageId once we have a stable value for that
    reference: ref,
    messageId,
    name: ref.name,
    language: ref.language,
    value: ref.text,
    timestamp: new Date(timestamp),
    isStreaming: false,
    isUserEdited: false,
  }
}

export function makeItemFromFileReference(ref: FileReference, messageId?: string, timestamp?: string): File {
  return {
    type: 'file',
    id: `file:${referenceID(ref)}#0`,
    reference: ref,
    messageId: messageId ?? NullMessageId,
    name: ref.path,
    language: ref.languageName ?? '',
    value: '',
    isStreaming: true,
    isUserEdited: false,
    timestamp: timestamp ? new Date(timestamp) : new Date(),
  }
}

export function makeItemFromIssueReference(ref: IssueReference, messageId?: string): Issue {
  return {
    type: 'issue',
    id: `issue:${ref.number}`,
    messageId: messageId ?? NullMessageId,
    name: ref.title ?? '',
    number: ref.number,
    owner: ref.repository.owner,
    repo: ref.repository.name,
  }
}

/**
 * Search the given items for files that have been edited.
 */
export function getEditedFiles(items: ItemsMap) {
  return Array.from(items.values())
    .flat()
    .filter(item => item.type === 'file')
    .filter(item => item.isUserEdited)
}
