# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Api::App::PlatformTypes::PullRequestInfoForListViewUpdatedPayload`.
# Please instead update this file by running `bin/tapioca dsl Api::App::PlatformTypes::PullRequestInfoForListViewUpdatedPayload`.


class Api::App::PlatformTypes::PullRequestInfoForListViewUpdatedPayload < GraphQL::Client::Schema::ObjectClass
  sig { returns(T.nilable(String)) }
  def __typename; end

  sig { returns(T.nilable(Api::App::PlatformTypes::PullRequest)) }
  def comments_updated; end

  sig { returns(T::Boolean) }
  def comments_updated?; end

  sig { returns(T.nilable(Api::App::PlatformTypes::PullRequest)) }
  def commit_checks_updated; end

  sig { returns(T::Boolean) }
  def commit_checks_updated?; end

  sig { returns(Api::App::PlatformTypes::PullRequest) }
  def pull_request; end

  sig { returns(T::Boolean) }
  def pull_request?; end

  sig { returns(T.nilable(Api::App::PlatformTypes::PullRequest)) }
  def review_decision_updated; end

  sig { returns(T::Boolean) }
  def review_decision_updated?; end

  sig { returns(T.nilable(Api::App::PlatformTypes::PullRequest)) }
  def status_updated; end

  sig { returns(T::Boolean) }
  def status_updated?; end

  sig { returns(T.nilable(Api::App::PlatformTypes::PullRequest)) }
  def title_updated; end

  sig { returns(T::Boolean) }
  def title_updated?; end
end
