# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SecurityCampaigns::CreateIssuesJob`.
# Please instead update this file by running `bin/tapioca dsl SecurityCampaigns::CreateIssuesJob`.


class SecurityCampaigns::CreateIssuesJob
  class << self
    sig do
      params(
        campaign_id: ::Integer,
        repository_ids: T::Array[::Integer],
        block: T.nilable(T.proc.params(job: SecurityCampaigns::CreateIssuesJob).void)
      ).returns(T.any(SecurityCampaigns::CreateIssuesJob, FalseClass))
    end
    def perform_later(campaign_id:, repository_ids:, &block); end

    sig { params(campaign_id: ::Integer, repository_ids: T::Array[::Integer]).void }
    def perform_now(campaign_id:, repository_ids:); end
  end
end
