# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SecurityCampaigns::SendOverdueNotificationJob`.
# Please instead update this file by running `bin/tapioca dsl SecurityCampaigns::SendOverdueNotificationJob`.


class SecurityCampaigns::SendOverdueNotificationJob
  class << self
    sig do
      params(
        campaign_id: ::Integer,
        block: T.nilable(T.proc.params(job: SecurityCampaigns::SendOverdueNotificationJob).void)
      ).returns(T.any(SecurityCampaigns::SendOverdueNotificationJob, FalseClass))
    end
    def perform_later(campaign_id:, &block); end

    sig { params(campaign_id: ::Integer).void }
    def perform_now(campaign_id:); end
  end
end
