# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `MonolithTwirp::Packageregistry::AuditLog::V1::AuditLogAPIClient`.
# Please instead update this file by running `bin/tapioca dsl MonolithTwirp::Packageregistry::AuditLog::V1::AuditLogAPIClient`.


class MonolithTwirp::Packageregistry::AuditLog::V1::AuditLogAPIClient < ::Twirp::Client
  sig { params(connection: T.any(String, ::Faraday::Connection), opts: T::Hash[Symbol, T.untyped]).void }
  def initialize(connection, opts = {}); end

  sig do
    params(
      input: MonolithTwirp::Packageregistry::AuditLog::V1::AuditLogRequest,
      req_opts: T.nilable(T::Hash[Symbol, T.untyped])
    ).returns(::Twirp::ClientResp[MonolithTwirp::Packageregistry::AuditLog::V1::AuditLogResponse])
  end
  def audit_log(input, req_opts = nil); end
end
