# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Hydro::Schemas::Billingplatform::V1::BudgetChangedNotification`.
# Please instead update this file by running `bin/tapioca dsl Hydro::Schemas::Billingplatform::V1::BudgetChangedNotification`.


class Hydro::Schemas::Billingplatform::V1::BudgetChangedNotification < Google::Protobuf::AbstractMessage
  sig do
    params(
      check_can_proceed_with_usage: T.nilable(T::Boolean),
      customer_id: T.nilable(String),
      pricing_target: T.nilable(Hydro::Schemas::Billingplatform::V1::Entities::PricingTarget),
      reason_type: T.nilable(T.any(Symbol, Integer))
    ).void
  end
  def initialize(check_can_proceed_with_usage: nil, customer_id: nil, pricing_target: nil, reason_type: nil); end

  sig { returns(T::Boolean) }
  def check_can_proceed_with_usage; end

  sig { params(value: T::Boolean).void }
  def check_can_proceed_with_usage=(value); end

  sig { void }
  def clear_check_can_proceed_with_usage; end

  sig { void }
  def clear_customer_id; end

  sig { void }
  def clear_pricing_target; end

  sig { void }
  def clear_reason_type; end

  sig { returns(String) }
  def customer_id; end

  sig { params(value: String).void }
  def customer_id=(value); end

  sig { returns(Object) }
  def has_pricing_target?; end

  sig { returns(T.nilable(Hydro::Schemas::Billingplatform::V1::Entities::PricingTarget)) }
  def pricing_target; end

  sig { params(value: T.nilable(Hydro::Schemas::Billingplatform::V1::Entities::PricingTarget)).void }
  def pricing_target=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def reason_type; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def reason_type=(value); end
end
