# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/token_scanning_service/v0/backfill_group_request.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.token_scanning_service.v0.BackfillGroupRequest" do
    optional :owner_id, :int64, 1
    optional :owner_scope, :enum, 2, "hydro.schemas.token_scanning_service.v0.BackfillGroupRequest.OwnerScope"
    optional :action, :enum, 3, "hydro.schemas.token_scanning_service.v0.BackfillGroupRequest.Action"
    optional :backfill_type, :enum, 4, "hydro.schemas.token_scanning_service.v0.BackfillGroupRequest.BackfillType"
    repeated :feature_flags, :string, 5
    optional :requested_at, :message, 6, "google.protobuf.Timestamp"
    optional :business, :message, 7, "hydro.schemas.token_scanning_service.v0.BackfillGroupRequest.Business"
    repeated :repository_ids, :int64, 8
    optional :security_configuration_id, :int64, 9
  end
  add_message "hydro.schemas.token_scanning_service.v0.BackfillGroupRequest.Business" do
    optional :id, :int64, 1
    optional :name, :string, 2
  end
  add_enum "hydro.schemas.token_scanning_service.v0.BackfillGroupRequest.BackfillType" do
    value :UNKNOWN_BACKFILL_TYPE, 0
    value :FULL, 1
    value :CUSTOM_PATTERN, 2
    value :GENERIC_SECRETS, 3
    value :LOW_CONFIDENCE_PATTERN, 4
  end
  add_enum "hydro.schemas.token_scanning_service.v0.BackfillGroupRequest.OwnerScope" do
    value :UNKNOWN_SCOPE, 0
    value :ORGANIZATION_SCOPE, 1
    value :BUSINESS_SCOPE, 2
    value :USER_SCOPE, 3
  end
  add_enum "hydro.schemas.token_scanning_service.v0.BackfillGroupRequest.Action" do
    value :UNKNOWN, 0
    value :START, 1
    value :CANCEL, 2
  end
end

module Hydro
  module Schemas
    module TokenScanningService
      module V0
        BackfillGroupRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.token_scanning_service.v0.BackfillGroupRequest").msgclass
        BackfillGroupRequest::Business = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.token_scanning_service.v0.BackfillGroupRequest.Business").msgclass
        BackfillGroupRequest::BackfillType = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.token_scanning_service.v0.BackfillGroupRequest.BackfillType").enummodule
        BackfillGroupRequest::OwnerScope = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.token_scanning_service.v0.BackfillGroupRequest.OwnerScope").enummodule
        BackfillGroupRequest::Action = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.token_scanning_service.v0.BackfillGroupRequest.Action").enummodule
      end
    end
  end
end
