# frozen_string_literal: true

# rubocop:disable Bundler/OrderedGems
# bootstrap version: v11 (rev to force rebundling on deploy / checkout)

# Make sure to run 'bin/bundle install' after updating this file

source "https://rubygems.org"

use_graphql_next = ENV["GRAPHQL_NEXT"] == "1"
graphql_next_version = "2.3.22"

use_sorbet_next = ENV["SORBET_NEXT"] == "1"
sorbet_next_version = "0.5.12196" # 2025-06-23
tapioca_next_version = "0.17.6" # 2025-07-04

rails_version = "8.1.0.alpha.823bb8c4ff"

# Select Rails components to reduce unneeded dependencies
gem "actionmailer", rails_version
gem "actionpack", rails_version
gem "actionview", rails_version
gem "activejob", rails_version
gem "activemodel", rails_version
gem "activerecord", rails_version
gem "activesupport", rails_version
gem "railties", rails_version

gem "actionview_precompiler"
gem "acme-client",         "2.0.25"
gem "addressable",         "~> 2.8"
gem "argon2"
gem "asciidoctor",         "2.0.23"
gem "aws-sdk-s3",          "~> 1"
gem "aws-sdk-ecr", "~> 1.2"
gem "bcrypt"
gem "benchmark",           "~> 0.4"
gem "bertrpc",             "1.3.1.github11.5.ga14458b"
gem "bert",                "1.1.10.52.gf3b2e72"
gem "bindata",             "2.5.1"
gem "bootsnap"
gem "braintree",           "~> 4.0"
gem "brotli",              "0.7.0"
gem "builder",             "3.3.0"
gem "cbor",                "0.5.10.1"
gem "cff",                 "1.3.0"
gem "chatops-controller",  "5.2.0.4.g2193e18"
gem "charlock_holmes",     "0.7.9"
gem "coconductor",         "~> 0.9"
gem "codeowners", github: "github/codeowners", ref: "8c811c9bf9857e3dfb55db0bc3439f243a3f546a"
gem "color",               "1.8"
gem "commonmarker",        "0.23.10"
gem "concurrent-ruby-ext"
gem "contentful",          "~> 2.18"
gem "creole", github: "minad/creole", ref: "c96add125358bbd040f386543a9716da16cbdd72"
gem "cruby_crash_info"
gem "css_parser",          "1.21.1"
gem "cuprite",             "0.15.1"

gem "csv",                 "3.3.5"
gem "cvss-suite",          "~> 3.3"
gem "dalli",               "3.2.8"
gem "date",                "~> 3.3"
gem "osslicensecompliance-client", github: "github/osslicensecompliance", ref: "4313a7fee6a54cc1eec541b3e670738d1590de70", glob: "ruby/*.gemspec"

gem "diff-lcs"
gem "divvy",               "1.1.4.g677870a"
gem "dnsruby",             "~> 1.72"
gem "dogstatsd-ruby",      "~> 5.7.1"
gem "dogapi",              "~> 1.45.0"
gem "ecma-re-validator",   "~> 0.1"
gem "ed25519",             "~> 1.4"
gem "email_reply_parser",  "0.5.11"
gem "elastomer-client",    "6.2.4"
gem "ethon",               "0.16.0"
gem "escape_utils",        "1.3"
gem "erb",                 "~> 5.0"
gem "ernicorn",            "1.0.3", :path => "vendor/internal-gems/ernicorn"
gem "excon",               "~>1.2"
gem "faker",               "~> 3.5.2"
gem "faraday",             "~> 1.0"
gem "faraday_middleware"
gem "fast_blank",          "1.0.1"
gem "fast_gettext",        "~> 4.0"
# Installing platform specific ffi gem makes the Ruby Next builds fail for Ruby 3.5
# Force it to use the Ruby platform specifically
gem "ffi",                 "1.17.2", force_ruby_platform: true
gem "flipper",             "0.23.1"
gem "freno-client",        "~> 0.9.0"
gem "gemoji",              "4.1.0"
gem "geoip2_compat",       "0.0.3"
gem "geo_pattern",         "~> 1.5"
gem "get_process_mem",     "~> 1.0.0"
gem "gettext",             ">=3.3.6", :require => false
gem "gettext_i18n_rails",  "1.13.0"
gem "hashdiff",            "1.2.0"
gem "hiredis-client",      "~> 0.25.1"
gem "httpclient",          "2.9.0" # script/vendor-gem https://github.com/Shopify/httpclient.git
gem "i18n",                "1.14.7"
gem "gibbon",              "~>3.0"
gem "github-ds",           "0.5.4"
gem "github-linguist",     "9.2.0"
gem "github-markup",       "5.0.1"
gem "github-pages-health-check", "1.19.0"
gem "logger", "~> 1.7.0"
gem "mime-types-data", "3.2025.0902"
gem "gitrpc",              :path => "vendor/gitrpc"
gem "google-apis-androidpublisher_v3", "~> 0.85"
gem "gpgme"
if use_graphql_next
  gem "graphql",             graphql_next_version
else
  gem "graphql",             "2.3.22"
end
gem "graphql-batch",       "0.5.4"
gem "graphql-client",      "0.26.0"
gem "graphql-schema_comparator", "1.2.1"
gem "graphql-pro",          "1.27.1"
source "https://rubygems.pkg.github.com/github" do
  gem "group_syncer",        "1.6.5.re8320a7d"
end
gem "rugged",              "1.4.3.102.ga6b7142"
gem "google-protobuf", "3.14.0.1.r907f12546", force_ruby_platform: true
gem "hana",                "~> 1.3.6"
gem "hashids",             "1.0.5"
gem "homograph-detector",  "~> 0.1.1"
gem "horcrux",             "0.1.2"
gem "inline_svg",          "1.10.0"
gem "iopromise",           "0.1.5"
gem "jwt",                 "~> 2.10.2"
gem "json_schema",         "~> 0.20.9"
gem "json-schema",         "~> 6.0"
gem "datadog",             "2.20.0"
gem "levenshtein-ffi", github: "dbalatero/levenshtein-ffi", ref: "4b20df76a28fb106e69520001cdfcf206bc8169b"
gem "lz4-ruby",            "~> 0.3.3"
gem "pandoc-ruby",         "2.1.10"
gem "parallel"
gem "parser",              "~> 3.3"
gem "parslet",             "2.0.0"
gem "licensee",            "~> 9.18"
gem "liquid"
gem "lru_redux",           "0.8.4.14.g99d8d60"
gem "mail",                "~> 2.6"
gem "matrix"
gem "memcached",           github: "github/memcached", ref: "13d52378016cb3a2f3d96197eee8454739876812"
gem "mochilo",             "1.3.8.g0a99999"
gem "monetize",            "1.13.0"
gem "money-open-exchange-rates", "~> 1.3"
gem "money",               "~> 6.19.0"
gem "msgpack",             "~> 1.8"
gem "mustache",            "1.1.1.r28cb499"
gem "net-http-persistent", "~> 4.0.6"
gem "net-smtp"
gem "net-ftp"
gem "net-pop"
gem "net-imap"
gem "nokogiri",            ">= 1.16.2", force_ruby_platform: true
gem "oauth2",              "~> 2.0.14"
gem "observer",            "0.1.2"
gem "octicons_helper",     "19.15.5"
gem "chunky_png",          "~> 1.4.0"
gem "org-ruby",            "0.9.12.re74a318"
gem "ostruct"
gem "pathspec",            "~> 2.1.0"
gem "phonelib",            "0.10.11"
gem "pinglish",            "0.2.1"
gem "prawn",               "2.5.0"
gem "prawn-svg",           "0.38.0"
gem "prawn-table",         "0.2.2"
gem "prelude-batch-loader", github: "seejohnrun/prelude", ref: "09fbb3d33c6da7ec490a10fd2006add422f15112"
gem "premailer",           "1.27.0"
gem "presto-client",       "0.6.3.r0b63000"
gem "primer_view_components", "0.44.0"
gem "prism"
gem "progeny",             "0.2.1"
gem "prometheus_exporter", "0.5.3", :require => false
gem "psych",               "~> 5.2"
gem "psych-comments",      "0.1.1"
gem "public_suffix",       "~> 6.0"
gem "rack",                "~> 2.2"
gem "rails-controller-testing", "1.0.5"
gem "rake",                "~> 13.3"
gem "rblineprof",          "0.3.7", :platforms => :mri
gem "rbi",                 "0.3.3"
gem "rbnacl",              "~> 7.1"
gem "rbtrace",             "~> 0.5", :platforms => :mri
gem "rdoc",                "~> 6.14"
gem "re2",                 "2.16.0", force_ruby_platform: true
gem "readline"
gem "RedCloth",            "4.3.4"
gem "redis",               "5.4.0"
gem "redis-client",        "0.25.2"
gem "redis-namespace",     "1.11.0"
gem "resilient",           "~> 0.4.0"
gem "resolv",              "~> 0.6.2"
gem "resqued",             "0.13.0"
gem "rich_text_renderer",  "~> 0.2.2"
# https://github.com/maxprokopiev/rinku/commit/8583fe1c0531d2fdea6e5c120fb1b0b800b452b7
gem "rinku",               "2.0.6.r8583fe1"
gem "rollup", github: "github/rollup", ref: "8c84e9c824fd47e331c1e1a77b679b6daad6d029"
gem "rotp",                "~> 6.3.0"
gem "rqrcode",             "3.1.0"
gem "ruby-progressbar",    "~>1.7", :require => false
gem "rubypants",           "0.7.0.15.g6478da5"
gem "sourcemap",           "0.1.1"
gem "sanitize",            "~> 7.0"
gem "scientist",           "1.6.5"
gem "scrolls",             "0.9.6"
gem "secure_headers",      "7.1.0"
gem "securerandom",        "~> 0.4.1"
gem "shed", "0.0.4.2.g2652da3"
gem "ssh_data",            "2.0.0"
gem "simple_uuid",         "~> 0.3.0"
gem "sinatra",             "3.2.0"
gem "stackprof",           "0.2.27"
gem "statsd-ruby",         "0.3.0.github.3.38.gd478cc7"
gem "statsig",             "~> 2.5.5"
gem "stripe",              "8.7.0"
gem "syslog",              "0.3.0"
gem "terminal-table",      "~>4.0"
gem "thor",                "~> 1.4"
gem "trilogy",             "2.9.0"
gem "trino-client",        "2.2.2"
gem "twilio-ruby",         "7.7.1"
gem "twirp",               "~> 1.10"
gem "unicorn",             "6.1.0.66.g1370"
gem "pitchfork"
# script/vendor-gem -n raindrops -r a36cf00dee5d7657bf95b66bd4559feaab010989 https://yhbt.net/raindrops.git
gem "raindrops",           "0.20.1.14.ga36cf00"
gem "browser",             "6.2.0"
gem "vernier"
gem "version_sorter",      "2.3.0"
gem "view_component",      "4.0.0"
gem "vonage", github: "Vonage/vonage-ruby-sdk", ref: "a4cea6635a965ca67c9e2da76adc1ea7f59f5e73"
gem "wcag_color_contrast", "~> 0.1.0"
gem "webauthn",            "3.4.1"
gem "wikicloth",           "0.8.4.github.rf8188e2"
gem "will_paginate",       ">= 3.3.1"
gem "yajl-ruby",           "1.4.3"
gem "ruby-kafka",          "1.3.0"
gem "zstd-ruby"
gem "ipaddr",              "1.2.7"

gem "rubyzip", "3.0.0.rc2"

# enterprise specific gems go here for now
#
# NOTE: the `oa-enterprise` gem is built from the "0-3-stable" branch
#       of the https://github.com/github/omniauth repository
gem "github-ldap",   "1.10.1.20.g06d2c92"
gem "net-ldap",      "0.20.0"
gem "oa-enterprise", "0.3.2.g3930d46"
gem "octokit",       "4.20.0"
gem "xmldsig",       "0.7.0"
gem "ruby-saml",     "1.18.1"

# This is the last version that supports protobuf 3.14
# Versions after 0.27.0 require protobuf >= 3.18 https://github.com/open-telemetry/opentelemetry-ruby/pull/1645
# https://github.com/github/ecosystem-api/issues/3303
gem "opentelemetry-exporter-otlp", "0.27.0"

gem "sorbet-runtime", use_sorbet_next ? sorbet_next_version : "0.5.12196"

gem "tzinfo-data"

# TODO: fido-challenger-client should be moved into the
# https://rubygems.pkg.github.com/github source block, but the version currently
# published to GPR does not seem to be correct. It has a bundler-generated
# bin/challenge file, which doesn't seem like what is intended based on the
# README: https://github.com/github/fido-challenger-client/blob/master/README.md#maintainer-note
# We should probably publish a new version of the gem, verify that it has the
# correct contents, and then update to use that.
gem "fido-challenger-client"

source "https://rubygems.pkg.github.com/github" do
  gem "actions-broker", "0.0.2"
  gem "actions-run-service", "0.0.4"
  gem "actions-runner-admin", "0.1.1"
  gem "actions-usage-metrics", "1.0.41"
  gem "advisory_db_toolkit", github: "github/advisory-db", glob: "packages/advisory_db_toolkit/*.gemspec", ref: "07d88d605efb81c5f0cf0cc15a2a9cb0b4418028"
  gem "aqueduct-client", "1.3.3"
  gem "authnd-client", "0.24.8"
  gem "authzd-client", "0.12.0.r5fa8b4fb6"
  gem "azure-storage-common"
  gem "azure-storage-blob",  "~> 2.0.2"
  gem "badge-ruler", "0.0.2"

  # Billing Platform Gem
  gem "billing-platform-client", "2.4.0"
  gem "blackbird-analysis", "0.2.0.r9649833ca"
  gem "blackbird-client", github: "github/blackbird-mw", glob: "ruby/*.gemspec", ref: "cc40d126976db1fc9ba5c14c533fe7b1ced73f31"
  gem "chatterbox-client", "2.4.1.48.ge07b52b"

  gem "console_auth", github: "github/console_auth", ref: "ff5c50fcf1ff0e0c65bf586d964ddb4b7fc0b433", :require => false
  gem "delorean_client", "0.4.0.r09ee7b0"
  gem "dependency-graph-platform-proto", github: "github/dependency-graph-platform-proto", ref: "11788ee7692f237d3e2589fe4588e43b6e8208d8"
  gem "dependency-snapshots-api-proto", github: "github/dependency-snapshots-api", ref: "d8cd6af636d202c2653cfc476d2023208d7747c6", glob: "gen/ruby/*.gemspec"
  gem "diff-analysis", "0.1.0.r8ff4356"
  gem "driftwood-client", "0.0.1.r1319997b9"
  # Used for licenses on both GHES & GitHub.com (the latter for GitHub Connect)
  gem "enterprise-crypto", "0.6.2"
  gem "github-trilogy-adapter", "3.0.0"
  gem "github-kv", "0.0.1.rdbd1267"
  gem "github-kredz", "1.0.1.1135.gf4a4623f5"
  gem "github-orca", "0.0.20.1626.gb0c19ef3"
  gem "github-scout", "0.1.11"
  gem "goomba", "0.0.1.524.g069b966"
  gem "issues-graph-client", "0.9.0.r34eff86f"
  # Licensify gems
  gem "licensify-client", "0.16.4"
  gem "monolith-twirp-licensing-customers", "1.12.0"
  gem "monolith-twirp-licensing-enterprise_installations", "1.0.0"
  gem "monolith-twirp-licensing-repositories", "1.2.0"
  gem "monolith-twirp-dependency_graph_platform-actions", "1.1.1"
  gem "monolith-twirp-dependency_graph_platform-advisories", "1.0.0"
  gem "monolith-twirp-dependency_graph_platform-integrations", "1.1.1"
  gem "monolith-twirp-advisorydb-advisories", "1.0.1"
  gem "monolith-twirp-billing-repositories", "1.1.1"
  gem "monolith-twirp-classroom-access_check", "1.0.0"
  gem "monolith-twirp-classroom-assignments", "1.0.0"
  gem "monolith-twirp-classroom-integration", "1.0.2"
  gem "monolith-twirp-event_hydrator-event_hydration", "1.11.0"
  gem "monolith-twirp-classroom-users", "1.0.5"
  gem "monolith-twirp-classroom-repositories", "1.1.3"
  gem "monolith-twirp-classroom-organizations", "1.0.4"
  gem "monolith-twirp-classroom-classroom_repositories", "1.1.1"
  gem "monolith-twirp-classroom-sync_classroom", "1.0.5"
  gem "monolith-twirp-classroom-assignment_reuse", "1.1.0"
  gem "monolith-twirp-classroom-classroom_codespaces", "1.2.0"
  gem "monolith-twirp-code_scanning-enterprise", "1.0.0"
  gem "monolith-twirp-code_scanning-managed_analyses", "1.5.0"
  gem "monolith-twirp-code_scanning-repositories", "1.0.0"
  gem "monolith-twirp-code_scanning-suggested_fixes", "1.4.0"
  gem "monolith-twirp-code_scanning-turboghas", "1.4.11"
  gem "monolith-twirp-copilot-organizations", "1.0.11"
  gem "monolith-twirp-copilot-limiter", "1.2.2"
  gem "monolith-twirp-copilot-users", "1.8.7"
  gem "monolith-twirp-copilot-token", "1.3.0"
  gem "monolith-twirp-dependabot-tokens", "1.0.1"
  gem "monolith-twirp-dependabot-pullrequests", "1.0.12"
  gem "monolith-twirp-dependabot-settings", "1.10.2"
  gem "monolith-twirp-education_web-users", "1.15.10"
  gem "monolith-twirp-education_web-repos", "1.3.2"
  gem "monolith-twirp-education_web-orgs", "1.2.0"
  gem "monolith-twirp-actions-core", "1.0.93"
  gem "monolith-twirp-actionsresults-core", "1.25.0"
  gem "monolith-twirp-auditlog-streaming", "1.11.4"
  gem "monolith-twirp-git_src_migrator-migrations", "1.11.0"
  gem "monolith-twirp-git_src_migrator-monolith", "1.6.3"
  gem "monolith-twirp-github-repositories", "1.0.0"
  gem "monolith-twirp-kredz-core", "1.0.3"
  gem "monolith-twirp-mailreplies-replies", "1.0.0"
  gem "monolith-twirp-merge-queue-go-mergequeuemonolith", "1.0.2"
  gem "monolith-twirp-merge-queue-go-mergequeueservice", "1.0.2"
  gem "monolith-twirp-elm-actions", "1.4.0"
  gem "monolith-twirp-elm-data", "1.0.0"
  gem "monolith-twirp-elm-issues", "1.0.0"
  gem "monolith-twirp-elm-organizations", "1.1.0"
  gem "monolith-twirp-elm-repositories", "1.4.0"
  gem "monolith-twirp-modelsgateway-access", "1.10.1"
  gem "monolith-twirp-modelsgateway-billing", "1.0.0"
  gem "monolith-twirp-modelsgateway-telemetry", "1.0.0"
  gem "monolith-twirp-notifications-notifyd", "1.2.8"
  gem "monolith-twirp-octoshift-imports", "2.16.0"
  gem "monolith-twirp-octoshift-migrations", "1.8.0"
  gem "monolith-twirp-support-helphub", "1.50.0"
  gem "monolith-twirp-packageregistry-auditlog", "1.0.2"
  gem "monolith-twirp-conduit-feeds", "1.9.3"
  gem "monolith-twirp-pages-pagesdeployerapi", "1.9.8"
  gem "monolith-twirp-pages-pagesdfsapi", "1.1.8"
  gem "monolith-twirp-spokesd-core", "1.0.0"
  gem "monolith-twirp-trusttiers-trusttier", "1.0.3"
  gem "monolith-twirp-proxima-enterprisemanagement", "1.2.4"
  gem "monolith-twirp-webhooks-core", "1.7.0"
  gem "monolith-twirp-pipelinemonitor-monitoring", "1.0.2"
  gem "monolith-twirp-dependency_graph-users", "1.0.2"
  gem "monolith-twirp-sweagentd-sweagentd", "1.1.1"
  gem "monolith-twirp-snippy-snippy", "1.0.4"
  gem "monolith-twirp-targeting-users", "1.0.8"
  gem "monolith-twirp-copilotapi-agents", "1.1.12"
  gem "monolith-twirp-copilotapi-chat", "1.1.4"
  gem "monolith-twirp-copilotapi-core", "1.6.0"
  gem "monolith-twirp-copilotapi-knowledge_bases", "1.2.4"
  gem "monolith-twirp-copilotapi-custom_copilots", "1.1.7"
  gem "monolith-twirp-copilotapi-custom_instructions", "1.0.0"
  gem "monolith-twirp-copilotapi-code_review", "1.0.1"
  gem "monolith-twirp-copilotapi-mcp", "1.1.0"
  gem "monolith-twirp-webhooksubscriptions-subscriptions", "1.7.0"
  gem "monolith-twirp-odometer-core", "1.0.22"
  gem "monolith-twirp-pullsd-repositories", "1.0.1"
  gem "monolith-twirp-pullsd-users", "1.0.0"
  gem "monolith-twirp-content_engine-core", "1.0.0"
  gem "monolith-twirp-examples-octocat", "1.0.1"
  gem "monolith-twirp-registrymetadata-core", "1.14.3"
  gem "monolith-twirp-billing-accounts", "1.17.0"
  gem "monolith-twirp-billing-products", "1.1.0"
  gem "monolith-twirp-dependency_graph_platform-repositories", "1.1.2"
  gem "monolith-twirp-features-actors", "1.0.4"
  gem "monolith-twirp-features-core", "1.1.1"
  gem "monolith-twirp-features-featureflaghub", "1.5.0"
  gem "monolith-twirp-features-featuresync", "1.0.0"
  gem "monolith-twirp-features-groups", "1.0.0"

  gem "octolytics",          "0.19.0"
  gem "prose_diff", github: "github/prose_diff", ref: "0a86eae7202c619d9fb7f41d670864f12272a5f2"
  gem "proto-dependency-graph-api", github: "github/dependency-graph-api", ref: "4f8e13657976f623553c6a56ed7b11b242f7a798", glob: "gen/ruby/*.gemspec"
  gem "proto-registry-metadata-api", "1.11.3.94.gd4a232d72"
  gem "proto-dependabot-api", "1.1.3.r8cdd21224"
  gem "proto-education-web", "0.0.12.racfd65492b"
  gem "proto-registry-metadata-migrator-api", "1.10.6.83.g459bcec7"
  gem "s4-client", "1.2.1.r10ab0de"
  gem "sarif", "0.1.3"
  gem "secret-scanning-proto", github: "github/secret-scanning-proto", ref: "33605da42bbf1689b0c5eccd3f0d0aaba36bdd49", glob: "gen/ruby/*.gemspec"
  gem "service-catalog-client", "0.7.0"
  gem "spamurai-dev-kit", "3.0.1"
  gem "spokes-proto", github: "github/spokes-proto", ref: "bd875ebd7951aa0fda62220793669f4bf9a3bd93", glob: "gen/ruby/*.gemspec"
  gem "treelights-client", "2.0.0.r8bfa33a"
  gem "windbeam_api", "0.15.0"

  gem "failbot", "3.3.1"
  gem "hydro-client", "5.1.3"
  gem "github-launch", "0.0.3"
  gem "github-telemetry", "0.53.1"
  gem "notifyd-client", "1.11.1"

  gem "zuorest", "3.8.0"

  # Turboscan client gem: https://github.com/github/turboscan
  gem "turboscan-client", "1.0.0.pre.ef4288f"

  # TurboGHAS client gem: https://github.com/github/turboghas
  gem "turboghas-client", "1.0.0.pre.8db2c96"

  # Turboquality client gem: https://github.com/github/turboquality
  gem "turboquality-client", "1.0.0.pre.36e4754"

  gem "kusto-data", "0.0.2"

  # Feature management protos gem: https://github.com/github/feature-management-protos
  gem "feature_management_feature_flags", "1.11.0"

  # Vexi client gems: https://github.com/github/feature-management-client-ruby
  gem "vexi", "1.11.1"
  gem "vexi_management", "0.2.13"

  # Available outside of development for script/generate-service-files.rb
  gem "serviceowners", "1.5.2"

  # Dependency of proto-trust-metadata-api
  gem "sigstore-proto", "0.1.0"
  gem "monolith-twirp-attester", "0.2.0"

  gem "github_chatops_extensions", "0.9.3"
  gem "mvnd", "0.1.33-alpha"
  gem "hosted-compute-ims", "1.0.3"
  gem "proto-trust-metadata-api", "0.19.0"
  gem "egress", "1.68.g52b0cd0"

  gem "diet_earthsmoke", "0.3.1"
end

group :development, :test do
  gem "arca", "~> 2.3", require: false
  gem "factory_bot_rails", "~> 6.5"
  gem "erb_lint", "0.9.0", require: false
  gem "erblint-github", "1.0.1", require: false
  gem "listen", "3.9.0"
  gem "method_source"
  gem "packwerk", "3.2.3"
  gem "packwerk-extensions", "0.3.0"
  gem "parse_packwerk", "0.26.1"
  gem "pry", "~> 0.15.2"
  gem "debug"
  gem "toxiproxy", "2.0.2"
  gem "webrick", git: "https://github.com/ruby/webrick", ref: "0c600e169bd4ae267cb5eeb6197277c848323bbe"
  gem "sqlite3", "~> 1.6", require: false, force_ruby_platform: true
end

# these available outside of development for using AST parsing
gem "rubocop", require: false
gem "rubocop-ast", require: false

# available outside of development for calling script/report_to_datadog.rb in a Janky job.
gem "datadog_api_client", "2.39.0", :require => false

group :development do
  gem "benchmark-ips", "~> 2.14", :require => false
  gem "benchmark-memory", require: false
  gem "dotenv", "~> 2.7"
  gem "sshkey", "~> 3.0.0"
  gem "rubocop-github", "0.26.0"
  gem "rubocop-rails-accessibility", "1.0.1", require: false
  gem "letter_opener",     "1.10.0"
  gem "tapioca", use_sorbet_next ? tapioca_next_version : "0.17.6"
  gem "sorbet", :require => false
  gem "rubocop-sorbet", require: false
  gem "lookbook", "2.3.13", require: false
end

group :test do
  gem "minitest", "~> 5.25"
  gem "minitest-stub-const", "0.6"
  gem "minitest-focus", "> 1.2.1"
  gem "rubocop-minitest", require: false
  gem "mocha",             "~> 2.7"
  gem "rack-test",         "2.2.0", :require => "rack/test"
  gem "timecop",           "0.9.10"
  gem "ladle",             "~> 1.0"
  gem "vcr",               "6.3.1"
  # mock net:http requests for vcr (eg, braintree)
  gem "webmock",           "~> 3"
  gem "capybara",          "3.40.0"
  gem "selenium-webdriver", "~> 4.35"
  gem "simplecov",         "~> 0.22.0"
  gem "simplecov-lcov",    "~> 0.9.0"
  gem "tcr",               "0.4.1"
  gem "pdf-reader", "2.14.1"
  gem "factory_bot_profile"
end
