# frozen_string_literal: true

# rubocop:disable Bundler/OrderedGems
# bootstrap version: v11 (rev to force rebundling on deploy / checkout)

source "https://rubygems.org"

use_graphql_next = ENV["GRAPHQL_NEXT"] == "1"
graphql_next_version = "2.3.4"

rails_version = "8.1.0.alpha.32dcdcaef6"

# Select Rails components to reduce unneeded dependencies
gem "actionmailer", rails_version
gem "actionpack", rails_version
gem "actionview", rails_version
gem "activejob", rails_version
gem "activemodel", rails_version
gem "activerecord", rails_version
gem "activesupport", rails_version
gem "railties", rails_version

gem "actionview_precompiler"
gem "actions-runner-admin", "0.0.1.r7af820e"
gem "actions-run-service", "0.0.1.r2301dc6"
gem "aleph-client",        "16.1.0.r8839e09aa"
gem "allocation_sampler",  "1.0.0"
gem "acme-client",         "2.0.9"
gem "addressable",         "~> 2.8"
gem "advisory_db_toolkit", "0.4.4.rb8d5982c8"
gem "argon2"
gem "asciidoctor",         "2.0.22"
gem "authzd-client",       "0.10.18.r650f14b8d"
gem "authnd-client",       "0.20.0.r6c49365e"
gem "aws-sdk-s3",          "~> 1"
gem "aws-sdk-ecr", "~> 1.2"
gem "azure-storage-blob",  "~> 2.0.2"
gem "bcrypt"
gem "benchmark",           "~> 0.3"
gem "bertrpc",             "1.3.1.github11.5.ga14458b"
gem "bert",                "1.1.10.52.gf3b2e72"
gem "bindata",             "2.5.0"
gem "blackbird-analysis",  "0.2.0.r9649833ca"
gem "blackbird-client",    github: "github/blackbird-mw", glob: "ruby/*.gemspec", ref: "349761c5925372ff37a67b6cb83cf4c465378817"
gem "bootsnap"
gem "braintree",           "~> 4.0"
gem "builder",             "3.3.0"
gem "cbor",                "0.5.9.8"
gem "cff",                 "1.3.0"
gem "chatops-controller",  "5.2.0.4.g2193e18"
gem "chatterbox-client",   "2.4.1.48.ge07b52b"
gem "charlock_holmes",     "0.7.9"
gem "coconductor",         "~> 0.9"
gem "codeowners",          "0.0.2.r8c811c9"
gem "color",               "1.8"
gem "commonmarker",        "0.23.10"
gem "concurrent-ruby-ext"
gem "console_auth",        "1.2.0.5.gf15b5be", :require => false
gem "contentful",          "~> 2.17"
gem "creole",              "0.3.6"
gem "cruby_crash_info"
gem "css_parser",          "1.17.1"
gem "cuprite",             "0.15.1"

gem "csv",                 "3.3.0"
gem "cvss-suite",          "~> 3.3"
gem "dalli",               "3.2.8"
gem "date",                "~> 3.3"
gem "monolith-twirp-dependency_graph_platform-actions", "1.1.1"
gem "monolith-twirp-dependency_graph_platform-integrations", "1.1.1"
gem "monolith-twirp-dependency_graph_platform-repositories", "1.1.1"
gem "dependency-graph-platform-proto", github: "github/dependency-graph-platform-proto", ref: "d9b8e4c9b30924ff5d9e5a609d1317101ce1198c"
gem "dependency-snapshots-api-proto", "0.0.1.r6d8b74a"
gem "delorean_client",     "0.4.0.r09ee7b0"
gem "diff-analysis",       "0.1.0.r8ff4356"
gem "diff-lcs"
gem "divvy",               "1.1.4.g677870a"
gem "dnsruby",             "1.61.5"
gem "dogstatsd-ruby",      "~> 5.6.2"
gem "dogapi",              "~> 1.45.0"
gem "driftwood-client",    "0.0.1.r4bb1232f6"
gem "diet_earthsmoke",     "0.3.1"
gem "ecma-re-validator",   "~> 0.1"
gem "ed25519",             "~> 1.2"
gem "egress",              "1.68.g52b0cd0"
gem "email_reply_parser",  "0.5.11"
gem "elastomer-client",    "6.2.0"
gem "ethon",               "0.16.0"
gem "escape_utils",        "1.3"
gem "erb",                 "~> 4.0"
gem "ernicorn",            "1.0.3", :path => "vendor/internal-gems/ernicorn"
gem "excon",               "~>0.71"
gem "failbot",             "3.1.3.17.g7ce2e51"
gem "faker",               "~> 3.4.2"
gem "faraday",             "~> 1.0"
gem "faraday_middleware"
gem "fast_blank",          "1.0.1"
gem "fast_gettext",        "~> 3.0"
gem "flipper",             "0.23.1"
gem "freno-client",        "~> 0.9.0"
gem "gemoji",              "4.1.0"
gem "geoip2_compat",       "0.0.3"
gem "geo_pattern",         "~> 1.5"
gem "get_process_mem",     "~> 0.2.7"
gem "gettext",             ">=3.3.6", :require => false
gem "gettext_i18n_rails",  "1.12.0"
gem "hashdiff",            "1.1.0"
gem "httpclient",          "2.8.3.74.g19790ac" # script/vendor-gem https://github.com/Shopify/httpclient.git
gem "i18n",                "1.14.5"
gem "issues-graph-client", "0.9.0.r34eff86f"
gem "gibbon",              "2.2.3.rea42a08"
gem "github-ds",           "0.5.4"
gem "github-kv",           "0.0.1.rdbd1267"
gem "github-kredz",        "1.0.1.1135.gf4a4623f5"
gem "github-launch",       "1.0.81.220.g2c3049cdf6"
gem "github-linguist",     "9.0.0"
gem "github-markup",       "5.0.1"
gem "github-orca",         "0.0.20.1626.gb0c19ef3"
gem "github-pages-health-check", "1.18.5"
gem "logger", "~> 1.6.0"
gem "mime-types-data", "3.2024.0702" # Older version to avoid warnings https://github.com/mime-types/mime-types-data/pull/50
gem "monolith-twirp-advisorydb-advisories", "1.0.1"
gem "monolith-twirp-billing-accounts", "1.17.0"
gem "monolith-twirp-billing-products", "1.1.0"
gem "monolith-twirp-billing-repositories", "1.0.0"
gem "monolith-twirp-licensing-customers", "1.6.0"
gem "monolith-twirp-licensing-repositories", "1.0.1"
gem "monolith-twirp-classroom-access_check", "1.0.0"
gem "monolith-twirp-classroom-assignments", "1.0.0"
gem "monolith-twirp-classroom-integration", "1.0.2"
gem "monolith-twirp-event_hydrator-event_hydration", "1.5.0"
gem "monolith-twirp-classroom-users", "1.0.3"
gem "monolith-twirp-classroom-repositories", "1.1.1"
gem "monolith-twirp-classroom-organizations", "1.0.2"
gem "monolith-twirp-classroom-classroom_repositories", "1.1.1"
gem "monolith-twirp-classroom-sync_classroom", "1.0.5"
gem "monolith-twirp-classroom-assignment_reuse", "1.1.0"
gem "monolith-twirp-classroom-classroom_codespaces", "1.2.0"
gem "monolith-twirp-code_scanning-enterprise", "1.0.0"
gem "monolith-twirp-code_scanning-managed_analyses", "1.4.0"
gem "monolith-twirp-code_scanning-repositories", "1.0.0"
gem "monolith-twirp-code_scanning-suggested_fixes", "1.2.0"
gem "monolith-twirp-code_scanning-turboghas", "1.4.5"
gem "monolith-twirp-copilot-organizations", "1.0.11"
gem "monolith-twirp-copilot-users", "1.5.3"
gem "monolith-twirp-dependabot-settings", "1.10.2"
gem "monolith-twirp-education_web-users", "1.15.8"
gem "monolith-twirp-education_web-repos", "1.3.2"
gem "monolith-twirp-education_web-orgs", "1.2.0"
gem "monolith-twirp-features-core", "1.1.1"
gem "monolith-twirp-features-featureflaghub", "1.5.0"
gem "monolith-twirp-features-featuresync", "1.0.0"
gem "monolith-twirp-features-groups", "1.0.0"
gem "monolith-twirp-actions-core", "1.0.85"
gem "monolith-twirp-features-actors", "1.0.4"
gem "monolith-twirp-actionsresults-core", "1.17.0"
gem "monolith-twirp-auditlog-streaming", "1.11.3"
gem "monolith-twirp-git_src_migrator-migrations", "1.8.0"
gem "monolith-twirp-git_src_migrator-monolith", "1.6.3"
gem "monolith-twirp-github-repositories", "1.0.0"
gem "monolith-twirp-kredz-core", "1.0.1"
gem "monolith-twirp-mailreplies-replies", "1.0.0"
gem "monolith-twirp-merge-queue-go-mergequeuemonolith", "1.0.2"
gem "monolith-twirp-merge-queue-go-mergequeueservice", "1.0.2"
gem "monolith-twirp-notifications-notifyd", "1.2.8"
gem "monolith-twirp-octoshift-imports", "2.4.0"
gem "monolith-twirp-octoshift-migrations", "1.8.0"
gem "monolith-twirp-support-helphub", "1.46.0"
gem "monolith-twirp-packageregistry-auditlog", "1.0.2"
gem "monolith-twirp-insights-auth", "1.3.0"
gem "monolith-twirp-insights-core", "1.12.1"
gem "monolith-twirp-insights-sql", "1.0.4"
gem "monolith-twirp-insights-onboarding", "1.0.0"
gem "monolith-twirp-conduit-feeds", "1.8.16"
gem "monolith-twirp-pages-pagesdeployerapi", "1.9.8"
gem "monolith-twirp-pages-pagesdfsapi", "1.1.8"
gem "monolith-twirp-spokesd-core", "1.0.0"
gem "monolith-twirp-trusttiers-trusttier", "1.0.3"
gem "monolith-twirp-proxima-enterprisemanagement", "1.2.3"
gem "monolith-twirp-webhooks-core", "1.7.0"
gem "monolith-twirp-pipelinemonitor-monitoring", "1.0.2"
gem "monolith-twirp-dependency_graph-users", "1.0.0"
gem "monolith-twirp-snippy-snippy", "1.0.4"
gem "monolith-twirp-copilotapi-agents", "1.1.12"
gem "monolith-twirp-copilotapi-chat", "1.0.50"
gem "monolith-twirp-copilotapi-core", "1.3.1"
gem "monolith-twirp-copilotapi-knowledge_bases", "1.2.4"
gem "monolith-twirp-copilotapi-code_review", "1.0.1"
gem "monolith-twirp-webhooksubscriptions-subscriptions", "1.5.0"
gem "ms_rest_azure", "~> 0.12.0"
gem "github_chatops_extensions", "0.5.2.96.g33cefed"
gem "gitrpc",              :path => "vendor/gitrpc"
gem "github-scout",        "0.1.10"
gem "google-api-client",   "~> 0.53"
gem "goomba",              "0.0.1.524.g069b966"
gem "gpgme"
if use_graphql_next
  gem "graphql",             graphql_next_version
else
  gem "graphql",             "2.3.10"
end
gem "graphql-batch",       "0.5.4"
gem "graphql-client",      "0.23.0"
gem "graphql-schema_comparator", "1.2.1"
gem "graphql-pro",          "1.27.1"
gem "group_syncer",        "1.6.5.re8320a7d"
gem "rugged",              "1.4.3.102.ga6b7142"
gem "google-protobuf", "3.14.0.1.r907f12546", force_ruby_platform: true
gem "hana",                "~> 1.3.6"
gem "hashids",             "1.0.5"
gem "homograph-detector",  "~> 0.1.1"
gem "hosted-compute-ims", github: "github/hosted-compute-ims", glob: "gen/twirp/ruby/*.gemspec", ref: "80b554702e2032d0981e0a49aa0a75d30602b5c0"
gem "horcrux",             "0.1.2"
gem "inline_svg",          "1.9.0"
gem "iopromise",           "0.1.5"
gem "ipaddress"
gem "json5",               "0.0.1"
gem "jwt",                 "~> 2.1.0"
gem "json_schema",         "~> 0.20.9"
gem "json-schema",         "~> 4.3"
gem "datadog", git: "https://github.com/datadog/dd-trace-rb", tag: "v2.4.0"
# script/vendor-gem https://github.com/github/kusto-client-ruby.git
gem "kusto-data",           "0.0.1.r613977e"
gem "levenshtein-ffi", github: "dbalatero/levenshtein-ffi", ref: "4b20df76a28fb106e69520001cdfcf206bc8169b"
gem "lz4-ruby",            "~> 0.3.3"
gem "pandoc-ruby",         "2.1.10"
gem "parallel"
gem "parser",              "~> 3.3"
gem "parslet",             "2.0.0"
gem "licensee",            "~> 9.10"
gem "liquid"
gem "lru_redux",           "0.8.4.14.g99d8d60"
gem "mail",                "~> 2.6"
gem "matrix"
gem "memcached",           github: "github/memcached", ref: "9429dfc17895d126436b2beeea6e9ce6bdac0524"
gem "mochilo",             "1.3.8.g0a99999"
gem "monetize",            "1.13.0"
gem "money-open-exchange-rates", "~> 1.3"
gem "monolith-twirp-examples-octocat", "1.0.1"
gem "money",               "~> 6.19.0"
gem "msgpack",             "~> 1.0"
gem "mustache",            "1.1.1.r28cb499"
gem "net-http-persistent", "~> 4.0.2"
gem "net-smtp"
gem "net-ftp"
gem "net-pop"
gem "net-imap"
gem "nokogiri",            ">= 1.18.8", force_ruby_platform: true
gem "notifyd-client",      "1.9.0"
gem "oauth2",              "~> 2.0.9"
gem "observer",            "0.1.2"
gem "octolytics",          "0.19.0"
gem "octicons_helper",     "19.11.0"
gem "chunky_png",          "~> 1.4.0"
gem "org-ruby",            "0.9.12.re74a318"
gem "ostruct"
gem "pathspec",            "~> 2.1.0"
gem "phonelib",            "0.9.2.r68b6df3"
gem "pinglish",            "0.2.1"
gem "prawn",               "2.5.0"
gem "prawn-svg",           "0.35.1"
gem "prawn-table",         "0.2.2"
gem "prelude-batch-loader", github: "seejohnrun/prelude", ref: "09fbb3d33c6da7ec490a10fd2006add422f15112"
gem "premailer",           "1.25.0"
gem "presto-client",       "0.6.3.r0b63000"
gem "prime"
gem "primer_view_components", "0.35.2"
gem "prism"
gem "progeny",             "0.2.1"
gem "prometheus_exporter", "0.5.3", :require => false
gem "prose_diff",          "0.3.3"
gem "proto-dependency-graph-api", "1.0.0.rc20b4d67e"
gem "proto-registry-metadata-api", "1.11.3.23.g34998dec0"
gem "proto-dependabot-api", "1.1.1.r4ee68d562"
gem "proto-registry-metadata-migrator-api", "1.10.6.83.g459bcec7"
gem "proto-trust-metadata-api", github: "github/trust-metadata-api", ref: "eda838134f77f863239acd2dfe6fca387a0a0e4b", glob: "ruby/trust-metadata-api/*.gemspec"
gem "psych",               "~> 5.1"
gem "psych-comments",      "0.1.1"
gem "monolith-twirp-registrymetadata-core", "1.14.2"
gem "public_suffix",       "~> 6.0"
gem "rack",                "~> 2.2"
gem "rails-controller-testing", "1.0.5"
gem "rake",                "~> 13.2"
gem "rblineprof",          "0.3.7", :platforms => :mri
gem "rbi"
gem "rbnacl",              "~> 7.0"
gem "rbtrace",             "~> 0.5", :platforms => :mri
gem "rdoc",                "~> 6.7"
gem "re2",                 "2.14.0", force_ruby_platform: true
gem "RedCloth",            "4.3.3"
gem "redis",               "~> 4.0"
gem "redis-namespace",     "1.6.0"
gem "resilient",           "~> 0.4.0"
gem "resqued",             "0.13.0"
gem "rich_text_renderer",  "~> 0.2.2"
# https://github.com/maxprokopiev/rinku/commit/8583fe1c0531d2fdea6e5c120fb1b0b800b452b7
gem "rinku",               "2.0.6.r8583fe1"
gem "rollup",              "0.7.0.10.g47bf997"
gem "rotp",                "~> 6.3.0"
gem "rqrcode",             "0.10.1"
gem "ruby-progressbar",    "~>1.7", :require => false
gem "rubypants",           "0.7.0.15.g6478da5"
gem "s4-client",           "1.2.1.r10ab0de"
gem "sourcemap",           "0.1.1"
gem "sanitize",            "~> 6.0"
gem "scientist",           "1.6.4"
gem "scrolls",             "0.9.3"
gem "secret-scanning-proto", github: "github/secret-scanning-proto", ref: "1a8330264420f01952c3d0ec6f99a636e4769450", glob: "gen/ruby/*.gemspec"
gem "secure_headers",      "7.0.0"
gem "securerandom",        "~> 0.3.1"
gem "shed", "0.0.4.2.g2652da3"
gem "ssh_data",            "1.3.0.20.g4ec1875"
gem "simple_uuid",         "~> 0.3.0"
gem "sinatra",             "2.2.3"
gem "spamurai-dev-kit",    "3.0.1"
gem "spokes-proto",        github: "github/spokes-proto", ref: "2288f9fd1df21a0e7e14b37d3b4a9b3270706a1f", glob: "gen/ruby/*.gemspec"
gem "stackprof",           "0.2.26"
gem "starry-client",       "0.0.1.r13457ca"
gem "statsd-ruby",         "0.3.0.github.3.38.gd478cc7"
gem "stripe",              "8.7.0"
gem "syslog",              "0.1.2"
gem "terminal-table",      "~>1.6.0"
gem "thor",                "~> 1.2"
gem "treelights-client",   "2.0.0.r8bfa33a"
gem "trilogy",             "2.9.0"
gem "github-trilogy-adapter", github: "github/github-trilogy-adapter", ref: "35655b652759da28821f08fa24c3536983d074f6"
gem "turboghas-client",    github: "github/turboghas", ref: "261bd3e027a9070b93a1478ab32125647828069b"
gem "turboscan-client",    github: "github/turboscan", ref: "1ef6de78ae6fc032fc0a438705434d807603f686"
gem "twilio-ruby",         "6.2.0"
gem "twirp",               "~> 1.10"
gem "unicorn",             "6.1.0.1.gbd68"
gem "uuidtools",           "2.1.5.1.gbeb132a"
# script/vendor-gem -n raindrops -r a36cf00dee5d7657bf95b66bd4559feaab010989 https://yhbt.net/raindrops.git
gem "raindrops",           "0.20.1.14.ga36cf00"
# VERSION=2.11.4.2 script/vendor-gem -n kgio https://github.com/github/kgio
gem "kgio",                "2.11.4.2.r5481408" # unicorn dependency
gem "browser",             "6.0.0"
gem "vernier"
gem "version_sorter",      "2.3.0"
gem "view_component",      "3.19.0"
gem "wcag_color_contrast", "~> 0.1.0"
gem "webauthn",            "3.1.0"
gem "wikicloth",           "0.8.4.github.rf8188e2"
gem "will_paginate",       ">= 3.3.1"
gem "windbeam_api",        "0.15.0"
gem "yajl-ruby",           "1.4.3"
gem "rapidjson"
gem "hydro-client",        "5.1.0.11.g8748412"
gem "ruby-kafka",          "1.3.0"
gem "zuorest",             "3.1.2"
gem "zstd-ruby"
gem "aqueduct-client",     "1.1.0"
gem "ipaddr",              "1.2.6"
gem "sarif",               "0.1.3"
# script/vendor-gem -n feature_management_feature_flags -p gen/ruby/feature_management/feature_flags -r gen/ruby/feature_management/feature_flags/vX.X.X --tag-prefix gen/ruby/feature_management/feature_flags/v https://github.com/github/feature-management-protos
gem "feature_management_feature_flags", "1.6.0"
gem "vexi", github: "github/feature-management-client-ruby", glob: "generated/vexi/*.gemspec", ref: "1388270b5667dd21a764d03206d8cc968bfb4027"
# script/vendor-gem -n vexi_management -p ./vexi_management -r vexi_management/vX.X.X --tag-prefix vexi_management/v https://github.com/github/feature-management-client-ruby
gem "vexi_management", "0.1.5"

gem "badge-ruler", "0.0.2"
gem "service-catalog-client", "0.7.0"
gem "rubyzip", "3.0.0.alpha.18.g5c6a7c9"

# enterprise specific gems go here for now
#
# NOTE: the `oa-enterprise` gem is built from the "0-3-stable" branch
#       of the https://github.com/github/omniauth repository
gem "github-ldap",   "1.10.1.20.g06d2c92"
gem "net-ldap",      "0.17.1"
gem "oa-enterprise", "0.3.2.g3930d46"
gem "octokit",       "4.20.0"
gem "xmldsig",       "0.7.0"
gem "ruby-saml",     "1.17.0.r7083eeb"

# Used for licenses on both GHES & GitHub.com (the latter for GitHub Connect)
gem "enterprise-crypto", "0.6.2"

# Meuse Gem
# script/vendor-gem https://github.com/github/meuse.git -r vX.X.X
gem "meuse-client", "1.17.1"

# Billing Platform Gem
gem "billing-platform-client", github: "github/billing-platform", tag: "v0.51.0"

# Licensify gem
gem "licensify-client", github: "github/licensify", ref: "32e18ec4fefbdcc305b263c9e71cf4398fd71d8f"

# Update ref then run bin/bundle and bin/tapioca dsl
gem "actions-usage-metrics", github: "github/actions-usage-metrics", ref: "123f3f491d478254398c40732db1cc24860f1c65"

# opentelemetry-instrumenation-pg and opentelemetry-instrumentation-mysql2 are required in order to build github-telemetry-ruby from source
# using the script/vendor-gem script.
gem "opentelemetry-instrumentation-pg", "~> 0.29.0"
gem "opentelemetry-instrumentation-mysql2", "~> 0.28.0"
# script/vendor-gem https://github.com/github/github-telemetry-ruby.git -r v0.49.9
gem "github-telemetry", "0.49.9"
# This is the last version that supports protobuf 3.14
# Versions after 0.27.0 require protobuf >= 3.18 https://github.com/open-telemetry/opentelemetry-ruby/pull/1645
# https://github.com/github/ecosystem-api/issues/3303
gem "opentelemetry-exporter-otlp", "0.27.0"

gem "sorbet-runtime", "0.5.11604"

gem "tzinfo-data"

gem "net_http_unix", "~> 0.2.2"

group :development, :test do
  gem "arca", "~> 2.3", require: false
  gem "factory_bot_rails", "~> 6.2"
  gem "erb_lint", "0.5.0", require: false
  gem "erblint-github", "1.0.1", require: false
  gem "listen", "3.3.1"
  gem "packwerk", "3.2.1"
  gem "packwerk-extensions", "0.3.0"
  gem "parse_packwerk", "0.23.0"
  gem "pry", "~> 0.14.2"
  gem "debug"
  gem "byebug", "11.1.3"
  gem "toxiproxy", "2.0.2"
  gem "webrick", git: "https://github.com/ruby/webrick", ref: "0c600e169bd4ae267cb5eeb6197277c848323bbe"
  gem "sqlite3", "~> 1.6", require: false, force_ruby_platform: true
end

# these available outside of development for using AST parsing for script/generate-service-files.rb
gem "rubocop", require: false
gem "rubocop-ast", require: false
gem "serviceowners", "1.5.0.29.g0d64431"

# available outside of development for calling script/report_to_datadog.rb in a Janky job.
gem "datadog_api_client", "2.25.0.dev.1.r6c6cc420", :require => false

group :development do
  gem "benchmark-ips", "~> 2.13", :require => false
  gem "benchmark-memory", require: false
  gem "dotenv", "~> 2.7"
  gem "sshkey", "~> 1.3.2"
  gem "rubocop-github", github: "github/rubocop-github", ref: "5431a4247af1c552647b5fd353ff39691f505cb2"
  gem "rubocop-rails-accessibility", "1.0.1", require: false
  gem "letter_opener",     "1.10.0"
  gem "tapioca", "0.16.3"
  gem "sorbet", :require => false
  gem "rubocop-sorbet", require: false
  gem "lookbook", "2.2.2", require: false
end

group :test do
  gem "minitest", "~> 5.21"
  gem "minitest-stub-const", "0.6"
  gem "minitest-focus", "> 1.2.1"
  gem "mocha",             "~> 2.5"
  gem "rack-test",         "2.1.0", :require => "rack/test"
  gem "timecop",           "0.9.8"
  gem "ladle",             "~> 1.0"
  gem "vcr",               "6.3.1"
  # mock net:http requests for vcr (eg, braintree)
  gem "webmock",           "~> 3"
  gem "capybara",          "3.40.0"
  gem "selenium-webdriver", "~> 4.17"
  gem "simplecov",         "~> 0.22.0"
  gem "simplecov-lcov",    "~> 0.8.0"
  gem "tcr",               "0.4.0"
  gem "pdf-reader", "2.12.0"
  gem "factory_bot_profile"
end
