web: script/unicorn-server
js-assets: script/serve-js-assets
css-assets: script/serve-css-assets
alloy-assets: script/serve-alloy-assets
ui-assets: script/serve-ui-assets
fm-lite: script/fm-lite-server
# kafka-lite must boot before alive does
kafka-lite: script/kafka-lite-server
alive: script/alive-server
git-daemon: script/git-daemon-server
gitrpcd1: script/gitrpcd-server --http-port 19418 --ernicorn-port 8149 --git-port=9480 --repository-path=$(pwd)/repositories/$(./script/gitrpcd-mode)/dgit1
gitrpcd2: script/gitrpcd-server --http-port 19419 --ernicorn-port 8150 --git-port=9481 --repository-path=$(pwd)/repositories/$(./script/gitrpcd-mode)/dgit2
gitrpcd3: script/gitrpcd-server --http-port 19420 --ernicorn-port 8151 --git-port=9482 --repository-path=$(pwd)/repositories/$(./script/gitrpcd-mode)/dgit3
gitrpcd4: script/gitrpcd-server --http-port 19421 --ernicorn-port 8152 --git-port=9483 --repository-path=$(pwd)/repositories/$(./script/gitrpcd-mode)/dgit4
gitrpcd5: script/gitrpcd-server --http-port 19422 --ernicorn-port 8153 --git-port=9484 --repository-path=$(pwd)/repositories/$(./script/gitrpcd-mode)/dgit5
gitauth: script/gitauth-server
codeload: script/codeload-server
babeld: script/babeld-server
alambic: script/alambic-server
memory-alpha: script/memory-alpha-server
lfs-server: script/lfs-server
librarian: script/librarian-server
resqued: script/resqued-server
ernicorn1: bin/ernicorn -h 127.0.0.1 -p 8149 -P tmp/pids/ernicorn1.pid
ernicorn2: bin/ernicorn -h 127.0.0.1 -p 8150 -P tmp/pids/ernicorn2.pid
ernicorn3: bin/ernicorn -h 127.0.0.1 -p 8151 -P tmp/pids/ernicorn3.pid
ernicorn4: bin/ernicorn -h 127.0.0.1 -p 8152 -P tmp/pids/ernicorn4.pid
ernicorn5: bin/ernicorn -h 127.0.0.1 -p 8153 -P tmp/pids/ernicorn5.pid
fakemunger: script/fakemunger-server -p 8140
gpgverify: script/gpgverify-server
authnd: script/authnd-server
authzd: script/authzd-server --dev
notifyd: script/notifyd-server --dev
aqueduct-lite: script/aqueduct-lite-server
hookshot-go: script/hookshot-go-server
spokesd: script/spokesd-server
aqueduct-bridge: bin/aqueduct-hydro-message-bridge
voltron: script/voltron-server
treelights: script/treelights-server
alloy: script/alloy-server
turboghas: script/turboghas
dev-identity-provider-ruby: script/dev-identity-provider-ruby-server
copilot-api: script/copilot-fauxpilot-api-server
slack-web: script/slack-web-server
slack-tunnel: script/slack-tunnel-server
slack-ghe-router: script/slack-ghe-router-server
slack-ghe-router-tunnel: script/slack-ghe-router-tunnel-server
primer: script/start-primer-react-watcher
kredz: script/kredz-server
models-gateway: script/models-gateway-server
github-mcp-server-remote: script/github-mcp-server-remote
