# typed: true
# frozen_string_literal: true

module Elastomer

  # The Adapter class provides some common functionality that can be used for
  # creating your own data adapters. The whole point of an adapter is to take
  # a data model - an ActiveRecord instance, for example - and extract
  # information into a document suitable for indexing in ElasticSearch.
  class Adapter
    # Public: Returns the document type for the adapter.
    #
    # Returns the document type as a String.
    def self.document_type
      return @document_type if defined? @document_type
      @document_type = name&.split("::")&.last&.underscore
    end

    # Public: Returns the name of the Index class responsible for storing the
    # generated documents. Subclasses need to implement this method.
    #
    # Raises a RuntimeError.
    def self.index_name
      raise "Subclasses need to specify the index the document belongs to."
    end

    # Public: Returns the MySQL database cluster the given adapter is sourced
    # from. Each adapter is expected to override this method if they need
    # to configure the cluster used for replication delay.
    #
    # Returns nil.
    def self.mysql_cluster
      raise "Subclasses need to specify the MySQL cluster of the model being indexed."
    end

    # Public: Create a new adapter instance given a database ID or a data
    # model instance (ActiveRecord).
    #
    # model_or_id - The database ID number (String or Integer) or the data
    #               model instance
    #
    # Returns an adapter instance.
    def self.create(model_or_id, *args)
      obj = T.unsafe(self).new(*args)

      case model_or_id
      when String, Integer
        obj.document_id = Integer(model_or_id)
      else
        obj.model = model_or_id
      end

      obj
    end

    # A no-op constructor that takes any number of arguments.
    def initialize(*args)
      @options = args.extract_options!
      @document_routing = args.first
      @document_id = nil
      @index = nil
    end

    # The options Hash passed to the initializer.
    attr_reader :options

    # The ID of the document. This will be used as the ElasticSearch ID for
    # the document.
    attr_accessor :document_id

    # Document routing information is provided by this method if routing is used
    # in the search index.
    attr_reader :document_routing

    # If needed, the adapter has access to the index that will be handling
    # the document(s) generated by the adapter. This is really only the case
    # for the Code adapter, but it is being handled at the superclass level
    # across the board.
    #
    # See the Elastomer::Index#store and Elastomer::Index#remove methods.
    attr_accessor :index

    # Public: Returns the document type for the adapter.
    #
    # Returns the document type as a String.
    def document_type
      self.class.document_type
    end

    # Public: Accessor for the data model instance. Subclasses should override
    # this method and generate the model from the document_id if the model has
    # not already been set. Otherwise this method will raise a
    # NotImplementedError, and no one wants that to happen.
    #
    # Returns the data model instance.
    # Raises a NotImplementedError if the model has not been set.
    def model
      return @model if defined? @model
      raise NotImplementedError,
            "The superclass does not know how to instantiate your model. Bad developer - no latte!"
    end

    # Public: Set the data model for the adapter. The data model object must
    # respond to the `id` method. The `document_id` will be set to the return
    # value of this id method.
    def model=(model)
      @model = model
      @document_id = model.id
    end

    # Public: Returns the value used to determine which index slice the document
    # data from this adapter should be written to. The default is to return
    # `nil` for indices that do not support slicing.
    def slice_value
      nil
    end

    # Public: Convenience method used to override the MySQL cluster configured at
    # the class level used for replication delay.
    def mysql_cluster
      self.class.mysql_cluster
    end

    def params
      {}
    end

    # Public: This method is called to clear any state the adapter might have
    # created in the course of generating documents to index. When we pass an
    # adapter to more than one index, this method will be called _between_
    # indexing runs. Subclasses should provide an implementation as needed.
    def reset!
      self
    end

    # Helper method to set the tags to be added to datadog metrics.
    def datadog_tags(index, add_index_name_tag = false)
      tags = index&.cluster_name.present? ? %W[cluster:#{index.cluster_name}] : []
      if add_index_name_tag && index&.name.present?
        tags << "index:#{index.name}"
      end
      tags
    end
  end
end
