# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GitHub::Proto::SecretScanning::Api::V2::ExemptionRequestEvent`.
# Please instead update this file by running `bin/tapioca dsl GitHub::Proto::SecretScanning::Api::V2::ExemptionRequestEvent`.


class GitHub::Proto::SecretScanning::Api::V2::ExemptionRequestEvent < Google::Protobuf::AbstractMessage
  sig { params(reason: T.nilable(T.any(Symbol, Integer)), requester_comment: T.nilable(String)).void }
  def initialize(reason: nil, requester_comment: nil); end

  sig { void }
  def clear_reason; end

  sig { void }
  def clear_requester_comment; end

  sig { returns(T.any(Symbol, Integer)) }
  def reason; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def reason=(value); end

  sig { returns(String) }
  def requester_comment; end

  sig { params(value: String).void }
  def requester_comment=(value); end
end
