# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GitHub::HostedComputeIms::AdminApi::UpdateCuratedImageDefinitionRequest`.
# Please instead update this file by running `bin/tapioca dsl GitHub::HostedComputeIms::AdminApi::UpdateCuratedImageDefinitionRequest`.


class GitHub::HostedComputeIms::AdminApi::UpdateCuratedImageDefinitionRequest < Google::Protobuf::AbstractMessage
  sig do
    params(
      enabled: T.nilable(T::Boolean),
      feature_flag: T.nilable(String),
      image_definition_id: T.nilable(Integer),
      is_image_generation_supported: T.nilable(T::Boolean),
      name: T.nilable(String)
    ).void
  end
  def initialize(enabled: nil, feature_flag: nil, image_definition_id: nil, is_image_generation_supported: nil, name: nil); end

  sig { void }
  def clear_enabled; end

  sig { void }
  def clear_feature_flag; end

  sig { void }
  def clear_image_definition_id; end

  sig { void }
  def clear_is_image_generation_supported; end

  sig { void }
  def clear_name; end

  sig { returns(T::Boolean) }
  def enabled; end

  sig { params(value: T::Boolean).void }
  def enabled=(value); end

  sig { returns(String) }
  def feature_flag; end

  sig { params(value: String).void }
  def feature_flag=(value); end

  sig { returns(Integer) }
  def image_definition_id; end

  sig { params(value: Integer).void }
  def image_definition_id=(value); end

  sig { returns(T::Boolean) }
  def is_image_generation_supported; end

  sig { params(value: T::Boolean).void }
  def is_image_generation_supported=(value); end

  sig { returns(String) }
  def name; end

  sig { params(value: String).void }
  def name=(value); end
end
