# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Starry::Proto::UserHasStarredRepositoryResponse`.
# Please instead update this file by running `bin/tapioca dsl Starry::Proto::UserHasStarredRepositoryResponse`.


class Starry::Proto::UserHasStarredRepositoryResponse < Google::Protobuf::AbstractMessage
  sig { params(user_has_starred: T.nilable(T::Boolean)).void }
  def initialize(user_has_starred: nil); end

  sig { void }
  def clear_user_has_starred; end

  sig { returns(T::Boolean) }
  def user_has_starred; end

  sig { params(value: T::Boolean).void }
  def user_has_starred=(value); end
end
