# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `MonolithTwirp::Elm::Actions::V1::ExportCheckSuitesRequest`.
# Please instead update this file by running `bin/tapioca dsl MonolithTwirp::Elm::Actions::V1::ExportCheckSuitesRequest`.


class MonolithTwirp::Elm::Actions::V1::ExportCheckSuitesRequest < Google::Protobuf::AbstractMessage
  sig do
    params(
      page: T.nilable(Integer),
      per_page: T.nilable(Integer),
      repository_id: T.nilable(Integer),
      should_only_export_latest: T.nilable(T::Boolean)
    ).void
  end
  def initialize(page: nil, per_page: nil, repository_id: nil, should_only_export_latest: nil); end

  sig { void }
  def clear_page; end

  sig { void }
  def clear_per_page; end

  sig { void }
  def clear_repository_id; end

  sig { void }
  def clear_should_only_export_latest; end

  sig { returns(Integer) }
  def page; end

  sig { params(value: Integer).void }
  def page=(value); end

  sig { returns(Integer) }
  def per_page; end

  sig { params(value: Integer).void }
  def per_page=(value); end

  sig { returns(Integer) }
  def repository_id; end

  sig { params(value: Integer).void }
  def repository_id=(value); end

  sig { returns(T::Boolean) }
  def should_only_export_latest; end

  sig { params(value: T::Boolean).void }
  def should_only_export_latest=(value); end
end
