# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `MonolithTwirp::Elm::Actions::V1::ExportCheckSuitesResponse`.
# Please instead update this file by running `bin/tapioca dsl MonolithTwirp::Elm::Actions::V1::ExportCheckSuitesResponse`.


class MonolithTwirp::Elm::Actions::V1::ExportCheckSuitesResponse < Google::Protobuf::AbstractMessage
  sig do
    params(
      error_message: T.nilable(String),
      export_check_suites: T.nilable(T.any(Google::Protobuf::RepeatedField[MonolithTwirp::Elm::Actions::V1::ExportCheckSuite], T::Array[MonolithTwirp::Elm::Actions::V1::ExportCheckSuite])),
      success: T.nilable(T::Boolean),
      total_count: T.nilable(Integer)
    ).void
  end
  def initialize(error_message: nil, export_check_suites: T.unsafe(nil), success: nil, total_count: nil); end

  sig { void }
  def clear_error_message; end

  sig { void }
  def clear_export_check_suites; end

  sig { void }
  def clear_success; end

  sig { void }
  def clear_total_count; end

  sig { returns(String) }
  def error_message; end

  sig { params(value: String).void }
  def error_message=(value); end

  sig { returns(Google::Protobuf::RepeatedField[MonolithTwirp::Elm::Actions::V1::ExportCheckSuite]) }
  def export_check_suites; end

  sig { params(value: Google::Protobuf::RepeatedField[MonolithTwirp::Elm::Actions::V1::ExportCheckSuite]).void }
  def export_check_suites=(value); end

  sig { returns(T::Boolean) }
  def success; end

  sig { params(value: T::Boolean).void }
  def success=(value); end

  sig { returns(Integer) }
  def total_count; end

  sig { params(value: Integer).void }
  def total_count=(value); end
end
