# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/github/custom_organization_roles/v0/custom_organization_role_created.proto

require 'google/protobuf'

require 'hydro/schemas/github/v1/entities/custom_organization_role_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.github.custom_organization_roles.v0.CustomOrganizationRoleCreated" do
    optional :role, :message, 1, "hydro.schemas.github.v1.entities.CustomOrganizationRole"
    optional :org_custom_org_roles_count, :int64, 2
  end
end

module Hydro
  module Schemas
    module Github
      module CustomOrganizationRoles
        module V0
          CustomOrganizationRoleCreated = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.custom_organization_roles.v0.CustomOrganizationRoleCreated").msgclass
        end
      end
    end
  end
end
