<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="saml20assertion_schema.xsd" namespace="urn:oasis:names:tc:SAML:2.0:assertion" />
  <xs:import schemaLocation="xmldsig_schema.xsd" namespace="http://www.w3.org/2000/09/xmldsig#" />
  <xs:element name="Response">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="saml2:Issuer" />
        <xs:element ref="ds:Signature" minOccurs="0"/>
        <xs:element name="Status">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="StatusCode">
                <xs:complexType>
                  <xs:attribute name="Value" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element ref="saml2:Assertion" />
      </xs:sequence>
      <xs:attribute name="Destination" type="xs:string" use="required" />
      <xs:attribute name="ID" type="xs:string" use="required" />
      <xs:attribute name="InResponseTo" type="xs:string" use="optional" />
      <xs:attribute name="IssueInstant" type="xs:dateTime" use="required" />
      <xs:attribute name="Version" type="xs:decimal" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>
