# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `MonolithTwirp::Licensing::Customers::V1::Customer`.
# Please instead update this file by running `bin/tapioca dsl MonolithTwirp::Licensing::Customers::V1::Customer`.


class MonolithTwirp::Licensing::Customers::V1::Customer < Google::Protobuf::AbstractMessage
  sig do
    params(
      codeSecurityLicensingModel: T.nilable(T.any(Symbol, Integer)),
      codeSecurityTrial: T.nilable(T::Boolean),
      ghasLicensingModel: T.nilable(T.any(Symbol, Integer)),
      ghasTrial: T.nilable(T::Boolean),
      id: T.nilable(Integer),
      sdlcLicensingModel: T.nilable(T.any(Symbol, Integer)),
      sdlcTrial: T.nilable(T::Boolean),
      secretProtectionLicensingModel: T.nilable(T.any(Symbol, Integer)),
      secretProtectionTrial: T.nilable(T::Boolean)
    ).void
  end
  def initialize(codeSecurityLicensingModel: nil, codeSecurityTrial: nil, ghasLicensingModel: nil, ghasTrial: nil, id: nil, sdlcLicensingModel: nil, sdlcTrial: nil, secretProtectionLicensingModel: nil, secretProtectionTrial: nil); end

  sig { void }
  def clear_codeSecurityLicensingModel; end

  sig { void }
  def clear_codeSecurityTrial; end

  sig { void }
  def clear_ghasLicensingModel; end

  sig { void }
  def clear_ghasTrial; end

  sig { void }
  def clear_id; end

  sig { void }
  def clear_sdlcLicensingModel; end

  sig { void }
  def clear_sdlcTrial; end

  sig { void }
  def clear_secretProtectionLicensingModel; end

  sig { void }
  def clear_secretProtectionTrial; end

  sig { returns(T.any(Symbol, Integer)) }
  def codeSecurityLicensingModel; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def codeSecurityLicensingModel=(value); end

  sig { returns(T::Boolean) }
  def codeSecurityTrial; end

  sig { params(value: T::Boolean).void }
  def codeSecurityTrial=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def ghasLicensingModel; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def ghasLicensingModel=(value); end

  sig { returns(T::Boolean) }
  def ghasTrial; end

  sig { params(value: T::Boolean).void }
  def ghasTrial=(value); end

  sig { returns(Integer) }
  def id; end

  sig { params(value: Integer).void }
  def id=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def sdlcLicensingModel; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def sdlcLicensingModel=(value); end

  sig { returns(T::Boolean) }
  def sdlcTrial; end

  sig { params(value: T::Boolean).void }
  def sdlcTrial=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def secretProtectionLicensingModel; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def secretProtectionLicensingModel=(value); end

  sig { returns(T::Boolean) }
  def secretProtectionTrial; end

  sig { params(value: T::Boolean).void }
  def secretProtectionTrial=(value); end
end
