# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `MonolithTwirp::Licensing::Customers::V1::GetBusinessTeamMembersRequest`.
# Please instead update this file by running `bin/tapioca dsl MonolithTwirp::Licensing::Customers::V1::GetBusinessTeamMembersRequest`.


class MonolithTwirp::Licensing::Customers::V1::GetBusinessTeamMembersRequest < Google::Protobuf::AbstractMessage
  sig { params(business_team_id: T.nilable(Integer)).void }
  def initialize(business_team_id: nil); end

  sig { returns(Integer) }
  def business_team_id; end

  sig { params(value: Integer).void }
  def business_team_id=(value); end

  sig { void }
  def clear_business_team_id; end
end
