# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GitHub::ActionsRunnerAdmin::Api::V1::AddRunnerScaleSetRequest`.
# Please instead update this file by running `bin/tapioca dsl GitHub::ActionsRunnerAdmin::Api::V1::AddRunnerScaleSetRequest`.


class GitHub::ActionsRunnerAdmin::Api::V1::AddRunnerScaleSetRequest < Google::Protobuf::AbstractMessage
  sig do
    params(
      entity: T.nilable(GitHub::ActionsRunnerAdmin::Entities::V1::GitHubEntity),
      group_id: T.nilable(Integer),
      labels: T.nilable(T.any(Google::Protobuf::RepeatedField[GitHub::ActionsRunnerAdmin::Api::V1::RunnerScaleSetLabel], T::Array[GitHub::ActionsRunnerAdmin::Api::V1::RunnerScaleSetLabel])),
      name: T.nilable(String),
      runner_setting: T.nilable(GitHub::ActionsRunnerAdmin::Api::V1::RunnerSetting)
    ).void
  end
  def initialize(entity: nil, group_id: nil, labels: T.unsafe(nil), name: nil, runner_setting: nil); end

  sig { void }
  def clear_entity; end

  sig { void }
  def clear_group_id; end

  sig { void }
  def clear_labels; end

  sig { void }
  def clear_name; end

  sig { void }
  def clear_runner_setting; end

  sig { returns(T.nilable(GitHub::ActionsRunnerAdmin::Entities::V1::GitHubEntity)) }
  def entity; end

  sig { params(value: T.nilable(GitHub::ActionsRunnerAdmin::Entities::V1::GitHubEntity)).void }
  def entity=(value); end

  sig { returns(Integer) }
  def group_id; end

  sig { params(value: Integer).void }
  def group_id=(value); end

  sig { returns(Object) }
  def has_entity?; end

  sig { returns(Object) }
  def has_runner_setting?; end

  sig { returns(Google::Protobuf::RepeatedField[GitHub::ActionsRunnerAdmin::Api::V1::RunnerScaleSetLabel]) }
  def labels; end

  sig { params(value: Google::Protobuf::RepeatedField[GitHub::ActionsRunnerAdmin::Api::V1::RunnerScaleSetLabel]).void }
  def labels=(value); end

  sig { returns(String) }
  def name; end

  sig { params(value: String).void }
  def name=(value); end

  sig { returns(T.nilable(GitHub::ActionsRunnerAdmin::Api::V1::RunnerSetting)) }
  def runner_setting; end

  sig { params(value: T.nilable(GitHub::ActionsRunnerAdmin::Api::V1::RunnerSetting)).void }
  def runner_setting=(value); end
end
