# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GitHub::ActionsRunnerAdmin::Api::V1::ConcurrencyServiceClient`.
# Please instead update this file by running `bin/tapioca dsl GitHub::ActionsRunnerAdmin::Api::V1::ConcurrencyServiceClient`.


class GitHub::ActionsRunnerAdmin::Api::V1::ConcurrencyServiceClient < ::Twirp::Client
  sig { params(connection: T.any(String, ::Faraday::Connection), opts: T::Hash[Symbol, T.untyped]).void }
  def initialize(connection, opts = {}); end

  sig do
    params(
      input: GitHub::ActionsRunnerAdmin::Api::V1::ListConcurrenciesForOwnerRequest,
      req_opts: T.nilable(T::Hash[Symbol, T.untyped])
    ).returns(::Twirp::ClientResp[GitHub::ActionsRunnerAdmin::Api::V1::ListConcurrenciesForOwnerResponse])
  end
  def list_concurrencies_for_owner(input, req_opts = nil); end

  sig do
    params(
      input: GitHub::ActionsRunnerAdmin::Api::V1::ListDefaultConcurrenciesRequest,
      req_opts: T.nilable(T::Hash[Symbol, T.untyped])
    ).returns(::Twirp::ClientResp[GitHub::ActionsRunnerAdmin::Api::V1::ListDefaultConcurrenciesResponse])
  end
  def list_default_concurrencies(input, req_opts = nil); end
end
