# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GitHub::ActionsRunnerAdmin::Api::V1::MigrationState`.
# Please instead update this file by running `bin/tapioca dsl GitHub::ActionsRunnerAdmin::Api::V1::MigrationState`.


module GitHub::ActionsRunnerAdmin::Api::V1::MigrationState
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

GitHub::ActionsRunnerAdmin::Api::V1::MigrationState::MIGRATION_STATE_PIPELINES = 1
GitHub::ActionsRunnerAdmin::Api::V1::MigrationState::MIGRATION_STATE_RUNNER_ADMIN = 2
GitHub::ActionsRunnerAdmin::Api::V1::MigrationState::MIGRATION_STATE_UNKNOWN = 0
