# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `MonolithTwirp::Octoshift::Imports::V1::EditReleaseRequest`.
# Please instead update this file by running `bin/tapioca dsl MonolithTwirp::Octoshift::Imports::V1::EditReleaseRequest`.


class MonolithTwirp::Octoshift::Imports::V1::EditReleaseRequest < Google::Protobuf::AbstractMessage
  sig do
    params(
      action: T.nilable(T.any(Symbol, Integer)),
      author_login: T.nilable(String),
      body: T.nilable(Google::Protobuf::StringValue),
      id: T.nilable(Integer),
      is_pre_release: T.nilable(T::Boolean),
      name: T.nilable(String),
      pending_tag: T.nilable(String),
      state: T.nilable(T.any(Symbol, Integer)),
      tag_name: T.nilable(String),
      updated_at: T.nilable(Google::Protobuf::Timestamp)
    ).void
  end
  def initialize(action: nil, author_login: nil, body: nil, id: nil, is_pre_release: nil, name: nil, pending_tag: nil, state: nil, tag_name: nil, updated_at: nil); end

  sig { returns(T.any(Symbol, Integer)) }
  def action; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def action=(value); end

  sig { returns(String) }
  def author_login; end

  sig { params(value: String).void }
  def author_login=(value); end

  sig { returns(T.nilable(Google::Protobuf::StringValue)) }
  def body; end

  sig { params(value: T.nilable(Google::Protobuf::StringValue)).void }
  def body=(value); end

  sig { void }
  def clear_action; end

  sig { void }
  def clear_author_login; end

  sig { void }
  def clear_body; end

  sig { void }
  def clear_id; end

  sig { void }
  def clear_is_pre_release; end

  sig { void }
  def clear_name; end

  sig { void }
  def clear_pending_tag; end

  sig { void }
  def clear_state; end

  sig { void }
  def clear_tag_name; end

  sig { void }
  def clear_updated_at; end

  sig { returns(Object) }
  def has_body?; end

  sig { returns(Object) }
  def has_updated_at?; end

  sig { returns(Integer) }
  def id; end

  sig { params(value: Integer).void }
  def id=(value); end

  sig { returns(T::Boolean) }
  def is_pre_release; end

  sig { params(value: T::Boolean).void }
  def is_pre_release=(value); end

  sig { returns(String) }
  def name; end

  sig { params(value: String).void }
  def name=(value); end

  sig { returns(String) }
  def pending_tag; end

  sig { params(value: String).void }
  def pending_tag=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def state; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def state=(value); end

  sig { returns(String) }
  def tag_name; end

  sig { params(value: String).void }
  def tag_name=(value); end

  sig { returns(T.nilable(Google::Protobuf::Timestamp)) }
  def updated_at; end

  sig { params(value: T.nilable(Google::Protobuf::Timestamp)).void }
  def updated_at=(value); end
end
