# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `MonolithTwirp::Octoshift::Imports::V1::ImportProtectedBranchAPIClient`.
# Please instead update this file by running `bin/tapioca dsl MonolithTwirp::Octoshift::Imports::V1::ImportProtectedBranchAPIClient`.


class MonolithTwirp::Octoshift::Imports::V1::ImportProtectedBranchAPIClient < ::Twirp::Client
  sig { params(connection: T.any(String, ::Faraday::Connection), opts: T::Hash[Symbol, T.untyped]).void }
  def initialize(connection, opts = {}); end

  sig do
    params(
      input: MonolithTwirp::Octoshift::Imports::V1::ImportProtectedBranchRequest,
      req_opts: T.nilable(T::Hash[Symbol, T.untyped])
    ).returns(::Twirp::ClientResp[MonolithTwirp::Octoshift::Imports::V1::ImportProtectedBranchResponse])
  end
  def import_protected_branch(input, req_opts = nil); end
end
