# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Repositories::Domain::Diffs`.
# Please instead update this file by running `bin/tapioca dsl Repositories::Domain::Diffs`.


class Repositories::Domain::Diffs
  include GeneratedDomainAccessorMethods

  module GeneratedDomainAccessorMethods; end
end
