# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Aqueduct::Api::V1::QueueLimitsResponse::LimitByBackends`.
# Please instead update this file by running `bin/tapioca dsl Aqueduct::Api::V1::QueueLimitsResponse::LimitByBackends`.


class Aqueduct::Api::V1::QueueLimitsResponse::LimitByBackends < Google::Protobuf::AbstractMessage
  sig do
    params(
      backends: T.nilable(T.any(Google::Protobuf::RepeatedField[String], T::Array[String])),
      value: T.nilable(Google::Protobuf::Int32Value)
    ).void
  end
  def initialize(backends: T.unsafe(nil), value: nil); end

  sig { returns(Google::Protobuf::RepeatedField[String]) }
  def backends; end

  sig { params(value: Google::Protobuf::RepeatedField[String]).void }
  def backends=(value); end

  sig { void }
  def clear_backends; end

  sig { void }
  def clear_value; end

  sig { returns(Object) }
  def has_value?; end

  sig { returns(T.nilable(Google::Protobuf::Int32Value)) }
  def value; end

  sig { params(value: T.nilable(Google::Protobuf::Int32Value)).void }
  def value=(value); end
end
