# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/github/copilot/v1/copilot_signup_settings_saved.proto

require 'google/protobuf'

require 'hydro/schemas/github/copilot/v1/entities/copilot_analytics_pb'
require 'hydro/schemas/github/copilot/v1/entities/copilot_settings_pb'
require 'hydro/schemas/github/copilot/v1/entities/copilot_user_details_pb'
require 'hydro/schemas/github/v1/entities/request_context_pb'
require 'hydro/schemas/github/v1/entities/user_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.github.copilot.v1.CopilotSignupSettingsSaved" do
    optional :user, :message, 1, "hydro.schemas.github.v1.entities.User"
    optional :copilot_user_details, :message, 2, "hydro.schemas.github.copilot.v1.entities.CopilotUserDetails"
    optional :old_settings, :message, 3, "hydro.schemas.github.copilot.v1.entities.CopilotSettings"
    optional :new_settings, :message, 4, "hydro.schemas.github.copilot.v1.entities.CopilotSettings"
    optional :request_context, :message, 5, "hydro.schemas.github.v1.entities.RequestContext"
    optional :copilot_analytics, :message, 6, "hydro.schemas.github.copilot.v1.entities.CopilotAnalytics"
  end
end

module Hydro
  module Schemas
    module Github
      module Copilot
        module V1
          CopilotSignupSettingsSaved = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.copilot.v1.CopilotSignupSettingsSaved").msgclass
        end
      end
    end
  end
end
