#!/bin/bash

# This is used to generate a JSON file with the raw JSON response from Contentful.
# JSON files will be generated in `test/fixtures/site/contentful/` and can be used to create fixtures for tests.
# This can be used in tests to modify valid JSON responses to create purposefully invalid responses.
read -p "Enter the name for the Contentful fixture JSON file (without the .json extension): " file_name
read -p "Enter the method call that will make the Contentful request (with parameters): " fetch_method

{
  rails runner "Site::Contentful::Helpers::FixtureHelper.generate('$file_name', $fetch_method)"
  echo "JSON file generated successfully."
} || {
  echo "An error occurred while generating the JSON file."
}
