# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PlatformTypes::IssueFieldDataType`.
# Please instead update this file by running `bin/tapioca dsl PlatformTypes::IssueFieldDataType`.


module PlatformTypes::IssueFieldDataType
  sig { returns(T::Boolean) }
  def date?; end

  sig { returns(T::Boolean) }
  def number?; end

  sig { returns(T::Boolean) }
  def single_select?; end

  sig { returns(T::Boolean) }
  def text?; end

  DATE = T.let("DATE", String)
  NUMBER = T.let("NUMBER", String)
  SINGLE_SELECT = T.let("SINGLE_SELECT", String)
  TEXT = T.let("TEXT", String)
end
