# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PlatformTypes::IssueFieldValueEdge`.
# Please instead update this file by running `bin/tapioca dsl PlatformTypes::IssueFieldValueEdge`.


class PlatformTypes::IssueFieldValueEdge < GraphQL::Client::Schema::ObjectClass
  sig { returns(T.nilable(String)) }
  def __typename; end

  sig { returns(String) }
  def cursor; end

  sig { returns(T::Boolean) }
  def cursor?; end

  sig do
    returns(T.nilable(T.any(PlatformTypes::IssueFieldTextValue, PlatformTypes::IssueFieldSingleSelectValue, PlatformTypes::IssueFieldDateValue, PlatformTypes::IssueFieldNumberValue)))
  end
  def node; end

  sig { returns(T::Boolean) }
  def node?; end
end
