# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/registry_metadata/v0/entities/migration_data_sync_event_type.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "hydro.schemas.registry_metadata.v0.entities.MigrationDataSyncEventType" do
    value :UNKNOWN, 0
    value :SHA_UPDATE, 1
    value :DELETE, 2
    value :DOWNLOAD_COUNT, 3
  end
end

module Hydro
  module Schemas
    module RegistryMetadata
      module V0
        module Entities
          MigrationDataSyncEventType = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.registry_metadata.v0.entities.MigrationDataSyncEventType").enummodule
        end
      end
    end
  end
end
