# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/github/security_center/v0/organization_advanced_security_license_toggled_per_repository.proto

require 'google/protobuf'

require 'hydro/schemas/github/security_center/v0/organization_advanced_security_license_toggled_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.github.security_center.v0.OrganizationAdvancedSecurityLicenseToggledPerRepository" do
    optional :repository_id, :int64, 1
    optional :organization_advanced_security_license_toggled, :message, 2, "hydro.schemas.github.security_center.v0.OrganizationAdvancedSecurityLicenseToggled"
  end
end

module Hydro
  module Schemas
    module Github
      module SecurityCenter
        module V0
          OrganizationAdvancedSecurityLicenseToggledPerRepository = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.security_center.v0.OrganizationAdvancedSecurityLicenseToggledPerRepository").msgclass
        end
      end
    end
  end
end
