# typed: strict
# frozen_string_literal: true

module Billing
  module UsageReportDependency
    extend ActiveSupport::Concern
    extend T::Helpers

    include Billing::Platform::Api::Utils
    include UsageDependency

    requires_ancestor { ApplicationController }

    abstract!

    sig { params(usage_report_request: ::Billing::MeteredUsage::UsageReportRequest).void }
    def create_usage_report_request(usage_report_request:)
      entity = usage_report_request.entity
      period = usage_report_request.period
      start_date = usage_report_request.start_date
      end_date = usage_report_request.end_date

      legacy_report_from_vnext_enabled = entity.feature_flag_enabled_or_raise?(:billing_vnext_legacy_usage_report) # rubocop:disable GitHub/FeatureManagement/NoVexiActorFeatureFlagEnabledOrRaiseUsage

      # If this is a legacy report from meuse, run the meuse export job and return early. Remove this if section once we have
      # enabled legacy reports from vNext
      if usage_report_request.is_legacy_report? && !legacy_report_from_vnext_enabled
        Billing::MeteredReportExportJob.perform_later(current_user, entity, Billing::UsageDependency::MEUSE_REPORT_WINDOW,
          start_date: (Time.now.utc - Billing::UsageDependency::MEUSE_REPORT_WINDOW.days).to_datetime,
          end_date: (entity.customer&.vnext_migration_date || DateTime.now.utc).to_datetime
        )
        audit_log_payload = {
          actor: current_user,
          customer_id: entity.customer&.id.to_s,
          period: period,
          days: Billing::UsageDependency::MEUSE_REPORT_WINDOW,
          start_date: (Time.now.utc - Billing::UsageDependency::MEUSE_REPORT_WINDOW.days).to_datetime,
          end_date: (entity.customer&.vnext_migration_date || DateTime.now.utc).to_datetime
        }

        add_entity_to_payload(entity: entity, payload: audit_log_payload)

        GitHub.instrument("billing.usage_report_create", audit_log_payload)
        return render json: { success: true }, status: 200
      end

      report_params = {
        customer_id: entity.customer&.id,
        start_date: start_date,
        end_date: end_date,
        actor_id: current_user&.id,
      }

      legacy_report_params = {
        billable_owner_type: usage_report_request.is_legacy_report? ? billable_owner_type(entity) : nil,
        billable_owner_id: usage_report_request.is_legacy_report? ? entity.billable_owner.id : nil,
      }

      report_params.merge!({ organization_ids: get_org_ids_for_org_admin(entity, current_user) }) if !usage_report_request.is_stafftools && should_filter_for_org_admin?(entity, current_user)
      report_params.merge!(legacy_report_params) if legacy_report_from_vnext_enabled && usage_report_request.is_legacy_report?
      report_params.merge!({ report_type: usage_report_request.vnext_report_type })

      usage_report_response = billing_platform_client.queue_usage_report_export(
        **report_params
      )

      if usage_report_response.is_a?(::Billing::Platform::Api::Error)
        if usage_report_response.try(:original_error)&.code == :already_exists
          return render json: { error: "User already has a pending usage report request", code: "IN_PROGRESS" }, status: 409
        else
          return render json: { error: "Unable to request usage report export" }, status: 500
        end
      end

      audit_log_payload = {
        actor: current_user,
        customer_id: entity.customer&.id.to_s,
        period: period,
      }

      add_entity_to_payload(entity: entity, payload: audit_log_payload)

      GitHub.instrument("billing.usage_report_create", audit_log_payload)
      GitHub.dogstats.increment("billing.usage_report.creation.count", tags: ["period:#{period}", "is_stafftools:#{usage_report_request.is_stafftools}"])
      render json: { success: true }, status: 200
    end

    sig { returns(Billing::Platform::Api::Client) }
    def billing_platform_client
      Billing::Platform::Api::Client.new
    end

    # this before_action will run first and raise error if type is missing
    sig { params(entity: ::Billing::Types::Account, type_selection: T.nilable(Integer)).void }
    def validate_report_type_for_entity(entity:, type_selection:)
      if params[:type].blank?
        render json: { error: "Missing report type" }, status: 400
      end

      # skip validation if the report needs to be generated by meuse endpoint
      return if type_selection == Billing::UsageDependency::USAGE_REPORT_LEGACY_TYPE && !entity.feature_flag_enabled_or_raise?(:billing_vnext_legacy_usage_report) # rubocop:disable GitHub/FeatureManagement/NoVexiActorFeatureFlagEnabledOrRaiseUsage

      if !Billing::UsageDependency::VALID_REPORT_TYPES.include?(type_selection)
        render json: { error: "Invalid report type" }, status: 400
      end
    end

    sig { returns(Integer) }
    def type_selection
      params[:type].to_i
    end

    sig { params(period_selection: T.nilable(String), custom_range_start_date: T.nilable(String), custom_range_end_date: T.nilable(String), entity: ::Billing::Types::Account, type: Integer).returns(T::Boolean) }
    def valid_date_range?(period_selection:, custom_range_start_date:, custom_range_end_date:, entity:, type:)
      return true if (period_selection.to_i == usage_report_legacy_selection[:type] || type == Billing::UsageDependency::USAGE_REPORT_LEGACY_TYPE) && entity.customer&.is_legacy_report_an_option?
      return is_custom_range_valid?(start_date: custom_range_start_date, end_date: custom_range_end_date, entity: entity, type: type) if is_custom_range?(period_selection.to_i)

      report_type_selection = usage_report_type_selections(
        is_legacy_option: false,
        migration_date: nil,
        min_custom_date: min_custom_date(customer: T.must(entity.customer))
      ).find { |type_selection| type_selection[:type] == type }

      return false unless report_type_selection
      report_type_selection[:usagePeriods].map { |period| period[:type] }.include?(period_selection.to_i)
    end
  end
end
