<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:tns="urn:oasis:names:tc:SAML:2.0:assertion" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
  <xs:import schemaLocation="xmldsig_schema.xsd" namespace="http://www.w3.org/2000/09/xmldsig#" />
  <xs:import schemaLocation="saml20encrypted_assertion_data_schema.xsd" namespace="http://www.w3.org/2001/04/xmlenc#" />

  <xs:element name="Issuer" type="xs:string" />
  <xs:element name="Assertion">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Issuer" type="xs:string" />
        <xs:element ref="ds:Signature" minOccurs="0" />
        <xs:element name="Subject">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="NameID">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="Format" type="xs:string" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="SubjectConfirmation">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="SubjectConfirmationData">
                      <xs:complexType>
                        <xs:attribute name="InResponseTo" type="xs:string" use="optional" />
                        <xs:attribute name="NotOnOrAfter" type="xs:dateTime" use="required" />
                        <xs:attribute name="Recipient" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="Method" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Conditions">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="AudienceRestriction">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Audience" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="NotBefore" type="xs:dateTime" use="required" />
            <xs:attribute name="NotOnOrAfter" type="xs:dateTime" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="AttributeStatement">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="Attribute">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="AttributeValue" type="xs:string" />
                  </xs:sequence>
                  <xs:attribute name="Name" type="xs:string" use="required" />
                  <xs:attribute name="NameFormat" type="xs:string" use="optional" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="AuthnStatement">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="AuthnContext">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="AuthnContextClassRef" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="AuthnInstant" type="xs:dateTime" use="required" />
            <xs:attribute name="SessionIndex" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="ID" type="xs:ID" use="required" />
      <xs:attribute name="IssueInstant" type="xs:dateTime" use="required" />
      <xs:attribute name="Version" type="xs:decimal" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="EncryptedAssertion">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="xenc:EncryptedData" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
