# typed: true
# frozen_string_literal: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file of the set of rule condition targets
# Please instead update this file by running `bin/dump-rules-schema`.

module Platform
  module Objects
    module RepositoryRules
      class RepositoryRuleConditions < Platform::Objects::Base
        description "Set of conditions that determine if a ruleset will evaluate"
        minimum_accepted_scopes ["public_repo"]

        # Determine whether the viewer can access this object via the API (called internally).
        # This is where Egress checks for OAuth scopes and GitHub Apps go.
        # Returns `true`, `false`, or `Promise` resolving to `true` or `false`
        def self.async_api_can_access?(permission, object)
          permission.typed_can_access?("RepositoryRuleset", object.ruleset)
        end

        # Determine whether the viewer can see this object (called internally).
        # Returns `true`, `false`, or `Promise` resolving to `true` or `false`
        def self.async_viewer_can_see?(permission, object)
          permission.typed_can_see?("RepositoryRuleset", object.ruleset)
        end

        field :ref_name, Objects::RepositoryRules::RefNameConditionTarget,
          description: "Configuration for the ref_name condition",
          null: true

        def ref_name
          condition = @object.conditions.find_by(target: "ref_name")
          return nil unless condition
          Platform::Models::RepositoryRuleParameters.new(@object.ruleset, condition.parameters, platform_type: "RefNameConditionTarget")
        end

        field :repository_name, Objects::RepositoryRules::RepositoryNameConditionTarget,
          description: "Configuration for the repository_name condition",
          null: true

        def repository_name
          condition = @object.conditions.find_by(target: "repository_name")
          return nil unless condition
          Platform::Models::RepositoryRuleParameters.new(@object.ruleset, condition.parameters, platform_type: "RepositoryNameConditionTarget")
        end

        field :repository_id, Objects::RepositoryRules::RepositoryIdConditionTarget,
          description: "Configuration for the repository_id condition",
          null: true

        def repository_id
          condition = @object.conditions.find_by(target: "repository_id")
          return nil unless condition
          Platform::Models::RepositoryRuleParameters.new(@object.ruleset, condition.parameters, platform_type: "RepositoryIdConditionTarget")
        end

        field :repository_property, Objects::RepositoryRules::RepositoryPropertyConditionTarget,
          description: "Configuration for the repository_property condition",
          null: true

        def repository_property
          condition = @object.conditions.find_by(target: "repository_property")
          return nil unless condition
          Platform::Models::RepositoryRuleParameters.new(@object.ruleset, condition.parameters, platform_type: "RepositoryPropertyConditionTarget")
        end

        field :organization_name, Objects::RepositoryRules::OrganizationNameConditionTarget,
          description: "Configuration for the organization_name condition",
          null: true, feature_flag: :member_privilege_rulesets

        def organization_name
          condition = @object.conditions.find_by(target: "organization_name")
          return nil unless condition
          Platform::Models::RepositoryRuleParameters.new(@object.ruleset, condition.parameters, platform_type: "OrganizationNameConditionTarget")
        end

        field :organization_id, Objects::RepositoryRules::OrganizationIdConditionTarget,
          description: "Configuration for the organization_id condition",
          null: true, feature_flag: :member_privilege_rulesets

        def organization_id
          condition = @object.conditions.find_by(target: "organization_id")
          return nil unless condition
          Platform::Models::RepositoryRuleParameters.new(@object.ruleset, condition.parameters, platform_type: "OrganizationIdConditionTarget")
        end

        field :organization_property, Objects::RepositoryRules::OrganizationPropertyConditionTarget,
          description: "Configuration for the organization_property condition",
          null: true, feature_flag: :custom_properties_for_orgs

        def organization_property
          condition = @object.conditions.find_by(target: "organization_property")
          return nil unless condition
          Platform::Models::RepositoryRuleParameters.new(@object.ruleset, condition.parameters, platform_type: "OrganizationPropertyConditionTarget")
        end
      end
    end
  end
end
