# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GitHub::Spokes::Proto::Objects::V1::ExpandOidsRequest::RevisionAndType`.
# Please instead update this file by running `bin/tapioca dsl GitHub::Spokes::Proto::Objects::V1::ExpandOidsRequest::RevisionAndType`.


class GitHub::Spokes::Proto::Objects::V1::ExpandOidsRequest::RevisionAndType < Google::Protobuf::AbstractMessage
  sig do
    params(
      object_type: T.nilable(GitHub::Spokes::Proto::Types::V1::ObjectType),
      revision: T.nilable(GitHub::Spokes::Proto::Types::V1::Revision)
    ).void
  end
  def initialize(object_type: nil, revision: nil); end

  sig { void }
  def clear_object_type; end

  sig { void }
  def clear_revision; end

  sig { returns(Object) }
  def has_object_type?; end

  sig { returns(Object) }
  def has_revision?; end

  sig { returns(T.nilable(GitHub::Spokes::Proto::Types::V1::ObjectType)) }
  def object_type; end

  sig { params(value: T.nilable(GitHub::Spokes::Proto::Types::V1::ObjectType)).void }
  def object_type=(value); end

  sig { returns(T.nilable(GitHub::Spokes::Proto::Types::V1::Revision)) }
  def revision; end

  sig { params(value: T.nilable(GitHub::Spokes::Proto::Types::V1::Revision)).void }
  def revision=(value); end
end
