# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `BillingPlatform::Api::V1::GetCopilotModelsRequest`.
# Please instead update this file by running `bin/tapioca dsl BillingPlatform::Api::V1::GetCopilotModelsRequest`.


class BillingPlatform::Api::V1::GetCopilotModelsRequest < Google::Protobuf::AbstractMessage
  sig { void }
  def initialize; end
end
