# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/github/copilot/v0/copilot_pull_request_summaries.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.github.copilot.v0.CopilotPullRequestSummaries" do
    optional :actor_id, :int32, 1
    optional :repository_id, :int32, 2
    optional :head_revision, :string, 3
    optional :base_revision, :string, 4
    optional :status, :string, 5
  end
end

module Hydro
  module Schemas
    module Github
      module Copilot
        module V0
          CopilotPullRequestSummaries = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.copilot.v0.CopilotPullRequestSummaries").msgclass
        end
      end
    end
  end
end
