# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/github/releases/v1/release_notes_generated.proto

require 'google/protobuf'

require 'hydro/schemas/github/v1/entities/request_context_pb'
require 'hydro/schemas/github/v1/entities/user_pb'
require 'hydro/schemas/github/releases/v1/entities/release_pb'
require 'hydro/schemas/github/v2/entities/repository_pb'
require 'hydro/schemas/github/v1/entities/spamurai_form_signals_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.github.releases.v1.ReleaseNotesGenerated" do
    optional :request_context, :message, 1, "hydro.schemas.github.v1.entities.RequestContext"
    optional :actor, :message, 2, "hydro.schemas.github.v1.entities.User"
    optional :release, :message, 3, "hydro.schemas.github.releases.v1.entities.Release"
    optional :repository, :message, 4, "hydro.schemas.github.v2.entities.Repository"
    optional :spamurai_form_signals, :message, 5, "hydro.schemas.github.v1.entities.SpamuraiFormSignals"
    optional :repository_owner, :message, 6, "hydro.schemas.github.v1.entities.User"
  end
end

module Hydro
  module Schemas
    module Github
      module Releases
        module V1
          ReleaseNotesGenerated = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.releases.v1.ReleaseNotesGenerated").msgclass
        end
      end
    end
  end
end
