# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/github/custom_repository_roles/v0/custom_repository_role_updated.proto

require 'google/protobuf'

require 'hydro/schemas/github/v1/entities/custom_repository_role_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.github.custom_repository_roles.v0.CustomRepositoryRoleUpdated" do
    optional :role, :message, 1, "hydro.schemas.github.v1.entities.CustomRepositoryRole"
  end
end

module Hydro
  module Schemas
    module Github
      module CustomRepositoryRoles
        module V0
          CustomRepositoryRoleUpdated = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.custom_repository_roles.v0.CustomRepositoryRoleUpdated").msgclass
        end
      end
    end
  end
end
