# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/registry_metadata/v0/layer_deleted.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'hydro/schemas/registry_metadata/v0/entities/actor_type_pb'
require 'hydro/schemas/registry_metadata/v0/entities/request_context_pb'
require 'hydro/schemas/registry_metadata/v0/entities/container_layer_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.registry_metadata.v0.LayerDeleted" do
    optional :request_context, :message, 1, "hydro.schemas.registry_metadata.v0.entities.RequestContext"
    optional :layer, :message, 2, "hydro.schemas.registry_metadata.v0.entities.ContainerLayer"
    optional :actor_id, :int64, 3
    optional :user_agent, :string, 4
    optional :deleted_at, :message, 5, "google.protobuf.Timestamp"
    optional :actor_type, :enum, 6, "hydro.schemas.registry_metadata.v0.entities.ActorType"
    optional :owner_id, :int64, 7
  end
end

module Hydro
  module Schemas
    module RegistryMetadata
      module V0
        LayerDeleted = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.registry_metadata.v0.LayerDeleted").msgclass
      end
    end
  end
end
