# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/github/memex/v1/memex_project_column_group_by.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'hydro/schemas/github/v1/entities/user_pb'
require 'hydro/schemas/github/v2/entities/memex_project_pb'
require 'hydro/schemas/github/v2/entities/memex_project_column_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.github.memex.v1.MemexProjectColumnGroupBy" do
    optional :actor, :message, 1, "hydro.schemas.github.v1.entities.User"
    optional :memex_project, :message, 2, "hydro.schemas.github.v2.entities.MemexProject"
    optional :memex_project_column, :message, 3, "hydro.schemas.github.v2.entities.MemexProjectColumn"
    optional :group_by_enabled, :bool, 4
    optional :applied_at, :message, 5, "google.protobuf.Timestamp"
  end
end

module Hydro
  module Schemas
    module Github
      module Memex
        module V1
          MemexProjectColumnGroupBy = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.memex.v1.MemexProjectColumnGroupBy").msgclass
        end
      end
    end
  end
end
