# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Hydro::Schemas::Turboquality::V0::PullRequestAnalysis::AdvisorySeverity`.
# Please instead update this file by running `bin/tapioca dsl Hydro::Schemas::Turboquality::V0::PullRequestAnalysis::AdvisorySeverity`.


module Hydro::Schemas::Turboquality::V0::PullRequestAnalysis::AdvisorySeverity
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Hydro::Schemas::Turboquality::V0::PullRequestAnalysis::AdvisorySeverity::ADVISORY_SEVERITY_CRITICAL = 4
Hydro::Schemas::Turboquality::V0::PullRequestAnalysis::AdvisorySeverity::ADVISORY_SEVERITY_HIGH = 3
Hydro::Schemas::Turboquality::V0::PullRequestAnalysis::AdvisorySeverity::ADVISORY_SEVERITY_LOW = 1
Hydro::Schemas::Turboquality::V0::PullRequestAnalysis::AdvisorySeverity::ADVISORY_SEVERITY_MEDIUM = 2
Hydro::Schemas::Turboquality::V0::PullRequestAnalysis::AdvisorySeverity::ADVISORY_SEVERITY_UNKNOWN = 0
