# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `DependabotApi::V1::GetSuggestedFixRequest`.
# Please instead update this file by running `bin/tapioca dsl DependabotApi::V1::GetSuggestedFixRequest`.


class DependabotApi::V1::GetSuggestedFixRequest < Google::Protobuf::AbstractMessage
  sig do
    params(
      autofix_job_id: T.nilable(Integer),
      github_pull_request_number: T.nilable(Integer),
      github_repo_id: T.nilable(Integer)
    ).void
  end
  def initialize(autofix_job_id: nil, github_pull_request_number: nil, github_repo_id: nil); end

  sig { returns(Integer) }
  def autofix_job_id; end

  sig { params(value: Integer).void }
  def autofix_job_id=(value); end

  sig { void }
  def clear_autofix_job_id; end

  sig { void }
  def clear_github_pull_request_number; end

  sig { void }
  def clear_github_repo_id; end

  sig { returns(Integer) }
  def github_pull_request_number; end

  sig { params(value: Integer).void }
  def github_pull_request_number=(value); end

  sig { returns(Integer) }
  def github_repo_id; end

  sig { params(value: Integer).void }
  def github_repo_id=(value); end
end
