# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `DependabotApi::V1::SuggestedFix`.
# Please instead update this file by running `bin/tapioca dsl DependabotApi::V1::SuggestedFix`.


class DependabotApi::V1::SuggestedFix < Google::Protobuf::AbstractMessage
  sig do
    params(
      autofix_job_id: T.nilable(Integer),
      created_at: T.nilable(Google::Protobuf::Timestamp),
      dependency_metadata: T.nilable(T.any(Google::Protobuf::RepeatedField[DependabotApi::V1::DependencyMetadata], T::Array[DependabotApi::V1::DependencyMetadata])),
      description: T.nilable(String),
      files: T.nilable(T.any(Google::Protobuf::RepeatedField[DependabotApi::V1::SuggestedFixFile], T::Array[DependabotApi::V1::SuggestedFixFile])),
      id: T.nilable(Integer),
      review_status: T.nilable(T.any(Symbol, Integer)),
      updated_at: T.nilable(Google::Protobuf::Timestamp)
    ).void
  end
  def initialize(autofix_job_id: nil, created_at: nil, dependency_metadata: T.unsafe(nil), description: nil, files: T.unsafe(nil), id: nil, review_status: nil, updated_at: nil); end

  sig { returns(Integer) }
  def autofix_job_id; end

  sig { params(value: Integer).void }
  def autofix_job_id=(value); end

  sig { void }
  def clear_autofix_job_id; end

  sig { void }
  def clear_created_at; end

  sig { void }
  def clear_dependency_metadata; end

  sig { void }
  def clear_description; end

  sig { void }
  def clear_files; end

  sig { void }
  def clear_id; end

  sig { void }
  def clear_review_status; end

  sig { void }
  def clear_updated_at; end

  sig { returns(T.nilable(Google::Protobuf::Timestamp)) }
  def created_at; end

  sig { params(value: T.nilable(Google::Protobuf::Timestamp)).void }
  def created_at=(value); end

  sig { returns(Google::Protobuf::RepeatedField[DependabotApi::V1::DependencyMetadata]) }
  def dependency_metadata; end

  sig { params(value: Google::Protobuf::RepeatedField[DependabotApi::V1::DependencyMetadata]).void }
  def dependency_metadata=(value); end

  sig { returns(String) }
  def description; end

  sig { params(value: String).void }
  def description=(value); end

  sig { returns(Google::Protobuf::RepeatedField[DependabotApi::V1::SuggestedFixFile]) }
  def files; end

  sig { params(value: Google::Protobuf::RepeatedField[DependabotApi::V1::SuggestedFixFile]).void }
  def files=(value); end

  sig { returns(Object) }
  def has_created_at?; end

  sig { returns(Object) }
  def has_updated_at?; end

  sig { returns(Integer) }
  def id; end

  sig { params(value: Integer).void }
  def id=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def review_status; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def review_status=(value); end

  sig { returns(T.nilable(Google::Protobuf::Timestamp)) }
  def updated_at; end

  sig { params(value: T.nilable(Google::Protobuf::Timestamp)).void }
  def updated_at=(value); end
end
