# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `DependabotApi::V1::SuggestedFixesClient`.
# Please instead update this file by running `bin/tapioca dsl DependabotApi::V1::SuggestedFixesClient`.


class DependabotApi::V1::SuggestedFixesClient < ::Twirp::Client
  sig { params(connection: T.any(String, ::Faraday::Connection), opts: T::Hash[Symbol, T.untyped]).void }
  def initialize(connection, opts = {}); end

  sig do
    params(
      input: DependabotApi::V1::ApplySuggestedFixRequest,
      req_opts: T.nilable(T::Hash[Symbol, T.untyped])
    ).returns(::Twirp::ClientResp[DependabotApi::V1::ApplySuggestedFixResponse])
  end
  def apply_suggested_fix(input, req_opts = nil); end

  sig do
    params(
      input: DependabotApi::V1::DismissSuggestedFixRequest,
      req_opts: T.nilable(T::Hash[Symbol, T.untyped])
    ).returns(::Twirp::ClientResp[DependabotApi::V1::DismissSuggestedFixResponse])
  end
  def dismiss_suggested_fix(input, req_opts = nil); end

  sig do
    params(
      input: DependabotApi::V1::GetSuggestedFixRequest,
      req_opts: T.nilable(T::Hash[Symbol, T.untyped])
    ).returns(::Twirp::ClientResp[DependabotApi::V1::GetSuggestedFixResponse])
  end
  def get_suggested_fix(input, req_opts = nil); end
end
