# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `MonolithTwirp::GitSrcMigrator::Migrations::V1::Migration`.
# Please instead update this file by running `bin/tapioca dsl MonolithTwirp::GitSrcMigrator::Migrations::V1::Migration`.


class MonolithTwirp::GitSrcMigrator::Migrations::V1::Migration < Google::Protobuf::AbstractMessage
  sig do
    params(
      actions_logs: T.nilable(String),
      actions_run_url: T.nilable(String),
      error_details: T.nilable(T.any(Google::Protobuf::RepeatedField[String], T::Array[String])),
      failure_details: T.nilable(T.any(Google::Protobuf::RepeatedField[MonolithTwirp::GitSrcMigrator::Migrations::V1::SourceMigrationFailureDetails], T::Array[MonolithTwirp::GitSrcMigrator::Migrations::V1::SourceMigrationFailureDetails])),
      failure_reason: T.nilable(String),
      git_data_size: T.nilable(Integer),
      id: T.nilable(Integer),
      metadata_gei_uri: T.nilable(String),
      repository_empty: T.nilable(T::Boolean),
      repository_id: T.nilable(Integer),
      state: T.nilable(T.any(Symbol, Integer))
    ).void
  end
  def initialize(actions_logs: nil, actions_run_url: nil, error_details: T.unsafe(nil), failure_details: T.unsafe(nil), failure_reason: nil, git_data_size: nil, id: nil, metadata_gei_uri: nil, repository_empty: nil, repository_id: nil, state: nil); end

  sig { returns(String) }
  def actions_logs; end

  sig { params(value: String).void }
  def actions_logs=(value); end

  sig { returns(String) }
  def actions_run_url; end

  sig { params(value: String).void }
  def actions_run_url=(value); end

  sig { void }
  def clear_actions_logs; end

  sig { void }
  def clear_actions_run_url; end

  sig { void }
  def clear_error_details; end

  sig { void }
  def clear_failure_details; end

  sig { void }
  def clear_failure_reason; end

  sig { void }
  def clear_git_data_size; end

  sig { void }
  def clear_id; end

  sig { void }
  def clear_metadata_gei_uri; end

  sig { void }
  def clear_repository_empty; end

  sig { void }
  def clear_repository_id; end

  sig { void }
  def clear_state; end

  sig { returns(Google::Protobuf::RepeatedField[String]) }
  def error_details; end

  sig { params(value: Google::Protobuf::RepeatedField[String]).void }
  def error_details=(value); end

  sig do
    returns(Google::Protobuf::RepeatedField[MonolithTwirp::GitSrcMigrator::Migrations::V1::SourceMigrationFailureDetails])
  end
  def failure_details; end

  sig do
    params(
      value: Google::Protobuf::RepeatedField[MonolithTwirp::GitSrcMigrator::Migrations::V1::SourceMigrationFailureDetails]
    ).void
  end
  def failure_details=(value); end

  sig { returns(String) }
  def failure_reason; end

  sig { params(value: String).void }
  def failure_reason=(value); end

  sig { returns(Integer) }
  def git_data_size; end

  sig { params(value: Integer).void }
  def git_data_size=(value); end

  sig { returns(Integer) }
  def id; end

  sig { params(value: Integer).void }
  def id=(value); end

  sig { returns(String) }
  def metadata_gei_uri; end

  sig { params(value: String).void }
  def metadata_gei_uri=(value); end

  sig { returns(T::Boolean) }
  def repository_empty; end

  sig { params(value: T::Boolean).void }
  def repository_empty=(value); end

  sig { returns(Integer) }
  def repository_id; end

  sig { params(value: Integer).void }
  def repository_id=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def state; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def state=(value); end
end
