#!/bin/bash
set -e

echo -e "==== Enabling feature flags ===="

# NOTE: toggle-feature-flag supports additional flags via the -F/--flag option
# Keeping this list sorted may help prevent merge conflicts.
bin/toggle-feature-flag enable \
  bogus_placeholder_feature \
  -F enterprise_teams_enabled_for_organizations \
  -F enterprise_teams_security_manager_sync \
  -F proxima_request_scoping_disabled \
  -F report_missing_tenant \
  -F security_center_backfill_code_scanning_alert_number \
  -F security_center_feedback_link \
  -F tenant_namespacing \
  --mode verbose

bin/toggle-global-flags --enable
