# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `TradeCompliance::TradeScreening::EisPollJob`.
# Please instead update this file by running `bin/tapioca dsl TradeCompliance::TradeScreening::EisPollJob`.


class TradeCompliance::TradeScreening::EisPollJob
  class << self
    sig do
      params(
        block: T.nilable(T.proc.params(job: TradeCompliance::TradeScreening::EisPollJob).void)
      ).returns(T.any(TradeCompliance::TradeScreening::EisPollJob, FalseClass))
    end
    def perform_later(&block); end

    sig { void }
    def perform_now; end
  end
end
