# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `prose_diff` gem.
# Please instead update this file by running `bin/tapioca gem prose_diff`.


# first, helpers neeced by the transformers
module ProseDiff
  private

  def gem_name; end
  def html(before_html, after_html, options = T.unsafe(nil)); end
  def output_version(cache = T.unsafe(nil)); end
  def semantic_version; end

  class << self
    def gem_name; end
    def html(before_html, after_html, options = T.unsafe(nil)); end
    def output_version(cache = T.unsafe(nil)); end
    def semantic_version; end
  end
end

class ProseDiff::Diff
  # @return [Diff] a new instance of Diff
  def initialize(before, after, options = T.unsafe(nil)); end

  def document; end
  def flattened(nodeset); end
  def node_set; end
  def strip_wrapped_text(nodeset); end
  def wrap_text(node); end

  class << self
    def diff_node(after, before, options); end
    def diff_node_set(after_node_sets, before_node_sets, options); end
  end
end

ProseDiff::Diff::NAMES = T.let(T.unsafe(nil), Array)

class ProseDiff::LCS
  # @return [LCS] a new instance of LCS
  def initialize(a, b, options = T.unsafe(nil), &comparator); end

  def backstep; end
  def backtrack; end
  def compute_backstep; end
  def compute_entry(c, d); end
  def lookup(x, y); end
  def match(c, d); end
  def peek(x, y); end
  def pos(i, j); end
  def pos_lower_right; end

  # @return [Boolean]
  def valid?(i = T.unsafe(nil), j = T.unsafe(nil)); end

  class << self
    # &block
    def fold_diff(comparator, a, b, acc); end

    def length(a, b, options = T.unsafe(nil), &comparator); end
    def pair(a, b, comparator = T.unsafe(nil)); end
    def smallest_contiguous_change(a, b); end
  end
end

ProseDiff::LCS::DIAG = T.let(T.unsafe(nil), Array)
ProseDiff::LCS::LEFT = T.let(T.unsafe(nil), Array)
ProseDiff::LCS::SELF = T.let(T.unsafe(nil), Array)
ProseDiff::LCS::UP = T.let(T.unsafe(nil), Array)

class ProseDiff::Node
  class << self
    def Document(value = T.unsafe(nil)); end
    def HTML(text, query = T.unsafe(nil)); end
    def LINE(html, doc = T.unsafe(nil)); end
    def NodeSet(value); end
    def PARENT(node_or_text_or_string, doc = T.unsafe(nil)); end

    # an undistinguished span
    def SPAN(text, doc = T.unsafe(nil)); end

    def TEXT(something, doc = T.unsafe(nil)); end
    def WHITESPACE(text, doc = T.unsafe(nil)); end
    def WORD(text, doc = T.unsafe(nil)); end
    def add_class(*args, &block); end
    def analysis(*args, &block); end
    def appear_to_correspond(*args, &block); end
    def appear_to_correspond?(*args, &block); end
    def are_comparable_lists?(*args, &block); end
    def are_comparable_lists_of_nodes?(*args, &block); end

    # @return [Boolean]
    def are_identical?(node, other_node); end

    def at(*args, &block); end
    def becomes_added(*args, &block); end
    def becomes_changed(*args, &block); end
    def becomes_moved(*args, &block); end
    def becomes_removed(*args, &block); end
    def becomes_unchanged(*args, &block); end
    def before(*args, &block); end
    def before_natural_attr_keys(*args, &block); end
    def before_text(*args, &block); end
    def children_of(*args, &block); end
    def classify_before(*args, &block); end
    def define_method_that_delegates(method_name); end
    def diff_attributes(*args, &block); end
    def diff_children(*args, &block); end
    def diff_with_before(*args, &block); end
    def digest(*args, &block); end
    def digested(node); end
    def digests(*args, &block); end
    def doesnt_have_natural_keys?(*args, &block); end
    def doppelganger(*args, &block); end
    def has_natural_keys?(*args, &block); end
    def has_same_content_as?(*args, &block); end
    def have_comparable_children?(*args, &block); end
    def have_comparable_text?(*args, &block); end
    def have_same_identification?(*args, &block); end
    def instance_methods_for_all_proxies; end
    def is_a_simple_text_container?(*args, &block); end
    def is_comparable_text?(*args, &block); end
    def is_compatible_with?(*args, &block); end
    def is_dominated_by_text?(*args, &block); end
    def is_textlike?(*args, &block); end
    def is_uncomplicated?(*args, &block); end
    def natural_attrs(*args, &block); end
    def natural_keys(*args, &block); end
    def number_that_correspond(*args, &block); end
    def number_that_match_exactly(*args, &block); end
    def other_changed?(*args, &block); end

    # @return [Boolean]
    def plural?(node_like_thing); end

    def preanalyze_moves(*args, &block); end
    def private_attrs(*args, &block); end
    def proxies_by_tag; end
    def replace_children(*args, &block); end
    def set_analysis(*args, &block); end
    def set_before(*args, &block); end
    def significant(*args, &block); end
    def significant_html(node); end
    def significants(*args, &block); end
    def split(*args, &block); end
    def split_children(*args, &block); end
    def tags_seen; end
    def text(*args, &block); end
    def text_differences_metric(*args, &block); end
    def text_hash(*args, &block); end
    def to_text_string(node); end
    def transform_children(*args, &block); end
    def unsplit(*args, &block); end
    def unsplit_all(*args, &block); end
    def valid?(*args, &block); end
    def valid_and_compatible?(*args, &block); end
    def was_added?(*args, &block); end
    def was_changed?(*args, &block); end
    def was_moved?(*args, &block); end
    def was_removed?(*args, &block); end
    def was_unchanged?(*args, &block); end
    def wordz(*args, &block); end

    private

    def dispatch_through_proxy(receiver, method_name, argv, &block); end
  end
end

ProseDiff::Node::ANALYSIS = T.let(T.unsafe(nil), String)
ProseDiff::Node::ATOMS = T.let(T.unsafe(nil), Array)
ProseDiff::Node::BEFORE_ID = T.let(T.unsafe(nil), String)
ProseDiff::Node::BEFORE_NATURAL_ATTR_KEYS = T.let(T.unsafe(nil), String)
ProseDiff::Node::BEFORE_TEXT = T.let(T.unsafe(nil), String)
ProseDiff::Node::CALL_COUNTS = T.let(T.unsafe(nil), Hash)
ProseDiff::Node::CLAZZ = T.let(T.unsafe(nil), String)

# Types of nodes
ProseDiff::Node::CONTAINERS = T.let(T.unsafe(nil), Array)

ProseDiff::Node::DEFAULT_XPATH_QUERY = T.let(T.unsafe(nil), String)
ProseDiff::Node::DIGEST = T.let(T.unsafe(nil), String)
ProseDiff::Node::ID = T.let(T.unsafe(nil), String)
ProseDiff::Node::INLINES = T.let(T.unsafe(nil), Array)
ProseDiff::Node::MOVED = T.let(T.unsafe(nil), String)
ProseDiff::Node::OPAQUE = T.let(T.unsafe(nil), ProseDiff::Node::Proxy::Opaque)
module ProseDiff::Node::Proxy; end

class ProseDiff::Node::Proxy::A
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::SplitsChildrenAndSelfBehaviour
end

class ProseDiff::Node::Proxy::Article
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::SuperBlockBehaviour
end

class ProseDiff::Node::Proxy::B < ::ProseDiff::Node::Proxy::Inline; end

module ProseDiff::Node::Proxy::BaseBehaviour
  def add_class(node, new_class); end
  def analysis(node); end

  # @return [Boolean]
  def appear_to_correspond?(node, other_node); end

  # tri:state: true, false, nil
  #
  # @return [Boolean]
  def are_comparable_lists?(a_list, b_list); end

  # tri:state: true, false, nil
  #
  # @return [Boolean]
  def are_comparable_lists_of_nodes?(a_list, b_list); end

  def at(options, category, key); end
  def becomes_added(node); end
  def becomes_changed(node); end
  def becomes_moved(node); end
  def becomes_removed(node); end

  # now recursive
  def becomes_unchanged(node); end

  def before_natural_attr_keys(after_node); end
  def before_text(after_node); end
  def classify_before(node, attr, value); end
  def diff_attributes(node, before, options); end
  def diff_children(node, before, options); end
  def diff_with_before(node, before, options); end

  # @return [Boolean]
  def doesnt_have_natural_keys?(node); end

  # @return [Boolean]
  def has_natural_keys?(node); end

  # @return [Boolean]
  def has_same_content_as?(node, other_node); end

  # tri:state: true, false, nil
  #
  # @return [Boolean]
  def have_comparable_children?(node, other_node); end

  # tri:state: true, false, nil
  #
  # @return [Boolean]
  def have_comparable_text?(node, other_node); end

  # tri:state: true, false, nil
  #
  # @return [Boolean]
  def have_same_identification?(node, other_node); end

  # @return [Boolean]
  def is_a_simple_text_container?(node); end

  # @return [Boolean]
  def is_comparable_text?(text, other_text); end

  # @return [Boolean]
  def is_compatible_with?(node, other_node); end

  # not meant to be polymorphic through proxies, but maybe that should change?
  #
  # @return [Boolean]
  def is_dominated_by_text?(node); end

  # @return [Boolean]
  def is_textlike?(node); end

  # @return [Boolean]
  def is_uncomplicated?(node); end

  def natural_attrs(node); end
  def natural_keys(node); end

  # @return [Boolean]
  def other_changed?(node); end

  def private_attrs(node); end
  def replace_children(node, nkotb); end
  def set_analysis(node, something); end
  def set_before(after_node, before_node); end
  def significant(options, array_of_attrs); end
  def split(node); end

  # returns the split children as a list
  def split_children(node); end

  def text_differences_metric(list_a, list_b); end
  def text_hash(node); end
  def unsplit(node, other_node); end
  def unsplit_all(args_or_set, additional = T.unsafe(nil)); end

  # @return [Boolean]
  def valid?(node); end

  # @return [Boolean]
  def valid_and_compatible?(node, other_node); end

  # @return [Boolean]
  def was_added?(node); end

  # @return [Boolean]
  def was_changed?(node); end

  # @return [Boolean]
  def was_moved?(node); end

  # @return [Boolean]
  def was_removed?(node); end

  # @return [Boolean]
  def was_unchanged?(node); end

  def wordz(node); end

  private

  def unsplit_nodeset(nodeset); end
end

ProseDiff::Node::Proxy::BaseBehaviour::DOMINATION_THRESHOLD = T.let(T.unsafe(nil), Float)
ProseDiff::Node::Proxy::BaseBehaviour::EMPTY_TEXT_HASH = T.let(T.unsafe(nil), String)
ProseDiff::Node::Proxy::BaseBehaviour::NODE_CLOSENESS_THRESHOLD = T.let(T.unsafe(nil), Float)

# code smell: couldn't figure out setting a namespaced attribute
class ProseDiff::Node::Proxy::BaseBehaviour::NamespacedAttributeProxy
  # @return [NamespacedAttributeProxy] a new instance of NamespacedAttributeProxy
  def initialize(node); end

  def [](attr); end
  def []=(attr, value); end
  def to_hash; end
  def values; end
end

ProseDiff::Node::Proxy::BaseBehaviour::TEXT_DIFFERENCE_THRESHOLD = T.let(T.unsafe(nil), Float)

class ProseDiff::Node::Proxy::Block
  include ::ProseDiff::Node::Proxy::BaseBehaviour
end

class ProseDiff::Node::Proxy::Blockquote
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::SimpleTextContainerBehaviour
  include ::ProseDiff::Node::Proxy::LevenshteinDistanceBehaviour

  # @return [Boolean]
  def have_comparable_text?(node, other_node); end

  # @return [Boolean]
  def is_compatible_with?(node, other_node); end
end

class ProseDiff::Node::Proxy::Body
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::SuperBlockBehaviour
end

class ProseDiff::Node::Proxy::Br < ::ProseDiff::Node::Proxy::Block; end

module ProseDiff::Node::Proxy::CanOnlyCorrespondToTheSameTagBehaviour
  # @return [Boolean]
  def is_compatible_with?(node, other_node); end
end

class ProseDiff::Node::Proxy::Caption
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::CanOnlyCorrespondToTheSameTagBehaviour

  # @return [Boolean]
  def appear_to_correspond?(node, other_node); end
end

class ProseDiff::Node::Proxy::Code
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::UnsplittableBehaviour

  # @return [Boolean]
  def appear_to_correspond?(node, other_node); end
end

class ProseDiff::Node::Proxy::Dd
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::CanOnlyCorrespondToTheSameTagBehaviour
  include ::ProseDiff::Node::Proxy::LevenshteinDistanceBehaviour
end

class ProseDiff::Node::Proxy::Del
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::SplitsChildrenAndSelfBehaviour

  def analysis(node); end
end

class ProseDiff::Node::Proxy::Div
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::CanOnlyCorrespondToTheSameTagBehaviour
  include ::ProseDiff::Node::Proxy::LevenshteinDistanceBehaviour

  # @return [Boolean]
  def have_comparable_text?(node, other_node); end
end

class ProseDiff::Node::Proxy::Dl
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::CanOnlyCorrespondToTheSameTagBehaviour

  # TODO: valid should check whether all elements are
  def diff_children(node, before, options); end

  # Two DLs are comparable if the text of their dts are comparable. dds don't count
  #
  # @return [Boolean]
  def have_comparable_text?(node, other_node); end

  private

  def chunk(node); end
end

class ProseDiff::Node::Proxy::Dt
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::CanOnlyCorrespondToTheSameTagBehaviour
  include ::ProseDiff::Node::Proxy::SimpleTextContainerBehaviour
  include ::ProseDiff::Node::Proxy::LevenshteinDistanceBehaviour
end

class ProseDiff::Node::Proxy::Em
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::SimpleTextContainerBehaviour
  include ::ProseDiff::Node::Proxy::LevenshteinDistanceBehaviour

  # @return [Boolean]
  def have_comparable_text?(node, other_node); end
end

class ProseDiff::Node::Proxy::Fixed < ::ProseDiff::Node::Proxy::Inline; end

class ProseDiff::Node::Proxy::H
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::LevenshteinDistanceBehaviour

  # @return [Boolean]
  def have_comparable_text?(node, other_node); end

  # @return [Boolean]
  def is_compatible_with?(node, other_node); end
end

class ProseDiff::Node::Proxy::H1 < ::ProseDiff::Node::Proxy::H; end
class ProseDiff::Node::Proxy::H2 < ::ProseDiff::Node::Proxy::H; end
class ProseDiff::Node::Proxy::H3 < ::ProseDiff::Node::Proxy::H; end
class ProseDiff::Node::Proxy::H4 < ::ProseDiff::Node::Proxy::H; end
class ProseDiff::Node::Proxy::H5 < ::ProseDiff::Node::Proxy::H; end
class ProseDiff::Node::Proxy::H6 < ::ProseDiff::Node::Proxy::H; end
class ProseDiff::Node::Proxy::Hr < ::ProseDiff::Node::Proxy::Block; end
class ProseDiff::Node::Proxy::I < ::ProseDiff::Node::Proxy::Inline; end

class ProseDiff::Node::Proxy::Img
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::CanOnlyCorrespondToTheSameTagBehaviour
  include ::ProseDiff::Node::Proxy::UnsplittableBehaviour

  # @return [Boolean]
  def appear_to_correspond?(node, other_node); end

  # @return [Boolean]
  def has_same_content_as?(node, other_node); end
end

class ProseDiff::Node::Proxy::Inline
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::SplitsChildrenAndSelfBehaviour
end

class ProseDiff::Node::Proxy::Input
  include ::ProseDiff::Node::Proxy::BaseBehaviour

  def appear_to_correspond(input, other_node); end
  def significant(options, array_of_attrs); end

  # @return [Boolean]
  def valid?(input); end
end

class ProseDiff::Node::Proxy::Ins
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::SplitsChildrenAndSelfBehaviour

  def analysis(node); end
end

module ProseDiff::Node::Proxy::LevenshteinDistanceBehaviour
  private

  # @return [Boolean]
  def is_comparable_text?(node, other_node, threshold = T.unsafe(nil)); end

  class << self
    # @return [Boolean]
    def is_comparable_text?(node, other_node, threshold = T.unsafe(nil)); end
  end
end

ProseDiff::Node::Proxy::LevenshteinDistanceBehaviour::TEXT_DIFFERENCE_THRESHOLD = T.let(T.unsafe(nil), Float)

class ProseDiff::Node::Proxy::Li
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::CanOnlyCorrespondToTheSameTagBehaviour
  include ::ProseDiff::Node::Proxy::LevenshteinDistanceBehaviour

  # @return [Boolean]
  def is_comparable_text?(node, other_node); end

  class << self
    def significant_text(li); end
  end
end

ProseDiff::Node::Proxy::Li::LIST_ITEM_DIFFERENCE_THRESHOLD = T.let(T.unsafe(nil), Float)

class ProseDiff::Node::Proxy::Line
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::UnsplittableBehaviour

  # @return [Boolean]
  def appear_to_correspond?(opaque, other_node); end
end

module ProseDiff::Node::Proxy::ListBehaviour
  # @return [Boolean]
  def appear_to_correspond?(node, other_node); end

  def diff_children(node, before, options); end
  def digest(li); end
  def digests(node); end
  def doppelganger(node); end

  # @return [Boolean]
  def have_comparable_children?(node, other_node); end

  # @return [Boolean]
  def have_comparable_text?(node, other_node); end

  def number_that_correspond(a_significants, b_significants); end
  def number_that_match_exactly(a_digests, b_digests); end
  def preanalyze_moves(node_children, before_children); end
  def significants(node); end
  def transform_children(children, options); end
end

ProseDiff::Node::Proxy::ListBehaviour::HAS_DOPPEL = T.let(T.unsafe(nil), String)

class ProseDiff::Node::Proxy::Ol
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::ListBehaviour
  include ::ProseDiff::Node::Proxy::CanOnlyCorrespondToTheSameTagBehaviour
  include ::ProseDiff::Node::Proxy::LevenshteinDistanceBehaviour

  def children_of(node); end
  def diff_children(node, before, options); end

  private

  def numbered_children_of(ol); end
end

class ProseDiff::Node::Proxy::Opaque
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::UnsplittableBehaviour

  # @return [Boolean]
  def appear_to_correspond?(opaque, other_node); end

  # @return [Boolean]
  def valid?(opaque); end
end

class ProseDiff::Node::Proxy::P
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::SimpleTextContainerBehaviour
  include ::ProseDiff::Node::Proxy::LevenshteinDistanceBehaviour

  # @return [Boolean]
  def have_comparable_text?(node, other_node); end

  # @return [Boolean]
  def is_compatible_with?(node, other_node); end
end

class ProseDiff::Node::Proxy::Pre
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::UnsplittableBehaviour
  include ::ProseDiff::Node::Proxy::CanOnlyCorrespondToTheSameTagBehaviour
  include ::ProseDiff::Node::Proxy::LevenshteinDistanceBehaviour

  # @return [Boolean]
  def appear_to_correspond?(node, other_node); end

  def diff_children(node, before, options); end

  private

  def split_children_helper(node); end
  def to_be_split(node); end
end

ProseDiff::Node::Proxy::Pre::HTML_TO_USE_REGEX = T.let(T.unsafe(nil), Regexp)
ProseDiff::Node::Proxy::Pre::SAME_TEXT = T.let(T.unsafe(nil), Proc)
class ProseDiff::Node::Proxy::Section < ::ProseDiff::Node::Proxy::Block; end

module ProseDiff::Node::Proxy::SimpleTextContainerBehaviour
  def diff_children(node, before, options); end

  private

  # slow :-()
  def children_diff(node, common_prefix, node_children, before_children, common_suffix, options); end

  # fastest
  def chunk_diff(node, common_prefix, node_children, before_children, common_suffix, options); end

  def fast_split_children(children); end

  # @return [Boolean]
  def is_a_simple_text_container?(node); end

  def strip_prefixes(outer_prefix, node_children, before_children, outer_suffix); end

  # fast
  def text_diff(node, common_prefix, node_child, before_child, common_suffix, options); end

  class << self
    # @return [Boolean]
    def is_a_simple_text_container?(node); end
  end
end

ProseDiff::Node::Proxy::SimpleTextContainerBehaviour::CHUNKING_THRESHOLD = T.let(T.unsafe(nil), Float)
ProseDiff::Node::Proxy::SimpleTextContainerBehaviour::WORD_DIFFER = T.let(T.unsafe(nil), Proc)

class ProseDiff::Node::Proxy::Span
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::SplitsChildrenAndSelfBehaviour
  include ::ProseDiff::Node::Proxy::SpanBehaviour

  # @return [Boolean]
  def is_textlike?(node); end

  def unsplit(node, other_node); end
end

module ProseDiff::Node::Proxy::SpanBehaviour
  # @return [Boolean]
  def appear_to_correspond?(node, other_node); end

  # @return [Boolean]
  def is_textlike?(node); end

  def unsplit(node, other_node); end
end

module ProseDiff::Node::Proxy::SplitsChildrenAndSelfBehaviour
  def split(node); end

  private

  def unsplit(node, other_node); end

  class << self
    def unsplit(node, other_node); end
  end
end

class ProseDiff::Node::Proxy::Strike < ::ProseDiff::Node::Proxy::Inline; end

class ProseDiff::Node::Proxy::Strong
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::SimpleTextContainerBehaviour
  include ::ProseDiff::Node::Proxy::LevenshteinDistanceBehaviour

  # @return [Boolean]
  def have_comparable_text?(node, other_node); end
end

module ProseDiff::Node::Proxy::SuperBlockBehaviour
  # @return [Boolean]
  def appear_to_correspond?(node, other_node); end

  def split_children(node); end
end

class ProseDiff::Node::Proxy::Table
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::CanOnlyCorrespondToTheSameTagBehaviour

  def diff_children(node, before, options); end

  # @return [Boolean]
  def have_comparable_children?(node, other_node); end

  # @return [Boolean]
  def have_comparable_text?(node, other_node); end

  # FIXME: Document the GFM assumptions, including
  #        * Every column has a TH
  #        * No colspans or colgroups
  #        * at least one row
  #
  # @return [Boolean]
  def valid?(node); end

  private

  def assign_rows_and_columns(node, before, options); end
  def clean_up(node, options); end

  # FIXME: Test adding and removing captions
  def diff_captions(node, before, options); end

  def inner_valid(node); end
  def own_rows(node); end
  def own_ths(node); end
  def sanitize_rows(node, before); end
end

class ProseDiff::Node::Proxy::Td
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::CanOnlyCorrespondToTheSameTagBehaviour

  # @return [Boolean]
  def appear_to_correspond?(node, other_node); end
end

class ProseDiff::Node::Proxy::Text
  include ::ProseDiff::Node::Proxy::BaseBehaviour

  def analysis(node); end

  # text never compares children
  #
  # @return [Boolean]
  def appear_to_correspond?(node, other_node); end

  def before(node); end

  # @return [Boolean]
  def has_same_content_as?(node, other_node); end

  # @return [Boolean]
  def is_uncomplicated?(node); end

  # @return [Boolean]
  def other_changed?(node); end

  def private_attrs(node); end

  # see http://stackoverflow.com/questions/7724135/ruby-string-split-on-more-than-one-character
  def split(node); end

  def text(node); end
  def unsplit(node, other_node); end

  # @return [Boolean]
  def was_added?(node); end

  # @return [Boolean]
  def was_changed?(node); end

  # @return [Boolean]
  def was_moved?(node); end

  # @return [Boolean]
  def was_removed?(node); end

  # @return [Boolean]
  def was_unchanged?(node); end
end

ProseDiff::Node::Proxy::Text::WHITESPACE = T.let(T.unsafe(nil), Regexp)

class ProseDiff::Node::Proxy::Tr
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::CanOnlyCorrespondToTheSameTagBehaviour

  # @return [Boolean]
  def appear_to_correspond?(node, other_node); end
end

class ProseDiff::Node::Proxy::Tt < ::ProseDiff::Node::Proxy::Inline; end
class ProseDiff::Node::Proxy::U < ::ProseDiff::Node::Proxy::Inline; end

class ProseDiff::Node::Proxy::Ul
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::ListBehaviour
  include ::ProseDiff::Node::Proxy::CanOnlyCorrespondToTheSameTagBehaviour
  include ::ProseDiff::Node::Proxy::LevenshteinDistanceBehaviour

  def children_of(node); end
end

module ProseDiff::Node::Proxy::UnsplittableBehaviour
  def diff_children(node, before, options); end
  def split(the_atom); end
end

class ProseDiff::Node::Proxy::Unword
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::SpanBehaviour
  include ::ProseDiff::Node::Proxy::UnsplittableBehaviour

  # @return [Boolean]
  def appear_to_correspond?(node, other_node); end

  def diff_with_before(node, before, options); end

  # @return [Boolean]
  def has_same_content_as?(node, other_node); end

  # @return [Boolean]
  def is_compatible_with?(node, other_node); end
end

class ProseDiff::Node::Proxy::Word
  include ::ProseDiff::Node::Proxy::BaseBehaviour
  include ::ProseDiff::Node::Proxy::SpanBehaviour
  include ::ProseDiff::Node::Proxy::UnsplittableBehaviour

  # @return [Boolean]
  def appear_to_correspond?(node, other_node); end

  # @return [Boolean]
  def is_compatible_with?(node, other_node); end
end

ProseDiff::Node::RE = T.let(T.unsafe(nil), Regexp)
ProseDiff::Node::SPANLIKE = T.let(T.unsafe(nil), Array)
ProseDiff::Node::SPANS = T.let(T.unsafe(nil), Array)
ProseDiff::Node::TOPLEVEL = T.let(T.unsafe(nil), Array)
ProseDiff::Node::WHITELISTED = T.let(T.unsafe(nil), Array)

module ProseDiff::Node::WordSplitting
  private

  # see http://stackoverflow.com/questions/7724135/ruby-string-split-on-more-than-one-character
  def split_by_word(full_text); end

  # @return [Boolean]
  def word?(fragment); end

  class << self
    # see http://stackoverflow.com/questions/7724135/ruby-string-split-on-more-than-one-character
    def split_by_word(full_text); end

    # @return [Boolean]
    def word?(fragment); end
  end
end

ProseDiff::Node::WordSplitting::LEADING_NONWORD_CHARACTERS = T.let(T.unsafe(nil), Regexp)
ProseDiff::Node::WordSplitting::LEADING_OPTIONAL_NONWORD_CHARACTERS = T.let(T.unsafe(nil), Regexp)
ProseDiff::Node::WordSplitting::LEADING_OPTIONAL_WORD_CHARACTERS = T.let(T.unsafe(nil), Regexp)
ProseDiff::Node::WordSplitting::LEADING_WORD_AND_FOLLOWING_NONWORD_CHARACTERS = T.let(T.unsafe(nil), Regexp)
ProseDiff::Node::WordSplitting::LEADING_WORD_CHARACTERS = T.let(T.unsafe(nil), Regexp)
ProseDiff::Node::WordSplitting::WORD = T.let(T.unsafe(nil), Regexp)
ProseDiff::OPTIONS = T.let(T.unsafe(nil), Hash)

module ProseDiff::Transformer
  private

  def transform_document(selector, value, options = T.unsafe(nil)); end
  def transform_nodes(selector, nodes, options = T.unsafe(nil)); end

  class << self
    # @return [Boolean]
    def analysis_is?(node, value, *names); end

    def computed_list(options); end
    def symbol(clazz); end
    def transform_document(selector, value, options = T.unsafe(nil)); end
    def transform_nodes(selector, nodes, options = T.unsafe(nil)); end
    def underscore(string); end
    def where_analysis_is(value, *names); end
    def where_name_is(*names); end
  end
end

class ProseDiff::Transformer::AllRedundantDivs < ::ProseDiff::Transformer::Base
  def transform_document(document); end
end

class ProseDiff::Transformer::Base
  # @return [Base] a new instance of Base
  def initialize(options = T.unsafe(nil)); end

  def add_class(node, *new_clazzes); end
  def default_options; end

  # evaluate an option as a predicate
  #
  # @return [Boolean]
  def option?(key); end

  # Returns the value of attribute options.
  def options; end

  def split_keys(options); end
  def transform_nodes(node_enumerable); end
end

ProseDiff::Transformer::Base::ANALYSES = T.let(T.unsafe(nil), Array)

class ProseDiff::Transformer::ChangedClasses < ::ProseDiff::Transformer::Base
  def default_options; end
  def query(*names); end
  def transform_document(document); end
end

ProseDiff::Transformer::ChangedClasses::DONT_WRAP = T.let(T.unsafe(nil), Array)

class ProseDiff::Transformer::ChangedNode < ::ProseDiff::Transformer::Base
  def transform_node(after); end
end

# run after wrap!
class ProseDiff::Transformer::CheckBoxes < ::ProseDiff::Transformer::Base
  def transform_document(document); end
end

class ProseDiff::Transformer::ChunkEdits < ::ProseDiff::Transformer::Base
  # FIXME: These should be configurable
  def transform_nodes(nodes); end
end

ProseDiff::Transformer::ChunkEdits::CHUNKABLES = T.let(T.unsafe(nil), Array)

class ProseDiff::Transformer::ChunkEdits::ChunkParser
  # @return [ChunkParser] a new instance of ChunkParser
  def initialize(nodes, separatable_node_names); end

  def amalgamate_separators; end
  def extract_trailing_separators; end
  def last_added_to_accepted; end
  def last_added_to_last_added; end
  def last_added_to_last_removed; end

  # last_added_to_*
  def last_added_to_ready; end

  def last_added_to_separator; end
  def last_removed_to_accepted; end
  def last_removed_to_last_added; end
  def last_removed_to_last_removed; end

  # last_removed_to_*
  def last_removed_to_ready; end

  def last_removed_to_separator; end
  def ready_to_accepted; end
  def ready_to_last_added; end
  def ready_to_last_removed; end

  # ready_to_*
  def ready_to_ready; end

  def ready_to_separator; end
  def separator_to_accepted; end
  def separator_to_last_added; end
  def separator_to_last_removed; end

  # separator_to_*
  def separator_to_ready; end

  def separator_to_separator; end
  def set_next_state; end
  def transform; end
  def update_nodes; end
end

class ProseDiff::Transformer::Css < ::ProseDiff::Transformer::Base
  def default_options; end
  def transform_document(document); end
end

class ProseDiff::Transformer::Expandables < ::ProseDiff::Transformer::Base
  def default_options; end

  # MUST follow vicinity
  def transform_document(document); end
end

class ProseDiff::Transformer::Moved < ::ProseDiff::Transformer::Base
  def digest(node); end
  def transform_children(*elements); end

  # Only wired to top-level at this time.
  def transform_document(document); end
end

class ProseDiff::Transformer::PropagateChanged < ::ProseDiff::Transformer::Base
  def transform_document(document); end
end

ProseDiff::Transformer::PropagateChanged::FIXED = T.let(T.unsafe(nil), Proc)

class ProseDiff::Transformer::RedundantSpan < ::ProseDiff::Transformer::Base
  def transform_node(node); end
end

class ProseDiff::Transformer::Replace < ::ProseDiff::Transformer::Base
  def default_options; end
  def transform_document(document); end
end

class ProseDiff::Transformer::SimpleTextDiff < ::ProseDiff::Transformer::Base
  def transform_nodes(nodes); end
end

class ProseDiff::Transformer::SortClasses < ::ProseDiff::Transformer::Base
  def default_options; end
  def transform_document(document); end
end

class ProseDiff::Transformer::StripPrivateDataAttributes < ::ProseDiff::Transformer::Base
  def default_options; end
  def transform_document(document); end
end

ProseDiff::Transformer::TRANSFORMERS = T.let(T.unsafe(nil), Hash)

class ProseDiff::Transformer::Vicinity < ::ProseDiff::Transformer::Base
  def default_options; end
  def isHeading(node); end
  def transform_document(document); end

  private

  def arrayize(str_or_arr); end
  def where_parented_by_and_analyses_are(parented_by, analyses, *names); end
end

class ProseDiff::Transformer::WhitespaceAgnostic < ::ProseDiff::Transformer::Base
  def default_options; end
  def transform_document(document); end

  class << self
    def clean(str); end
  end
end

class ProseDiff::Transformer::Wrap < ::ProseDiff::Transformer::Base
  def default_options; end
  def transform_document(document); end
end

ProseDiff::Transformer::Wrap::DONT_WRAP = T.let(T.unsafe(nil), Array)
