# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GitHub::Spokes::Proto::Objects::V1::Object`.
# Please instead update this file by running `bin/tapioca dsl GitHub::Spokes::Proto::Objects::V1::Object`.


class GitHub::Spokes::Proto::Objects::V1::Object < Google::Protobuf::AbstractMessage
  sig do
    params(
      blob_object: T.nilable(GitHub::Spokes::Proto::Objects::V1::BlobObject),
      commit_object: T.nilable(GitHub::Spokes::Proto::Objects::V1::CommitObject),
      error_object: T.nilable(GitHub::Spokes::Proto::Objects::V1::ErrorObject),
      object: T.nilable(GitHub::Spokes::Proto::Types::V1::Object),
      tag_object: T.nilable(GitHub::Spokes::Proto::Objects::V1::TagObject),
      tree_object: T.nilable(GitHub::Spokes::Proto::Objects::V1::TreeObject),
      truncated: T.nilable(T::Boolean)
    ).void
  end
  def initialize(blob_object: nil, commit_object: nil, error_object: nil, object: nil, tag_object: nil, tree_object: nil, truncated: nil); end

  sig { returns(T.nilable(GitHub::Spokes::Proto::Objects::V1::BlobObject)) }
  def blob_object; end

  sig { params(value: T.nilable(GitHub::Spokes::Proto::Objects::V1::BlobObject)).void }
  def blob_object=(value); end

  sig { void }
  def clear_blob_object; end

  sig { void }
  def clear_commit_object; end

  sig { void }
  def clear_error_object; end

  sig { void }
  def clear_object; end

  sig { void }
  def clear_tag_object; end

  sig { void }
  def clear_tree_object; end

  sig { void }
  def clear_truncated; end

  sig { returns(T.nilable(GitHub::Spokes::Proto::Objects::V1::CommitObject)) }
  def commit_object; end

  sig { params(value: T.nilable(GitHub::Spokes::Proto::Objects::V1::CommitObject)).void }
  def commit_object=(value); end

  sig { returns(T.nilable(Symbol)) }
  def entity; end

  sig { returns(T.nilable(GitHub::Spokes::Proto::Objects::V1::ErrorObject)) }
  def error_object; end

  sig { params(value: T.nilable(GitHub::Spokes::Proto::Objects::V1::ErrorObject)).void }
  def error_object=(value); end

  sig { returns(Object) }
  def has_object?; end

  sig { returns(T.nilable(GitHub::Spokes::Proto::Types::V1::Object)) }
  def object; end

  sig { params(value: T.nilable(GitHub::Spokes::Proto::Types::V1::Object)).void }
  def object=(value); end

  sig { returns(T.nilable(GitHub::Spokes::Proto::Objects::V1::TagObject)) }
  def tag_object; end

  sig { params(value: T.nilable(GitHub::Spokes::Proto::Objects::V1::TagObject)).void }
  def tag_object=(value); end

  sig { returns(T.nilable(GitHub::Spokes::Proto::Objects::V1::TreeObject)) }
  def tree_object; end

  sig { params(value: T.nilable(GitHub::Spokes::Proto::Objects::V1::TreeObject)).void }
  def tree_object=(value); end

  sig { returns(T::Boolean) }
  def truncated; end

  sig { params(value: T::Boolean).void }
  def truncated=(value); end
end
