# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Api::Internal::GitHubModels::Access`.
# Please instead update this file by running `bin/tapioca dsl Api::Internal::GitHubModels::Access`.


class Api::Internal::GitHubModels::Access
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
