# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/pages_dfs/v1/entities/opt_bool.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.pages_dfs.v1.entities.OptBool" do
    optional :value, :bool, 1
  end
end

module Hydro
  module Schemas
    module PagesDfs
      module V1
        module Entities
          OptBool = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.pages_dfs.v1.entities.OptBool").msgclass
        end
      end
    end
  end
end
