# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/github/ip_allow_list/v0/enable.proto

require 'google/protobuf'

require 'hydro/schemas/github/v1/entities/user_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.github.ip_allow_list.v0.EnableAppAccess" do
    optional :owner_type, :enum, 1, "hydro.schemas.github.ip_allow_list.v0.EnableAppAccess.Type"
    optional :owner_id, :uint64, 2
    optional :actor, :message, 3, "hydro.schemas.github.v1.entities.User"
  end
  add_enum "hydro.schemas.github.ip_allow_list.v0.EnableAppAccess.Type" do
    value :ORG, 0
    value :BUSINESS, 1
  end
end

module Hydro
  module Schemas
    module Github
      module IpAllowList
        module V0
          EnableAppAccess = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.ip_allow_list.v0.EnableAppAccess").msgclass
          EnableAppAccess::Type = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.ip_allow_list.v0.EnableAppAccess.Type").enummodule
        end
      end
    end
  end
end
