# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ConditionalPullRequestStateFilterJob`.
# Please instead update this file by running `bin/tapioca dsl ConditionalPullRequestStateFilterJob`.


class ConditionalPullRequestStateFilterJob
  class << self
    sig do
      params(
        ids: T.untyped,
        states: T.untyped,
        block: T.nilable(T.proc.params(job: ConditionalPullRequestStateFilterJob).void)
      ).returns(T.any(ConditionalPullRequestStateFilterJob, FalseClass))
    end
    def perform_later(ids:, states:, &block); end

    sig { params(ids: T.untyped, states: T.untyped).returns(T.untyped) }
    def perform_now(ids:, states:); end
  end
end
