# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `DestroyAuthenticationTokensJob`.
# Please instead update this file by running `bin/tapioca dsl DestroyAuthenticationTokensJob`.


class DestroyAuthenticationTokensJob
  class << self
    sig do
      params(
        authenticatable_id: ::Integer,
        authenticatable_class: T.nilable(::String),
        block: T.nilable(T.proc.params(job: DestroyAuthenticationTokensJob).void)
      ).returns(T.any(DestroyAuthenticationTokensJob, FalseClass))
    end
    def perform_later(authenticatable_id, authenticatable_class, &block); end

    sig { params(authenticatable_id: ::Integer, authenticatable_class: T.nilable(::String)).void }
    def perform_now(authenticatable_id, authenticatable_class); end
  end
end
