# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GlobalNotices`.
# Please instead update this file by running `bin/tapioca dsl GlobalNotices`.


module GlobalNotices
  extend GeneratedDomainRegistrationMethods

  module GeneratedDomainRegistrationMethods
    sig { returns(GlobalNotices::Domain) }
    def domain; end
  end
end
