# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RepositoryUnlock`.
# Please instead update this file by running `bin/tapioca dsl RepositoryUnlock`.


class RepositoryUnlock
  include GeneratedAsyncReflectionAssociations
  include GeneratedPreludeBatchMethods
  include GeneratedAssociationMethods
  include GeneratedAttributeMethods
  extend CommonRelationMethods
  extend GeneratedRelationMethods
  include GeneratedEntityReferenceMethods

  private

  sig { returns(NilClass) }
  def to_ary; end

  class << self
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::RepositoryUnlock).void)
      ).returns(::RepositoryUnlock)
    end
    def new(attributes = nil, &block); end
  end

  module CommonRelationMethods
    sig { params(block: T.nilable(T.proc.params(record: ::RepositoryUnlock).returns(T.untyped))).returns(T::Boolean) }
    def any?(&block); end

    sig { params(column_name: T.any(String, Symbol)).returns(T.any(Integer, Float, BigDecimal)) }
    def average(column_name); end

    sig { params(block: T.nilable(T.proc.params(object: ::RepositoryUnlock).void)).returns(::RepositoryUnlock) }
    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::RepositoryUnlock).void)
      ).returns(T::Array[::RepositoryUnlock])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::RepositoryUnlock).void)
      ).returns(::RepositoryUnlock)
    end
    def build(attributes = nil, &block); end

    sig { params(operation: Symbol, column_name: T.any(String, Symbol)).returns(T.any(Integer, Float, BigDecimal)) }
    def calculate(operation, column_name); end

    sig { params(column_name: T.nilable(T.any(String, Symbol))).returns(Integer) }
    sig { params(column_name: NilClass, block: T.proc.params(object: ::RepositoryUnlock).void).returns(Integer) }
    def count(column_name = nil, &block); end

    sig { params(block: T.nilable(T.proc.params(object: ::RepositoryUnlock).void)).returns(::RepositoryUnlock) }
    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::RepositoryUnlock).void)
      ).returns(T::Array[::RepositoryUnlock])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::RepositoryUnlock).void)
      ).returns(::RepositoryUnlock)
    end
    def create(attributes = nil, &block); end

    sig { params(block: T.nilable(T.proc.params(object: ::RepositoryUnlock).void)).returns(::RepositoryUnlock) }
    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::RepositoryUnlock).void)
      ).returns(T::Array[::RepositoryUnlock])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::RepositoryUnlock).void)
      ).returns(::RepositoryUnlock)
    end
    def create!(attributes = nil, &block); end

    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::RepositoryUnlock).void)
      ).returns(T::Array[::RepositoryUnlock])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::RepositoryUnlock).void)
      ).returns(::RepositoryUnlock)
    end
    def create_or_find_by(attributes, &block); end

    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::RepositoryUnlock).void)
      ).returns(T::Array[::RepositoryUnlock])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::RepositoryUnlock).void)
      ).returns(::RepositoryUnlock)
    end
    def create_or_find_by!(attributes, &block); end

    sig { returns(T::Array[::RepositoryUnlock]) }
    def destroy_all; end

    sig { params(conditions: T.untyped).returns(T::Boolean) }
    def exists?(conditions = :none); end

    sig { returns(T.nilable(::RepositoryUnlock)) }
    def fifth; end

    sig { returns(::RepositoryUnlock) }
    def fifth!; end

    sig do
      params(
        args: T.any(String, Symbol, ::ActiveSupport::Multibyte::Chars, T::Boolean, BigDecimal, Numeric, ::ActiveRecord::Type::Binary::Data, ::ActiveRecord::Type::Time::Value, Date, Time, ::ActiveSupport::Duration, T::Class[T.anything])
      ).returns(::RepositoryUnlock)
    end
    sig do
      params(
        args: T::Array[T.any(String, Symbol, ::ActiveSupport::Multibyte::Chars, T::Boolean, BigDecimal, Numeric, ::ActiveRecord::Type::Binary::Data, ::ActiveRecord::Type::Time::Value, Date, Time, ::ActiveSupport::Duration, T::Class[T.anything])]
      ).returns(T::Enumerable[::RepositoryUnlock])
    end
    sig do
      params(
        args: NilClass,
        block: T.proc.params(object: ::RepositoryUnlock).void
      ).returns(T.nilable(::RepositoryUnlock))
    end
    def find(args = nil, &block); end

    sig { params(args: T.untyped).returns(T.nilable(::RepositoryUnlock)) }
    def find_by(*args); end

    sig { params(args: T.untyped).returns(::RepositoryUnlock) }
    def find_by!(*args); end

    sig do
      params(
        start: T.untyped,
        finish: T.untyped,
        batch_size: Integer,
        error_on_ignore: T.untyped,
        order: Symbol,
        block: T.proc.params(object: ::RepositoryUnlock).void
      ).void
    end
    sig do
      params(
        start: T.untyped,
        finish: T.untyped,
        batch_size: Integer,
        error_on_ignore: T.untyped,
        order: Symbol
      ).returns(T::Enumerator[::RepositoryUnlock])
    end
    def find_each(start: nil, finish: nil, batch_size: 1000, error_on_ignore: nil, order: :asc, &block); end

    sig do
      params(
        start: T.untyped,
        finish: T.untyped,
        batch_size: Integer,
        error_on_ignore: T.untyped,
        order: Symbol,
        block: T.proc.params(object: T::Array[::RepositoryUnlock]).void
      ).void
    end
    sig do
      params(
        start: T.untyped,
        finish: T.untyped,
        batch_size: Integer,
        error_on_ignore: T.untyped,
        order: Symbol
      ).returns(T::Enumerator[T::Enumerator[::RepositoryUnlock]])
    end
    def find_in_batches(start: nil, finish: nil, batch_size: 1000, error_on_ignore: nil, order: :asc, &block); end

    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::RepositoryUnlock).void)
      ).returns(T::Array[::RepositoryUnlock])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::RepositoryUnlock).void)
      ).returns(::RepositoryUnlock)
    end
    def find_or_create_by(attributes, &block); end

    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::RepositoryUnlock).void)
      ).returns(T::Array[::RepositoryUnlock])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::RepositoryUnlock).void)
      ).returns(::RepositoryUnlock)
    end
    def find_or_create_by!(attributes, &block); end

    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::RepositoryUnlock).void)
      ).returns(T::Array[::RepositoryUnlock])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::RepositoryUnlock).void)
      ).returns(::RepositoryUnlock)
    end
    def find_or_initialize_by(attributes, &block); end

    sig { params(signed_id: T.untyped, purpose: T.untyped).returns(T.nilable(::RepositoryUnlock)) }
    def find_signed(signed_id, purpose: nil); end

    sig { params(signed_id: T.untyped, purpose: T.untyped).returns(::RepositoryUnlock) }
    def find_signed!(signed_id, purpose: nil); end

    sig { params(arg: T.untyped, args: T.untyped).returns(::RepositoryUnlock) }
    def find_sole_by(arg, *args); end

    sig { returns(T.nilable(::RepositoryUnlock)) }
    sig { params(limit: Integer).returns(T::Array[::RepositoryUnlock]) }
    def first(limit = nil); end

    sig { returns(::RepositoryUnlock) }
    def first!; end

    sig { returns(T.nilable(::RepositoryUnlock)) }
    def forty_two; end

    sig { returns(::RepositoryUnlock) }
    def forty_two!; end

    sig { returns(T.nilable(::RepositoryUnlock)) }
    def fourth; end

    sig { returns(::RepositoryUnlock) }
    def fourth!; end

    sig { returns(Array) }
    def ids; end

    sig do
      params(
        of: Integer,
        start: T.untyped,
        finish: T.untyped,
        load: T.untyped,
        error_on_ignore: T.untyped,
        order: Symbol,
        use_ranges: T.untyped,
        block: T.proc.params(object: PrivateRelation).void
      ).void
    end
    sig do
      params(
        of: Integer,
        start: T.untyped,
        finish: T.untyped,
        load: T.untyped,
        error_on_ignore: T.untyped,
        order: Symbol,
        use_ranges: T.untyped
      ).returns(::ActiveRecord::Batches::BatchEnumerator)
    end
    def in_batches(of: 1000, start: nil, finish: nil, load: false, error_on_ignore: nil, order: :asc, use_ranges: nil, &block); end

    sig { params(record: T.untyped).returns(T::Boolean) }
    def include?(record); end

    sig { returns(T.nilable(::RepositoryUnlock)) }
    sig { params(limit: Integer).returns(T::Array[::RepositoryUnlock]) }
    def last(limit = nil); end

    sig { returns(::RepositoryUnlock) }
    def last!; end

    sig { params(block: T.nilable(T.proc.params(record: ::RepositoryUnlock).returns(T.untyped))).returns(T::Boolean) }
    def many?(&block); end

    sig { params(column_name: T.any(String, Symbol)).returns(T.untyped) }
    def maximum(column_name); end

    sig { params(record: T.untyped).returns(T::Boolean) }
    def member?(record); end

    sig { params(column_name: T.any(String, Symbol)).returns(T.untyped) }
    def minimum(column_name); end

    sig { params(block: T.nilable(T.proc.params(object: ::RepositoryUnlock).void)).returns(::RepositoryUnlock) }
    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::RepositoryUnlock).void)
      ).returns(T::Array[::RepositoryUnlock])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::RepositoryUnlock).void)
      ).returns(::RepositoryUnlock)
    end
    def new(attributes = nil, &block); end

    sig { params(block: T.nilable(T.proc.params(record: ::RepositoryUnlock).returns(T.untyped))).returns(T::Boolean) }
    def none?(&block); end

    sig { params(block: T.nilable(T.proc.params(record: ::RepositoryUnlock).returns(T.untyped))).returns(T::Boolean) }
    def one?(&block); end

    sig { params(column_names: T.untyped).returns(T.untyped) }
    def pick(*column_names); end

    sig { params(column_names: T.untyped).returns(T.untyped) }
    def pluck(*column_names); end

    sig { returns(T.nilable(::RepositoryUnlock)) }
    def second; end

    sig { returns(::RepositoryUnlock) }
    def second!; end

    sig { returns(T.nilable(::RepositoryUnlock)) }
    def second_to_last; end

    sig { returns(::RepositoryUnlock) }
    def second_to_last!; end

    sig { returns(::RepositoryUnlock) }
    def sole; end

    sig { params(initial_value_or_column: T.untyped).returns(T.any(Integer, Float, BigDecimal)) }
    sig do
      type_parameters(:U)
        .params(
          initial_value_or_column: T.nilable(T.type_parameter(:U)),
          block: T.proc.params(object: ::RepositoryUnlock).returns(T.type_parameter(:U))
        ).returns(T.type_parameter(:U))
    end
    def sum(initial_value_or_column = nil, &block); end

    sig { returns(T.nilable(::RepositoryUnlock)) }
    sig { params(limit: Integer).returns(T::Array[::RepositoryUnlock]) }
    def take(limit = nil); end

    sig { returns(::RepositoryUnlock) }
    def take!; end

    sig { returns(T.nilable(::RepositoryUnlock)) }
    def third; end

    sig { returns(::RepositoryUnlock) }
    def third!; end

    sig { returns(T.nilable(::RepositoryUnlock)) }
    def third_to_last; end

    sig { returns(::RepositoryUnlock) }
    def third_to_last!; end
  end

  module GeneratedAssociationMethods
    sig { params(args: T.untyped, blk: T.untyped).returns(::Repository) }
    def build_repository(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(::User) }
    def build_revoked_by(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(::StaffAccessGrant) }
    def build_staff_access_grant(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(::User) }
    def build_unlocked_by(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(::Repository) }
    def create_repository(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(::Repository) }
    def create_repository!(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(::User) }
    def create_revoked_by(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(::User) }
    def create_revoked_by!(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(::StaffAccessGrant) }
    def create_staff_access_grant(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(::StaffAccessGrant) }
    def create_staff_access_grant!(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(::User) }
    def create_unlocked_by(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(::User) }
    def create_unlocked_by!(*args, &blk); end

    sig { returns(T.nilable(::Repository)) }
    def reload_repository; end

    sig { returns(T.nilable(::User)) }
    def reload_revoked_by; end

    sig { returns(T.nilable(::StaffAccessGrant)) }
    def reload_staff_access_grant; end

    sig { returns(T.nilable(::User)) }
    def reload_unlocked_by; end

    sig { returns(T.nilable(::Repository)) }
    def repository; end

    sig { params(value: T.nilable(::Repository)).void }
    def repository=(value); end

    sig { returns(T::Boolean) }
    def repository_changed?; end

    sig { returns(T::Boolean) }
    def repository_previously_changed?; end

    sig { void }
    def reset_repository; end

    sig { void }
    def reset_revoked_by; end

    sig { void }
    def reset_staff_access_grant; end

    sig { void }
    def reset_unlocked_by; end

    sig { returns(T.nilable(::User)) }
    def revoked_by; end

    sig { params(value: T.nilable(::User)).void }
    def revoked_by=(value); end

    sig { returns(T::Boolean) }
    def revoked_by_changed?; end

    sig { returns(T::Boolean) }
    def revoked_by_previously_changed?; end

    sig { returns(T.nilable(::StaffAccessGrant)) }
    def staff_access_grant; end

    sig { params(value: T.nilable(::StaffAccessGrant)).void }
    def staff_access_grant=(value); end

    sig { returns(T::Boolean) }
    def staff_access_grant_changed?; end

    sig { returns(T::Boolean) }
    def staff_access_grant_previously_changed?; end

    sig { returns(T.nilable(::User)) }
    def unlocked_by; end

    sig { params(value: T.nilable(::User)).void }
    def unlocked_by=(value); end

    sig { returns(T::Boolean) }
    def unlocked_by_changed?; end

    sig { returns(T::Boolean) }
    def unlocked_by_previously_changed?; end
  end

  module GeneratedAssociationRelationMethods
    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def active(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def active_for_user(*args, &blk); end

    sig { returns(PrivateAssociationRelation) }
    def all; end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def and(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def annotate(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def arel_columns(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def create_with(*args, &blk); end

    sig { params(value: T::Boolean).returns(PrivateAssociationRelation) }
    def distinct(value = true); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def eager_load(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def except(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def excluding(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def extending(*args, &blk); end

    sig { params(association: Symbol).returns(T::Array[T.untyped]) }
    def extract_associated(association); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def from(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelationGroupChain) }
    def group(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def having(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def in_order_of(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def includes(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def invert_where(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def joins(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def left_joins(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def left_outer_joins(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def limit(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def limit_execution_time(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def lock(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def merge(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def none(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def null_relation?(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def offset(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def only(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def optimizer_hints(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def or(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def order(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def preload(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def readonly(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def references(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def regroup(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def reorder(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def reselect(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def reverse_order(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def rewhere(*args, &blk); end

    sig { params(args: T.untyped).returns(PrivateAssociationRelation) }
    sig do
      params(
        blk: T.proc.params(record: ::RepositoryUnlock).returns(BasicObject)
      ).returns(T::Array[::RepositoryUnlock])
    end
    def select(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def strict_loading(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def structurally_compatible?(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def uniq!(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def unscope(*args, &blk); end

    sig { returns(PrivateAssociationRelationWhereChain) }
    sig { params(args: T.untyped).returns(PrivateAssociationRelation) }
    def where(*args); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def with(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def with_active_grant(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def with_recursive(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def without(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def without_ids(*args, &blk); end
  end

  module GeneratedAsyncReflectionAssociations
    sig { returns(Promise[T.nilable(::Repository)]) }
    def async_repository; end

    sig { returns(Promise[T.nilable(::User)]) }
    def async_revoked_by; end

    sig { returns(Promise[T.nilable(::StaffAccessGrant)]) }
    def async_staff_access_grant; end

    sig { returns(Promise[T.nilable(::User)]) }
    def async_unlocked_by; end
  end

  module GeneratedAttributeMethods
    sig { returns(T.untyped) }
    def created_at; end

    sig { params(value: T.untyped).returns(T.untyped) }
    def created_at=(value); end

    sig { returns(T::Boolean) }
    def created_at?; end

    sig { returns(T.untyped) }
    def created_at_before_last_save; end

    sig { returns(T.untyped) }
    def created_at_before_type_cast; end

    sig { returns(T::Boolean) }
    def created_at_came_from_user?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def created_at_change; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def created_at_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def created_at_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def created_at_in_database; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def created_at_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def created_at_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def created_at_previously_was; end

    sig { returns(T.untyped) }
    def created_at_was; end

    sig { void }
    def created_at_will_change!; end

    sig { returns(T.untyped) }
    def expires_at; end

    sig { params(value: T.untyped).returns(T.untyped) }
    def expires_at=(value); end

    sig { returns(T::Boolean) }
    def expires_at?; end

    sig { returns(T.untyped) }
    def expires_at_before_last_save; end

    sig { returns(T.untyped) }
    def expires_at_before_type_cast; end

    sig { returns(T::Boolean) }
    def expires_at_came_from_user?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def expires_at_change; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def expires_at_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def expires_at_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def expires_at_in_database; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def expires_at_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def expires_at_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def expires_at_previously_was; end

    sig { returns(T.untyped) }
    def expires_at_was; end

    sig { void }
    def expires_at_will_change!; end

    sig { returns(T.untyped) }
    def id; end

    sig { params(value: T.untyped).returns(T.untyped) }
    def id=(value); end

    sig { returns(T::Boolean) }
    def id?; end

    sig { returns(T.untyped) }
    def id_before_last_save; end

    sig { returns(T.untyped) }
    def id_before_type_cast; end

    sig { returns(T::Boolean) }
    def id_came_from_user?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def id_change; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def id_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def id_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def id_in_database; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def id_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def id_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def id_previously_was; end

    sig { returns(T.untyped) }
    def id_value; end

    sig { params(value: T.untyped).returns(T.untyped) }
    def id_value=(value); end

    sig { returns(T::Boolean) }
    def id_value?; end

    sig { returns(T.untyped) }
    def id_value_before_last_save; end

    sig { returns(T.untyped) }
    def id_value_before_type_cast; end

    sig { returns(T::Boolean) }
    def id_value_came_from_user?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def id_value_change; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def id_value_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def id_value_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def id_value_in_database; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def id_value_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def id_value_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def id_value_previously_was; end

    sig { returns(T.untyped) }
    def id_value_was; end

    sig { void }
    def id_value_will_change!; end

    sig { returns(T.untyped) }
    def id_was; end

    sig { void }
    def id_will_change!; end

    sig { returns(T.untyped) }
    def reason; end

    sig { params(value: T.untyped).returns(T.untyped) }
    def reason=(value); end

    sig { returns(T::Boolean) }
    def reason?; end

    sig { returns(T.untyped) }
    def reason_before_last_save; end

    sig { returns(T.untyped) }
    def reason_before_type_cast; end

    sig { returns(T::Boolean) }
    def reason_came_from_user?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def reason_change; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def reason_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def reason_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def reason_in_database; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def reason_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def reason_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def reason_previously_was; end

    sig { returns(T.untyped) }
    def reason_was; end

    sig { void }
    def reason_will_change!; end

    sig { returns(T.untyped) }
    def repository_id; end

    sig { params(value: T.untyped).returns(T.untyped) }
    def repository_id=(value); end

    sig { returns(T::Boolean) }
    def repository_id?; end

    sig { returns(T.untyped) }
    def repository_id_before_last_save; end

    sig { returns(T.untyped) }
    def repository_id_before_type_cast; end

    sig { returns(T::Boolean) }
    def repository_id_came_from_user?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def repository_id_change; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def repository_id_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def repository_id_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def repository_id_in_database; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def repository_id_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def repository_id_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def repository_id_previously_was; end

    sig { returns(T.untyped) }
    def repository_id_was; end

    sig { void }
    def repository_id_will_change!; end

    sig { void }
    def restore_created_at!; end

    sig { void }
    def restore_expires_at!; end

    sig { void }
    def restore_id!; end

    sig { void }
    def restore_id_value!; end

    sig { void }
    def restore_reason!; end

    sig { void }
    def restore_repository_id!; end

    sig { void }
    def restore_revoked!; end

    sig { void }
    def restore_revoked_at!; end

    sig { void }
    def restore_revoked_by_id!; end

    sig { void }
    def restore_staff_access_grant_id!; end

    sig { void }
    def restore_unlocked_by_id!; end

    sig { void }
    def restore_updated_at!; end

    sig { returns(T.untyped) }
    def revoked; end

    sig { params(value: T.untyped).returns(T.untyped) }
    def revoked=(value); end

    sig { returns(T::Boolean) }
    def revoked?; end

    sig { returns(T.untyped) }
    def revoked_at; end

    sig { params(value: T.untyped).returns(T.untyped) }
    def revoked_at=(value); end

    sig { returns(T::Boolean) }
    def revoked_at?; end

    sig { returns(T.untyped) }
    def revoked_at_before_last_save; end

    sig { returns(T.untyped) }
    def revoked_at_before_type_cast; end

    sig { returns(T::Boolean) }
    def revoked_at_came_from_user?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def revoked_at_change; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def revoked_at_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def revoked_at_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def revoked_at_in_database; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def revoked_at_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def revoked_at_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def revoked_at_previously_was; end

    sig { returns(T.untyped) }
    def revoked_at_was; end

    sig { void }
    def revoked_at_will_change!; end

    sig { returns(T.untyped) }
    def revoked_before_last_save; end

    sig { returns(T.untyped) }
    def revoked_before_type_cast; end

    sig { returns(T.untyped) }
    def revoked_by_id; end

    sig { params(value: T.untyped).returns(T.untyped) }
    def revoked_by_id=(value); end

    sig { returns(T::Boolean) }
    def revoked_by_id?; end

    sig { returns(T.untyped) }
    def revoked_by_id_before_last_save; end

    sig { returns(T.untyped) }
    def revoked_by_id_before_type_cast; end

    sig { returns(T::Boolean) }
    def revoked_by_id_came_from_user?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def revoked_by_id_change; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def revoked_by_id_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def revoked_by_id_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def revoked_by_id_in_database; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def revoked_by_id_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def revoked_by_id_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def revoked_by_id_previously_was; end

    sig { returns(T.untyped) }
    def revoked_by_id_was; end

    sig { void }
    def revoked_by_id_will_change!; end

    sig { returns(T::Boolean) }
    def revoked_came_from_user?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def revoked_change; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def revoked_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def revoked_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def revoked_in_database; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def revoked_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def revoked_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def revoked_previously_was; end

    sig { returns(T.untyped) }
    def revoked_was; end

    sig { void }
    def revoked_will_change!; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def saved_change_to_created_at; end

    sig { returns(T::Boolean) }
    def saved_change_to_created_at?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def saved_change_to_expires_at; end

    sig { returns(T::Boolean) }
    def saved_change_to_expires_at?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def saved_change_to_id; end

    sig { returns(T::Boolean) }
    def saved_change_to_id?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def saved_change_to_id_value; end

    sig { returns(T::Boolean) }
    def saved_change_to_id_value?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def saved_change_to_reason; end

    sig { returns(T::Boolean) }
    def saved_change_to_reason?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def saved_change_to_repository_id; end

    sig { returns(T::Boolean) }
    def saved_change_to_repository_id?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def saved_change_to_revoked; end

    sig { returns(T::Boolean) }
    def saved_change_to_revoked?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def saved_change_to_revoked_at; end

    sig { returns(T::Boolean) }
    def saved_change_to_revoked_at?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def saved_change_to_revoked_by_id; end

    sig { returns(T::Boolean) }
    def saved_change_to_revoked_by_id?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def saved_change_to_staff_access_grant_id; end

    sig { returns(T::Boolean) }
    def saved_change_to_staff_access_grant_id?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def saved_change_to_unlocked_by_id; end

    sig { returns(T::Boolean) }
    def saved_change_to_unlocked_by_id?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def saved_change_to_updated_at; end

    sig { returns(T::Boolean) }
    def saved_change_to_updated_at?; end

    sig { returns(T.untyped) }
    def staff_access_grant_id; end

    sig { params(value: T.untyped).returns(T.untyped) }
    def staff_access_grant_id=(value); end

    sig { returns(T::Boolean) }
    def staff_access_grant_id?; end

    sig { returns(T.untyped) }
    def staff_access_grant_id_before_last_save; end

    sig { returns(T.untyped) }
    def staff_access_grant_id_before_type_cast; end

    sig { returns(T::Boolean) }
    def staff_access_grant_id_came_from_user?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def staff_access_grant_id_change; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def staff_access_grant_id_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def staff_access_grant_id_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def staff_access_grant_id_in_database; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def staff_access_grant_id_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def staff_access_grant_id_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def staff_access_grant_id_previously_was; end

    sig { returns(T.untyped) }
    def staff_access_grant_id_was; end

    sig { void }
    def staff_access_grant_id_will_change!; end

    sig { returns(T.untyped) }
    def unlocked_by_id; end

    sig { params(value: T.untyped).returns(T.untyped) }
    def unlocked_by_id=(value); end

    sig { returns(T::Boolean) }
    def unlocked_by_id?; end

    sig { returns(T.untyped) }
    def unlocked_by_id_before_last_save; end

    sig { returns(T.untyped) }
    def unlocked_by_id_before_type_cast; end

    sig { returns(T::Boolean) }
    def unlocked_by_id_came_from_user?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def unlocked_by_id_change; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def unlocked_by_id_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def unlocked_by_id_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def unlocked_by_id_in_database; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def unlocked_by_id_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def unlocked_by_id_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def unlocked_by_id_previously_was; end

    sig { returns(T.untyped) }
    def unlocked_by_id_was; end

    sig { void }
    def unlocked_by_id_will_change!; end

    sig { returns(T.untyped) }
    def updated_at; end

    sig { params(value: T.untyped).returns(T.untyped) }
    def updated_at=(value); end

    sig { returns(T::Boolean) }
    def updated_at?; end

    sig { returns(T.untyped) }
    def updated_at_before_last_save; end

    sig { returns(T.untyped) }
    def updated_at_before_type_cast; end

    sig { returns(T::Boolean) }
    def updated_at_came_from_user?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def updated_at_change; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def updated_at_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def updated_at_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def updated_at_in_database; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def updated_at_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def updated_at_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def updated_at_previously_was; end

    sig { returns(T.untyped) }
    def updated_at_was; end

    sig { void }
    def updated_at_will_change!; end

    sig { returns(T::Boolean) }
    def will_save_change_to_created_at?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_expires_at?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_id?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_id_value?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_reason?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_repository_id?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_revoked?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_revoked_at?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_revoked_by_id?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_staff_access_grant_id?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_unlocked_by_id?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_updated_at?; end
  end

  module GeneratedEntityReferenceMethods
    sig { returns(T.nilable(::Repositories::IRepository)) }
    def repository; end
  end

  module GeneratedPreludeBatchMethods
    sig { returns(T.untyped) }
    def _repository_preloaded_via_domain; end

    sig { returns(Promise[T.untyped]) }
    def async_batch__repository_preloaded_via_domain; end
  end

  module GeneratedRelationMethods
    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def active(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def active_for_user(*args, &blk); end

    sig { returns(PrivateRelation) }
    def all; end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def and(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def annotate(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def arel_columns(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def create_with(*args, &blk); end

    sig { params(value: T::Boolean).returns(PrivateRelation) }
    def distinct(value = true); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def eager_load(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def except(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def excluding(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def extending(*args, &blk); end

    sig { params(association: Symbol).returns(T::Array[T.untyped]) }
    def extract_associated(association); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def from(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelationGroupChain) }
    def group(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def having(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def in_order_of(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def includes(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def invert_where(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def joins(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def left_joins(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def left_outer_joins(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def limit(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def limit_execution_time(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def lock(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def merge(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def none(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def null_relation?(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def offset(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def only(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def optimizer_hints(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def or(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def order(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def preload(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def readonly(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def references(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def regroup(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def reorder(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def reselect(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def reverse_order(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def rewhere(*args, &blk); end

    sig { params(args: T.untyped).returns(PrivateRelation) }
    sig do
      params(
        blk: T.proc.params(record: ::RepositoryUnlock).returns(BasicObject)
      ).returns(T::Array[::RepositoryUnlock])
    end
    def select(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def strict_loading(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def structurally_compatible?(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def uniq!(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def unscope(*args, &blk); end

    sig { returns(PrivateRelationWhereChain) }
    sig { params(args: T.untyped).returns(PrivateRelation) }
    def where(*args); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def with(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def with_active_grant(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def with_recursive(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def without(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def without_ids(*args, &blk); end
  end

  class PrivateAssociationRelation < ::ActiveRecord::AssociationRelation
    include CommonRelationMethods
    include GeneratedAssociationRelationMethods

    Elem = type_member { { fixed: ::RepositoryUnlock } }

    sig { returns(T::Array[::RepositoryUnlock]) }
    def to_a; end

    sig { returns(T::Array[::RepositoryUnlock]) }
    def to_ary; end
  end

  class PrivateAssociationRelationGroupChain < PrivateAssociationRelation
    Elem = type_member { { fixed: ::RepositoryUnlock } }

    sig { params(column_name: T.any(String, Symbol)).returns(T::Hash[T.untyped, T.any(Integer, Float, BigDecimal)]) }
    def average(column_name); end

    sig do
      params(
        operation: Symbol,
        column_name: T.any(String, Symbol)
      ).returns(T::Hash[T.untyped, T.any(Integer, Float, BigDecimal)])
    end
    def calculate(operation, column_name); end

    sig { params(column_name: T.untyped).returns(T::Hash[T.untyped, Integer]) }
    def count(column_name = nil); end

    sig { params(args: T.untyped, blk: T.untyped).returns(T.self_type) }
    def having(*args, &blk); end

    sig { params(column_name: T.any(String, Symbol)).returns(T::Hash[T.untyped, T.untyped]) }
    def maximum(column_name); end

    sig { params(column_name: T.any(String, Symbol)).returns(T::Hash[T.untyped, T.untyped]) }
    def minimum(column_name); end

    sig { returns(T::Hash[T.untyped, Integer]) }
    def size; end

    sig do
      params(
        column_name: T.nilable(T.any(String, Symbol)),
        block: T.nilable(T.proc.params(record: T.untyped).returns(T.untyped))
      ).returns(T::Hash[T.untyped, T.any(Integer, Float, BigDecimal)])
    end
    def sum(column_name = nil, &block); end
  end

  class PrivateAssociationRelationWhereChain
    Elem = type_member { { fixed: ::RepositoryUnlock } }

    sig { params(args: T.untyped).returns(PrivateAssociationRelation) }
    def associated(*args); end

    sig { params(args: T.untyped).returns(PrivateAssociationRelation) }
    def missing(*args); end

    sig { params(opts: T.untyped, rest: T.untyped).returns(PrivateAssociationRelation) }
    def not(opts, *rest); end
  end

  class PrivateCollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include CommonRelationMethods
    include GeneratedAssociationRelationMethods

    Elem = type_member { { fixed: ::RepositoryUnlock } }

    sig do
      params(
        records: T.any(::RepositoryUnlock, T::Enumerable[T.any(::RepositoryUnlock, T::Enumerable[::RepositoryUnlock])])
      ).returns(PrivateCollectionProxy)
    end
    def <<(*records); end

    sig do
      params(
        records: T.any(::RepositoryUnlock, T::Enumerable[T.any(::RepositoryUnlock, T::Enumerable[::RepositoryUnlock])])
      ).returns(PrivateCollectionProxy)
    end
    def append(*records); end

    sig { returns(PrivateCollectionProxy) }
    def clear; end

    sig do
      params(
        records: T.any(::RepositoryUnlock, T::Enumerable[T.any(::RepositoryUnlock, T::Enumerable[::RepositoryUnlock])])
      ).returns(PrivateCollectionProxy)
    end
    def concat(*records); end

    sig { returns(T::Array[::RepositoryUnlock]) }
    def load_target; end

    sig do
      params(
        records: T.any(::RepositoryUnlock, T::Enumerable[T.any(::RepositoryUnlock, T::Enumerable[::RepositoryUnlock])])
      ).returns(PrivateCollectionProxy)
    end
    def prepend(*records); end

    sig do
      params(
        records: T.any(::RepositoryUnlock, T::Enumerable[T.any(::RepositoryUnlock, T::Enumerable[::RepositoryUnlock])])
      ).returns(PrivateCollectionProxy)
    end
    def push(*records); end

    sig do
      params(
        other_array: T.any(::RepositoryUnlock, T::Enumerable[T.any(::RepositoryUnlock, T::Enumerable[::RepositoryUnlock])])
      ).returns(T::Array[::RepositoryUnlock])
    end
    def replace(other_array); end

    sig { returns(PrivateAssociationRelation) }
    def scope; end

    sig { returns(T::Array[::RepositoryUnlock]) }
    def target; end

    sig { returns(T::Array[::RepositoryUnlock]) }
    def to_a; end

    sig { returns(T::Array[::RepositoryUnlock]) }
    def to_ary; end
  end

  class PrivateRelation < ::ActiveRecord::Relation
    include CommonRelationMethods
    include GeneratedRelationMethods

    Elem = type_member { { fixed: ::RepositoryUnlock } }

    sig { returns(T::Array[::RepositoryUnlock]) }
    def to_a; end

    sig { returns(T::Array[::RepositoryUnlock]) }
    def to_ary; end
  end

  class PrivateRelationGroupChain < PrivateRelation
    Elem = type_member { { fixed: ::RepositoryUnlock } }

    sig { params(column_name: T.any(String, Symbol)).returns(T::Hash[T.untyped, T.any(Integer, Float, BigDecimal)]) }
    def average(column_name); end

    sig do
      params(
        operation: Symbol,
        column_name: T.any(String, Symbol)
      ).returns(T::Hash[T.untyped, T.any(Integer, Float, BigDecimal)])
    end
    def calculate(operation, column_name); end

    sig { params(column_name: T.untyped).returns(T::Hash[T.untyped, Integer]) }
    def count(column_name = nil); end

    sig { params(args: T.untyped, blk: T.untyped).returns(T.self_type) }
    def having(*args, &blk); end

    sig { params(column_name: T.any(String, Symbol)).returns(T::Hash[T.untyped, T.untyped]) }
    def maximum(column_name); end

    sig { params(column_name: T.any(String, Symbol)).returns(T::Hash[T.untyped, T.untyped]) }
    def minimum(column_name); end

    sig { returns(T::Hash[T.untyped, Integer]) }
    def size; end

    sig do
      params(
        column_name: T.nilable(T.any(String, Symbol)),
        block: T.nilable(T.proc.params(record: T.untyped).returns(T.untyped))
      ).returns(T::Hash[T.untyped, T.any(Integer, Float, BigDecimal)])
    end
    def sum(column_name = nil, &block); end
  end

  class PrivateRelationWhereChain
    Elem = type_member { { fixed: ::RepositoryUnlock } }

    sig { params(args: T.untyped).returns(PrivateRelation) }
    def associated(*args); end

    sig { params(args: T.untyped).returns(PrivateRelation) }
    def missing(*args); end

    sig { params(opts: T.untyped, rest: T.untyped).returns(PrivateRelation) }
    def not(opts, *rest); end
  end
end
