# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SecretScanningSelectiveEnablementJob`.
# Please instead update this file by running `bin/tapioca dsl SecretScanningSelectiveEnablementJob`.


class SecretScanningSelectiveEnablementJob
  class << self
    sig do
      params(
        org: ::Organization,
        actor: ::User,
        config_name: ::String,
        config_description: ::String,
        repo_ids: T::Array[::Integer],
        block: T.nilable(T.proc.params(job: SecretScanningSelectiveEnablementJob).void)
      ).returns(T.any(SecretScanningSelectiveEnablementJob, FalseClass))
    end
    def perform_later(org:, actor:, config_name:, config_description:, repo_ids:, &block); end

    sig do
      params(
        org: ::Organization,
        actor: ::User,
        config_name: ::String,
        config_description: ::String,
        repo_ids: T::Array[::Integer]
      ).void
    end
    def perform_now(org:, actor:, config_name:, config_description:, repo_ids:); end
  end
end
