#!/bin/bash
set -e

SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
cd "$SCRIPT_DIR"/../..

source $SCRIPT_DIR/lib/subproject-containers

# check for local docker images for subprojects
load_local_stored_docker_images

images=$(jq -r 'to_entries | .[] | "\(.key) \(.value)"' ./script/dx/subproject-to-image-map.json)
echo "$images" | while read -r version_file image; do
  sha=$(cat "$version_file" | grep -v '^#')
  tagged_image="$image:$sha"
  pull "$tagged_image"
done
