# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `MonolithTwirp::Modelsgateway::Access::V1::GetModelAccessRequest`.
# Please instead update this file by running `bin/tapioca dsl MonolithTwirp::Modelsgateway::Access::V1::GetModelAccessRequest`.


class MonolithTwirp::Modelsgateway::Access::V1::GetModelAccessRequest < Google::Protobuf::AbstractMessage
  sig do
    params(
      access_token: T.nilable(String),
      is_billable_source: T.nilable(T::Boolean),
      model_key: T.nilable(String),
      org_name: T.nilable(String)
    ).void
  end
  def initialize(access_token: nil, is_billable_source: nil, model_key: nil, org_name: nil); end

  sig { returns(String) }
  def access_token; end

  sig { params(value: String).void }
  def access_token=(value); end

  sig { void }
  def clear_access_token; end

  sig { void }
  def clear_is_billable_source; end

  sig { void }
  def clear_model_key; end

  sig { void }
  def clear_org_name; end

  sig { returns(T::Boolean) }
  def is_billable_source; end

  sig { params(value: T::Boolean).void }
  def is_billable_source=(value); end

  sig { returns(String) }
  def model_key; end

  sig { params(value: String).void }
  def model_key=(value); end

  sig { returns(String) }
  def org_name; end

  sig { params(value: String).void }
  def org_name=(value); end
end
