# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/github/copilot/v1/entities/copilot_settings.proto

require 'google/protobuf'

require 'hydro/schemas/github/copilot/v1/entities/copilot_snippy_configuration_pb'
require 'hydro/schemas/github/copilot/v1/entities/copilot_editor_chat_configuration_pb'
require 'hydro/schemas/github/copilot/v1/entities/copilot_public_code_suggestions_configuration_pb'
require 'hydro/schemas/github/copilot/v1/entities/copilot_telemetry_configuration_pb'
require 'hydro/schemas/github/copilot/v1/entities/copilot_pull_request_summarizations_configuration_pb'
require 'hydro/schemas/github/copilot/v1/entities/copilot_private_docs_configuration_pb'
require 'hydro/schemas/github/copilot/v1/entities/copilot_github_chat_configuration_pb'
require 'hydro/schemas/github/copilot/v1/entities/copilot_custom_models_configuration_pb'
require 'hydro/schemas/github/copilot/v1/entities/copilot_cli_configuration_pb'
require 'hydro/schemas/github/copilot/v1/entities/copilot_github_chat_bing_access_configuration_pb'
require 'hydro/schemas/github/copilot/v1/entities/copilot_mobile_chat_configuration_pb'
require 'hydro/schemas/github/copilot/v1/entities/copilot_beta_features_opt_in_configuration_pb'
require 'hydro/schemas/github/copilot/v1/entities/copilot_extensions_configuration_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.github.copilot.v1.entities.CopilotSettings" do
    optional :telemetry_configuration, :enum, 1, "hydro.schemas.github.copilot.v1.entities.CopilotTelemetryConfiguration"
    optional :snippy_setting, :enum, 2, "hydro.schemas.github.copilot.v1.entities.CopilotSnippyConfiguration"
    optional :editor_chat_setting, :enum, 3, "hydro.schemas.github.copilot.v1.entities.CopilotEditorChatConfiguration"
    optional :public_code_suggestions_setting, :enum, 5, "hydro.schemas.github.copilot.v1.entities.CopilotPublicCodeSuggestionsConfiguration"
    optional :github_chat_setting, :enum, 6, "hydro.schemas.github.copilot.v1.entities.CopilotGithubChatConfiguration"
    optional :custom_models_setting, :enum, 7, "hydro.schemas.github.copilot.v1.entities.CopilotCustomModelsConfiguration"
    optional :cli_setting, :enum, 8, "hydro.schemas.github.copilot.v1.entities.CopilotCliConfiguration"
    optional :pr_summarizations_setting, :enum, 9, "hydro.schemas.github.copilot.v1.entities.CopilotPullRequestSummarizationsConfiguration"
    optional :private_docs_setting, :enum, 10, "hydro.schemas.github.copilot.v1.entities.CopilotPrivateDocsConfiguration"
    optional :github_chat_bing_access_setting, :enum, 11, "hydro.schemas.github.copilot.v1.entities.CopilotGithubChatBingAccessConfiguration"
    optional :mobile_chat_setting, :enum, 12, "hydro.schemas.github.copilot.v1.entities.CopilotMobileChatConfiguration"
    optional :copilot_beta_features_opt_in_setting, :enum, 13, "hydro.schemas.github.copilot.v1.entities.CopilotBetaFeaturesOptInConfiguration"
    optional :copilot_extensions_setting, :enum, 14, "hydro.schemas.github.copilot.v1.entities.CopilotExtensionsConfiguration"
  end
end

module Hydro
  module Schemas
    module Github
      module Copilot
        module V1
          module Entities
            CopilotSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.copilot.v1.entities.CopilotSettings").msgclass
          end
        end
      end
    end
  end
end
