#!/usr/bin/env bash

set -e

# Obfuscate the ruby code.
# The list of files/directories to obfuscate was taken from 2.22 release of GHES.
# https://github.com/github/enterprise2/blob/73841898850210a9f6d4a8ac6de0844cd088a35d/build-pkg-github.sh#L48
# Plus the packages directory.
#
# /bin/tools/ruby-concealer.rb is from the gh-builder-focal base image.


find app -iname '*.rb' -type f -print0 | xargs -0 "ruby" "/bin/tools/ruby-concealer.rb" 2>&1 | awk '!/already concealed/' && \
find config/initializers -iname '*.rb' -type f -print0 | xargs -0 "ruby" "/bin/tools/ruby-concealer.rb" 2>&1 | awk '!/already concealed/' && \
ruby "/bin/tools/ruby-concealer.rb" "config/routes.rb" 2>&1 | awk '!/already concealed/' && \
find db -iname '*.rb' -type f -print0 | xargs -0 "ruby" "/bin/tools/ruby-concealer.rb" 2>&1 | awk '!/already concealed/' && \
find lib -iname '*.rb' -type f -print0 | xargs -0 "ruby" "/bin/tools/ruby-concealer.rb" 2>&1 | awk '!/already concealed/' && \
find packages -iname '*.rb' -type f -print0 | xargs -0 "ruby" "/bin/tools/ruby-concealer.rb" 2>&1 | awk '!/already concealed/' && \
find vendor/internal-gems/*/lib  -iname '*.rb' -type f -print0 | xargs -0 "ruby" "/bin/tools/ruby-concealer.rb" 2>&1 | awk '!/already concealed/' && \
find vendor/gitrpc/lib -iname '*.rb' -type f -print0 | xargs -0 "ruby" "/bin/tools/ruby-concealer.rb" 2>&1 | awk '!/already concealed/' && \
find vendor/gems/*/ruby/*/gems/enterprise-crypto-*/lib -iname '*.rb' -type f -print0 | xargs -0 "ruby" "/bin/tools/ruby-concealer.rb" 2>&1 | awk '!/already concealed/'
