#!/bin/bash
#/ Usage: stop-query-harvester
#/ Kills query harvester and add query harvester logs to the artifacts directory for now

set -e

[ -s tmp/query-harvester.pid ] && kill $(cat tmp/query-harvester.pid) || true
[ -s tmp/query-harvester ] && gzip -c tmp/query-harvester > $ARTIFACTS_DIR/query-harvester.gz || true
