#!/bin/bash
# Usage: script/ci/vtcombo-down
#
set -e

PID_FILE=tmp/vtcombo.pid

if [[ "$DX_EDGE" = true ]] && [[ "$DX_FEATURE_SUBPROJECT_CONTAINERS" = true ]]; then
  docker stop vitess &>/dev/null || true
  docker rm vitess &>/dev/null || true
else
  if [ -f "$PID_FILE" ]; then
    kill $(cat $PID_FILE) && rm -f $PID_FILE
  fi
fi
