# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/github/v1/entities/billing_plan_owner.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.github.v1.entities.BillingPlanOwner" do
    optional :global_id, :string, 1
    optional :database_id, :int64, 2
    optional :type, :enum, 3, "hydro.schemas.github.v1.entities.BillingPlanOwner.Type"
    optional :name, :string, 4
    optional :tier, :int32, 5
    optional :spammy, :bool, 6
    optional :suspended, :bool, 7
    optional :spamurai_classification, :enum, 8, "hydro.schemas.github.v1.entities.BillingPlanOwner.SpamuraiClassification"
  end
  add_enum "hydro.schemas.github.v1.entities.BillingPlanOwner.Type" do
    value :TYPE_UNKNOWN, 0
    value :TYPE_USER, 1
    value :TYPE_ORGANIZATION, 2
    value :TYPE_BUSINESS, 3
  end
  add_enum "hydro.schemas.github.v1.entities.BillingPlanOwner.SpamuraiClassification" do
    value :SPAMURAI_CLASSIFICATION_UNKNOWN, 0
    value :HAMMY, 1
    value :SPAMMY, 2
  end
end

module Hydro
  module Schemas
    module Github
      module V1
        module Entities
          BillingPlanOwner = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.v1.entities.BillingPlanOwner").msgclass
          BillingPlanOwner::Type = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.v1.entities.BillingPlanOwner.Type").enummodule
          BillingPlanOwner::SpamuraiClassification = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.v1.entities.BillingPlanOwner.SpamuraiClassification").enummodule
        end
      end
    end
  end
end
