# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/github/v1/entities/project_card.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.github.v1.entities.ProjectCard" do
    optional :content_type, :enum, 1, "hydro.schemas.github.v1.entities.ProjectCard.ContentType"
  end
  add_enum "hydro.schemas.github.v1.entities.ProjectCard.ContentType" do
    value :CONTENT_TYPE_UNKNOWN, 0
    value :ISSUE, 1
    value :PULL_REQUEST, 2
    value :NOTE, 3
  end
end

module Hydro
  module Schemas
    module Github
      module V1
        module Entities
          ProjectCard = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.v1.entities.ProjectCard").msgclass
          ProjectCard::ContentType = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.v1.entities.ProjectCard.ContentType").enummodule
        end
      end
    end
  end
end
