# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Licensify::Services::V1::GetGroupedCountsRequest`.
# Please instead update this file by running `bin/tapioca dsl Licensify::Services::V1::GetGroupedCountsRequest`.


class Licensify::Services::V1::GetGroupedCountsRequest < Google::Protobuf::AbstractMessage
  sig do
    params(
      customerId: T.nilable(Integer),
      products: T.nilable(T.any(Google::Protobuf::RepeatedField[T.any(Symbol, Integer)], T::Array[T.any(Symbol, Integer)]))
    ).void
  end
  def initialize(customerId: nil, products: T.unsafe(nil)); end

  sig { void }
  def clear_customerId; end

  sig { void }
  def clear_products; end

  sig { returns(Integer) }
  def customerId; end

  sig { params(value: Integer).void }
  def customerId=(value); end

  sig { returns(Google::Protobuf::RepeatedField[T.any(Symbol, Integer)]) }
  def products; end

  sig { params(value: Google::Protobuf::RepeatedField[T.any(Symbol, Integer)]).void }
  def products=(value); end
end
