# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Licensify::Services::V1::GetCustomerLicenseCountsRequest`.
# Please instead update this file by running `bin/tapioca dsl Licensify::Services::V1::GetCustomerLicenseCountsRequest`.


class Licensify::Services::V1::GetCustomerLicenseCountsRequest < Google::Protobuf::AbstractMessage
  sig { params(customerId: T.nilable(Integer)).void }
  def initialize(customerId: nil); end

  sig { void }
  def clear_customerId; end

  sig { returns(Integer) }
  def customerId; end

  sig { params(value: Integer).void }
  def customerId=(value); end
end
