# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Licensify::Services::V1::ProductEnablementServiceClient`.
# Please instead update this file by running `bin/tapioca dsl Licensify::Services::V1::ProductEnablementServiceClient`.


class Licensify::Services::V1::ProductEnablementServiceClient < ::Twirp::Client
  sig { params(connection: T.any(String, ::Faraday::Connection), opts: T::Hash[Symbol, T.untyped]).void }
  def initialize(connection, opts = {}); end

  sig do
    params(
      input: Licensify::Services::V1::GetProductEnablementsRequest,
      req_opts: T.nilable(T::Hash[Symbol, T.untyped])
    ).returns(::Twirp::ClientResp[Licensify::Services::V1::GetProductEnablementsResponse])
  end
  def get_product_enablements(input, req_opts = nil); end

  sig do
    params(
      input: Licensify::Services::V1::UpsertProductEnablementRequest,
      req_opts: T.nilable(T::Hash[Symbol, T.untyped])
    ).returns(::Twirp::ClientResp[Licensify::Services::V1::UpsertProductEnablementResponse])
  end
  def upsert_product_enablement(input, req_opts = nil); end
end
