# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `MonolithTwirp::CodeScanning::Turboghas::V1::Feature`.
# Please instead update this file by running `bin/tapioca dsl MonolithTwirp::CodeScanning::Turboghas::V1::Feature`.


module MonolithTwirp::CodeScanning::Turboghas::V1::Feature
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

MonolithTwirp::CodeScanning::Turboghas::V1::Feature::FEATURE_ALL = 1
MonolithTwirp::CodeScanning::Turboghas::V1::Feature::FEATURE_CODE_SCANNING = 2
MonolithTwirp::CodeScanning::Turboghas::V1::Feature::FEATURE_DEPENDABOT = 8
MonolithTwirp::CodeScanning::Turboghas::V1::Feature::FEATURE_NONE = 0
MonolithTwirp::CodeScanning::Turboghas::V1::Feature::FEATURE_SECRET_SCANNING = 4
