# typed: strict
# frozen_string_literal: true

class Discussion::CopilotSummarizer
  extend T::Sig

  # Keep in sync with Hydro enum `github.discussions.v2.GiveCopilotSummaryFeedback.CopilotSummaryFeedbackChoice`
  DISCUSSION_SUMMARY_FEEDBACK_OPTIONS = T.let(%w[
    UNKNOWN
    UNHELPFUL
    INCORRECT
    POORLY_FORMATTED
    OFFENSIVE_OR_DISCRIMINATORY
    OTHER
    POSITIVE
  ].freeze, T::Array[String])

  DISCUSSION_SUMMARY_NEGATIVE_FEEDBACK_LABELS = T.let({
    "UNHELPFUL" => "Not helpful",
    "INCORRECT" => "Incorrect",
    "POORLY_FORMATTED" => "Poorly formatted",
    "OFFENSIVE_OR_DISCRIMINATORY" => "Offensive or discriminatory",
    "OTHER" => "Other",
  }.freeze, T::Hash[String, String])

  # Default prompt for summarizing a discussion.
  # Users can override this with a custom prompt if they have the necessary permissions.
  # Used in Copilot API (packages/copilot/app/models/copilot/user/copilot_api.rb).
  # Update `USER_PROMPT_VERSION` to be the commit SHA for this change whenever updating the prompt string
  USER_PROMPT = <<~MARKDOWN
    Create a concise summary for a discussion thread to help users quickly understand the key points without reading the entire conversation.

    Use an unordered list with 3 bullet points. Use `**` for bold keywords.

    Structure as follows:

    - **Overview:** Summarize initial post or accepted answer.
    - **Key Points:** Highlight main themes or recurring topics.
    - **Next Steps:** List specific action items, open questions, or risks if applicable.
  MARKDOWN

  # The commit SHA in which the `USER_PROMPT` string was last modified
  #
  # https://github.com/github/github/blob/<USER_PROMPT_VERSION>/packages/discussions/app/models/discussion/copilot_dependency.rb#L34
  # is the prompt for the given version
  USER_PROMPT_VERSION = "63784f1a5569beb8f96b61cdc713c492b9427046"

  DATADOG_PREFIX = "discussions.copilot"

  sig { params(discussion: Discussion).void }
  def initialize(discussion:)
    @discussion = discussion
  end

  sig do
    params(
      actor: User,
      token: Copilot::EncryptedToken,
      prompt: T.nilable(String)
    ).returns(CopilotSummaryAgentResponse)
  end
  def summarize(actor:, token:, prompt: nil)
    copilot_api = T.let(
      actor.copilot_api(integration_id: CopilotAPI::COPILOT_CHAT_INTEGRATION_ID, token: token),
      Copilot::User::CopilotApi
    )
    raw_response = copilot_api.summarize(references: [copilot_api_reference], custom_prompt: prompt,
      default_prompt: USER_PROMPT)
    instrument_copilot_summarize(actor: actor)
    summary_response = CopilotSummaryAgentResponse.from(raw_response)
    count_copilot_summary_token_usage(summary_response)
    summary_response
  end

  # How many comments we want to send in copilot-api requests when summarizing a discussion.
  COPILOT_API_REFERENCE_COMMENT_LIMIT = 100

  # Public: Returns a Hash that fits the shape of `agentprompt.Reference` type in
  # https://github.com/github/copilot-api/blob/fa44afed1877246702f0325a38a91128fe642514/pkg/agent/agentprompt/reference.go#L11-L17
  sig { returns T::Hash[Symbol, T.untyped] }
  def copilot_api_reference
    {
      type: "github.discussion",
      id: discussion_id.to_s,
      data: copilot_api_reference_data,
    }
  end

  # Public: Returns a Hash that fits the shape of `reference.Discussion` type in
  # https://github.com/github/copilot-api/blob/91c6e84d3a12d5e57c6cd656948c80ca53b31bd4/pkg/chat/reference/discussion.go#L57-L76
  sig { returns T::Hash[Symbol, T.untyped] }
  def copilot_api_reference_data
    {
      type: "discussion", # https://github.com/github/copilot-api/blob/b26554bd359036519e5ea4afab3f074a3d5c0c32/pkg/chat/reference/reference.go#L108
      body: GitHub::Goomba::CopilotSummaryPipeline.to_text(body),
      id: discussion_id,
      repository: repository_for_copilot_api,
      number: number,
      authorLogin: author_display_login,
      answer: chosen_comment_copilot_summarizer&.copilot_api_reference_data,
      comments: copilot_comment_summarizers.map(&:copilot_api_reference_data),
      totalUpvotes: total_upvotes,
      reactionCounts: reaction_counts_for_copilot_api,
      labels: labels_for_copilot_api,
      category: category_for_copilot_api,
    }
  end

  # Public: Emit an event indicating a user gave feedback about a discussion summary that was generated by Copilot.
  #
  # actor - the user who requested the summary
  # feedback_choices - the user's selection of which `DISCUSSION_SUMMARY_FEEDBACK_OPTIONS` values convey their
  #                    feedback about the summary
  # feedback_text - the user's own words about the summary
  # header_request_id - the X-Request-Id header of the original request sent to copilot-api
  #
  # Returns a Boolean indicating success.
  sig do
    params(
      actor: User,
      feedback_choices: T::Array[String],
      feedback_text: T.nilable(String),
      header_request_id: T.nilable(String)
    ).returns(T::Boolean)
  end
  def instrument_copilot_summary_feedback(actor:, feedback_choices:, feedback_text: nil, header_request_id: nil)
    return false if feedback_choices.empty?

    invalid_feedback_choices = feedback_choices - DISCUSSION_SUMMARY_FEEDBACK_OPTIONS
    return false if invalid_feedback_choices.present?

    # Hydro
    GlobalInstrumenter.instrument "discussion.give_copilot_summary_feedback",
      analytics_tracking_id: actor.analytics_tracking_id,
      feedback_choice: feedback_choices,
      feedback: feedback_text,
      organization_id: organization_id,
      repository_id: repository_id,
      header_request_id: header_request_id,
      prompt_version: USER_PROMPT_VERSION
    true
  end

  private

  sig { returns Discussion }
  attr_reader :discussion

  sig { params(summary_response: CopilotSummaryAgentResponse).void }
  def count_copilot_summary_token_usage(summary_response)
    total_tokens = summary_response.total_token_usage
    completion_tokens = summary_response.completion_token_usage
    prompt_tokens = summary_response.prompt_token_usage
    tags = ["model:#{summary_response.model}"]
    metric = "#{DATADOG_PREFIX}.summarize.tokens_used"

    if completion_tokens && completion_tokens > 0
      GitHub.dogstats.distribution(metric, completion_tokens, tags: tags + ["usage_type:completion"])
    end
    if prompt_tokens && prompt_tokens > 0
      GitHub.dogstats.distribution(metric, prompt_tokens, tags: tags + ["usage_type:prompt"])
    end
  end

  # Private: Returns a Hash to suit the structure of the `Repo` field in the `Discussion` type in copilot-api.
  # https://github.com/github/copilot-api/blob/ef95100895e125d4c807e5f9f3dc22e7eedd6cab/pkg/chat/reference/discussion.go#L50
  sig { returns T::Hash[Symbol, T.nilable(T.any(String, Integer))] }
  def repository_for_copilot_api
    # https://github.com/github/copilot-api/blob/6e63037b201294704eda3031beef16f57e453560/pkg/chat/reference/discussion.go#L12-L16
    { id: repository_id, name: repository&.name, owner: repository_owner_login }
  end

  # Private: Returns a list of labels to suit the structure of the `Labels` field in the `Discussion` type in
  # copilot-api. https://github.com/github/copilot-api/blob/e28abf0fe94107f4ccad13708c2c2407bc89756b/pkg/chat/reference/discussion.go#L59
  sig { returns T::Array[T::Hash[Symbol, T.nilable(String)]] }
  def labels_for_copilot_api
    discussion.labels.order(:lowercase_name).map do |label|
      # https://github.com/github/copilot-api/blob/e28abf0fe94107f4ccad13708c2c2407bc89756b/pkg/chat/reference/discussion.go#L39-L43
      { name: label.name, description: label.description }
    end
  end

  # Private: Returns a list of reaction counts to suit the structure of the `ReactionCounts` field in the `Discussion`
  # type in copilot-api. https://github.com/github/copilot-api/blob/e28abf0fe94107f4ccad13708c2c2407bc89756b/pkg/chat/reference/discussion.go#L60
  sig { returns T::Array[T::Hash[Symbol, T.any(String, Integer)]] }
  def reaction_counts_for_copilot_api
    reactions_count.map do |reaction, count|
      # https://github.com/github/copilot-api/blob/e28abf0fe94107f4ccad13708c2c2407bc89756b/pkg/chat/reference/discussion.go#L23-L27
      { reaction: reaction, count: count }
    end
  end

  # Private: Returns a category hash to suit the structure of the `Category` field in the `Discussion` type in
  # copilot-api. https://github.com/github/copilot-api/blob/ef95100895e125d4c807e5f9f3dc22e7eedd6cab/pkg/chat/reference/discussion.go#L62
  sig { returns T::Hash[Symbol, T.nilable(String)] }
  def category_for_copilot_api
    # https://github.com/github/copilot-api/blob/ef95100895e125d4c807e5f9f3dc22e7eedd6cab/pkg/chat/reference/discussion.go#L65-L69
    { name: category&.name || "none", description: category&.description }
  end

  # Private: Includes top-level comments and nested replies for providing to copilot-api for use in summarizing
  # the discussion. Comments are sorted in ascending chronological order.
  sig { returns T::Array[DiscussionComment] }
  def comments_for_copilot_summary
    should_limit_comments = comment_count > COPILOT_API_REFERENCE_COMMENT_LIMIT
    comment_group_limit = (COPILOT_API_REFERENCE_COMMENT_LIMIT.to_f / 2).round
    comments_scope = discussion.comments.not_spammy.not_wiped.not_minimized
    if answered?
      comments_scope = comments_scope.where.not(id: discussion.chosen_comment_id)
    end
    oldest_comments = if should_limit_comments
      comments_scope.reorder(id: :asc).limit(comment_group_limit).to_a
    else
      comments_scope.to_a # default order by creation time is fine
    end
    newest_comments = if should_limit_comments
      comments_scope.reorder(id: :desc).limit(comment_group_limit).to_a
    else
      []
    end
    (oldest_comments + newest_comments).sort_by { |comment| [comment.created_at, comment.id] }
  end

  sig { returns T::Array[DiscussionComment::CopilotSummarizer] }
  def copilot_comment_summarizers
    comments_for_copilot_summary.map { |comment| DiscussionComment::CopilotSummarizer.new(comment: comment) }
  end

  sig { returns T.nilable(DiscussionComment::CopilotSummarizer) }
  def chosen_comment_copilot_summarizer
    return unless answered?
    DiscussionComment::CopilotSummarizer.new(comment: T.must(chosen_comment))
  end

  sig { params(actor: User).void }
  def instrument_copilot_summarize(actor:)
    # Hydro
    GlobalInstrumenter.instrument "discussion.copilot_summarize",
      analytics_tracking_id: actor.try(:analytics_tracking_id),
      organization_id: organization_id,
      repository_id: repository_id
  end

  sig { returns Integer }
  def discussion_id
    T.must(discussion.id)
  end

  sig { returns T.nilable(DiscussionComment) }
  def chosen_comment
    discussion.chosen_comment
  end

  sig { returns T.nilable(T::Boolean) }
  def answered?
    discussion.answered?
  end

  sig { returns(T.nilable(Integer)) }
  def organization_id
    discussion.organization_id
  end

  sig { returns(Integer) }
  def repository_id
    discussion.repository_id
  end

  sig { returns(T.nilable(Repository)) }
  def repository
    discussion.repository
  end

  sig { returns(String) }
  def author_display_login
    discussion.author_display_login
  end

  sig { returns(T.nilable(String)) }
  def repository_owner_login
    discussion.repository_owner_login
  end

  sig { returns(String) }
  def body
    discussion.body || ""
  end

  sig { returns(T.nilable(DiscussionCategory)) }
  def category
    discussion.category
  end

  sig { returns(Integer) }
  def number
    discussion.number
  end

  sig { returns(Integer) }
  def comment_count
    discussion.comment_count
  end

  sig { returns(Integer) }
  def total_upvotes
    discussion.total_upvotes
  end

  sig { returns T::Hash[String, Integer] }
  def reactions_count
    discussion.reactions_count
  end
end
