# typed: true
# frozen_string_literal: true

module SiteHelper
  extend T::Helpers

  # Adds a 'return_to' param to the login url so that successful
  # login sends you right back to where you were.
  sig { params(options: T::Hash[Symbol, T.untyped]).returns(String) }
  def site_nav_login_path(options = {})
    invalid_return_paths = ["/", "/dashboard/logged_out"]
    request = T.let(T.unsafe(self).request, ActionDispatch::Request) # Global request object, passed from the controller

    unless invalid_return_paths.include?(request.path)
      options[:return_to] = coordinated_return_to
    end

    T.unsafe(self).login_path(options) # Automatically generated by Rails from `login` route
  end

  sig { returns(T.nilable(String)) }
  def coordinated_return_to
    request = T.let(T.unsafe(self).request, ActionDispatch::Request) # Global request object, passed from the controller
    params = T.let(T.unsafe(self).params, T.any(ActionController::Parameters, Hash)) # Global request url params object, passed from the controller

    if request.path == "/join" && params[:setup_organization]
      T.unsafe(self).new_organization_path # Automatically generated from Rails `resources :organizations` in /config/routes.rb
    else
      params[:return_to] || T.unsafe(self).return_to_path # from /app/helpers/url_helper.rb#L884
    end
  end

  sig { returns(T::Boolean) }
  def home_page?
    request = T.let(T.unsafe(self).request, ActionDispatch::Request) # Global request object, passed from the controller

    request.path == T.unsafe(self).home_path || # Automatically generated from Rails `get 'home'` in /config/routes.rb
    request.path == "/home"
  end

  # Note: Only used by logged out header /app/views/site/_marketing_header.html.erb#L284
  sig { returns(T::Boolean) }
  def display_signin_popover?
    response = T.let(T.unsafe(self).response, ActionDispatch::Response) # Global response object, passed from the controller

    return false if !response.not_found?
    return false if GitHub.private_mode_enabled?
    return false if !T.unsafe(self).customized(:sign_in_message).blank? # From /app/helpers/custom_messages_helper.rb#L7

    true
  end

  # Note: Only used by logged in header /app/views/site/header/logged_in/_user.html.erb#L7
  # The switch account popover is a popover that appears when a user
  # receives a not_found response. This could be because they are not
  # authorized to view the page, or because the page does not exists.
  # We cannot distinguish between these two cases, because we don't want to
  # leak existence of a resource, so we show the popover in both cases.
  # We only show the popover if the user is logged in and has valid stashed accounts.
  sig { returns(T::Boolean) }
  def display_switch_account_popover?
    response = T.let(T.unsafe(self).response, T.nilable(ActionDispatch::Response)) # Global response object, passed from the controller

    return false unless response&.not_found?
    return false if @disable_account_switcher_popover
    return false unless T.unsafe(self).logged_in? # From app/controllers/application_controller/authenticated_system.rb#L16
    return false unless T.unsafe(self).account_switcher_helper.enabled? # From /app/controllers/application_controller/saved_user_sessions_cookie_dependency.rb#L25

    elligible = T.unsafe(self).account_switcher_helper.stashed_accounts.valid.any?

    if elligible && T.unsafe(self).flash[:stale_session_signedin]&.starts_with?("SWITCHED")
      GitHub.dogstats.increment("account_switcher.not_found_after_switch")
    end

    elligible
  end

  sig { void }
  def disable_account_switcher_popover
    @disable_account_switcher_popover = true
  end

  sig { returns(String) }
  def mktg_default_font_path
    "/static/fonts/github/mona-sans.woff2"
  end

  sig { returns(String) }
  def mktg_alt_font_path
    "/static/fonts/github/hubot-sans.woff2"
  end

  sig { returns(String) }
  def readme_header_font_path
    "/static/fonts/blimone/Blimone-Medium-Inktrap.woff2"
  end

  sig { returns(String) }
  def customer_stories_alt_font_path
    "/static/fonts/blimone/Blimone-Medium-Inktrap.woff2"
  end

  sig { params(mode: T.any(String, Symbol), dark_theme: T.any(String, Symbol), light_theme: T.any(String, Symbol)).returns(String) }
  def mktg_color_theme_attributes(mode: "dark", dark_theme: "dark", light_theme: "light")
    "data-color-mode=#{mode} data-light-theme=#{light_theme} data-dark-theme=#{dark_theme}"
  end

  sig { params(mode: T.any(String, Symbol), dark_theme: T.any(String, Symbol), light_theme: T.any(String, Symbol)).returns(T::Hash[Symbol, T.any(String, Symbol)]) }
  def mktg_color_theme_data(mode: "dark", dark_theme: "dark", light_theme: "light")
    { color_mode: mode, light_theme: light_theme, dark_theme: dark_theme }
  end

  sig { params(uid: String).returns(T::Boolean) }
  def user_disabled_global_banner?(uid)
    return false unless T.unsafe(self).cookies && T.unsafe(self).cookies[:disabled_global_site_banners]
    T.unsafe(self).cookies[:disabled_global_site_banners].split(",").include?(uid)
  end

  sig { params(allowed_paths: T.any(T::Array[String], NilClass), excluded_paths: T.any(T::Array[String], NilClass)).returns(T::Boolean) }
  def allowed_on_pages?(allowed_paths: nil, excluded_paths: nil)
    request = T.let(T.unsafe(self).request, ActionDispatch::Request) # Global request object, passed from the controller
    current_path = request.path

    is_allowed = allowed_paths.nil? || allowed_paths.include?(current_path)
    is_not_excluded = excluded_paths.nil? || !excluded_paths.include?(current_path)

    is_allowed && is_not_excluded
  end

  sig { params(prefix: T.nilable(String), suffix: T.nilable(String)).returns(String) }
  def request_path_parametrize(prefix: "", suffix: "")
    request = T.let(T.unsafe(self).request, ActionDispatch::Request) # Global request object, passed from the controller

    return "" if request.path == "/" || request.path == "/home"
    "#{prefix}#{request.path.force_encoding('UTF-8').parameterize}#{suffix}"
  end

  sig { returns(T::Boolean) }
  def marketing_page?
    controller = T.let(T.unsafe(self).controller, T.any(ActionController::Base, ApplicationController)) # Global controller object
    request = T.let(T.unsafe(self).request, ActionDispatch::Request) # Global request object, passed from the controller
    return true if controller.class == DashboardController && request.path == "/" && !T.unsafe(self).logged_in?
    return true if controller.class.ancestors.include?(Site::BaseController)
    false
  end

  sig { void }
  def marketing_turbo_enable
    @marketing_turbo_disabled = false
  end

  sig { returns(T::Boolean) }
  def marketing_turbo_disabled?
    return @marketing_turbo_disabled if defined? @marketing_turbo_disabled
    return true if marketing_page?
    false
  end

  # ActiveStorage::Filename#sanitize - Characters considered unsafe for storage (e.g. \, $, and the RTL override character) are replaced with a dash.
  # based on https://github.com/github/github/blob/master/packages/apps/app/models/integration_single_file.rb#L25-L30
  sig { params(filename: String).returns(String) }
  def sanitize_filename(filename)
    sanitized = filename.encode(Encoding::UTF_8, invalid: :replace, undef: :replace, replace: "�").strip.tr("\u{202E}\u{202B}\u{200F}%$|:;/\t\r\n\\", "-")
    sanitized.gsub!("..", "") # Remove directory traversal sequences
    sanitized.gsub!(/\A-+|-+\z/, "") # Ensure filename does not start or end with a dash
    sanitized
  end

  # Returns true when the current_user is an EMU
  sig { returns(T::Boolean) }
  def emu?
    T.unsafe(self).current_user&.enterprise_managed_business.present?
  end
end
