# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro/schemas/github/security_campaigns/v0/security_campaign_autofix_generation_incomplete.proto

require 'google/protobuf'

require 'hydro/schemas/github/v1/entities/organization_pb'
require 'hydro/schemas/github/security_campaigns/v0/entities/security_campaign_pb'
require 'hydro/schemas/github/security_campaigns/v0/entities/security_campaign_autofix_alert_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hydro.schemas.github.security_campaigns.v0.SecurityCampaignAutofixGenerationIncomplete" do
    optional :organization, :message, 1, "hydro.schemas.github.v1.entities.Organization"
    optional :security_campaign, :message, 2, "hydro.schemas.github.security_campaigns.v0.entities.SecurityCampaign"
    repeated :alerts, :message, 3, "hydro.schemas.github.security_campaigns.v0.entities.SecurityCampaignAutofixAlert"
  end
end

module Hydro
  module Schemas
    module Github
      module SecurityCampaigns
        module V0
          SecurityCampaignAutofixGenerationIncomplete = Google::Protobuf::DescriptorPool.generated_pool.lookup("hydro.schemas.github.security_campaigns.v0.SecurityCampaignAutofixGenerationIncomplete").msgclass
        end
      end
    end
  end
end
